### ISSUE TITLE
Couldn't find a debug adapter descriptor for the debug type 'solidity' (extension might have failed to to activate)

### ISSUE THREAD

**Issue by MichaelChiara** [ethereum/solidity#12501] opened 2022-01-07 23:20 UTC
## Environment

- Compiler version:
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce
```solidity
//Contract based on [https://docs.openzeppelin.com/contracts/3.x/erc721](https://docs.openzeppelin.com/contracts/3.x/erc721)
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/utils/Counters.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";

contract MyNFT is ERC721URIStorage, Ownable {
    using Counters for Counters.Counter;
    Counters.Counter private _tokenIds;

    constructor() public ERC721("MyNFT", "NFT") {}

    function mintNFT(address recipient, string memory tokenURI)
        public onlyOwner
        returns (uint256)
    {
        _tokenIds.increment();

        uint256 newItemId = _tokenIds.current();
        _mint(recipient, newItemId);
        _setTokenURI(newItemId, tokenURI);

        return newItemId;
    }
}
```

```solidity
// Some *minimal* Solidity source code to reproduce the bug.
// ...
```
-->

Not really sure how to report this.  Apologies for inconveniences.  Help fixing this issue would be great.

**Comment by hrkrshnn** [comment] 2022-01-12 11:34
@MichaelChiara What exactly is the issue here?

**Comment by cameel** [comment] 2022-01-17 23:05
This does not look like any of the messages the compiler produces. The message makes me think of an error you would get if you put `solidity` into the `language` field in [Standard JSON input](https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description). If you're manually constructing that input, please note that the word `Solidity` must be capitalized.

Anyway, I think it's coming from another tool and is not really a problem in the compiler so I'm going to close it. If you heave more details indicating that it's actually caused by a compiler bug, feel free to reopen.

**Closed as completed by cameel** 2022-01-17 23:05 UTC
Labels: waiting for more input

**Comment by hadysalama** [comment] 2022-02-17 04:18
If you're using Meadow it's deprecated.

**Comment by ogubuikeAlex** [comment] 2022-03-19 16:44
This issue arises when I try to debug my smart contract on VScode using f5

Any help?

**Comment by cameel** [comment] 2022-03-19 22:56
@king-Alex-d-great If you're using vscode-solidity extension, please [submit an issue in that projects' bug tracker instead](https://github.com/juanfranblanco/vscode-solidity/issues/new).
