### ISSUE TITLE
Minus bug

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#4079] opened 2018-05-06 23:39 UTC
Solidity allows to compile the following line:

`a - b;`

To test if this code actually does something I used this contract:

```
pragma solidity ^0.4.23;

contract C{
    event dos(uint256);
    function test(uint256 a, uint256 b) returns (uint256){
        a - b;
        dos(a);
        dos(b);
        a - b;
    }
}
```

By running the test function it doesn't change any variable and also in the EVM nothing happens to either variable or stuff pushed on the stack. Also it doesn't return any value, always return 0.

This should raise an error in solidity. This code does nothing, but usually coders would mean `=-` instead of the minus. This error is easy to make and should therefore not compile.

**Comment by chriseth** [comment] 2018-05-07 06:18
Duplicate of https://github.com/ethereum/solidity/issues/1380

**Closed as completed by chriseth** 2018-05-07 06:18 UTC
