### ISSUE TITLE
Old- and new-style constructors are allowed at the same time

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3911] opened 2018-04-17 09:27 UTC
Found by @yann300.

```
contract test {
    uint a;
    constructor () {
        a = 5;
    }
    function test () {
        a = 10;
    }
}
```

The above should raise an error of two constructors declared. Currently it compiles without warnings and whichever constructor was declared first takes precedence (the other is just ignored).

**Comment by chriseth** [comment] 2018-04-17 09:44
Duplicate of https://github.com/ethereum/solidity/issues/3904

**Comment by chriseth** [comment] 2018-04-17 09:49
Oh I'm sorry, confused this because I was working on both.

**Closed as completed** 2018-04-18 13:00 UTC
Labels: bug :bug:
