### ISSUE TITLE
[ewasm] Constructors with parameters crash code generator

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#10117] opened 2020-10-27 14:41 UTC
Originally reported in #10100 which has more code examples.

Ewasm code generation for constructors that take parameters is either buggy or unimplemented.

## Steps to Reproduce
```solidity
contract C {
    constructor(uint) {}
}
```
```bash
solc --ewasm test.sol
```
Output:
```
Unknown exception during compilation: map::at
```

The crash happens at [line 364 in `BinaryTransform::operator()(BuiltinCall const&)`](https://github.com/ethereum/solidity/blob/v0.7.4/libyul/backends/wasm/BinaryTransform.cpp#L364), apparently when generating code for a `datasize()` call:
```c++
return toBytes(Opcode::I64Const) + lebEncodeSigned(static_cast<int64_t>(m_subModulePosAndSize.at(name).second));
```

## Environment
- Compiler version: 0.7.4+commit.3f05b770.Linux.g++

**Comment by axic** [comment] 2020-10-27 17:37
This is the generated Yul code:
```
object "C_7" {
    code {
       ...
        function copy_arguments_for_constructor_6_object_C_7() -> ret_param_0 {
            let programSize := datasize("C_7")
            ...
```

The problem is that `BinaryTransform` cannot handle the special case where `datasize` refers to self.

**Comment by cameel** [comment] 2020-11-10 12:29
Just to update the status here, this still fails for the same reason (`datasize` referring to its own object), but now more gracefully:

```
Exception during compilation: /solidity/libyul/backends/wasm/BinaryTransform.cpp(367): Throw in function solidity::bytes solidity::yul::wasm::BinaryTransform::operator()(const solidity::yul::wasm::BuiltinCall&)
Dynamic exception type: boost::wrapexcept<solidity::yul::YulAssertion>
std::exception::what:
[solidity::util::tag_comment*] =
```

The failing assertion:
```c++
// TODO: support the case where name refers to the current object
yulAssert(m_subModulePosAndSize.count(name), "");
```

**Comment by axic** [comment] 2020-11-10 23:25
It wasn't implemented, just the graceful assertion was added.

The generator needs to
a) keep the current object name in order to support that,
b) keep a placeholder value for the `size` and patch it after final assembly.

That placeholder can be a `i32.const` with padding and storing the list of offsets to update, or it could refer to a single global, which again has an `i32.cons` with padding. LEB128 allows for padding, but Wasm at one point asked for the canonical shortest representation, however the final Wasm 1.0 allows padded values.

**Comment by cameel** [comment] 2020-11-10 23:34
Yeah, I was just stating that to make it clear that #10121 wasn't the fix (I initially thought that it might have been).
But thanks for explaining it in detail. That's even more helpful.

**Comment by NunoFilipeSantos** [comment] 2023-02-08 18:10
We're closing all wasm issues for now.

**Closed as completed by NunoFilipeSantos** 2023-02-08 18:10 UTC
Labels: bug :bug:, should compile without error, wasm
