### ISSUE TITLE
Unify [help wanted] labels

### ISSUE THREAD

**Issue by chfast** [ethereum/solidity#3243] opened 2017-11-24 10:41 UTC
Now we have 3 distinct labels for more/less the same purpose:
- https://github.com/ethereum/solidity/labels/help%20wanted
- https://github.com/ethereum/solidity/labels/good%20first%20issue
- https://github.com/ethereum/solidity/labels/up-for-grabs

Let's use `help wanted` or `good first issue` because GitHub adds special meaning to them: https://help.github.com/articles/about-labels/#using-default-labels.

**Comment by axic** [comment] 2017-11-24 13:37
I agree it is a good idea to use those labels:

<img width="987" alt="screen shot 2017-11-24 at 13 36 22" src="https://user-images.githubusercontent.com/20340/33212790-88023fb4-d11c-11e7-8453-0ad4d0180f0d.png">

We need help in reviewing every single issue and adding `help wanted` and `good first issue` to it.

**Comment by axic** [comment] 2017-11-24 13:40
So we could change every `up-for-grabs` labeled issue to `help wanted`. Adding `good first issue` requires review.

**Comment by chriseth** [comment] 2017-11-24 14:22
The problem is that some tags have external dependencies: http://up-for-grabs.net/#/

**Comment by axic** [comment] 2017-11-24 14:38
As it turns out that site only suggests `up-for-grabs`, but if you have a look, many use `help wanted`. It doesn't actually do anything unless you add the project to https://github.com/up-for-grabs/up-for-grabs.net/tree/gh-pages/_data/projects, where one can define the label.

Created a pull request with `help wanted`: https://github.com/up-for-grabs/up-for-grabs.net/pull/825

**Comment by axic** [comment] 2017-11-27 15:06
@chriseth the PR was merged, there should be no other reason not to rename the label then.

**Comment by axic** [comment] 2017-12-02 01:53
Marked all `up-for-grabs` issues as `help wanted` too. @chriseth can we remove the `up-for-grabs` label?

**Comment by axic** [comment] 2017-12-18 13:46
Removed the `up-for-grabs` label.

**Closed as completed by axic** 2017-12-18 13:46 UTC
