### ISSUE TITLE
Error message about disallowed argument location should explain why the location is not allowed

### ISSUE THREAD

**Issue by nventuro** [ethereum/solidity#11987] opened 2021-09-16 20:37 UTC
When compiling the following contract with solc v0.8.7:

```
pragma solidity ^0.8.0;

contract Test {
    struct MyStruct {
        uint256 a;
    }
    
    function foo(MyStruct storage bar) public;
}
```

we get the following error message:

```
TypeError: Data location must be "memory" or "calldata" for parameter in function, but "storage" was given.
    function foo(MyStruct storage bar) public;
                 ^------------------^
```

This is not particularly helpful as functions can actually receive `storage` arguments, but only if they are `internal` or `private`. The error message is not particularly insightful on this distinction, nor helps the developer achieve their task.

### Suggestion

A simple improvement could be:
```
Data location must be "memory" or "calldata" for parameter in "public" or "external" function
```

Even better, a suggestion could be appended at the end:

```
TypeError: Data location must be "memory" or "calldata" for parameter in "public" or "external" function, but 
"storage" was given.
    function foo(MyStruct storage bar) public;
                 ^------------------^

Use "internal" or "private" functions to pass storage pointers.
```

**Comment by axic** [comment] 2021-09-16 20:53
I think this would be as a nice improvement. Did you find similar other cases?

**Comment by nventuro** [comment] 2021-09-17 13:54
Hm I don't recall any off any of the top of my head - I just run into this the other day and was puzzled by the error message until I realized what was going on.

**Comment by jhb10c** [comment] 2021-09-20 20:38
Hey @cameel, @chriseth. I would like to work on this. I can update the error to the suggestion by @nventuro. If there are any specifications, could you all provide more info?

**Comment by cameel** [comment] 2021-09-20 20:47
Well, the version with adjusting the message is straightforward:
- find the message in the code
- tweak description
- run `isoltest` to update tests

A version with the extra suggestion would be harder. You can have an extra message if you specify a secondary location - but that's not what they were meant for and if would be weird if secondary location was pointing at the same thing. But maybe it would make sense if you made it point at the `public`/`external` keyword?

You could also issue two errors, one with "info" severity meant to contain just this extra suggestion - but there's the risk that the user will want to hide info messages.

Neither of these seems particularly nice so I I'd go with just tweaking the text unless you can figure out a nicer solution.

**Comment by jhb10c** [comment] 2021-09-21 05:07
Thanks for the instructions. I will update the error message for now and leave the extra suggestion for later. There are some similar cases. As such I will also update the error messages for external/public functions with the following data types: bytes; uint[]; structs; mapping(uint => uint); mapping(uint => uint)[].

**Comment by jhb10c** [comment] 2021-09-25 07:25
Alright, the files are updated and I ran isoltest to check the updated tests. I think everything works fine. 

I will rebase and submit the pull request later today.

**Comment by jhb10c** [comment] 2021-09-26 01:05
Spoke to soon. There is an issue. I have updated the tests and ran isoltest. However, when I reproduce the error with solc, it produces the original error. I then tried to rebuild the compiler with the updated tests. The original error was still there.  

This leads me to think: 1.) I have not updated the correct test; or 2.) I am building the compiler incorrectly.  @cameel, do you have any advice? Thanks again! 


(The main locations of the error message is dataLocations/publicFunction and types/mapping. The updated files can be found on my branch.)

**Comment by cameel** [comment] 2021-09-26 20:37
The same error might be raised from multiple places. Are you sure you found them all? If you are sure you did, I'd suggest manually modifying expectations in all tests that have this message to see which ones fail. Then you can use a debugger to see which path the compiler takes there. If that's still not enough to figure this out, you can also submit a draft PR with your code and these failing tests and we'll take a look.

**Comment by jhb10c** [comment] 2021-09-28 02:50
Thank you. I appreciate the advice. The message locations have been triple checked and all instances of error message was tracked down. I have submitted a pr.

**Comment by cameel** [comment] 2021-10-06 20:32
@jhb10c Do you want to try to add the extra message that suggests to use `internal` or `private`? It can be done using a secondary location, like here:
https://github.com/ethereum/solidity/blob/a9b99dd63b545e5ca8968058cfb8518206b8e343/libsolidity/interface/CompilerStack.cpp#L186-L194

You'd just leave the location field empty and only provide a message.

**Comment by nventuro** [comment] 2023-03-21 13:40
It's a bit sad that this simple suggestion remains unimplemented after over a year and a half :/

**Comment by cameel** [comment] 2023-03-22 22:41
Well, there are just too many of them. We've actually been chasing small improvements for too long and they've been siphoning off a lot of our focus that should have gone into major language features.

Still, I think that improving the error messages is a kind of issue that should not be just dismissed and closed as stale. It's still very relevant.

We'd welcome a contribution here, though, judging from the previous attempt, we'd still have to find some time to give some guidance here before we can mark it as a `good first issue`.

**Comment by amanx123** [comment] 2023-03-27 18:22
i would like to get involved and work on it !

**Comment by ekpyron** [comment] 2023-03-27 18:39
I'm sorry, but we won't solve this issue any time soon. The implementation effort and, even if outsourced, the reviewing effort is larger than the benefits. Generally, this kind of analysis and helpful suggestions on a case-by-case basis is of course nice, but can, for now, be done externally to the compiler in a linter, static analysis tool or IDE.

This doesn't mean that the issue is not valid and that it wouldn't be *better* to solve this in the compiler, but we currently have to focus on the overreaching language development, which will make a lot of finer error message distinctions like this obsolete or will at least significantly change the way they would have to be implemented.

Therefore, to avoid raising wrong expectations, I'm closing this issue. In the future, when we have made sufficient progress on the core language, we can revisit and then again allow issues about error- and diagnostics-cosmetics like this.

**Closed as completed by ekpyron** 2023-03-27 18:39 UTC
Labels: help wanted, good first issue candidate, low effort, low impact, should have
