### ISSUE TITLE
Cannot link the compiler with Boost 1.76.0 (`undefined reference to boost::program_options`)

### ISSUE THREAD

**Issue by nerotiger** [ethereum/solidity#11757] opened 2021-08-07 20:47 UTC
## Environment

- Compiler version:
> gcc --version
> gcc (GCC) 10.1.0
> cmake --version
> cmake version 3.21.1
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:
> uname -a
> Linux 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

## Steps to Reproduce
```
build]$ cmake ..
-- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is GNU 10.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost headers in 
-- Found Boost::filesystem at 
-- Found Boost::unit_test_framework at 
-- Found Boost::program_options at 
-- Found Boost::system at 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test fstack-protector-strong
-- Performing Test fstack-protector-strong - Success
-- Performing Test Wimplicit-fallthrough
-- Performing Test Wimplicit-fallthrough - Success
-- Performing Test fmacro-prefix-map=/tmp/solidity=/solidity
-- Performing Test fmacro-prefix-map=/tmp/solidity=/solidity - Success
-- Performing Test Wpessimizing-move
-- Performing Test Wpessimizing-move - Success
-- Performing Test Wredundant-move
-- Performing Test Wredundant-move - Success
-- Performing Test $<$<COMPILE_LANGUAGECXX>-Wextra-semi>
-- Performing Test $<$<COMPILE_LANGUAGECXX>-Wextra-semi> - Success
-- Performing Test Wfinal-dtor-non-final-class
-- Performing Test Wfinal-dtor-non-final-class - Failed
-- Performing Test Wnewline-eof
-- Performing Test Wnewline-eof - Failed
-- Performing Test Wsuggest-destructor-override
-- Performing Test Wsuggest-destructor-override - Failed
-- Performing Test Wduplicated-cond
-- Performing Test Wduplicated-cond - Success
-- Performing Test Wduplicate-enum
-- Performing Test Wduplicate-enum - Failed
-- Performing Test Wlogical-op
-- Performing Test Wlogical-op - Success
-- Performing Test Wno-unknown-attributes
-- Performing Test Wno-unknown-attributes - Failed

------------------------------------------------------------------------
-- Configuring solidity 0.8.7
------------------------------------------------------------------------
--                  CMake Version                            3.21.1
-- CMAKE_BUILD_TYPE Build type                               RelWithDebInfo
-- TARGET_PLATFORM  Target platform                          Linux
--------------------------------------------------------------- features
-- COVERAGE         Coverage support                         OFF
------------------------------------------------------------- components
-- TESTS            Build tests                              ON
------------------------------------------------------------------ flags
-- OSSFUZZ                                                   OFF
------------------------------------------------------------------------

-- Could NOT find Z3 (missing: Z3_LIBRARY Z3_INCLUDE_DIR) (Required is at least version "4.8.0")
No SMT solver found (or it has been forcefully disabled). Optional SMT checking will not be available.  
Please install Z3 or CVC4 or remove the option disabling them (USE_Z3, USE_CVC4).
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/solidity/build

gmake
```
```
[ 56%] Linking CXX executable solidity-upgrade
/usr/local/include/boost/program_options/variables_map.hpp:155: error: undefined reference to 'boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/solidity/tools/solidityUpgrade/SourceUpgrade.cpp:119: error: undefined reference to 'boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/usr/local/include/boost/program_options/variables_map.hpp:155: error: undefined reference to 'boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/local/include/boost/program_options/variables_map.hpp:155: error: undefined reference to 'boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/local/include/boost/program_options/detail/value_semantic.hpp:22: error: undefined reference to 'boost::program_options::arg[abi:cxx11]'
/usr/local/include/boost/program_options/detail/value_semantic.hpp:22: error: undefined reference to 'boost::program_options::arg[abi:cxx11]'
/usr/local/include/boost/program_options/detail/value_semantic.hpp:184: error: undefined reference to 'boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
/usr/local/include/boost/program_options/detail/convert.hpp:79: error: undefined reference to 'boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/include/boost/program_options/detail/parsers.hpp:28: error: undefined reference to 'boost::program_options::detail::cmdline::cmdline(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
/usr/local/include/boost/program_options/detail/value_semantic.hpp:149: error: undefined reference to 'boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
/usr/local/include/boost/program_options/detail/value_semantic.hpp:153: error: undefined reference to 'boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/solidity-upgrade.dir/solidityUpgrade/SourceUpgrade.cpp.o:SourceUpgrade.cpp:vtable for boost::wrapexcept<boost::program_options::invalid_option_value>: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/solidity-upgrade.dir/solidityUpgrade/SourceUpgrade.cpp.o:SourceUpgrade.cpp:vtable for boost::program_options::validation_error: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/solidity-upgrade.dir/solidityUpgrade/SourceUpgrade.cpp.o:SourceUpgrade.cpp:vtable for boost::program_options::invalid_option_value: error: undefined reference to 'boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/solidity-upgrade.dir/solidityUpgrade/SourceUpgrade.cpp.o:SourceUpgrade.cpp:vtable for boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>: error: undefined reference to 'boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
CMakeFiles/solidity-upgrade.dir/solidityUpgrade/SourceUpgrade.cpp.o:SourceUpgrade.cpp:vtable for boost::program_options::typed_value<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, char>: error: undefined reference to 'boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/solidity-upgrade] Error 1
make[1]: *** [tools/CMakeFiles/solidity-upgrade.dir/all] Error 2
make: *** [all] Error 2
```
ll -al boost_1_76_0.tar.gz 
-rw-r--r-- 1 water wheel 130274594 Apr 21 01:15 boost_1_76_0.tar.gz

**Comment by cameel** [comment] 2021-08-08 13:57
Looks like there's a problem with locating Boost libs on your system. I see that at least headers are there so it's not necessarily that they are missing.

1) Could you make sure that boost libs actually exist? On my system they're in `/usr/lib/libboost_program_options.a` and `/usr/lib/libboost_program_options.so.1.76.0`. I think our default config uses the static one.
2) Could you take a look at the linker command being used and see if paths are correct there? For example for `solidity-upgrade` executable you'll find the command inside `tools/CMakeFiles/solidity-upgrade.dir/link.txt` in the build directory.

**Comment by nerotiger** [comment] 2021-08-08 20:28
> Looks like there's a problem with locating Boost libs on your system. I see that at least headers are there so it's not necessarily that they are missing.
> 
> 1. Could you make sure that boost libs actually exist? On my system they're in `/usr/lib/libboost_program_options.a` and `/usr/lib/libboost_program_options.so.1.76.0`. I think our default config uses the static one.
```
[root@fabric02 water]# find / -name "libboost_program_options.a"
/usr/local/lib/libboost_program_options.a
[root@fabric02 water]# find / -name "libboost_program_options.so.1.76.0"
/usr/local/lib/libboost_program_options.so.1.76.0
```
actually, I reinstalled gcc, upgraded from 4.8 to 5.x finding out it required the minimum of 8.0, and got 10.1.
hence boost was upgraded altogether. 

**I will make two link files to /usr/lib**

> 2. Could you take a look at the linker command being used and see if paths are correct there? For example for `solidity-upgrade` executable you'll find the command inside `tools/CMakeFiles/solidity-upgrade.dir/link.txt` in the build directory.

```
[root@fabric02 solidity-upgrade.dir]# cat link.txt 
/usr/bin/c++  -fuse-ld=gold -O2 -g3 CMakeFiles/solidity-upgrade.dir/solidityUpgrade/main.cpp.o CMakeFiles/solidity-upgrade.dir/solidityUpgrade/UpgradeChange.cpp.o CMakeFiles/solidity-upgrade.dir/solidityUpgrade/Upgrade050.cpp.o CMakeFiles/solidity-upgrade.dir/solidityUpgrade/Upgrade060.cpp.o CMakeFiles/solidity-upgrade.dir/solidityUpgrade/Upgrade070.cpp.o CMakeFiles/solidity-upgrade.dir/solidityUpgrade/SourceUpgrade.cpp.o -o solidity-upgrade  ../libsolidity/libsolidity.a /usr/local/lib/libboost_program_options.a /usr/local/lib/libboost_system.a ../libyul/libyul.a ../libevmasm/libevmasm.a ../liblangutil/liblangutil.a ../libsmtutil/libsmtutil.a ../libsolutil/libsolutil.a /usr/local/lib/libboost_system.a ../deps/lib/libjsoncpp.a /usr/local/lib/libboost_filesystem.a 
```
in the link.txt, there are in the correct place... (/usr/local/lib/...)

**Comment by Assawal** [comment] 2021-08-08 20:46
> > Looks like there's a problem with locating Boost libs on your system. I see that at least headers are there so it's not necessarily that they are missing.
> > 
> > 1. Could you make sure that boost libs actually exist? On my system they're in `/usr/lib/libboost_program_options.a` and `/usr/lib/libboost_program_options.so.1.76.0`. I think our default config uses the static one.
> 
> ```
> [root@fabric02 water]# find / -name "libboost_program_options.a"
> /usr/local/lib/libboost_program_options.a
> [root@fabric02 water]# find / -name "libboost_program_options.so.1.76.0"
> /usr/local/lib/libboost_program_options.so.1.76.0
> ```
> 
> actually, I reinstalled gcc, upgraded from 4.8 to 5.x finding out it required the minimum of 8.0, and got 10.1.
> hence boost was upgraded altogether.
> 
> **I will make two link files to /usr/lib**
> 
> > 1. Could you take a look at the linker command being used and see if paths are correct there? For example for `solidity-upgrade` executable you'll find the command inside `tools/CMakeFiles/solidity-upgrade.dir/link.txt` in the build directory.
> 
> ```
> [root@fabric02 solidity-upgrade.dir]# cat link.txt 
> /usr/bin/c++  -fuse-ld=gold -O2 -g3 CMakeFiles/solidity-upgrade.dir/solidityUpgrade/main.cpp.o CMakeFiles/solidity-upgrade.dir/solidityUpgrade/UpgradeChange.cpp.o CMakeFiles/solidity-upgrade.dir/solidityUpgrade/Upgrade050.cpp.o CMakeFiles/solidity-upgrade.dir/solidityUpgrade/Upgrade060.cpp.o CMakeFiles/solidity-upgrade.dir/solidityUpgrade/Upgrade070.cpp.o CMakeFiles/solidity-upgrade.dir/solidityUpgrade/SourceUpgrade.cpp.o -o solidity-upgrade  ../libsolidity/libsolidity.a /usr/local/lib/libboost_program_options.a /usr/local/lib/libboost_system.a ../libyul/libyul.a ../libevmasm/libevmasm.a ../liblangutil/liblangutil.a ../libsmtutil/libsmtutil.a ../libsolutil/libsolutil.a /usr/local/lib/libboost_system.a ../deps/lib/libjsoncpp.a /usr/local/lib/libboost_filesystem.a 
> ```
> 
> in the link.txt, there are in the correct place... (/usr/local/lib/...)

**Comment by Assawal** [comment] 2021-08-08 20:47
tools/CMakeFiles/solidity-upgrade.dir/link.txt

**Comment by cameel** [comment] 2021-08-08 22:01
> I will make two link files to /usr/lib

That's not necessary. Looks like CMake does find the lib files inside `/usr/local/lib/` and properly includes them in the linker command. The problem must be somewhere else.

There's something weird going on. Linker gets the right file but does not see the symbols. Here's some more things to try:
- I see that you're running some commands as root. Could you make sure that the lib files are readable by a normal user? What are their permissions and which user owns them?
- Could you make sure the files are not corrupted? Do they have non-zero size? What do you see if you run `ar -t /usr/local/lib/libboost_program_options.a`? On my system it prints this:
    ```
    cmdline.o
    config_file.o
    options_description.o
    parsers.o
    variables_map.o
    value_semantic.o
    positional_options.o
    utf8_codecvt_facet.o
    convert.o
    winmain.o
    split.o
    ```
- If you're building boost from source, could you try installing it with a package manager instead?

**Comment by nerotiger** [comment] 2021-08-08 22:38
> * ar -t /usr/local/lib/libboost_program_options.a

mine is like this:
```
[water@fabric02 ~]$ ar -t /usr/local/lib/libboost_program_options.a
cmdline.o
config_file.o
options_description.o
parsers.o
variables_map.o
value_semantic.o
positional_options.o
utf8_codecvt_facet.o
convert.o
winmain.o
split.o

```
exactly identical to yours.

**Comment by nerotiger** [comment] 2021-08-08 22:43
That's not necessary. Looks like CMake does find the lib files inside `/usr/local/lib/` and properly includes them in the linker command. The problem must be somewhere else.
> indeed.

* I see that you're running some commands as root. Could you make sure that the lib files are readable by a normal user? What are their permissions and which user owns them?

> I can run entirely everything as root. and normally I build stuff as my own user/wheel, there was no permission error seen.
> I will try entirely solidity with 755,644 under my own user name.

* If you're building boost from source, could you try installing it with a package manager instead?

> I did build boost from source, and there was merely an error prompted. I just recompiled it once again.
> I will try yum package, but I don't see that may help. will let you know in a while.

**Comment by cameel** [comment] 2021-08-08 23:02
Did you compile Boost using the GCC version you had before upgrading it to 10.1? If so, this might be your problem.

[GCC Manual > Dual ABI](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html)
> If you get linker errors about undefined references to symbols that involve types in the `std::__cxx11` namespace or the tag `[abi:cxx11]` then it probably indicates that you are trying to link together object files that were compiled with different values for the _GLIBCXX_USE_CXX11_ABI macro. This commonly happens when linking to a third-party library that was compiled with an older version of GCC. If the third-party library cannot be rebuilt with the new ABI then you will need to recompile your code with the old ABI. 

You do have `std::__cxx11::basic_string` in your error messages so I think that's it and recompiling Boost should resolve it.

**Comment by nerotiger** [comment] 2021-08-08 23:31
> Did you compile Boost using the GCC version you had before upgrading it to 10.1? If so, this might be your problem.
> 
> [GCC Manual > Dual ABI](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html)
> 
> > If you get linker errors about undefined references to symbols that involve types in the `std::__cxx11` namespace or the tag `[abi:cxx11]` then it probably indicates that you are trying to link together object files that were compiled with different values for the _GLIBCXX_USE_CXX11_ABI macro. This commonly happens when linking to a third-party library that was compiled with an older version of GCC. If the third-party library cannot be rebuilt with the new ABI then you will need to recompile your code with the old ABI.
> 
> You do have `std::__cxx11::basic_string` in your error messages so I think that's it and recompiling Boost should resolve it.

I have recomplied Boost, nothing worked. I used system package, still no success. 
```
Installed:
  epel-release.noarch 0:7-13                                                                                                             

Complete!
[root@fabric02 build]# yum install boost boost-thread boost-devel
Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

Loading mirror speeds from cached hostfile
Package boost-1.53.0-28.el7.x86_64 already installed and latest version
Package boost-thread-1.53.0-28.el7.x86_64 already installed and latest version
Package boost-devel-1.53.0-28.el7.x86_64 already installed and latest version
Nothing to do
```
![image](https://user-images.githubusercontent.com/8183249/128648822-29f2ebc9-dde9-46e5-a77a-d6c46f7c640a.png)

**Comment by nerotiger** [comment] 2021-08-09 00:12
I have recomplied boost again from pure clean tarball file and run test according to its manual. 
```
[root@fabric02 boost_1_76_0]# pushd tools/build/test; python3 test_all.py; popd
/home/water/src/boost_1_76_0/tools/build/test /home/water/src/boost_1_76_0
Note: skipping extra tests
unit_tests                        :PASSED
module_actions                    :PASSED
...
...
builtin_glob_archive              :PASSED

        === Test summary ===
        PASS: 154
        FAIL: 0
```
all passed with 0 fails. 
still, same error on solidity-upgrade. 

**shall I recompile gcc and cmake again?**

![image](https://user-images.githubusercontent.com/8183249/128649874-763fe0fb-4faa-451c-a78f-764e10dc733d.png)

**Comment by hrkrshnn** [comment] 2021-08-09 07:19
> shall I recompile gcc and cmake again?

It seems unlikely that this is the problem.

The `yum` command shows that boost was already installed. Could you please clean the boost and install again? Also surprised that the package manager is installing boost 1.53 (that was released in 2013) Perhaps some components in your system are outdated?

**Comment by nerotiger** [comment] 2021-08-09 11:03
> The `yum` command shows that boost was already installed. Could you please clean the boost and install again? Also surprised that the package manager is installing boost 1.53 (that was released in 2013) Perhaps some components in your system are outdated?

I tried the entire thing on another newly made CentOS8.4 (gcc 8.4.1, cmake 3.18.2, boost 1.76) and it just worked fine. 
```
[ 67%] Building CXX object libsolidity/CMakeFiles/solidity.dir/interface/Version.cpp.o
[ 69%] Linking CXX static library libsolidity.a
[100%] Built target solidity
Scanning dependencies of target solcli
[100%] Building CXX object solc/CMakeFiles/solcli.dir/CommandLineInterface.cpp.o
[100%] Linking CXX static library libsolcli.a
[100%] Built target solcli
[100%] Linking CXX executable solc
[100%] Built target solc
```
but on that old CentOS7, with gcc 10.1 ... still didn't work. I've reinstalled boost 3 times...

**Comment by hrkrshnn** [comment] 2021-08-09 11:25
@nerotiger It's nice that the problem doesn't exist in a newer version of centos. Hopefully that is a workable solution for you. I'm closing this issue in that case. Feel free to reply or reopen if you think the issue is unresolved and needs changes from our side.

**Closed as completed by hrkrshnn** 2021-08-09 11:25 UTC
