### ISSUE TITLE
Empty return statement permitted on functions with return values

### ISSUE THREAD

**Issue by decanus** [ethereum/solidity#4541] opened 2018-07-22 10:29 UTC
When declaring a function with a return type definition, it is expected that the would compiler ensure this return is enforced.

However, the following snippet is completely valid and compiles without any errors

```solidity
pragma solidity ^0.4.24;

contract Token {
    
    function transfer(address to, uint256 amount) public returns (bool) {
        return;
    }
}
```

Tested with:
- 0.4.25-nightly.2018.7.20+commit.d3000e70.Emscripten.clang
- 0.4.24+commit.e67f0147.Emscripten.clang

**Comment by christianparpart** [comment] 2018-07-23 08:08
The return value seems to default to `false` (as of the assembly output). I can confirm that HEAD development isn't generating a warning/error either. Thanks for the report @decanus.

**Comment by decanus** [comment] 2018-07-23 10:02
I think that default only exists because return data is allocated but nothing is pushed into it, so not really a default imo @christianparpart

**Comment by axic** [comment] 2018-07-23 10:36
This has been discussed in #708 and #1401 seems also relevant.

I think this should be part of a design discussion.

Mostly we were on the opinion to delegate these warnings into the Remix static analyzer. It could have a check to ensure that a function either only uses named return value assignments or return statements (or at least if it uses a return variable it must have a value assigned to on all code paths).

**Comment by decanus** [comment] 2018-07-23 10:52
@axic to me it seems kind of broken that those warnings would be delegated, especially that it is considered a warning. I would assume this to be a clear error.

**Comment by axic** [comment] 2018-07-23 11:04
If it is only a warning, but it still valid code, then there is no way to get rid of the warning by restructuring code (assuming it is valid code). Note: there is no other way to disable compiler warnings, but by changing code. Hence it is delegated to an upper layer.

If we consider it as a deprecated feature, than of course the warning belongs here.

Looking into this again, this seems to stem from an old behaviour where tuple return values weren't allowed. The better example is:
```
pragma solidity ^0.4.24;
contract Token {
    function transfer(address to, uint256 amount) public returns (bool a, bool b, bool c) {
        a = ..
        b = ...
        if (msg.value)
           c = ..
        else 
           c = ..
        return;
    }
}
```

Without having support for tuples `return (true, true, false)` the above was the only way to handle this. This isn't the case anymore.

As a result I'd say disallowing an empty `return` when there are return parameters (whether named or unnamed) could be considered as a useful breaking change.

**Comment by axic** [comment] 2018-07-24 23:41
Another relevant thread #2951.

**Comment by chriseth** [comment] 2018-08-02 16:02
I'm actually surprised this is not a duplicate of an existing issue.

I'm fine with disallowing `return;` if there are return parameters. We might even take this into 0.5.0.

**Comment by chriseth** [comment] 2018-08-02 16:03
It should be a trivial change at the beginning of `TypeChecker::endVisit(Return const&)`

**Comment by christianparpart** [comment] 2018-08-06 10:19
Discussion result: Always require the same amount of return statement parameter components as the function signature's declaration mandates.

**Closed as completed** 2018-08-08 12:59 UTC
Labels: breaking change :warning:, language design :rage4:
