### ISSUE TITLE
Variables can be used before they're declared, and the only scope is function

### ISSUE THREAD

**Issue by roadriverrail** [ethereum/solidity#1400] opened 2016-11-19 04:22 UTC
While going through to work on another issue, I noticed that the only use of local variable scoping I could find was in CallableDefinition, which means that FunctionDefinition, ModifierDefinition, and EventDefinition are the only resolution of scoping in Solidity.  Additionally, it looks like types and variable names are resolved before expressions are compiled, meaning that it's possible to use a variable before its type is declared.

I'm not sure that either is necessarily wrong (though I'd probably personally like having block-level locals).  I was just curious if this merited further attention.

Just as a sort of reference, this contract compiles for me:

```
pragma solidity ^0.4.4;

contract Test {

function Moog () {
  i=1;
  int i;
  if (i==0) { j=0; }
  else { uint j; j=1; }
}

}
```

**Comment by axic** [comment] 2016-11-19 08:24
Duplicate of #219 and it has been documented since:

> This behaviour is inherited from javascript. 

I would be in favour of strict declaration order too.

**Closed as completed** 2016-11-21 09:36 UTC
