### ISSUE TITLE
Add #define to Solidity

### ISSUE THREAD

**Issue by clemlak** [ethereum/solidity#11745] opened 2021-08-04 17:15 UTC
## Abstract

Add a way to define macros using `#define` within the source code to declare constants (numbers, strings, addresses, expressions, etc) and fragments of code:

```c
#define PI 3141592653589793238
```

## Motivation

Storing values and performing computations in a smart contract costs gas (and thus money). However when comes the time to gas golf a contract, a dilemma can appear between optimizing the gas usage as much as possible or keeping the readability of the code.

### Example 1

This simplistic example shows that using a direct numeric value for `PI` obviously consumes less gas than storing and reading its value from a constant variable. However too much optimization might impact both the maintainability and the readability of the code.

> Case 1, using PI as a constant

```solidity
contract PIExample {
    uint256 public constant PI = 3141592653589793238;
    uint256 public area;
    uint256 public circumference;
    
    // 44,450 gas used
    function setArea(uint256 r) external {
        area = PI * r ** 2;
    }
    
    // 44,210 gas used
    function setCircumference(uint256 r) external {
        circumference = 2 * PI * r;
    }
}
```

> Case 2, using PI value directly

```solidity
contract PIExample {
    uint256 public area;
    uint256 public circumference;
    
    // 44,428 gas used
    function setArea(uint256 r) external {
        area = 3141592653589793238 * r ** 2;
    }
    
    // 43,978 gas used
    function setCircumference(uint256 r) external {
        circumference = 2 * 3141592653589793238 * r;
    }
}
```

Programming languages such as C allow developers to define macros within the source code. These macros can represent constants but also fragments of code that can receive arguments. These *defines* are preprocessed by the compiler before compiling the actual code.

Having this feature in Solidity would (in some cases) avoid the necessity to declare constant variables or private functions and then would reduce the gas cost while keeping the readability of the code.

The previous example could then be written as:

```csharp
#define PI 3141592653589793238

contract PIExample {
    uint256 public area;
    uint256 public circumference;
    
    function setArea(uint256 r) external {
        area = PI * r ** 2;
    }
    
    function setCircumference(uint256 r) external {
        circumference = 2 * PI * r;
    }
}
```

### Example 2

This other example compares 3 different cases where two private functions and one constant are used. As expected, using directly the expressions or the values instead of their declarations will reduce the gas cost but also impact the maintainability and readability of the code.

> Case 1: Private functions and PI constant

```solidity
contract PIExample {
    uint256 public constant PI = 3141592653589793238;
    uint256 public area;
    uint256 public circumference;
    
    function calculateArea(uint256 r) private pure returns (uint256) {
        return PI * r ** 2;
    }
    
    function calculateCircumference(uint256 r) private pure returns (uint256) {
        return 2 * PI * r;
    }
    
    // 44,493 gas used
    function setArea(uint256 r) external {
        area = calculateArea(r);
    }
    
    // 44,253 gas used
    function setCircumference(uint256 r) external {
        circumference = calculateCircumference(r);
    }
}
```

> Case 2: No private functions, with PI constant

```solidity
contract PIExample {
    uint256 public constant PI = 3141592653589793238;
    uint256 public area;
    uint256 public circumference;
    
    // 44,450 gas used
    function setArea(uint256 r) external {
        area = PI * r ** 2;
    }
    
    // 44,210 gas used
    function setCircumference(uint256 r) external {
        circumference = 2 * PI * r;
    }
}
```

> Case 3: No private functions, no PI constant

```solidity
contract PIExample {
    uint256 public area;
    uint256 public circumference;
    
    // 44,428 gas used
    function setArea(uint256 r) external {
        area = 3141592653589793238 * r ** 2;
    }
    
    // 43,978 gas used
    function setCircumference(uint256 r) external {
        circumference = 2 * 3141592653589793238 * r;
    }
}
```

Using `#define`, the previous example could be written as:

```csharp
#define PI 3141592653589793238
#define calculateArea(r) (PI * r * r)
#define calculateCircumference(r) (2 * PI * R)

contract PIExample {
    uint256 public area;
    uint256 public circumference;
    
    // 44,428 gas used
    function setArea(uint256 r) external {
        area = calculateArea(r);
    }
    
    // 43,978 gas used
    function setCircumference(uint256 r) external {
        circumference = calculateCircumference(r);
    }
    
    /**
     * Now calculateArea(r) and calculateCircumference(r) can be reused
     * multiple times in different functions with no additional gas cost
     */
}
```

Obviously these 2 examples are depicting very basic use cases of the `#define` macro, and even if the improvement of both the gas cost and the readability might not be obviously here, the impact on large-scale projects might be significant.

Additionally, these macros could also be used to:
- Reduce the storage of some math libraries by replacing constant variables
- Reduce the gas cost of large projects by replacing private functions
- Etc

*Note: A suggested way to achieve this feature without modifying the Solidity language was to use an external preprocessing tool, such as [hardhat-preprocessor](https://hardhat.org/plugins/hardhat-preprocessor.html). However, relying on an external tool is not an option since it would result in writing non-standard Solidity code and would break the compatibility with many tools.*

## Specification

The specification of the `#define` macro would be very similar to the one used in the C programming language.

### Simple macro

A simple macro is a fragment of code defined by a name using `#define`:

```c
#define PI 31415
#define SOME_ADDRESS 0x012345...
```

Every time the compiler would encounter `PI` in the code, it would replace it by `31415`, etc.

### Function-like macro

More complex macros could be defined too: function-like macros. These special macros would work like a function call and would accept arguments.

```c
#define PI 31415
#define circleArea(r) (PI * r * r)
#define max(a, b) (a < b) ? b : a
```

The compiler would then replace `circleArea(r)` by `(31415 * r * r)`, etc.

### Multiline macro

Macros could also be defined on multiple lines, such as:

```c
#define PI\
        3141592653589793238
```

### Inheritance

Macros should be available in the child contracts.

## Backwards Compatibility

The addition of this feature would not impact the compatibility with previous Solidity version.

**Comment by hrkrshnn** [comment] 2021-08-05 07:59
> This simplistic example shows that using a direct numeric value for PI obviously consumes less gas than storing and reading its value from a constant variable.

@clemlak Did you use a solidity version `>= 0.8.4` and enabled optimization for this comparison? Could you please share the gas comparisons?

**Comment by hrkrshnn** [comment] 2021-08-05 08:15
```
#define circleArea(r) (PI * r * r)
#define max(a, b) (a < b) ? b : a
```

A problem with macros like this is that they don't have proper type checking. I would say that this goes against the goal of type safety in the language

---

If the goal of macros when compared to proper typed functions / typed constants is merely gas, this can be fixed by the optimizer. The Yul based codegen and it's optimizer (not enabled by default; but will be the standard in future solidity versions) has an inliner that can inline these constants and small functions, making the gas of macro v/s optimized code to be the same (You can already test this with command `--experimental-via-ir --optimize` or the corresponding standard json settings.) 

As for current solidity, in version `0.8.2`, we included a simple bytecode level inliner that should inline the code examples from above. I believe this should be able to cover at least the constants and small functions without any control flow. We purposefully kept this inliner simple for now. If you have specific examples that you think should be covered by the inliner, we can take a look.

**Comment by chriseth** [comment] 2021-08-05 08:56
Duplicate of #10

**Comment by sambacha** [comment] 2021-09-15 21:18
> ## Abstract
> Add a way to define macros using `#define` within the source code to declare constants (numbers, strings, addresses, expressions, etc) and fragments of code:
> 
> ```c
> #define PI 3141592653589793238
> ```
> 
> ## Motivation
> Storing values and performing computations in a smart contract costs gas (and thus money). However when comes the time to gas golf a contract, a dilemma can appear between optimizing the gas usage as much as possible or keeping the readability of the code.
> 
> ### Example 1
> This simplistic example shows that using a direct numeric value for `PI` obviously consumes less gas than storing and reading its value from a constant variable. However too much optimization might impact both the maintainability and the readability of the code.
> 
> > Case 1, using PI as a constant
> 
> ```solidity
> contract PIExample {
>     uint256 public constant PI = 3141592653589793238;
>     uint256 public area;
>     uint256 public circumference;
>     
>     // 44,450 gas used
>     function setArea(uint256 r) external {
>         area = PI * r ** 2;
>     }
>     
>     // 44,210 gas used
>     function setCircumference(uint256 r) external {
>         circumference = 2 * PI * r;
>     }
> }
> ```
> 
> > Case 2, using PI value directly
> 
> ```solidity
> contract PIExample {
>     uint256 public area;
>     uint256 public circumference;
>     
>     // 44,428 gas used
>     function setArea(uint256 r) external {
>         area = 3141592653589793238 * r ** 2;
>     }
>     
>     // 43,978 gas used
>     function setCircumference(uint256 r) external {
>         circumference = 2 * 3141592653589793238 * r;
>     }
> }
> ```
> 
> Programming languages such as C allow developers to define macros within the source code. These macros can represent constants but also fragments of code that can receive arguments. These _defines_ are preprocessed by the compiler before compiling the actual code.
> 
> Having this feature in Solidity would (in some cases) avoid the necessity to declare constant variables or private functions and then would reduce the gas cost while keeping the readability of the code.
> 
> The previous example could then be written as:
> 
> ```cs
> #define PI 3141592653589793238
> 
> contract PIExample {
>     uint256 public area;
>     uint256 public circumference;
>     
>     function setArea(uint256 r) external {
>         area = PI * r ** 2;
>     }
>     
>     function setCircumference(uint256 r) external {
>         circumference = 2 * PI * r;
>     }
> }
> ```
> 
> ### Example 2
> This other example compares 3 different cases where two private functions and one constant are used. As expected, using directly the expressions or the values instead of their declarations will reduce the gas cost but also impact the maintainability and readability of the code.
> 
> > Case 1: Private functions and PI constant
> 
> ```solidity
> contract PIExample {
>     uint256 public constant PI = 3141592653589793238;
>     uint256 public area;
>     uint256 public circumference;
>     
>     function calculateArea(uint256 r) private pure returns (uint256) {
>         return PI * r ** 2;
>     }
>     
>     function calculateCircumference(uint256 r) private pure returns (uint256) {
>         return 2 * PI * r;
>     }
>     
>     // 44,493 gas used
>     function setArea(uint256 r) external {
>         area = calculateArea(r);
>     }
>     
>     // 44,253 gas used
>     function setCircumference(uint256 r) external {
>         circumference = calculateCircumference(r);
>     }
> }
> ```
> 
> > Case 2: No private functions, with PI constant
> 
> ```solidity
> contract PIExample {
>     uint256 public constant PI = 3141592653589793238;
>     uint256 public area;
>     uint256 public circumference;
>     
>     // 44,450 gas used
>     function setArea(uint256 r) external {
>         area = PI * r ** 2;
>     }
>     
>     // 44,210 gas used
>     function setCircumference(uint256 r) external {
>         circumference = 2 * PI * r;
>     }
> }
> ```
> 
> > Case 3: No private functions, no PI constant
> 
> ```solidity
> contract PIExample {
>     uint256 public area;
>     uint256 public circumference;
>     
>     // 44,428 gas used
>     function setArea(uint256 r) external {
>         area = 3141592653589793238 * r ** 2;
>     }
>     
>     // 43,978 gas used
>     function setCircumference(uint256 r) external {
>         circumference = 2 * 3141592653589793238 * r;
>     }
> }
> ```
> 
> Using `#define`, the previous example could be written as:
> 
> ```cs
> #define PI 3141592653589793238
> #define calculateArea(r) (PI * r * r)
> #define calculateCircumference(r) (2 * PI * R)
> 
> contract PIExample {
>     uint256 public area;
>     uint256 public circumference;
>     
>     // 44,428 gas used
>     function setArea(uint256 r) external {
>         area = calculateArea(r);
>     }
>     
>     // 43,978 gas used
>     function setCircumference(uint256 r) external {
>         circumference = calculateCircumference(r);
>     }
>     
>     /**
>      * Now calculateArea(r) and calculateCircumference(r) can be reused
>      * multiple times in different functions with no additional gas cost
>      */
> }
> ```
> 
> Obviously these 2 examples are depicting very basic use cases of the `#define` macro, and even if the improvement of both the gas cost and the readability might not be obviously here, the impact on large-scale projects might be significant.
> 
> Additionally, these macros could also be used to:
> 
> * Reduce the storage of some math libraries by replacing constant variables
> * Reduce the gas cost of large projects by replacing private functions
> * Etc
> 
> _Note: A suggested way to achieve this feature without modifying the Solidity language was to use an external preprocessing tool, such as [hardhat-preprocessor](https://hardhat.org/plugins/hardhat-preprocessor.html). However, relying on an external tool is not an option since it would result in writing non-standard Solidity code and would break the compatibility with many tools._
> 
> ## Specification
> The specification of the `#define` macro would be very similar to the one used in the C programming language.
> 
> ### Simple macro
> A simple macro is a fragment of code defined by a name using `#define`:
> 
> ```c
> #define PI 31415
> #define SOME_ADDRESS 0x012345...
> ```
> 
> Every time the compiler would encounter `PI` in the code, it would replace it by `31415`, etc.
> 
> ### Function-like macro
> More complex macros could be defined too: function-like macros. These special macros would work like a function call and would accept arguments.
> 
> ```c
> #define PI 31415
> #define circleArea(r) (PI * r * r)
> #define max(a, b) (a < b) ? b : a
> ```
> 
> The compiler would then replace `circleArea(r)` by `(31415 * r * r)`, etc.
> 
> ### Multiline macro
> Macros could also be defined on multiple lines, such as:
> 
> ```c
> #define PI\
>         3141592653589793238
> ```
> 
> ### Inheritance
> Macros should be available in the child contracts.
> 
> ## Backwards Compatibility
> The addition of this feature would not impact the compatibility with previous Solidity version.

A project has already implemented this functionality:
https://github.com/MerkleX/tSol

I used it briefly [sambacha/transpiler-solidity/tree/trunk](https://github.com/sambacha/transpiler-solidity/tree/trunk), it has to use a modified build system (gradle) to properly deploy on chain. 

Trail of Bits did a security audit of the original repo, however the audit was not published publicly. 

Hopefully this adds some clarity to your proposal. As you can see by https://github.com/ethereum/solidity/issues/10 this is a long standing debate.

**Comment by banshee** [comment] 2021-09-23 18:21
> As for current solidity, in version `0.8.4`, we included a simple bytecode level inliner that should inline the code examples from above. I believe this should be able to cover at least the constants and small functions without any control flow. We purposefully kept this inliner simple for now. If you have specific examples that you think should be covered by the inliner, we can take a look.

One motivation for this kind of thing is to define the constants on the compiler command line, not in the files.  You'd do this in a file:

```
#ifndef SOME_ADDRESS
#error you must define SOME_ADDRESS to be some address
#ifndef
```

and then on the compiler command line you'd do

```
invokeTheSolCompiler -DSOME_ADDRESS=0xabcdefg
```

**Comment by axic** [comment] 2021-09-24 10:52
> One motivation for this kind of thing is to define the constants on the compiler command line, not in the files. 

@banshee for this use case I think #1650 is a better solution as it fits the syntax more nicely.

**Comment by sambacha** [comment] 2021-10-05 15:56
> > As for current solidity, in version `0.8.4`, we included a simple bytecode level inliner that should inline the code examples from above. I believe this should be able to cover at least the constants and small functions without any control flow. We purposefully kept this inliner simple for now. If you have specific examples that you think should be covered by the inliner, we can take a look.
> 
> One motivation for this kind of thing is to define the constants on the compiler command line, not in the files. You'd do this in a file:
> 
> ```
> #ifndef SOME_ADDRESS
> #error you must define SOME_ADDRESS to be some address
> #ifndef
> ```
> 
> and then on the compiler command line you'd do
> 
> ```
> invokeTheSolCompiler -DSOME_ADDRESS=0xabcdefg
> ```

makes sense, esp. after seeing @axic link to https://github.com/ethereum/solidity/issues/1650

**Comment by Nielsbishere** [comment] 2022-01-06 18:18
I'm also in need of this;
`function x() testPublicOrExternal`
Where I can set a define testPublicOrExternal to `external` if it's production and `public` if it's a test.

**Comment by ekpyron** [comment] 2022-11-07 16:59
Closing this both as a duplicate of the already mentioned issues and as well as a feature we will most likely not implement (superior solutions like proper compile-time-constant expression evaluation are in our pipeline).

**Closed as completed by ekpyron** 2022-11-07 16:59 UTC
Labels: waiting for more input, language design :rage4:, medium effort, medium impact

**Comment by CJ42** [comment] 2023-11-03 19:58
The example that was given seems invalid for the argument of the higher gas cost.
The constant PI was defined as public, which leads the bytecode to generate a JUMP to get into the bytecode part that defines this function.
