### ISSUE TITLE
solc in /tmp

### ISSUE THREAD

**Issue by jonknight73** [ethereum/solidity#6915] opened 2019-06-06 15:41 UTC
## Description
solc will not load any solidity files in /tmp, even when it has read-write access. 

## Environment
```bash
jon@hpjon:/tmp$ solc --version
solc, the solidity compiler commandline interface
Version: 0.5.7+commit.6da8b019.Linux.g++

jon@hpjon:/tmp$ uname -a
Linux hpjon 4.18.0-20-generic #21~18.04.1-Ubuntu SMP Wed May 8 08:43:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

jon@hpjon:/tmp$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

jon@hpjon:/tmp$ which solc
/snap/bin/solc 
```

## Steps to Reproduce

```bash
$ cd /tmp
$ solc file.sol 
"file.sol" is not found.
```
The file does exist. It is viewable. The same file compiles as expected when copied to my home directory. Solc works as expected in any other directory.  

A colleague was able to reproduce this behaviour.

**Comment by leonardoalt** [comment] 2019-06-13 15:34
Hi @jonknight73 ,

I couldn't reproduce it on Arch Linux.
@bshastry can you take a look? (Ubuntu)

@jonknight73 could it be related to group permissions on the binary and on `/tmp`?

**Comment by chriseth** [comment] 2019-06-17 16:05
This seems to use the "snap" distribution of solidity.

**Comment by axic** [comment] 2019-12-12 22:41
@elopio could this be specific to snap?

**Comment by come-maiz** [comment] 2019-12-13 00:45
It is, yes. Snaps can't access `/tmp`.

**Comment by axic** [comment] 2019-12-13 11:54
I think this should be documented.

**Comment by come-maiz** [comment] 2019-12-13 16:47
Actually, it should be fixed in snaps. When you try to access a path that's outside of your confined box, it should explain what's up and ideally offer a command for an administrator to give access to that path.
Luckily, I no longer work there, because doing this has been hard.

I'll add a note in the install instructions pointing to https://snapcraft.io/blog/demystifying-snap-confinement

**Closed as completed** 2019-12-14 12:24 UTC
Labels: documentation :book:
