### ISSUE TITLE
Support overloading for modifiers

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3041] opened 2017-10-06 12:14 UTC
```
contract C {
  modifier m(uint a) { _; }
  modifier m(bytes b) { _; }
  modifier m(uint a, bytes b) { _; }
}
```

(From Pivotaltracker https://www.pivotaltracker.com/story/show/104324810.)

**Comment by chriseth** [comment] 2018-03-13 10:45
This should be a duplicate of https://github.com/ethereum/solidity/issues/72

**Closed as completed** 2019-03-22 11:04 UTC
Labels: language design :rage4:

**Comment by martasaparicio** [comment] 2020-08-05 14:49
is overloading modifiers available?
