### ISSUE TITLE
Incorrect warning about unreachable code.

### ISSUE THREAD

**Issue by blishko** [ethereum/solidity#10620] opened 2020-12-15 18:47 UTC
## Description
For the following example
```
abstract contract A {
    bool s;

    function f() public view mod {
        assert(s); // holds for C, but fails for B
    }
    modifier mod() virtual;
}

contract B is A {
    modifier mod() virtual override {
        s = false;
        _;
    }
}

contract C is B {
    modifier mod() override {
        s = true;
        _;
    }
}
```

The compiler reports the following warning:
```
Warning: Unreachable code.
 --> /Users/mblicha/projects/solidity/build/test.sol:4:34:
  |
4 |     function f() public view mod {
  |                                  ^ (Relevant source part starts here and spans across multiple lines).

```

This warning is very confusing and most likely also incorrect. I would expect this to be compiled without any warning.

## Environment

- Compiler version: 0.7.5, also current `develop`
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: MacOs 10.13

## Steps to Reproduce
Just compile with `solc`.

**Comment by chriseth** [comment] 2021-02-16 08:35
Might be related to / duplicate of https://github.com/ethereum/solidity/issues/10084

**Comment by chriseth** [comment] 2021-06-02 11:00
Reduced the example to
```
abstract contract A {
    function f() public view mod {
        require(block.timestamp > 10);
    }
    modifier mod() virtual;
}
```

The assert can be replaced by a `require` but not by a regular statement.

**Closed as completed** 2021-06-03 14:56 UTC
Labels: bug :bug:, should compile without error
