### ISSUE TITLE
Function lookup doesn't work with overloading

### ISSUE THREAD

**Issue by lukehutch** [ethereum/solidity#12409] opened 2021-12-15 06:51 UTC
## Description

If trying to look up an overloaded function, e.g. `transfer` which is defined both as `transfer(address,uint256)` (ERC20) and `transfer(address,uint256,bytes)` (ERC223), then Solidity gives a warning:

```
// TypeError: Member "transfer" not unique after argument-dependent lookup in contract
this.transfer.selector
```

It would be great if it were possible to look up functions based on parameter types:

```
this.transfer(address,uint256).selector
```

## Environment

- Compiler version: 0.8.10
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client:
- Operating system: Linux

## Steps to Reproduce

As above

**Comment by ekpyron** [comment] 2022-08-12 13:01
Closing this as a duplicate of https://github.com/ethereum/solidity/issues/3556

**Closed as completed by ekpyron** 2022-08-12 13:01 UTC
Labels: language design :rage4:
