### ISSUE TITLE
Ternary operator expressions and array literal indexing are not evaluated at compilation time

### ISSUE THREAD

**Issue by 18a6** [ethereum/solidity#14129] opened 2023-04-17 00:36 UTC
## Description
Not sure if solidity evaluates RValue at runtime or compile time. 

## Environment
- Compiler version: v0.8.17.
- Operating system: Ubuntu 22.04.

## Steps to Reproduce
```
//throws compilation error
uint8 public a = 255 + 1;

//throws no compilation error although it's equivalent to the previous expression
uint8 public a = 255 + (true ? 1 : 0);
uint8 public a = 255 + [1][0]; 
```

**Comment by jinilshah21** [comment] 2023-04-17 11:01
```
//SPDX-License-Identifier: MIT
pragma solidity 0.8.17 ;
contract A {
    
    uint8 public a ;
     function s() public {//this will give compilation error
         a = 255 + 1;
     }
   
    //throws no compilation error
    function s1() public {//once called gives error
        a = 255 + (true ? 1 : 0);
    }
   
    function s2() public {//once called giver error
         a = 255 + [1][0]; 
    }
}
```
uint8 public a = 255 + 1;  gives compilation error because a cannot store more than 255, and it is evident that it will not store 255+1 as 0. 

On the other hand, other two lines do not show compilation error, but on calling the default getter function of a, it will give an outofbound error which means that a cannot store rvalue greater than 255.

**Comment by cameel** [comment] 2023-04-17 11:24
This is not a bug, just a limitation of the compiler. Expressions involving ternary operator or indexing of array literals are not evaluated at compilation time and the oversized constant cannot be detected. They're still subject to runtime overflow checks though.

We won't be addressing this directly so I'm closing the issue, but we have #3157 in the pipeline which will generally enable the compiler to evaluate more kinds of expressions at compilation time and those two cases are likely to be covered by it as well.

**Closed as not planned by cameel** 2023-04-17 11:24 UTC

**Comment by jinilshah21** [comment] 2023-04-17 11:28
Oh, I get it. Is there any issue which I can work on? I have good experience with solidity

**Comment by shahoo** [comment] 2023-04-17 13:41
Yes  I want to learn solidity
