### ISSUE TITLE
Disallow visibility specifiers in fallback functions

### ISSUE THREAD

**Issue by federicobond** [ethereum/solidity#2637] opened 2017-07-26 13:50 UTC
It does not make sense to specify visibility for fallback functions, and it's ignored anyway.

**Comment by axic** [comment] 2017-07-26 13:53
Duplicate of #1048.

**Closed as completed by axic** 2017-07-26 13:53 UTC

**Comment by federicobond** [comment] 2017-07-26 14:04
Sorry, I should have checked instead of trusting my memory.
