### ISSUE TITLE
"Stack too deep" on literal constant "0" access

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#14027] opened 2023-03-06 13:52 UTC
The use-case I am showing is really hard to believe and reproduce, we discovered it during debugging and trying to disable `stackAllocation` option under `viaIR` mode.

## Description

Using "0" (zero) literal constant unexpectedly produces "Stack too deep"

## Environment

- Compiler version: 0.8.19

## Steps to Reproduce

Using 0 literal constant produces compilation error:

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/702124/223128508-bb641776-dc96-4132-a3fd-8cc47cf4d064.png">

While using `calldata()` in non-payable method:

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/702124/223128363-41f45d6b-2c2f-47ae-99f3-4efdd62b9912.png">

**Comment by k06a** [comment] 2023-03-06 14:44
I suspect that compiler is trying to reuse constants on the stack, I believe it should push new constant on stack in case of inability to access some constant due “Stack too deep”.

**Comment by cameel** [comment] 2023-03-06 14:47
Well, dealing with such constants is the job of the stack compressor, could be something that can be improved or could be just a very complex situation where moving one thing pulls a whole sequence of other things and there's basically no freedom or movement.

But in any case, with via IR and optimizer this shouldn't cause "Stack too deep" anyway thanks to the memory mover. Do you have a link to the code that causes it? We do have known issues like #13906 and this could very well be the same thing, but would not hurt to have another repro.

**Comment by k06a** [comment] 2023-03-06 16:03
> Do you have a link to the code that causes it?

@cameel sure, check out this PR https://github.com/1inch/limit-order-protocol/pull/221 (see commit [Fix "Stack too deep" on 0 constant literal](https://github.com/1inch/limit-order-protocol/pull/221/commits/3246e378f59a10c4f12eddf79a71d728419905e3))

**Comment by k06a** [comment] 2023-03-17 13:15
BTW, don't you consider this issue as critical?

**Comment by cameel** [comment] 2023-03-23 23:55
We do, but it's not something that can be just patched quickly. The whole mechanism needs design changes. Reports of cases that break are very helpful, but they won't be addressed one by one. It will all be fixed by the rewrite that's a part of #13721, which is a current roadmap task.

> @cameel sure, check out this PR

I need to get back to this at some point. Actually, I talked about the repros with @ekpyron earlier and he says that all he needs is really just something that can be passed directly to the compiler without all the layers in between (i.e. the framework, config, etc.). So basically the Standard JSON input. Does not even need to be a minimal example. If you have that at hand and could attach it here, it would save us the hassle of having to extract it...

**Comment by sambacha** [comment] 2023-03-24 07:52
> We do, but it's not something that can be just patched quickly. The whole mechanism needs design changes. Reports of cases that break are very helpful, but they won't be addressed one by one. It will all be fixed by the rewrite that's a part of #13721, which is a current roadmap task.
> 
> > @cameel sure, check out this PR
> 
> I need to get back to this at some point. Actually, I talked about the repros with @ekpyron earlier and he says that all he needs is really just something that can be passed directly to the compiler without all the layers in between (i.e. the framework, config, etc.). So basically the Standard JSON input. Does not even need to be a minimal example. If you have that at hand and could attach it here, it would save us the hassle of having to extract it...

```json
{
  "version": "0.8.18",
  "settings": {
    "optimizer": {
      "viaIR": true,
      "optimizer": {
        "enabled": true,
        "runs": 100,
        "details": {
          "yul": true,
          "yulDetails": {
            "stackAllocation": false,
            "optimizerSteps": ""
          }
        }
      }
    }
  }
}
```

If you use the `viaIR` option, its recommended you set the [optimization step sequence](https://docs.soliditylang.org/en/v0.8.17/yul.html#optimization-step-sequence) to `"u"`, to make Hardhat work as well as possible:
[` optimizerSteps: "u", `](https://github.com/NomicFoundation/hardhat/pull/3415/files#diff-1fe5ed9021fd6c44faa887df40a9ada86f43fcdd1eb22476ad7958742834daafR32-R51)

**Comment by ekpyron** [comment] 2023-03-27 12:59
Judging from the screenshots you're posting, the compilation failure is actually due to *not* compiling via-IR, while the issue description indicates that you *are* compiling via-IR? I've seen cases in which hardhat had implicit compilation passes e.g. for code coverage, without IR, even if via-IR is generally enabled (not sure about it the circumstances, though), maybe that's what's happening?

Whether this issue occurs with via-IR enabled or disabled makes a huge difference in the severity of the problem. Non-trivial inline assembly in legacy codegen is known to be subject to issues like this rather easily and we'll not allocate resources to fixing it, but will try to transition towards via-IR codegen this year instead.

For via-IR codegen, cases similar to the described one may still occur and fall under https://github.com/ethereum/solidity/issues/14067 and https://github.com/ethereum/solidity/issues/13721, which we assigned high priority in the short term.

**Comment by k06a** [comment] 2023-03-27 13:17
We used the following settings:
```
solidity: {
    version: '0.8.18',
    settings: {
         optimizer: {
             enabled: true,
             runs: 100,
             details: {
                 yulDetails: {
                     stackAllocation: false,
                 },
             },
         },
         viaIR: true,
     },
}
```

**Comment by ekpyron** [comment] 2023-03-27 13:37
Ah, yeah, the assertion (i.e. the stack-too-deep error message) should probably distinguish between legacy codegen and via-IR codegen with disabled stack optimization. Is it surprising, though, that if you tell the compiler to use naive stack usage (that's basically what the setting does), that that'll result in stack-too-deep errors? The compiler does some optimization and behaves - to a certain degree - clever in these cases, but that's exactly the part that you're disabling explicitly, so I'm not entirely sure what you're expecting here.

**Comment by k06a** [comment] 2023-03-27 14:40
@ekpyron I didn’t expected compiler to reuse constants in stack, especially when they are too deep. Solution is simple: just push these constants every time they needed, do not keep them in stack.

**Comment by k06a** [comment] 2023-03-27 14:42
We tried to measure gas overhead for this “stack allocation” feature trying to resolve stack-too-deeps on our own and compare gas usage.

**Comment by ekpyron** [comment] 2023-03-27 15:01
The fact that it reuses the constant is probably an effect of the regular optimizer, not of the stack allocation. One of the upcoming hardforks may give us ``PUSH0``, in which case we can generally avoid doing this in case of zeroes - but in general reusing a constant has the same cost of 3 gas as pushing it again, but costs at least one additional byte of code size, so generally, ignoring the effect on stack depth, it's always beneficial.

There are mechanisms in place to "rematerialize" variables with constant value in case you otherwise get a stack-too-deep error, though - I'm not entirely sure why they don't kick in here, they should. If you give me a simple direct compiler invocation that reproduces the case, I can have a quick look at that.

However, I think there's also a misunderstanding about the "stack allocation" setting here, maybe this should be documented more clearly - disabling the stack allocation setting is basically deprecated - the compiler will fall back on a naive way of allocating stack slots and will simultaneously try to reduce stack pressure by applying some optimization steps to reduce "stack pressure", which can potentially do more harm than good (and which may be the reason for the issue here).

The "stack allocation feature" does not have gas overhead itself, it should *always* produce more optimal code than the legacy path. What may result in overhead is if the more clever stack allocation is still not enough and it *additionally* needs to move variables to memory. We should probably add a setting to disable that selectively as well - but in your particular case that should be rather easy to do indirectly - if you just *not* mark the assembly block as "memory-safe", that should disable moving variables to memory and have no other effect.

But yeah, the only reason the stack allocation setting is still there is for debugging, since the naive stack allocation is easier to reproduce and anticipate by debuggers, but even that will soon be deprecated once we have better tooling support that relies on debugging data instead (which is currently being worked on).

**Comment by cameel** [comment] 2023-03-27 15:08
> One of the upcoming hardforks may give us `PUSH0`

So in about ~2 weeks. [`PUSH0` is in Shanghai](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md).

**Comment by cameel** [comment] 2023-03-27 15:10
Also, we probably should add some of that info about the stack allocation to the docs.

**Comment by nikola-matic** [comment] 2023-11-30 09:03
Heya @k06a, given the `PUSH0` support was implemented in https://github.com/ethereum/solidity/pull/14469 and https://github.com/ethereum/solidity/pull/14468, I'm tentatively closing this issue. If this is something you can still reproduce, please re-open it.

**Comment by k06a** [comment] 2023-11-30 09:12
@nikola-matic this issue was not about `0` constant, it was about handling all constants. Can we have compiler flag to prevent reusing constants on stack?

**Comment by nikola-matic** [comment] 2023-11-30 09:36
> @nikola-matic this issue was not about `0` constant, it was about handling all constants. Can we have compiler flag to prevent reusing constants on stack?

The title of the issue, as well as the description seem to indicate otherwise. The reason the issue likely occurred with zero and not another constant (sub 32) is that 0 would not have been rematerialized (optimizer step `m`) prior to `PUSH0`, unlike `PUSH1-32`.

You could change the title and re-open the issue - but the only repro we have at the moment is fairly difficult to reproduce, which doesn't make it very useful when trying to fix/implement the actual optimizer step that's responsible for this.

**Comment by k06a** [comment] 2023-11-30 10:05
This technique (reusing constants on stack) makes writing code really difficult in some cases. Imagine having "Stack too deep" in such small method where we have obviously less than 10 vars on stack...

**Comment by nikola-matic** [comment] 2023-11-30 10:27
> This technique (reusing constants on stack) makes writing code really difficult in some cases. Imagine having "Stack too deep" in such small method where we have obviously less than 10 vars on stack...

I definitely agree, it's just that this issue in its current form makes it difficult to keep track of. I.e. referring to stack too deep with zero literals in the title, as well as in the description, as well as in the repro is somewhat misleading, as this should no longer be an issue. We have a little fewer than 400 open issues, so this will just get lost if it stays this way.

I'll re-open it for now and pass it on to @ekpyron and @cameel for the final decision.

**Comment by ekpyron** [comment] 2023-11-30 14:51
There is no such thing as an explicit technique of reusing constants on stack. The Yul optimizer involves multiple transformations some of which require the code in a form in which constants are all rematerialized, some of which require equal expressions to be shared as variables.

The original issue here seems to partially be due to a misunderstanding of the ``stackAllocation`` optimization option. It's deprecated and should not be used in general.

All that being said, the main underlying issue in the compiler here is that it currently doesn't have good cost functions on the Yul level. In a recent release, we switched to rematerializing at the end of optimization, which should alleviate cases like this (restore constants, if it's cost-efficient), but it lacks good cost estimates and still behaves conservative. Note that rematerializing a constant can have a cost of up to 32 bytes in code size that we cannot just ignore. We do have a setting to tweak the trade-off here, the runs parameter to the optimizer, but it is a current known flaw of the Yul optimizer to not take that into account well enough.

However, we still have the stack compressor that should try to rematerialize all constants in the presence of stack-too-deep errors. The process needs some improvement, but the main problem may again be that this method is not reliable with ``stackAllocation`` set to false.

So in summary: yes, we're aware of issues like this. No, we cannot simply have an option to "disable reusing constants on stack". Don't try to disable the ``stackAllocation`` option to the optimizer, it may not behave as you expect. We'll be working on improving the heuristics of the Yul optimizer and making it take into account the runs parameter properly.

Furthermore, regarding the earlier question of whether we should consider this critical: this issue is about deprecated, non-default compiler settings - unless the default behaviour suffers from similar issues (it does in some cases, which we take more seriously), this is definitely *not* critical.


All that being said, the setting you desire already technically exists:
You can add the "LiteralRematerializer", which replaces all variables that have a known literal value by the literal itself, to the end of the optimizer cleanup sequence (that is after the colon ``:`` - the literal rematerializer is refererred to as ``T`` in the sequence - best followed by another pass of an unused pruner ``u``). So using ``dhfoDgvulfnTUtnIf[xa[r]EscLMcCTUtTOntnfDIulLculVcul[j]Tpeulxa[rul]xa[r]cLgvifCTUca[r]LSsTFOtfDnca[r]Iulc]jmul[jul]VcTOculjmul:fDnTOcmTu`` as the optimizer sequence should pretty much give you the behaviour you want.

**Closed as completed by ekpyron** 2023-11-30 14:51 UTC
