### ISSUE TITLE
The unary "+" in "((x) /= (2 % x)) + (-y)" reports an error

### ISSUE THREAD

**Issue by haoyang9804** [ethereum/solidity#15236] opened 2024-07-01 17:24 UTC
## Description
The unary "+" in "((x) /= (2 % x)) + (-y)" reports an error, but x = ((x) /= (2 % x)) + (-y) does not.

## Environment

- Compiler version: 0.8.27-develop.2024.6.25+commit.ce4be6e1.Darwin.appleclang

## Steps to Reproduce
```solidity
pragma solidity ^0.8.0;

contract Test {
  function f(int32 x) external pure returns (int32) {
    int32 y = 1;
    ((x) /= (2 % x)) + (-y);
    return 2;
  }
}
```
Compiling the above program raises an error complaining that `+` is disallowed in `((x) /= (2 % x)) + (-y);`. However, when I change this expression statement into `x = ((x) /= (2 % x)) + (-y);`, the compiler does not raise the error.
According to my understanding of Solidity type system, `expr /= expr` is an assignment expression, and its value equals the value of the left-hand-side identifier. I think `+` can connect the assignment expression and an identifier expression `(-y)`.

**Comment by ekpyron** [comment] 2024-07-02 13:42
Thanks for reporting, this is definitely an unintended regression introduced in 0.8.20!

**Comment by cameel** [comment] 2024-07-08 12:40
Probably a duplicate of #14624.

**Closed as completed** 2024-08-05 09:53 UTC
Labels: bug :bug:, selected for development, low effort, medium impact
