### ISSUE TITLE
The IR-based codegen allocated more memory for the struct.

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15383] opened 2024-09-02 02:48 UTC
## Description

The IR-based codegen allocated more memory for the struct. After optimization, the IR-based codegen should allocate less memory？

## Environment

- Compiler version: 0.8.26
- Target EVM version (as per compiler settings): Geth
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: Linux

## Steps to Reproduce

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
contract BugTest {
    struct Complex {
        uint256 x;
        bytes32 y;
        address z;
    }
    function testBug() public  {
        Complex memory a = Complex({
            x: 123456,
            y: keccak256(abi.encodePacked("test")),
            z: address(0x1234567890123456789012345678901234567890)
        });
        bytes memory encoded = abi.encode(a);
        assembly {
            let p := mload(0x40)
            sstore(p, 1)
        }
    }
}
```
### Legacy Codegen
storage:
```
{'388': '1'}
```
### IR-based Codegen
storage:
```
{'416': '1'}
```

The IR-based codegen's free memory pointer is positioned further back.

**Comment by mehtavishwa30** [comment] 2024-11-25 12:33
Hey @Subway2023! This behaviour is not a bug. It is, in fact, an inefficiency with memory management that has been a known issue in general and on our roadmap. To keep track of the developments on this, see the original report of this and other related issues in https://github.com/ethereum/solidity/issues/13320. The issue: https://github.com/ethereum/solidity/issues/13475, although closed, also adds important context.

I will be closing this issue as a duplicate.

**Closed as completed by mehtavishwa30** 2024-11-25 12:33 UTC
Labels: optimizer
