### ISSUE TITLE
Event overwritten with incompatible one

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#4803] opened 2018-08-12 18:40 UTC
The following code compiles without warnings, even though `Foo` overwrites the `Approve(address,address)` event with an incompatible one. This should fail to compile because it's not an overloading of `Approve` with a different signature, but a replacement of it with an incompatible one, because of the `indexed`.

```solidity
pragma solidity ^0.4.24;

contract IFoo {
    event Approve(address a, address b);
}
contract Foo is IFoo {
    event Approve(address indexed a, address b);
}
```

Related to https://github.com/ethereum/solidity/issues/4168.

**Comment by chriseth** [comment] 2018-08-13 11:46
@axic do we want to fix this with 0.5.0?

**Comment by leonardoalt** [comment] 2018-08-29 10:54
@axic This is inheritance related, since the problem is that the events from the super contract are not propagating. Do we still want it for 0.5.0 or for the Inheritance project?

**Comment by chriseth** [comment] 2020-04-01 14:07
Duplicate of #3421

**Closed as completed by chriseth** 2020-04-01 14:07 UTC
Labels: bug :bug:
