### ISSUE TITLE
SMTChecker: Unable to determine the return value of the function

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15012] opened 2024-04-12 12:41 UTC
## Environment

- Compiler version: 0.8.25
- Target EVM version (as per compiler settings): No restrictions
- Framework/IDE (e.g. Truffle or Remix): Command-line
- EVM execution environment / backend / blockchain client: None
- Operating system: Linux

## Steps to Reproduce

```solidity
contract C {
  uint x;

  function f() public view returns (uint) { return x+1; }
  function smtCheckerTest() public {
      uint256 varOut0;
      varOut0=f();
      assert(varOut0==1);
  }
}
```

```bash
solc C.sol --model-checker-engine bmc
```
![1712925694803](https://github.com/ethereum/solidity/assets/147013944/4a7e872a-a45c-43ef-a76e-ac2be9db5f9a)

**Comment by Subway2023** [comment] 2024-04-12 12:50
```solidity
contract SomeOtherContract {
    function f() public returns (int){
        return 2;
    }
}
contract ExampleContract {
    SomeOtherContract public otherContract;
    function f() public{
        otherContract = new SomeOtherContract();
        assert(otherContract.f()==2);
    }
}
```
If the called function is located in another contract, the SMTChecker correctly determines the return value.

**Comment by blishko** [comment] 2024-04-17 09:24
The difference is not in whether or not the function is in the same or other contract, the difference is that in the second example, the function returns a constant value, while in the first one it returns `x+1`. BMC engine does not keep context around so it does not know that `x` never changes. CHC engine is more powerful and should work as expected on this example. @Subway2023, can you confirm this?

**Comment by Subway2023** [comment] 2024-04-17 09:28
> ```solidity
> contract SomeOtherContract {
>     function f() public returns (int){
>         return 2;
>     }
> }
> contract ExampleContract {
>     SomeOtherContract public otherContract;
>     function f() public{
>         otherContract = new SomeOtherContract();
>         assert(otherContract.f()==2);
>     }
> }
> ```
> 
> If the called function is located in another contract, the SMTChecker correctly determines the return value.

```bash
solc SomeOtherContract.sol --model-checker-engine all
```
![1713346077892](https://github.com/ethereum/solidity/assets/147013944/d0c09500-ee0c-4dda-b225-c4c5632147d3)

**Comment by blishko** [comment] 2024-04-17 10:27
This is because it is an external call, which in general cannot be trusted even though it is a contract in the same source.
If you want to trust external call to known contracts you can add the option `--model-checker-ext-calls trusted`.
With this option CHC engine verifies that the assertion cannot be violated.

**Comment by blishko** [comment] 2024-04-23 14:14
The current behaviour matches the expected behaviour, so I am closing this issue.

**Closed as not planned by blishko** 2024-04-23 14:14 UTC
Labels: smt
