### ISSUE TITLE
[UDVT operators] Support compile-time constant eval

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#14022] opened 2023-03-02 09:22 UTC
```
type T0 is int24;
using {add as +} for T0 global;
function add(T0 x, T0 y) pure returns (T0) { return T0.wrap(T0.unwrap(x) + T0.unwrap(y)); }
T0 constant cons0 = T0.wrap(0) + T0.wrap(1);
```

errors

```
$ solc test.sol
...
Error: Initial value for constant variable has to be compile-time constant.
 --> test/libsolidity/syntaxTests/D/6d2aa9781baf289de6a94f7f3adc9c8bb7b7e463.sol:5:23:
  |
5 |   T0 constant cons0 = T0.wrap(0) + T0.wrap(1);
  |                       ^^^^^^^^^^^^^^^^^^^^^^^
````

Leaving it unlabeled because not sure if feature or bug.

**Comment by cameel** [comment] 2023-03-03 08:14
Yeah, it's not a bug (we even have a test case showing an error in such usage). Operator invocations are currently just function calls and can do things like (pure) external calls so they cannot be used in initialization of compile-time constants or for setting array sizes.

This will be possible later this year, when we have compile-time evaluation for functions (#13724). I'm going to close it because it's already considered a part of that issue.

**Closed as not planned by cameel** 2023-03-03 08:14 UTC
