### ISSUE TITLE
ABIEncoderV2 should be enabled when passing an array of string as a function parameter.

### ISSUE THREAD

**Issue by cakesoft-khushi** [ethereum/solidity#10060] opened 2020-10-17 07:29 UTC
# Description :
### When I try to pass array of string as a function parameter, I get the error as:
    Error: This type is only supported in ABIEncoderV2. Use "pragma experimental ABIEncoderV2;" to enable the feature.
     --> practice.sol:3:18:
     |
    3|     function foo(string[] memory) public{
     |                  ^^^^^^^^^^^^^^^

### But if I enable ABIEncoderV2, I get the warning as:

    Warning: This is a pre-release compiler version, please do not use it in production.

### Taking a string array as a function parameter becomes an essential while working on most of the use case problems. Passing an array of strings is more accessible than calling a function multiple times to pass an array of strings

# Steps to Reproduce :

    pragma solidity ^0.7.0;
    contract A{
        function foo(string[] memory) public{
        //code;
        }
    }

### After enabling ABIEncoderV2 :-

    pragma solidity ^0.7.0;
    pragma experimental ABIEncoderV2;
    contract A{
        function foo(string[] memory) public{
        //code;
        }
    }    

# Environment :
* Compiler Version : ^0.7.0
* Operating System : Ubuntu
* EVM execution environment / backend / blockchain client : 
* Framework/IDE :

**Comment by cameel** [comment] 2020-10-17 14:20
> But if I enable ABIEncoderV2, I get the warning as:
> 
> ```
> Warning: This is a pre-release compiler version, please do not use it in production.
> ```

Did you by chance mean some other warning? This one is not related to ABIEncoderV2 at all. You get it if you build the compiler in development mode.

If you're building the compiler yourself and want this warning to go away, just place an empty file called `prerelease.txt` in the root of the repository before the build. Making it empty tells the build system that it's not a pre-release. Or use a source bundle from the release page (e.g. [source for 0.7.3 is here](https://github.com/ethereum/solidity/releases/download/v0.7.3/solidity_0.7.3.tar.gz)) where we include it automatically.

> After enabling ABIEncoderV2 :-

The only warnings I get when compiling this example on 0.7.0 are:
```
Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> /tmp/test.sol
```

So I think your problem might be different. Could you show me how exactly you're invoking the compiler?

By the way, we're considering enabling ABIEncoderV2 by default in one of the future breaking releases (see #9609) and this is literally what you're requesting but I don't think this would fix your problem if adding the directive manually doesn't already.

**Comment by cameel** [comment] 2020-10-27 15:13
I'm going to close this because, as currently reported, this is the expected behavior. Please feel free to reopen if you have more input.

**Closed as completed by cameel** 2020-10-27 15:13 UTC
Labels: waiting for more input
