### ISSUE TITLE
[Bug] Solc considers Natspec comment that contains `@` above a `contract` as invalid Natspec comment

### ISSUE THREAD

**Issue by CJ42** [ethereum/solidity#14587] opened 2023-10-05 07:22 UTC
## Description

I am writing a contract and I am adding some Natspec comments for documentation purpose above the `contract` definition.

I have added some content inside a tag and this content includes the string `@openzeppelin/contracts` to refer to the [NPM package from OpenZeppelin](https://www.npmjs.com/package/@openzeppelin/contracts).

However, the solc compiler interprets this content as a Natspec tag and fail to compile. See the screenshot below for the error message.

<img width="997" alt="image" src="https://github.com/ethereum/solidity/assets/31145285/9e801a2a-f550-4557-8427-e9b4b539db2c">

## Environment

- Compiler version: 0.8.17 (but believe to apply to latest 0.8.21 as well)
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): Hardhat
- EVM execution environment / backend / blockchain client:
- Operating system: MacOS Monterey v12.3

## Steps to Reproduce

What is confusing is that the code below compiles without any issue.

```solidity
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.17;

/**
 * @title MyContract
 *
 * @dev Some content that includes the word `@openzeppelin/contracts`.
 */
contract MyContract {
    uint256 internal _example;
}
```

What am I doing wrong in the code below? I have copy pasted it, in case there is anything I am missing:

_This does not compile_
```solidity
/**
 * @title LSP7CompatibleERC20 extension
 *
 * @dev The interface `IERC20` is not included in the inheritance because it
 * is already inherited by `IERC20Metadata` in `@openzeppelin/contracts`.
 */
abstract contract LSP7CompatibleERC20 {
    // ...
}
```

**Comment by nikola-matic** [comment] 2023-12-11 12:23
You're referencing `@openzeppeling/contracts` on a newline, so it's parsing it as a new docstring tag, which then of course errors out, because there's no such tag as `@openzeppelin/contracts` :)

If you put the comment on the same line - it will compile. Now, this whole thing is somewhat unfortunate, but there's really no unambiguous way to differentiate between an actual docstring tag and a library reference, at least not without introducing new syntax (or at least allowing for indentation to mark subsequent newlines as part of the above docstring tag).

I'll be closing this as not a bug.

**Closed as completed by nikola-matic** 2023-12-11 12:23 UTC
Labels: bug :bug:
