### ISSUE TITLE
Docs unclear on whether 39- and 41-digit long hexadecimal literals are also validated as addresses

### ISSUE THREAD

**Issue by hacker-DOM** [ethereum/solidity#13728] opened 2022-11-17 17:29 UTC
What does this mean? 🙈 

https://github.com/ethereum/solidity/blob/0b4b1045cf3e78065f446714872926cde72e5135/docs/types/value-types.rst?plain=1#L436

Does it mean hexadecimals that are 40 hexadecimal digits long?

I was under the impression addresses have to be 20 bytes, but I could be mistaken

**Comment by cameel** [comment] 2022-11-17 23:04
In a hexadecimal literal each byte is represented by two digits. An address in such a format has 40 digits.

Anyway, this is not a bug report or a feature request so I'm closing this. Please use the [#solidity](https://gitter.im/ethereum/solidity) channel for support questions.

**Closed as not planned by cameel** 2022-11-17 23:04 UTC

**Comment by hacker-DOM** [comment] 2022-11-27 13:01
@cameel  Thanks for your response! However, think you misunderstood my question. In plain text, a range is usually implied to be inclusive (if I say something will take `between 1 and 2 days`, it translates to `1 <= days_expected <= 2`

From your response I conclude that the intention really is just 40 digits (which was my original question), so I propose it gets changed to

```
Hexadecimal literals that are 40 digits 
```

for clarity. Would you accept such a pull request, and if so, would a fork from `develop`, pull requested to `develop`, work?

**Comment by cameel** [comment] 2022-11-27 18:24
@hacker-DOM Ah, right, looks like I did understand the question differently :) Now I see what you meant.

> From your response I conclude that the intention really is just 40 digits

Actually, no :) The addresses are 40 digits but this part just says that the compiler does also check 39- and 41-digit literals and issues an error if they look like addresses. Which is true:

```
Error: This looks like an address but is not exactly 40 hex digits. It is 39 hex digits. If this is not used as an address, please prepend '00'. For more information please see https://docs.soliditylang.org/en/develop/types.html#address-literals
 --> test.sol:3:5:
  |
3 |     0xdCad3a6d3569DF655070DEd06cb7A1b2Ccd1D3F;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

You can still submit a PR if you think it should be clarified more. And yeah, in that case you'd fork `develop` and submit a PR to `develop` - though I'd recommend to still create a branch for your commit since it makes pulling in changes from the main repo easier. Take a look at our [review checklist](https://github.com/ethereum/solidity/blob/develop/ReviewChecklist.md), especially the first and the last section.
