### ISSUE TITLE
Feature request: flattened source code output

### ISSUE THREAD

**Issue by miohtama** [ethereum/solidity#5657] opened 2018-12-14 11:22 UTC
## Abstract

``solc`` could generate flattened sol source code in output JSON.

## Motivation

A flattened source code, all includes eliminated and having source in a single file, is needed for source code verification (reproducible builds). The most common venue is EtherScan and public verification.

Currently there are third party tools doing this - see ( https://github.com/BlockCatIO/solidity-flattener and https://github.com/nomiclabs/truffle-flattener ). However the add extra complexity to the toolchain, as the natural place to to produce the flattened source code would be the compiler itself as the compiler know from where it has assembled the source code files. For non-trivial source code tree doing a flattened version of a contract tends to be a labour intensive process.

## Specification

In Input Description, include new `outputSelection` option `source`. This will procude matching `source` item in `contracts` section.

## Backwards Compatibility

As this is additional change to the compiler output, I do not see it should cause 

## Earlier discussion

https://github.com/ethereum/solidity/issues/2620

https://github.com/ethereum/solidity/issues/611

**Comment by chriseth** [comment] 2018-12-14 13:41
Thank you for opening this issue! The fact that etherscan only supports single files as input is a missing feature on their side. Contract source code verification should be done based on standard-json input and not based on flattened files. Note that not all contracts can be compiled in a single file because they might import multiple contracts of the same name or use aliasing during import.

**Comment by miohtama** [comment] 2018-12-17 10:39
@chriseth Thank you for very insightful feedback.

Regardless if you are transfering a single source file or multiple source files, you need to have a method to extract these source files and bundle them for a verification.

I agree with you, the current flattened method is a poor man's `tar`.

If `standard-json` input is the answer, then we should be able to generate a bundle that contains all `standard-json` plus source code files inlined/bundled/etc. there? Then you can pass this mega JSON blob to a `solc` compiler elsewhere? 

I am aware of `ethpm` work where they try to address some of these issues through a hash links. However I feel some of `ipfs://` and `bzz://` is still futuretech and meanwhile developers need to work with git and local filesystems.

**Comment by chriseth** [comment] 2018-12-17 16:18
@miohtama Actually the solidity compiler already has such a flattener, it provides such a json bundle as you mentioned:
`solc --metadata --metadata-literal` gives you the full standard-json input needed to compile a particular contract.

**Comment by miohtama** [comment] 2018-12-18 10:19
Excellent. Will explore this.

**Comment by axic** [comment] 2019-01-29 16:48
> `solc --metadata --metadata-literal` gives you the full standard-json input needed to compile a particular contract.

Well to be clear it doesn't give the standard-json input, but an output which can be easily translated into one.

**Comment by flickmaking** [comment] 2019-02-27 18:07
@chriseth @axic @miohtama Greetings!

It was not clear to me which approach I should take. For instance, I did the following:

```
truffle-flattener ./contracts/Master.sol > ./contracts/Flattened.sol
copy ./contracts/Master.sol ./development/Master.sol
del ./contracts/Master.sol
del ./client/src/contracts/*.*
rename ./contracts/Flattened.sol ./contracts/Master.sol
```
I manually removed all the `pragma solidity ^0.5.0;` from `./contracts/Master.sol`, except the one on the first line. Then I did:
```
truffle compile --all
truffle migrate --network kovan --reset
```
When veryfying at https://kovan.etherscan.io/ which file should I use?

`./contracts/Master.sol`
or
`./client/src/contracts/Master.json`

I tried both, separately of course, and it did not verify with either, 

What should I do? Should  I bundle all the `./client/src/contracts/*.json` into a `./client/src/contracts/GrandMaster.json`? How do I do that? Would it work when verifying?

**Comment by chriseth** [comment] 2019-03-05 18:23
@flickmaking this looks like a question for the truffle framework.

**Comment by chriseth** [comment] 2019-03-05 18:23
I'm closing this since `solc --metadata --metadata-literal` is superior to the suggested method.

**Closed as completed by chriseth** 2019-03-05 18:23 UTC

**Comment by MicahZoltu** [comment] 2019-04-04 06:45
Where is `--metadata-literal` documented?

I'm not a fan of the tight integration between Swarm and solc since Swarm is still alpha and hasn't received any active development that I have seen.  I would much rather see either integration with IPFS, or even better, if `solc` had a way to spit out an input-json with the source code inlined as its output, and running solc with that single file as input (and no other files) would reproduce the build exactly

I can create a separate ticket for this if desired, but I do feel like the current `--metadata` solution isn't particularly great due to swarm dependency and complications of fetching files from swarm.
