### ISSUE TITLE
Build errors on Ubuntu 14.04

### ISSUE THREAD

**Issue by ryepdx** [ethereum/solidity#39] opened 2015-08-29 07:29 UTC
Recently did a fresh pull and tried to re-build my copy of `solc`. Got this error:

    c++: error: unrecognized command line option ‘-fstack-protector-strong’

So I updated to gcc-4.9, per a suggestion on [StackOverflow](http://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-4-9-on-ubuntu-14-04) and now I get:

```
In file included from /home/ryepdx/Code/cpp/solidity/test/contracts/Wallet.cpp:27:0:
/home/ryepdx/Code/cpp/solidity/./test/libsolidity/solidityExecutionFramework.h: In static member function ‘static dev::bytes dev::solidity::test::ExecutionFramework::encode(byte)’:
/home/ryepdx/Code/cpp/solidity/./test/libsolidity/solidityExecutionFramework.h:137:15: error: stack protector not protecting function: all local arrays are less than 4 bytes long [-Werror=stack-protector]
  static bytes encode(byte _value) { return bytes(31, 0) + bytes{_value}; }
               ^
cc1plus: all warnings being treated as errors
make[2]: *** [test/CMakeFiles/test.dir/contracts/Wallet.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/ryepdx/Code/cpp/solidity/test/contracts/AuctionRegistrar.cpp:28:0:
/home/ryepdx/Code/cpp/solidity/./test/libsolidity/solidityExecutionFramework.h: In static member function ‘static dev::bytes dev::solidity::test::ExecutionFramework::encode(byte)’:
/home/ryepdx/Code/cpp/solidity/./test/libsolidity/solidityExecutionFramework.h:137:15: error: stack protector not protecting function: all local arrays are less than 4 bytes long [-Werror=stack-protector]
  static bytes encode(byte _value) { return bytes(31, 0) + bytes{_value}; }
               ^
cc1plus: all warnings being treated as errors
make[2]: *** [test/CMakeFiles/test.dir/contracts/AuctionRegistrar.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/test.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by LefterisJP** [comment] 2015-08-29 08:11
Sorry, gcc 4.9 is not a hard requirement. When [this](https://github.com/ethereum/cpp-ethereum-cmake/pull/45) gets merged you will be able to build even with older gcc.

As for your error in solidity let me try it out now and see.

**Comment by LefterisJP** [comment] 2015-08-29 08:51
I can't reproduce your compile error with gcc 5.2. Can you try and make sure that you have pulled the latest cpp-ethereum-cmake and made a clean build of cpp-ethereum?

**Closed** 2015-09-16 11:15 UTC
Labels: help wanted
