### ISSUE TITLE
Simple Syntax for Struct Storage Pointer

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#9551] opened 2020-07-29 20:20 UTC
Currently to use a struct storage pointer/Diamond Storage I need to do this:

```solidity
DiamondStorage storage ds;
bytes32 position = DiamondStorageContract.DIAMOND_STORAGE_POSITION;           
assembly { ds_slot := position }
```

It would be really nice to be able to do this on one line without assembly.  Something like this:

```solidity
DiamondStorage storage ds = DiamondStorageContract.DIAMOND_STORAGE_POSITION 
```

`DiamondStorageContract.DIAMOND_STORAGE_POSITION` is a bytes32 constant in the [DiamondStorageContract](https://github.com/mudgen/Diamond/blob/master/contracts/DiamondStorageContract.sol) contract.

This pattern is extensively used in diamonds  which are [growing in use](https://dev.to/mudgen/ethereum-s-maximum-contract-size-limit-is-solved-with-the-diamond-standard-2189#the-diamond-standard-is-gaining-traction).

For more info see the [Diamond Standard](https://eips.ethereum.org/EIPS/eip-2535) and the [diamond reference implementation](https://github.com/mudgen/Diamond).

**Comment by axic** [comment] 2020-07-29 20:58
Duplicate of #597. Also your prior issue #8353.

**Comment by mudgen** [comment] 2020-07-29 21:02
Yes, this is specifically a request to do it without assembly, as in this example:

```solidity
DiamondStorage storage ds = DiamondStorageContract.DIAMOND_STORAGE_POSITION 
```

Where DiamondStorage is a struct and the right side is a `bytes32` variable or constant.

**Comment by axic** [comment] 2020-07-29 21:07
I understand that you are proposing a new syntax. I think this should be considered among the countless other proposals in #597, therefore I suggest to move this discussion over there.

**Comment by axic** [comment] 2020-07-29 21:10
Using different types on the two sides makes it look an implicit conversion and pretty much every instance of implicit conversion has been removed from the language. My personal view is this syntax has little chance of adoption for that reason.

**Comment by leonardoalt** [comment] 2020-07-29 21:14
> Using different types on the two sides makes it look an implicit conversion and pretty much every instance of implicit conversion has been removed from the language. My personal view is this syntax has little chance of adoption for that reason.

I agree with that and think the suggestion in this issue is incredibly dangerous.

**Comment by mudgen** [comment] 2020-07-29 21:14
I see.  @axic @chriseth What do you think the syntax could be now?

**Comment by leonardoalt** [comment] 2020-07-29 21:17
@mudgen as mentioned before, the discussion about the topic has been going on here: https://github.com/ethereum/solidity/issues/597 . Please check that issue also for the proposed ideas for syntax as well

**Comment by mudgen** [comment] 2020-07-29 21:22
@leonardoalt Okay, thanks.

**Comment by chriseth** [comment] 2020-07-30 08:35
I most generally believe that you should not hide semantics behind syntax and then call it "simple". In my opinion, the code that uses inline assembly is simpler than the other.

**Comment by mudgen** [comment] 2020-07-30 12:41
@chriseth I see what you mean, that makes sense.  I'm interested in your Solidity syntax for expressing the semantics.

**Comment by axic** [comment] 2020-07-30 12:44
Can we close this issue and focus on #597? That issue has all the syntax suggestions for this problem. I'd like to avoid scattering the discussion around this in multiple issues, because in the end that makes the resolution of this question harder.

**Comment by mudgen** [comment] 2020-07-30 12:49
@axic Yes, I can move my comments/request to the other issue. Thanks for making things better.

**Closed as completed** 2020-07-30 15:26 UTC
