### ISSUE TITLE
Codegen runs into invalid swap request (31)

### ISSUE THREAD

**Issue by leekt** [ethereum/solidity#11312] opened 2021-04-25 14:26 UTC
## Description

solidity compile fails with below error
code can be found in [here](https://github.com/minnow-dev/solidity-bug-uniswap-oracle)

```
Exception during compilation: /Users/distiller/project/libevmasm/Instruction.h(267): Throw in function solidity::evmasm::Instruction solidity::evmasm::swapInstruction(unsigned int)
Dynamic exception type: boost::wrapexcept<solidity::evmasm::InvalidOpcode>
std::exception::what: InvalidOpcode
[solidity::util::tag_comment*] = Invalid SWAP instruction requested (31).
Error HH600: Compilation failed

```

weird thing is, it succeeds if optimization is on.

PS. i guess #10931 is relevant but it is marked as resolved
PS2. i figured out it happens because of BlockVerifier.sol, but haven't found out the root cause

## Environment

- Compiler version: 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4
- Target EVM version (as per compiler settings): default for all
- Framework/IDE (e.g. Truffle or Remix): hardhat
- EVM execution environment / backend / blockchain client: not relevant i guess
- Operating system: macOS big sur 11.2.3

### to check if fails when optimization is not turned on

1. clone

`git clone git@github.com:minnow-dev/solidity-bug-uniswap-oracle`

2. npm install

`npm install`

3. compile

`npm run compile`

### to check if succeeds when optimization is turned on

1. clone

`git clone git@github.com:minnow-dev/solidity-bug-uniswap-oracle`

2. npm install

`npm install`

3. remove comments on `hardhat.config.ts`

👇 like this and try also with different "version", i've tested it works same on 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4
```
export default {
  solidity: {
    compilers :[
      {
        version: "0.8.0",
        settings: {
          optimizer: {
            enabled: true,
            runs: 200
          }
        }
      }
    ]
  },
  networks: {
    hardhat: {
      gas: 10000000,
      accounts: {
        accountsBalance: "1000000000000000000000000",
      },
      allowUnlimitedContractSize: true,
      timeout: 1000000
    },
    coverage: {
      url: "http://localhost:8555",
    },
  },
};
```

4. compile

`npm run compile`

**Comment by cameel** [comment] 2021-04-25 19:28
Looks like this started happening in 0.7.5. Here's a smaller repro:

```solidity
contract C {
    function foo() public {
        uint x;

        assembly {
            let a let b let c let d
            let e let f let g let h
            let i let j let k let l
            let m let n let o let p

            x := 0
        }
    }
}
```

The error goes away if there are less than 16 Yul variables in the assembly block or if we remove the single Solidity variable.

Also fails if all the variables are declared in Solidity rather than Yul:
```solidity
contract C {
    function foo() public {
        uint x;

        uint a; uint b; uint c; uint d;
        uint e; uint f; uint g; uint h;
        uint i; uint j; uint k; uint l;
        uint m; uint n; uint o; uint p;

        assembly {
            x := 0
        }
    }
}
```

And yeah, it's a duplicate of #10931 but we did not have a repro there so big thanks for actually posting code that triggers it!

**Comment by leekt** [comment] 2021-04-26 04:45
Thanks, do you think it will be ok for me to use 0.8.4 for the above code with optimization enabled? Since that will be a quick and easy patch for me if there aren't any other bug related to this.

**Comment by cameel** [comment] 2021-04-26 15:30
I can't guarantee anything because I haven't looked at the implementation but the bug seems to be caused by the compiler running out of stack slots. That's due to too many local variables and parameters so just using less of them (e.g. by moving parts of the code to helper functions) should a good workaround. Enabling the optimizer is good too because I think it solves your problem by just by eliminating some of the intermediate variables.

**Comment by axic** [comment] 2021-04-26 17:27
It fails on `libsolidity/codegen/ContractCompiler.cpp(880)`. If the assertion within the first branch is moved out, then at least a proper source location is shown:
```
$ solc/solc 11312.sol 
Compiler error: Stack too deep(17), try removing local variables.
 --> 11312.sol:5:9:
  |
5 |         assembly {
  |         ^ (Relevant source part starts here and spans across multiple lines).`
```

**Closed as completed** 2021-04-27 08:50 UTC
Labels: bug :bug:, should compile without error
