### ISSUE TITLE
codegen error:  Copying of type struct memory[] memory to storage not yet supported.

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15404] opened 2024-09-04 16:23 UTC
## Environment

- Compiler version: 0.8.26
- Target EVM version (as per compiler settings): None
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: Linux

## Steps to Reproduce
```solidity
contract Example {
    struct MemoryUint {
        uint field;
    }
    struct RecursiveStruct {
        RecursiveStruct[] vals;
    }
    RecursiveStruct[] storageVals;
    function test() public returns (uint) {
        uint[] memory before = new uint[](1);
        bytes memory corrupt = abi.encode(uint(32), uint(0));
        MemoryUint memory afterCorrupt;
        afterCorrupt.field = uint(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff80);
        before[0] = 123456;
        uint[][2] memory decoded = abi.decode(corrupt, (uint[][2]));
        return processDecoded(decoded);
    }
    function processDecoded(uint[][2] memory decoded) internal returns (uint) {
        assembly {
            let result := mload(add(decoded, 0x40))
            mstore(0x40, add(result, 0x20))
        }
        RecursiveStruct memory val;
        storageVals.push(val);
        return decoded[1][0];
    }
}
```
```
solc test.sol --bin
```
```
Unimplemented feature:
/solidity/libsolidity/codegen/ArrayUtils.cpp(227): Throw in function solidity::frontend::ArrayUtils::copyArrayToStorage(const solidity::frontend::ArrayType&, const solidity::frontend::ArrayType&) const::<lambda(solidity::frontend::CompilerContext&)>
Dynamic exception type: boost::wrapexcept<solidity::langutil::UnimplementedFeatureError>
std::exception::what: Copying of type struct Example.RecursiveStruct memory[] memory to storage not yet supported.
[solidity::util::tag_comment*] = Copying of type struct Example.RecursiveStruct memory[] memory to storage not yet supported.
```

**Comment by mehtavishwa30** [comment] 2024-09-16 13:00
Closing as this is a duplicate of https://github.com/ethereum/solidity/issues/12783. This is supported by via IR and is not planned to be implemented in the legacy pipeline. We just merged a small PR (https://github.com/ethereum/solidity/pull/15432) that makes it clear to users that copying of arrays and structs to storage is only unimplemented in legacy and is supported and via IR.

Additionally, please note that the latest release of the Solidity compiler ([v0.8.27](https://github.com/ethereum/solidity/releases/tag/v0.8.27)) includes a change that makes the compiler report this behaviour as an error instead of an ICE.

**Closed as not planned by mehtavishwa30** 2024-09-16 13:00 UTC
Labels: bug :bug:
