### ISSUE TITLE
"Warning: Unnamed return variable can remain unassigned" with constant assert(false)

### ISSUE THREAD

**Issue by ToweringTopaz** [ethereum/solidity#11674] opened 2021-07-17 03:56 UTC
## Description

The compiler shows the following for some functions where it is untrue: Warning: Unnamed return variable can remain unassigned. Add an explicit return with value to all non-reverting code paths or name the variable.

If the condition of such an assert or require evaluates to false as a constant, the warning is incorrect. All non-reverting code paths have explicit returns.

## Environment

- Compiler version: 0.8.6, 0.8.7 nightly 7.15
- Target EVM version (as per compiler settings): any
- Framework/IDE (e.g. Truffle or Remix): remix
- EVM execution environment / backend / blockchain client: N/A
- Operating system: N/A

## Steps to Reproduce

    function testFunc(uint _n) internal pure returns (uint) {
        if (_n == 7) return 0;
        if (_n == 3) return 1;
        assert(false); // require(false) also triggers the warning
    }

**Comment by cameel** [comment] 2021-07-18 16:13
Duplicate of #11265. The compiler currently does not analyze the condition inside `assert()`/`require()` so it cannot tell that your function will never go past it. As a workaround you can use `revert`.

**Closed as completed** 2021-07-26 12:46 UTC
