### ISSUE TITLE
Unable to check existence of precompiled contract by its address or get its code in VM or Sepolia testnet

### ISSUE THREAD

**Issue by amit-supraoracles** [ethereum/solidity#15428] opened 2024-09-12 09:25 UTC
## Description
For the precompiled contract : `BN256Pairing (0x08)`
1. Since it is a contract, I want to view its code by its address.
2. I want to verify if this specific precompiled contract is available on the Sepolia testnet.

**Current Output :** Shows `false and 0x`
**Expected Output :** Should `show true and some code`

## Environment

- Compiler version: 0.8.0
- Framework/IDE (e.g. Truffle or Remix): Remix IDE
- EVM execution environment : Sepolia Testnet
- Operating system: Linux

## Steps to Reproduce
Deploy following smart contract in Sepolia testnet and hit `checkPrecompileExists` or `getCode` (0x0000000000000000000000000000000000000008)

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract PrecompileChecker {
   
    // Function to check if code exists at the BN256Pairing precompile address
    function checkPrecompileExists() public view returns (bool) {
         address BN256PAIRING = address(0x08);
        uint256 size;
        assembly {
            size := extcodesize(BN256PAIRING)
        }
        return size > 0;
    }

    // Function to get the code at a specified address
    function getCode(address _address) public view returns (bytes memory) {
        bytes memory code;
        assembly {
            // Get the size of the code at the specified address
            let size := extcodesize(_address)
            // Allocate space for the code
            code := mload(0x40)
            // Update free memory pointer
            mstore(0x40, add(code, add(size, 0x20)))
            // Store the size of the code
            mstore(code, size)
            // Copy the code to memory
            extcodecopy(_address, add(code, 0x20), 0, size)
        }
        return code;
    }
}


```

**Comment by mehtavishwa30** [comment] 2024-09-16 10:26
Closing this as it is not a bug in the Solidity compiler. This is due to the fact that the EVM bytecode does not have precompile codes and it is highly unlikely that it will be supported at the EVM level to allow code introspection.

**Closed as not planned by mehtavishwa30** 2024-09-16 10:26 UTC
Labels: bug :bug:
