### ISSUE TITLE
Release verification

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/solidity#2576] opened 2017-07-17 14:46 UTC
We're working on figuring out how/if we can verify solidity versions and releases.  My first inclination was to see if the release tags were using signed commits.  At a glance it doesn't appear they are.

https://help.github.com/articles/signing-commits-using-gpg/

Some of us who are working on package manager functionality would like a way to verify that the commit hashes for a version of solidity are in fact authentic.  We know that we can use github as the oracle and just choose to trust any hash found in the solidity repository but that's less than ideal.  It would be nice to have a static set of public keys we could verify signed commits against.

Thoughts?

**Comment by axic** [comment] 2017-07-18 09:25
Our work in progress issues are #628 and #2238.

In short: metadata would go into a contract.

**Comment by chriseth** [comment] 2017-07-25 13:54
If ENS is as convenient for you, I would prefer to use that. I think it provides much better key management than GPGs web of trust.

**Comment by chriseth** [comment] 2020-06-11 14:33
Closing as duplicate of #628

**Closed as completed by chriseth** 2020-06-11 14:33 UTC
