### ISSUE TITLE
Solidity compiler outputs truncated source map?

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#10837] opened 2021-01-22 22:10 UTC
## Description

So, this bug was found in an 0.5.16 project that I can't easily upgrade to a current version; however I'm filing a bug report anyway because I don't see any indication that this issue was ever reported elsewhere or explicitly fixed.  So, there's still a chance it might exist.  Apologies for the poor, highly-non-minimal, reproduction example, but this isn't my project and I'm not very familiar with it.

The bug seems to be that, under certain situations, the compiler outputs a source map that is too short.  I have no idea what causes this.  In the particular example where I found it, the bytecode is 2976 instructions long, with a total length of 5221 bytes.  (Note that this is constructor bytecode.)  However, the source map is a mere 472 instructions long, cutting off abruptly after the `AND` instruction at PC 843.

So, apologies again for the less-than-ideal reproduction example and the outdated version, but there definitely seems to be a problem here.  Of course, there's a decent chance it's already fixed!  But I figure I have to report this anyway.

## Environment

- Compiler version: 0.5.16
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Truffle
- Operating system: Linux Mint 20.1 Ulyssa 64-bit

## Steps to Reproduce

The issue can be observed in [this Truffle project](https://github.com/fodisi/hackapay).  (More specifically, commit 515f2b1, if there's any ambiguity there.)

With Truffle installed, run `truffle compile --all`.  Then inspect `build/contracts/ContestTeam.json`.  Specifically, the `bytecode` field, which holds the constructor bytecode, and the `sourceMap` field, which holds the constructor source map.  You'll see that the constructor source map is only 472 instructions long.  If you disassemble the bytecode, or if you capture the `opcodes` compiler output, you'll see that it's much longer than 472 instructions.

For ease of reference, I've put the relevant information, including the full JSON compiler input, in [this GitHub gist](https://gist.github.com/haltman-at/ba346ea19f90b20b49dead4a2ff70708).  This way you won't need to use Truffle to reproduce the issue.  For the compiler output, I just listed the parts that seemed to be relevant -- the assembly, constructor bytecode, constructor opcodes, and constructor sourcemap for the `ContestTeam` contract.  Again, sorry about the non-minimality of the example, but it's what I have.

Thank you!

**Comment by chriseth** [comment] 2021-01-25 19:13
From the files you linked in the gist, I don't see a problem. The constructor assembly seems to be properly annotated with source locations until the end: https://gist.github.com/haltman-at/ba346ea19f90b20b49dead4a2ff70708#file-assembly-txt-L486
And these locations match with the end of `sourcemap.txt`: https://gist.github.com/haltman-at/ba346ea19f90b20b49dead4a2ff70708#file-sourcemap-txt

The linked assembly for the constructor also end at line 498 https://gist.github.com/haltman-at/ba346ea19f90b20b49dead4a2ff70708#file-assembly-txt-L498 which sounds more consistent with 472 instructions than with 2976. Note that the runtime opcodes are considered data for the constructor and thus do not appear in the source references of the constructor.

Am I seeing something wrong here?

**Comment by haltman-at** [comment] 2021-01-25 21:30
Hm, it's possible I've misdescribed the issue.  There definitely is a problem here, but it may not be that the source map is truncated.

I should perhaps describe how this originally came up.  It came up originally when investigating [this issue](https://github.com/trufflesuite/truffle/issues/3713), which arose from trying to debug a particular transaction generated in that project; Truffle Debugger crashed after the code ran off the end of the source map.  So, I interpreted that as "the source map is too short".  We could instead perhaps interpret it as "the contract accidentally has reachable code in its data segment"?

However, the latter explanation doesn't make sense to me, considering where it is that the source map ends.  As mentioned, the last mapped instruction is an `AND`.  I'm pretty sure the code segment would ordinarily end with some sort of instruction that affects the control flow, not an `AND` that lets it just run off into the data segment!

If you want to reproduce this original problem, well, just try creating a new `ContestTeam` with any nonzero address passed as the argument, and step through the resulting transaction, and you'll run off the end of the source map.

All the action here happens in the base constructor, since the constructor has no body besides these.  `Payable` has no explicit constructor and inherits only from an interface.  First comes `AttendeeRole`'s constructor, although (due to the optimizer, I infer) the `_addAttendee` call is put off till later.  We then enter the `Pausable` constructor, which runs fine.  Then we get back to that `_addAttendee` call that .  Note that `ContestTeam` overrides this function, so that's the version that gets called.  The `whenNotPaused` modifier runs fine.  Then we've got the call to `super._addAttendee`, i.e., the version in `AttendeeRole`.  Due to the optimizer the exact flow is a bit out of order here, but this is still basically how things go.  That calls `Roles.add` in OpenZeppelin, which calls `Roles.has`... and this is where things hit a problem.

Let's look at the code for `Roles.has`.  Once we make it past the `require`, we find ourselves at a `JUMPDEST` at PC 814, instruction index 449.

The code at this point, from this `JUMPDEST` to the next `JUMP`, goes as follows:
```
JUMPDEST POP PUSH1 0x1 PUSH1 0x1 PUSH1 0xA0 SHL SUB AND PUSH1 0x0 SWAP1 DUP2 MSTORE PUSH1 0x20 SWAP2 SWAP1 SWAP2 MSTORE PUSH1 0x40 SWAP1 KECCAK256 SLOAD PUSH1 0xFF AND SWAP1 JUMP
```
(I've copied this from the `opcodes` output, which is why it says `KECCAK256` instead of `SHA3`.)

Evidently, this is the code for retrieving `role.bearer[account]`, and then returning from `has`; here `role.bearer` is a `mapping (address => bool)`.

As you can see, after the `SHA3 SLOAD` sequence, there's a `PUSH1 0xFF AND` (to make sure we only get the lowest byte, since this is a `bool`), followed by a `SWAP1 JUMP` (to return to the caller; the return address on the stack at this point is 0x0026d, which is indeed in `Roles.add`, right after the call to `Roles.has`).  That `AND` there, at PC 843, instruction index 471, is the last instruction in the source map.  The `SWAP1 JUMP` following it, and all subsequent instructions, do not appear in it, because there are only 472 instructions in the source map and that `AND` was the last one.

So, that's why I described it as a truncated source map -- because we actually run off the end of it while trying to debug this transaction.  And this doesn't look like we ran off the end of it into the data section; it looks like we ran off the end of it in the middle of fetching a mapping value, in the course of ordinary code.

So I don't know whether somehow the optimizer combined code and data here or something, but one way or another, the end result is that we have ended up with a source map that is too short.

I don't know how to read the assembly file well enough to say whether you're seeing something wrong there.  It's entirely possible, as far as I know, that that part is being generated correctly.  But by the time we've got our ultimate result, i.e. source map and bytecode (or opcodes, as these seem to match), something has gone wrong, whether it was before assembly generation or after.

**Comment by haltman-at** [comment] 2021-01-26 15:13
Btw, here's something really weird... I figured I should see if I could indeed create a more minimal example of the problem, and maybe even try it with an updated compiler version.  So my first step, naturally, was to prune out from the input all the sources not actually necessary to compile the `ContestTeam` contract.  When I did this, the problem went away, as best I can tell??  So that's certainly surprising...

(I'm wondering if this may be due to those other sources somehow affecting the operation of the optimizer, as the result seemed to run more in-order and skip fewer things?)

**Comment by haltman-at** [comment] 2021-02-26 23:50
FWIW, I've found a second example of this, although it's also with Solidity 0.5.x.  Specifically it can be observed in [this](https://github.com/cds-amal/balancer-core) Truffle project, in the constructor bytecode for the `BPool` contract.  The constructor source map is only 241 instructions long, ending at PC 408, but the constructor code continues past that position and on running it you'll find a jump to PC 409.  So once again on running it you end up past the end of the sourcemap.

**Comment by mehtavishwa30** [comment] 2023-12-04 14:59
Thank you for detailing the issue. We will be closing this for now and will only investigate further in case we are able to reproduce this for the currently supported compiler versions.

**Closed as completed by mehtavishwa30** 2023-12-04 14:59 UTC
Labels: bug :bug:, needs investigation
