### ISSUE TITLE
 👋 Big Issue: Can't pass any require statement. (All require statement return false always.)

### ISSUE THREAD

**Issue by ericlewis966** [ethereum/solidity#13558] opened 2022-09-23 21:02 UTC
👋Hi. 👋
I am working with ERC1155 standard smart contract.

But now all require statements in the contract return **false** even **require(true)**.

I am so confused about this issue.

What's happened in the contract and how can I fix it?

(build env is Hardhat)

**Comment by Marenz** [comment] 2022-09-26 12:26
Based on this description we will not be able to help. Could you provide a reproduceable minimal test case demonstrating your problem?

**Comment by dev-soumyadeep** [comment] 2022-09-27 15:21
Need more info , please share code

**Comment by cameel** [comment] 2022-10-20 18:50
I'm going to close this since the issue provides no information about the problem. Feel free to reopen if you can show how to reproduce it with the compiler. As it is, it sounds more like a configuration problem with the framework.

**Closed as not planned by cameel** 2022-10-20 18:50 UTC
Labels: waiting for more input
