### ISSUE TITLE
ICE when overriding a struct getter with a Natspec-documented return value and the name in the struct is different: "No return param name given"

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12528] opened 2022-01-14 00:26 UTC
## Description
When a virtual function has a documented return parameter, overriding it with one that returns a struct instead triggers an internal compiler error.

Such an override is valid (see https://github.com/ethereum/solidity/issues/11826#issuecomment-902835510) but apparently we don't have any tests covering it with Natspec.

The error happens also if the return value is unnamed.

It does not happen when you give the getter the type of the field (rather than the whole struct).

I found this while trying to compile [Uniswap v3](https://github.com/Uniswap/v3-core) with 0.8.11. Apart from missing explicit conversions this was the only issue preventing successful compilation.

## How to reproduce
```solidity
interface I {
    /// @return abc A value
    function p() external view returns (uint abc);
}

struct S {
    uint xyz;
}

contract C is I {
    S public override p;
}
```
```
Internal compiler error:
/solidity/libsolidity/interface/Natspec.cpp(201): Throw in function static Json::Value solidity::frontend::Natspec::extractReturnParameterDocs(const std::multimap<std::__cxx11::basic_string<char>, solidity::frontend::DocTag>&, const std::vector<std::__cxx11::basic_string<char> >&)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: No return param name given: xyz
[solidity::util::tag_comment*] = No return param name given: xyz
```

## Environment

- Compiler version: 0.8.11

**Comment by bshastry** [comment] 2022-01-14 09:18
May be a duplicate of https://github.com/ethereum/solidity/issues/11514

**Comment by cameel** [comment] 2022-01-14 22:32
It might but the repro is not completely the same. Your case has no name in `@return`. Given that #9947 was fixed and the fix did not cover #11514, I think it's better to keep both open until we're sure both are fixed.

**Comment by Rav3nPL** [comment] 2022-01-17 22:59
Seems like it is there since 0.8.0, tried compile Uniswap v3 contracts every version from 0.8.0 up to .11

**Comment by cameel** [comment] 2022-01-17 23:07
@Rav3nPL This is going to be fixed soon, but if you need a workaround, simply rename the `_liqiudity` return value to `liquidity`. Or just remove the whole line:
```bash
sed -i '/@return _liquidity/d' contracts/interfaces/pool/IUniswapV3PoolState.sol
```

**Comment by Rav3nPL** [comment] 2022-01-18 00:30
I see PR is waiting, just wanted to point it was there for some time.
Yes, I found that nasty underscore causing this.

**Closed as completed** 2022-01-18 11:48 UTC
Labels: bug :bug:, should compile without error
