### ISSUE TITLE
The error handling component cannot output all compile-time errors.

### ISSUE THREAD

**Issue by haoyang9804** [ethereum/solidity#15522] opened 2024-10-17 19:50 UTC
## Description

The following test program includes two compile-time errors: 1) `struct_instance9`, of storage pointer type, is accessed without prior assignment; and 2) `Type uint256 is not implicitly convertible to expected type uint64` at line `uint64 a = 11 << b;`.
However, the second error seems to suppress the throw-out of the first error message. The compiler only reports the second error. If I comment out the whole contract C, the first error will be reported.
```solidity
contract contract0 {
  struct struct1 {
    bool b;
  }

  function func5() public returns (uint256 var7) {
    struct1 storage struct_instance9;
    return struct_instance9.b ? 1 : 0;
  }
}

contract C {
  function f() external returns (uint64 b) {
    uint64 a = 11 << b;
  }
}
```

## Environment

- Compiler version:0.8.28-develop

**Comment by manvirsingh1716** [comment] 2024-10-25 13:50
1. Error with struct_instance9 (Uninitialized Storage Pointer)
Problem: In Solidity, declaring a struct with storage pointer type means it points to a specific storage slot. However, since struct_instance9 is not assigned an actual storage location, the compiler flags it as an error when you attempt to access its fields.
Solution:  Using memory allocates a fresh instance of the struct for temporary use.
->change struct_instance9 to memory if you only need it within the function.

2. Error with Shift Operation (uint256 to uint64 Conversion)
Problem: When performing a shift operation in Solidity, the result defaults to uint256 type, which might not match the expected output type, especially if you want it to be a uint64. The compiler throws an error because it doesn’t implicitly cast the result of the shift operation to uint64.

Solution: Explicitly cast the result of the shift operation to uint64 to match the expected variable type.
->Perform the left shift operation on 11, then cast the result as uint64 explicitly.
Hope it helps if you want i can change the code for you. Thanks .

**Comment by batu3H** [comment] 2024-10-26 19:44
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by mehtavishwa30** [comment] 2024-11-25 12:39
Hey @haoyang9804!

Thanks for bringing this up. However, this is not a bug, but in fact it is intended compiler behaviour.

Internally, certain errors are non-fatal and let the analysis continue. On the other hand, there are other errors that are considered fatal and thus, interrupt analysis immediately, preventing other errors from being found.

Ideally, all errors would be non-fatal with the downside being that the analysis becomes more complex. With a fatal error we can assume that after the check, the code must satisfy a certain property and we no longer have to account that in further checks. That's not the case with non-fatal ones. This behaviour of the compiler is what your code is running into.

Closing this issue based on the above.

**Closed as not planned by mehtavishwa30** 2024-11-25 12:39 UTC
