### ISSUE TITLE
srcmap-runtime is inaccurate

### ISSUE THREAD

**Issue by duytai** [ethereum/solidity#8961] opened 2020-05-17 08:14 UTC
## Description

srcmap-runtime is inaccurate

## Environment

- Compiler version:  0.5.10+commit.5a6ea5b1.Linux.g++
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu

## Steps to Reproduce
I use the below command to get get srcmap-runtime of smart contract __RampInstantTokenPool__(https://etherscan.io/address/0x85e112e0f75f2b4751a647b81fcbca3bb3c78f84#code)
```bash
solc --combined-json bin-runtime,srcmap-runtime RampInstantTokenPool.sol
```
After that, I decompress srcmap-runtime and try to print out all mappings from bytecode to source code. Some mapped code are incomplete. For example:
```
equire(msg.sender == owner, "only the owner can call this");
```
It must be 
```
require(msg.sender == owner, "only the owner can call this");
```

here is decompress srcmap code snippet:
```javascript
decompress(srcmap) {
    return srcmap
      .split(';')
      .reduce((result, slfj) => {
        const [s, l, f, j] = slfj.split(':')
        const [last] = result.slice(-1)
        return result.concat({
          s: s ? parseInt(s, 10) : last.s,
          l: l ? parseInt(l, 10) : last.l,
          f: f ? parseInt(f, 10) : last.f,
          j: j || last.j,
        })
      }, [])
  }
```

**Comment by chriseth** [comment] 2020-05-18 09:54
Confirmed, all start and end locations seem to be off by one for this contract in remix when using the "copy to clipboard" feature of etherscan. Other contracts are fine. My guess would be that this is due to a two-byte unicode character.

**Comment by chriseth** [comment] 2020-05-19 19:09
Ah, ok, it seems to be the copyright symbol. Could be a duplicate of https://github.com/ethereum/solidity/issues/4614

**Comment by Marenz** [comment] 2020-05-20 16:09
I can confirm that the copyright sign is causing this.

**Comment by Marenz** [comment] 2020-05-20 16:16
I also think this is a duplicate of #4614 and will close this one in favor of the other.

**Closed by Marenz** 2020-05-20 16:16 UTC
Labels: bug :bug:
