### ISSUE TITLE
Compiler does not consider events when validating contract inheritance

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#3421] opened 2018-01-22 17:32 UTC
Decision from call:
 - event overloading is fine
 - event overwriting should be disallowed (there should not be two event declarations in an inheritance hierarchy that have the same event signature (after "index" has been stripped))

error starting from 0.7.x

-----

Test case 1:

```solidity
pragma solidity ^0.5;

contract Sender {
    event Send(address from);
}

// ❌ This should fail -- event signature does not conform to parent
contract SpecialSender is Sender {
    event Send(address indexed from);
}
```

And after https://github.com/ethereum/solidity/issues/3419 ... test case 2

```solidity
interface iSender {
    event Send(address from);
}

// ❌ This should fail -- event signature does not conform to parent
interface iSpecialSender /* is iSender */ {
    event Send(address indexed from);
}
```

**Comment by fulldecent** [comment] 2018-01-22 17:35
Side note: I am blowing up with issues lately. Are my contributions welcome here, or am I complaining too much and wasting everyone's time? I'm doing this for fun, nobody is sponsoring me. So I hope this is having a positive impact.

Is there a chat room for actual contributors here? Gitter is all beginner questions and is absolutely useless for me.

What is the vetting process for me to become a member of the Ethereum github organization?

**Comment by chriseth** [comment] 2018-01-23 17:07
@fulldecent yes, we noticed :)

we have https://gitter.im/ethereum/solidity and https://gitter.im/ethereum/solidity-dev - the former is for users the latter for contributors.

As far as the issue is concerned: This is actually not different for functions. We have an open issue to restrict such inheritance for functions, it would be great if you could cross-link that!

**Comment by fulldecent** [comment] 2018-01-23 20:31
Sorry I'm having trouble finding that other issue. But here is a test case:

```
pragma solidity ^0.4.19;

interface A {
    function bob() public;
}

contract B is A {
    function bob(uint256 mary) public pure {
        mary = mary;
        return;
    }
}
```

**Comment by fulldecent** [comment] 2019-12-02 13:32
Updated per call today

**Comment by axic** [comment] 2020-04-01 14:01
This also compiles without warnings:
```
contract Sender {
    event Send(address from);
}

contract SpecialSender is Sender {
    event Send(address from) anonymous;
}
```

**Comment by axic** [comment] 2020-04-01 14:03
A longer discussion is #4168.

**Comment by chriseth** [comment] 2020-07-13 13:44
Fixed in https://github.com/ethereum/solidity/pull/9326

**Closed as completed by chriseth** 2020-07-13 13:44 UTC
Labels: breaking change :warning:
