### ISSUE TITLE
error: error.sol:33:11: Error: Expected identifier, got 'LParen'

### ISSUE THREAD

**Issue by Mxxim** [ethereum/solidity#1524] opened 2016-12-26 14:50 UTC
This is my contract code.

```linenums
contract contractA {
    
    int32[] a;
    
    function setA(int32[] aa) {
        a = aa;
    }
    
    function getA() returns (int32[]){
        return a;
    }
    
}

contract contractC {
    
    int32[] a;
    
    function setA(int32[] aa) {
        a = aa;
    }
    
    function getA() returns (int32[]){
        return a;
    }
    
}

contract contractB {
    contractA A = new contractA();
    contractC C = new contractC();
    
    C.setA(A.getA());
    
}
```
When compiling this source code, it happens error. But if there is no `C.setA(A.getA())`, it can compile.

And I find I can't pass `int32[]` type from other contract. How can I write contractB to backup contractA data to contractC ?

**Comment by chriseth** [comment] 2017-01-02 11:01
This is a question better suited for https://ethereum.stackexchange.com
The short answer is that you cannot use dynamic returned data in function calls.
Closing since this is not a bug report.

**Closed as completed by chriseth** 2017-01-02 11:01 UTC
