### ISSUE TITLE
Internal compiler error with no description about error

### ISSUE THREAD

**Issue by zemse** [ethereum/solidity#9270] opened 2020-06-29 20:54 UTC
## Description

I have a method in one contract that returns a Struct (ABI encoder v2 enabled). When I call that method in other contract with doesn't have ABI encoder V2 enabled, it gives the following error in the solc output.

```javascript
{
    component: 'general',
    formattedMessage: 'InternalCompilerError: \n',
    message: 'Internal compiler error (/root/project/libsolidity/codegen/CompilerUtils.cpp:1418):',
    severity: 'error',
    type: 'InternalCompilerError'
  }
```

However, when I also enable ABI Encoder V2 in the calling contract, it compiles. But it should not give internal compiler error and it should display error message that in calling contract that the method you are calling needs ABI encoder v2 enabled here.

## Environment

- Compiler version: `0.6.10`
- Target EVM version (as per compiler settings): `istanbul` (default)
- Framework/IDE (e.g. Truffle or Remix): Custom compile script (Repo https://github.com/KMPARDS/esn-contracts)
- EVM execution environment / backend / blockchain client: Ganache
- Operating system: macOS

## Steps to Reproduce

`OtherContract.sol`:
```solidity
// SPDX-License-Identifier: MIT

pragma solidity ^0.6.10;
pragma experimental ABIEncoderV2;

contract OtherContract {
    struct Taxi {
        uint256 numberPlate;
    }

    function methodThatReturnsStruct() public pure returns (Taxi memory) {
        // bytes32 temp;
        return Taxi({ numberPlate: 1729 });
    }
}

```

`MainContract.sol`:
```solidity
// SPDX-License-Identifier: MIT

pragma solidity ^0.6.10;
// pragma experimental ABIEncoderV2;

import "./OtherContract.sol";

contract MainContract {
    function main() public pure returns (uint256) {
        OtherContract contractVariable = OtherContract(address(0));
        OtherContract.Taxi memory result = contractVariable.methodThatReturnsStruct();
        return result.numberPlate;
    }
}

```

If you compile this, it will give a error which won't tell you what/where it went wrong. I had to give time redoing the multi file changes I introduced in my project to know that which file changes were causing this error. If you have the `pragma experimental ABIEncoderV2;`, it will work as expected.

**Comment by bshastry** [comment] 2020-07-09 12:45
I was able to reduce this to the following multi source syntactic test case:

```
==== Source: i0.sol ====
pragma experimental ABIEncoderV2;
contract D {
        struct S { int m; }
        function f() public returns (S memory) {}
}
==== Source: i1.sol ====
import "i0.sol";
contract C {
        function a() public {
                D d;
                d.f();
        }
}
```

that throws

https://github.com/ethereum/solidity/blob/8548bf1b4c4080a0a9cc5bc69ddf78d948301541/libsolidity/codegen/CompilerUtils.cpp#L1435

To reproduce

```
$ cp test.sol test/libsolidity/syntaxTests/
$ soltest -t syntaxTests/test
Running 1 test case...
/home/bhargava/work/github/solidity/test/boostTest.cpp(121): error: in "syntaxTests/test": Exception during extracted test: /home/bhargava/work/github/solidity/libsolidity/codegen/CompilerUtils.cpp(1435): Throw in function unsigned int solidity::frontend::CompilerUtils::loadFromMemoryHelper(const solidity::frontend::Type &, bool, bool)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

**Comment by chriseth** [comment] 2020-07-13 11:11
This is the problem about different ABIEncoder pragmas in different source files.

**Comment by axic** [comment] 2020-07-14 12:38
Duplicate of #8379 then?

**Comment by chriseth** [comment] 2020-07-14 13:03
maybe

**Closed as completed** 2020-10-07 08:46 UTC
Labels: bug :bug:
