### ISSUE TITLE
Failed to decode output: Error: Number can only safely store up to 53 bits ？

### ISSUE THREAD

**Issue by IcyLemon** [ethereum/solidity#3792] opened 2018-03-28 06:09 UTC
I ecountered a problem. My code snippet is below: 
```
pragma solidity ^0.4.19;
pragma experimental ABIEncoderV2;

contract EmployeeRepo {
    mapping(uint32=>Trader) public employees;

    struct Employee {
        string name;
        string orgName;
        string department;
        string position;
    }

    function get(uint32 id) constant returns(string[4] result) {
        result[0] = employees[id].name;
        result[1] = employees[id].orgName;
        result[2] = employees[id].department;
        result[3] = employees[id].position;
    }

    // other api such as add, delete...
}
```
Note: in get() method, I want to return a string array (so I use  "pragma experimental ABIEncoderV2;").

I debug above code in Remix Solidity IDE. Firstly add an employee successfully, then when I invoke get(), error occures as follow:
`error: Failed to decode output: Error: Number can only safely store up to 53 bits `

It appears that the string array's length is too large. If I modify the length of array from 4 to 1, get() works fine. 

I wonder where I went wrong, and who knows how to solve this problem?

Thanks a lot.

**Comment by chriseth** [comment] 2018-03-30 13:51
The error does not originate from Solidity. This could be a duplicate of https://github.com/ethereumjs/ethereumjs-vm/issues/114 . In any case, it seems to be an error in either ethereumjs or remix.

**Closed as completed by chriseth** 2018-03-30 13:51 UTC
