### ISSUE TITLE
Confusing compilation error starting from solc 0.6.0

### ISSUE THREAD

**Issue by barakman** [ethereum/solidity#10220] opened 2020-11-05 18:49 UTC
## Description

Prior to solc 0.6.0, the statement `arr.push(x, y);` would give the error-message:
```
Wrong argument count for function call: 2 arguments given but expected 1...
```

Starting from solc 0.6.0, the same statement gives the rather confusing error-message:
```
Member "push" not found or not visible after argument-dependent lookup...
```

It feels like your internal state-machine has been unable to find a matching "prototype" for this "function".
Or perhaps this is just a subsequent result of the changes made in `push` (not returning a value) starting from solc 0.6.0?

In either case, since `push` is a keyword (rather than a function) in the perspective of the user, it doesn't quite make sense to emit this error-message.

Moreover (and worse), this message implies that `push` cannot be used on the operand, which implies that the operand is not a dynamic storage-level array (even when it is).

## Environment

- Compiler version: 0.6.0 or higher
- Target EVM version (as per compiler settings): any
- Framework/IDE (e.g. Truffle or Remix): any
- EVM execution environment / backend / blockchain client: any
- Operating system: any

## Steps to Reproduce

```solidity
pragma solidity 0.6.0;

contract Test {
    uint256[] private arr;

    function func(uint256 x, uint256 y) public {
        arr.push(x, y);
    }
}
```

**Comment by cameel** [comment] 2020-11-06 11:16
Yeah, those error messages could be better. There's already an issue for it: #9607. It says it's about overload resolution but it's a symptom of the same problem so I added your case there.

I'm going to close this issue as a duplicate to keep the discussion in one place so if you have any comments, please post them in #9607. The issue is already in the implementation backlog so you can expect it to be fixed in one of the upcoming releases.

**Closed as completed by cameel** 2020-11-06 11:16 UTC
