### ISSUE TITLE
Error "Events not supported."

### ISSUE THREAD

**Issue by lfrickel** [ethereum/solidity#2248] opened 2017-05-07 12:04 UTC
I take an example from the "Events" section of the OFFICIAL guide to Solidity (http://solidity.readthedocs.io/en/develop/contracts.html?highlight=event#events):
```
pragma solidity ^0.4.11;

contract ClientReceipt {
    event Deposit(address indexed _from, bytes32 indexed _id, uint _value);

    function deposit(bytes32 _id) {
        // Any call to this function (even deeply nested) can
        // be detected from the JavaScript API by filtering
        // for `Deposit` to be called.
        Deposit(msg.sender, _id, msg.value);
    }
}
```
I compile this through the Parity or Remix editors and get a number of errors:
```
"msg.value" used in non-payable function. Do you want to add the "payable" modifier to this function?
        Deposit(msg.sender, _id, msg.value);
                                 ^-------^
9: 34
Events not supported.
    event Deposit(address indexed _from, bytes32 indexed _id, uint _value);
    ^---------------------------------------------------------------------^
3: 5
Parameter type "bytes32" not supported.
    function deposit(bytes32 _id) {
                     ^---------^
5: 22
Only internal function calls supported.
        Deposit(msg.sender, _id, msg.value);
        ^---------------------------------^
9: 9
Not supported.
        Deposit(msg.sender, _id, msg.value);
        ^-----^
9: 9
Member access: Only call and array length supported.
        Deposit(msg.sender, _id, msg.value);
                ^--------^
9: 17
Member access: Only call and array length supported.
        Deposit(msg.sender, _id, msg.value);
                                 ^-------^
```

Someone can explain to me: HOW CAN IT BE?
I MUST have events for my contract!
Thankful in advance for the answer!

**Comment by chriseth** [comment] 2017-05-17 09:33
The first warning is legitimate, I just submitted a fix to the documentation (you need the `payable` keyword for the `deposit` function).
Everything below the first warning seems to be taken from the why3 module and are not really compilation errors. Where exactly did you get the error messages from? Remix, for example, should only display such errors in the analysis / formal verification tab and not together with the actual compiler error messages.

**Comment by ya7ya** [comment] 2017-05-26 21:50
I'm seeing the same `Events not supported` Error too. I'm using [`solc@0.4.11`](https://github.com/ethereum/solc-js)

EDIT: this Error doesn't appear when using `web3.eth.compile.solidity` with `testrpc` , but i had to change the contract version to `0.4.6` since `testrpc` didn't get the `solc` update yet. which is what I was trying to do in the first place when I came across this error. 

**Reproducing the Error**
here is a test contract
```solidity
pragma solidity ^0.4.8;

contract ExampleContract {
  uint value;
  event TestCreated(uint num);

  function ExampleContract(uint num) {
    value = num;
    TestCreated(value);
  }

}

```
Contract compiled using this code

```javascript
var fs = require('fs')
var solc = require('solc')

var source = fs.readFileSync('./ExampleContract.sol','utf-8')
var result = solc.compile(source,1)

console.log(result)
```
output

```bash
{ contracts: 
   { ':ExampleContract': 
      { assembly: [Object],
        bytecode: '60606040523415600b57fe5b604051602080609783398101604052515b60008190556040805182815290517f5fbee550eb150cc26085cbcbe88e483d449fb743965366989ef32bc3e4e00aa09181900360200190a15b505b60338060646000396000f30060606040525bfe00a165627a7a723058201961e327070bb40c79d25e56171ec0d24b0e16a5b515eeab8cbc631c3a403a680029',
        functionHashes: {},
        gasEstimates: [Object],
        interface: '[{"inputs":[{"name":"num","type":"uint256"}],"payable":false,"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"num","type":"uint256"}],"name":"TestCreated","type":"event"}]',
        metadata: '{"compiler":{"version":"0.4.11+commit.68ef5810"},"language":"Solidity","output":{"abi":[{"inputs":[{"name":"num","type":"uint256"}],"payable":false,"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"num","type":"uint256"}],"name":"TestCreated","type":"event"}],"devdoc":{"methods":{}},"userdoc":{"methods":{}}},"settings":{"compilationTarget":{"":"ExampleContract"},"libraries":{},"optimizer":{"enabled":true,"runs":200},"remappings":[]},"sources":{"":{"keccak256":"0xf5063781a1b7bf86faa311a3a4fc47a0e87d9fddbfbc4c39ff2bf4f78f3660e7","urls":["bzzr://8b6f3143e9cb1a1a74fe96eb47fe57d618ddb9266ff11a649afdf2d7d4452a7f"]}},"version":1}',
        opcodes: 'PUSH1 0x60 PUSH1 0x40 MSTORE CALLVALUE ISZERO PUSH1 0xB JUMPI INVALID JUMPDEST PUSH1 0x40 MLOAD PUSH1 0x20 DUP1 PUSH1 0x97 DUP4 CODECOPY DUP2 ADD PUSH1 0x40 MSTORE MLOAD JUMPDEST PUSH1 0x0 DUP2 SWAP1 SSTORE PUSH1 0x40 DUP1 MLOAD DUP3 DUP2 MSTORE SWAP1 MLOAD PUSH32 0x5FBEE550EB150CC26085CBCBE88E483D449FB743965366989EF32BC3E4E00AA0 SWAP2 DUP2 SWAP1 SUB PUSH1 0x20 ADD SWAP1 LOG1 JUMPDEST POP JUMPDEST PUSH1 0x33 DUP1 PUSH1 0x64 PUSH1 0x0 CODECOPY PUSH1 0x0 RETURN STOP PUSH1 0x60 PUSH1 0x40 MSTORE JUMPDEST INVALID STOP LOG1 PUSH6 0x627A7A723058 SHA3 NOT PUSH2 0xE327 SMOD SIGNEXTEND 0xb4 0xc PUSH26 0xD25E56171EC0D24B0E16A5B515EEAB8CBC631C3A403A68002900 ',
        runtimeBytecode: '60606040525bfe00a165627a7a723058201961e327070bb40c79d25e56171ec0d24b0e16a5b515eeab8cbc631c3a403a680029',
        srcmap: '25:159:0:-;;;100:81;;;;;;;;;;;;;;;;;;;141:5;:11;;;158:18;;;;;;;;;;;;;;;;;100:81;;25:159;;;;;;;',
        srcmapRuntime: '25:159:0:-;;;;' } },
  formal: 
   { errors: 
      [ ':5:3: Error: Events not supported.\n  event TestCreated(uint num);\n  ^--------------------------^\n',
        ':9:5: Error: Only internal function calls supported.\n    TestCreated(value);\n    ^----------------^\n',
        ':9:5: Error: Not supported.\n    TestCreated(value);\n    ^---------^\n' ] },
  sourceList: [ '' ],
  sources: { '': { AST: [Object] } } }

```

**Comment by axic** [comment] 2017-05-30 08:50
@ya7ya please note that you are taking the `errors` from the `formal` object. Please ignore it if you are not interested in the Why3 output, which would be available within `formal`.

The real compilation errors would be part of the top level `errors` object.

**Comment by axic** [comment] 2017-05-30 08:56
Obsoleted by #2195.

**Comment by axic** [comment] 2017-06-22 11:59
Closing this as the `formal` object should not be checked for errors if Why3 is not required.

**Closed as completed by axic** 2017-06-22 11:59 UTC
