### ISSUE TITLE
`pop` without parentheses is accepted by the compiler as a valid storage array type member

### ISSUE THREAD

**Issue by markolazic01** [ethereum/solidity#14643] opened 2023-10-25 10:15 UTC
## Description

`pop` without parentheses is accepted by the compiler as a valid storage array type member.
Accessing `pop` does not pop the last element of an array nor perform any state-changing action.
It is perceived as a view-only attribute of the storage array type, returning type 'function (uint`N`[] storage pointer)' where `N`(uint size) is same as of the array we're operating with.

## Environment

- Compiler version: latest (0.8.21)
- Target EVM version (as per compiler settings): default (Shanghai)
- Framework/IDE (e.g. Truffle or Remix): any
- EVM execution environment / backend / blockchain client: any
- Operating system: any

## Steps to Reproduce
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.21;

contract C {
    uint256[] public a = [1,2,3];

    function c() external view {
        a.pop; //Does not produce error nor warning
    }
}
```
_Please note that the variations of described issue seem not to be present with other storage array members._
_(`push` without parentheses or `length` with parentheses does not compile.)_

## Return Value

```
TypeError: Type function (uint256[] storage pointer) is not implicitly convertible to expected type uint256.
 --> PopTest.sol:8:9:
  |
8 |         uint256 b = a.pop;
  |         ^^^^^^^^^^^^^^^^^
```

## Additional Information

During the examination of the code present in the repository I've found piece of code where the `pop` member is added.
(Right after adding 2 variations of the `push` member.)
```
members.emplace_back("pop", TypeProvider::function(
    TypePointers{thisAsPointer},
    TypePointers{},
    strings{std::string()},
    strings{},
    FunctionType::Kind::ArrayPop
)->withBoundFirstArgument());
```
_(located at: libsolidity/ast/Types.cpp @ L1927-1933)_

If this piece of code is commented out, accessing either `pop` or `pop()` will produce an error.

Since the similar problem does not occur with `push` and there is seemingly no cases of `pop` member being checked solely, that implies that compiler analyzers can oversee member created with the specific settings that `pop` is created with.

Hope this helps :)

**Comment by ekpyron** [comment] 2023-10-30 13:57
In principle, this is intentional and correct behaviour - if you're able to call ``a.pop`` as ``a.pop()``, then ``a.pop`` itself is a callable function expression.
However, it is indeed an expression without effect - for ``pure`` expressions without effect we emit a warning, but not for ``view`` expressions without effect. That is something we could consider changing.

**Comment by markolazic01** [comment] 2023-10-30 20:41
Understood, thank you for your response.
Can you by any chance provide an example of a pure expression without an effect?
Also, if `push` member is callable via `a.push()`, then why is `a.push` not a callable function expression, but throws an error instead describing that `push` member of the storage array type does not exist?
Many thanks in advance!

**Comment by markolazic01** [comment] 2023-10-31 11:26
I think also the return type of `a.pop` - 'function (uint256[] storage pointer)' - is not utilizable at all 🤔

**Comment by ekpyron** [comment] 2023-10-31 16:41
``a.push`` is ambiguous, since it has two signatures (with and without argument). For comparison, the behaviour is similar to regular functions:
```
function f() pure {}
function g() pure {}
function g(uint256) pure {}

contract C {
  function test() public pure {
    f; // valid, even though there is no effect - also missing a warning, though
    g; // error due to ambiguity
  }
}
```
The main difference is that the types of `a.push` resp. `a.pop` are function types with a bound argument and can thereby not actually be assigned to function pointers.

An example of a statement that has no effect and correctly warns about that is ``1;``.

**Comment by markolazic01** [comment] 2023-10-31 16:56
I highly appreciate your explanation, thank you very much 😊

**Comment by cameel** [comment] 2023-11-27 13:19
Since this is not a bug and has been explained, I'm closing the issue.

**Closed as not planned by cameel** 2023-11-27 13:19 UTC

**Comment by markolazic01** [comment] 2023-11-29 09:06
This issue should not be closed as it is needed to emit a warning on `view` expression without effect. 
Otherwise calling `pop` without parentheses by accident can be overseen, which can lead to various problems.

**Comment by cameel** [comment] 2023-11-29 14:22
Okay, but that's a bit different and broader than the original issue so I think it would still be better to open a new one specifically about that if you're interested in pursuing it. Here the title and the description go into detail about the original problem, and the comment about the warning is just a small digression.

Also, it's not really clear if we'd really do that in the end - this needs some discussion first, because there are reasons why we don't do that already. And it's far from our current priorities (which is the new type system). So a forum thread to hash out potential problems for that proposal might be more appropriate way to take the first stab at this. The main problem is that there are cases where statements with no effect are used to suppress warnings about unused variables. We'd need to find a good alternative mechanism for that.

**Comment by markolazic01** [comment] 2023-11-30 22:20
Thanks, I understand, I will consider creating a new issue then.
I just wanted to make sure that you guys are aware of the situation when it comes to this topic, even though it is far from critical.
Hopefully we will find out what the other developers think about this and come to a proper solution.
