### ISSUE TITLE
Constructor syntax is prone to errors.

### ISSUE THREAD

**Issue by JesseBusman** [ethereum/solidity#3526] opened 2018-02-15 15:50 UTC
# **Problem**

Having a constructor syntax that can also be parsed as a normal function is a bad idea.
The constructor is not like any other function and the syntax should not treat it as such.

For example:
```
contract Test {
    address owner;
    uint a;
    function Test(uint _a) public { owner = msg.sender; a = _a; }
}
```
Now, the programmer decides to rename the contract:
```
contract Bird {
    address owner;
    uint a;
    function Test(uint _a) public { owner = msg.sender; a = _a; }
}
```

It is very easy to forget to also rename the constructor function. If you do forget, the contract will not be initialized which can cause unexpected behaviour. Also, anyone can now call the Test function to become owner and change the value of a.

# **Solution**

I suggest adding this syntax for the constructor:
`constructor (uint _a) { owner = msg.sender; a = _a; }`

Using the `internal`, `external`, `private` and `public` modifiers on the constructor should not be allowed.

If multiple constructors are present (using the old and/or the new syntax), the compilation should fail.

The old constructor syntax should be deprecated. A warning should be given, encouraging the use of the new constructor syntax.

**Comment by federicobond** [comment] 2018-02-15 16:29
This is a duplicate of https://github.com/ethereum/solidity/issues/3196. Let's keep the discussion there.

**Comment by chriseth** [comment] 2018-02-15 18:06
People come up with the same solution independently, that hints that it is a good solution :)

**Closed as completed** 2018-02-15 18:06 UTC
