### ISSUE TITLE
Infinite gas reported for constant string getter

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3354] opened 2017-12-22 12:36 UTC
```
contract C {
  string public constant name = "Hello World";
  uint public constant num = 4;
}
```

```
Gas estimation:
construction:
   118 + 74000 = 74118
external:
   name():	infinite
   num():	208
```

(from https://github.com/ethereum/browser-solidity/issues/964)

**Comment by prashantprabhakar** [comment] 2017-12-28 06:55
+1. Can reproduce. 
```pragma solidity ^0.4.16;

contract Storage{
    string public storage1;
    function store_it(string _s) public{
        storage1 = _s;
    }
}


Gas Estimates:

> "storage1()": "infinite",
> "store_it(string)": "infinite"

**Comment by modenero** [comment] 2017-12-29 11:18
https://ethereum.stackexchange.com/a/34645/20276

![Infinite gas](https://i.stack.imgur.com/BZDyZ.png)

**Comment by chriseth** [comment] 2017-12-30 18:32
We should probably change the commandline output to say that there is no constant upper bound. While it could still be constant for this case, the word `infinite` should not be used in the general case.

**Comment by strangepowers** [comment] 2018-04-01 13:48
I'm getting something similar:
```
contract Test{
    string public arbitraryMsg;

}```

and this warning:

```Gas requirement of function Test.arbitraryMsg() high: infinite. If the gas requirement of a function is higher than the block gas limit, it cannot be executed. Please avoid loops in your functions or actions that modify large areas of storage (this includes clearing or copying arrays in storage)```

Is the use of strings discouraged on the evm?

**Comment by leberknecht** [comment] 2018-05-17 13:30
Are there any details on how Remix is doing the estimation? I have this snippet:
```solidity
contract MyContract {
    uint40 currentValue;
    function getOutstanding() public view returns(uint40) {
        return currentValue;
    }
}
```
And Remix also reports `getOutstanding` to have infinite gas requirement. While i do understand that this happens when accessing dynamic arrays or when accessing variables with no bounds, i'm struggling with understanding it here.

**Comment by chriseth** [comment] 2018-05-28 20:32
@leberknecht the gas requirements are reported as constant for me. Are you using a recent compiler? We fixed a bug in this place at some point.

**Comment by leberknecht** [comment] 2018-05-29 08:24
Hm, i'm getting this on remix webinterface with compiler version `0.4.24+commit.e67f0147`
![image](https://user-images.githubusercontent.com/1165177/40646769-79128f22-632a-11e8-9e31-72ad715fb44e.png)

**Comment by chriseth** [comment] 2018-06-04 17:40
@leberknecht could you please paste the "metadata" and "gas estimates" json from the contract "details" pane?

**Comment by leberknecht** [comment] 2018-06-05 10:57
Sure:
Metadata:
```
{"compiler":{"version":"0.4.24+commit.e67f0147"},"language":"Solidity","output":{"abi":[{"constant":true,"inputs":[],"name":"getOutstanding","outputs":[{"name":"","type":"uint40"}],"payable":false,"stateMutability":"view","type":"function"}],"devdoc":{"methods":{}},"userdoc":{"methods":{}}},"settings":{"compilationTarget":{"browser/ballot.sol":"MyContract"},"evmVersion":"byzantium","libraries":{},"optimizer":{"enabled":false,"runs":200},"remappings":[]},"sources":{"browser/ballot.sol":{"keccak256":"0x8009767b3b2a17e427ab70ac82f1230e5fc2a742fe51eec64350e28cbbb3870c","urls":["bzzr://f71ecfa0175ed150bf27b414039326a5f14987f1cea02bb2ce1d2202d1a37091"]}},"version":1}
```
Gas-Estimates:
```
{
	"Creation": {
		"codeDepositCost": "38400",
		"executionCost": "infinite",
		"totalCost": "infinite"
	},
	"External": {
		"getOutstanding()": "infinite"
	}
}
```

**Comment by jeichel-miovision** [comment] 2018-06-08 14:54
I am also seeing the same error when using the address object with solidity  0.4.22,  0.4.23, and  0.4.24.

```
pragma solidity ^0.4.22;

contract Creator {
  address creator;

  constructor() public {
    creator = msg.sender;
  }

  function getCreator() public constant returns(address) {
    return creator;
  }
}
```

Metadata:
```
{"compiler":{"version":"0.4.24+commit.e67f0147"},"language":"Solidity","output":{"abi":[{"constant":true,"inputs":[],"name":"getCreator","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"}],"devdoc":{"methods":{}},"userdoc":{"methods":{}}},"settings":{"compilationTarget":{"browser/test_a.sol":"Creator"},"evmVersion":"byzantium","libraries":{},"optimizer":{"enabled":false,"runs":200},"remappings":[]},"sources":{"browser/test_a.sol":{"keccak256":"0xa596abef0ff478d8fa8036d674f48fc67d7010463ef17dc99c6cecf915c919ce","urls":["bzzr://178340e41b4233cec04ff720740f20b0d653053a6f3a28d12a1eb01731e2c541"]}},"version":1}
```

Gas-Estimates:
```
{
	"Creation": {
		"codeDepositCost": "47400",
		"executionCost": "infinite",
		"totalCost": "infinite"
	},
	"External": {
		"getCreator()": "infinite"
	}
}
```

**HOWEVER**, solidity 0.4.21 does not give me the error (the constructor syntax is different too)
```
pragma solidity 0.4.21;

contract Creator {
  address creator;

  function Creator() public {
    creator = msg.sender;
  }

  function getCreator() public constant returns(address) {
    return creator;
  }
}
```

Metadata:
```
{"compiler":{"version":"0.4.21+commit.dfe3193c"},"language":"Solidity","output":{"abi":[{"constant":true,"inputs":[],"name":"getCreator","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"}],"devdoc":{"methods":{}},"userdoc":{"methods":{}}},"settings":{"compilationTarget":{"browser/test_a.sol":"Creator"},"evmVersion":"byzantium","libraries":{},"optimizer":{"enabled":false,"runs":200},"remappings":[]},"sources":{"browser/test_a.sol":{"keccak256":"0x024efc108da5a220a45ddc2a6dbdec1dea622bc0bbb449d7a9d26678fae3ba84","urls":["bzzr://4419c0cfb17beb0dc4bc60bc30a089e5480808f56f3fb8ceaf76da4c1642ac48"]}},"version":1}
```

Gas-Estimates
```
{
	"Creation": {
		"codeDepositCost": "47000",
		"executionCost": "20360",
		"totalCost": "67360"
	},
	"External": {
		"getCreator()": "442"
	}
}
```

**Comment by chriseth** [comment] 2018-06-13 14:14
The later reports should have the same root cause as #3779 , but the original issue is different.

The problem is that we use a loop to copy the array, even if it is of constant size and the gas estimator currently cannot cope with that. This is probably much easier to solve once we have yul.

**Comment by cameel** [comment] 2022-09-27 00:51
Closing because we decided to remove the gas estimator from the compiler: #13566.

**Closed as not planned by cameel** 2022-09-27 00:51 UTC
