### ISSUE TITLE
Stack too deep error with a struct containing 16 members, only with public state variable

### ISSUE THREAD

**Issue by 0xSamWitch** [ethereum/solidity#14106] opened 2023-04-08 18:30 UTC
## Description

Using a struct with 16 members gives stack too deep error both with and without viaIR, but only with `public` state member. Changing `private` state and creating an equivalent function returning the struct compiles fine.

## Environment

- Compiler version:
0.8.19
Remix & hardhat using viaIR
## Steps to Reproduce

Try and compile this:
```js
contract C {

  struct Struct {
    uint16 u1;
    uint16 u2;
    uint16 u3;
    uint16 u4;
    uint16 u5;
    uint16 u6;
    uint16 u7;
    uint16 u8;
    uint16 u9;
    uint16 u10;
    uint16 u11;
    uint16 u12;
    uint16 u13;
    uint16 u14;
    uint16 u15;
    uint16 u16;
  }  

  Struct public myStruct; // <--- public gives an issue
}
```
> CompilerError: Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.

Using viaIR:
> YulException: Cannot swap Slot RET with Variable value1: too deep in the stack by 1 slots in [ RET headStart value14 value13 value12 value11 value10 value9 value8 value7 value6 value5 value4 value3 value2 value15 value0 value1 ]
memoryguard was present.

Now compile this, changing to private state variable and external function exporting it, works fine:
```js
contract C {

  struct Struct {
    uint16 u1;
    uint16 u2;
    uint16 u3;
    uint16 u4;
    uint16 u5;
    uint16 u6;
    uint16 u7;
    uint16 u8;
    uint16 u9;
    uint16 u10;
    uint16 u11;
    uint16 u12;
    uint16 u13;
    uint16 u14;
    uint16 u15;
    uint16 u16;
  }
  
  Struct _myStruct; // <--- remove public and make getter

  function myStruct() external view returns (Struct memory) {
    return _myStruct;
  }
}
```

**Comment by Upendra-Jaiswal** [comment] 2023-04-08 19:09
Assign it to me please

**Comment by Upendra-Jaiswal** [comment] 2023-04-08 19:21
Actually the issue is that when you declare struct in external scope,it doesn't get stored on stack, it is stored on storage or memory which has huge space to store. When you declare it as public,it gets stored in stack and gives "stack too deep" error.

**Comment by Upendra-Jaiswal** [comment] 2023-04-09 06:27
What do you want me to do actually??  I can make changes to .CPP files.. but what are the exact changes should be made... Should I increase it from 16 to 32..?? What is ultimate goal?? To remove this error completely from compiler??

**Comment by Upendra-Jaiswal** [comment] 2023-04-09 20:01
Error should be removed from public scope??

**Comment by ekpyron** [comment] 2023-04-11 10:19
First of all, for historic reasons, the generated public getter does *not* return a ``Struct memory``, but the 16 elements of the struct as tuple, which makes it harder to generate code for it without stack issues.

However, if I compile your example with ``--via-ir --bin --optimize`` with solc 0.8.19, it actually compiles without issues. So I guess the issue you're seeing is that hardhat compiles the contract with reduced optimizations (e.g. ``--yul-optimizations "u"`` does trigger the issue). This is something that should still be fixed - ideally even with minimal optimizations only, the compiler should be able to prevent stack issues in this case.

So I'm linking this to https://github.com/ethereum/solidity/issues/13721, which is the umbrella issue for solving remaining stack issues like this and closing this issue as an example case to be considered for #13721.

**Closed as completed by ekpyron** 2023-04-11 10:19 UTC
Labels: bug :bug:
