### ISSUE TITLE
It seems currently impossible to override a "function"

### ISSUE THREAD

**Issue by niklasb** [ethereum/solidity#5555] opened 2018-11-30 22:08 UTC
## Environment

- Compiler version:
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

**Comment by chriseth** [comment] 2018-11-30 22:48
Thanks for opening this issue! Could you please provide some example code that you expect to compile correctly but that does not?

**Comment by chriseth** [comment] 2018-11-30 22:49
I guess this is a duplicate of #5556

**Closed as completed by chriseth** 2018-11-30 22:49 UTC
Labels: waiting for more input
