### ISSUE TITLE
Why always return 0 (Use Remix IDE)

### ISSUE THREAD

**Issue by seantw1974** [ethereum/solidity#12218] opened 2021-10-31 09:24 UTC
The simple example always return zeron (0) 
No matter what number we set , always return 0, Why???
Any issue ???

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.4.16 <0.9.0;

contract SimpleStorage {
    uint storedData;

    function set(uint x) public {
        storedData = x;
    }

    function get() public view returns (uint) {
        return storedData;
    }
}
```

**Comment by cameel** [comment] 2021-10-31 13:49
Are you sure you're testing it correctly? Did you call `set()` with a non-zero value and did it execute without errors in the Remix console?

I just tried this in Remix and I did not get zero:
1. Open Remix
2. Create a new file and paste your code.
3. Click "Compile" on the "Solidity compiler" tab.
3. Click "Deploy" on the "Deploy & run transactions" tab.
4. Type 42 next to the orange button named "set" and click the button.
5. Click the blue button named "get".

After this Remix shows `0: uint256: 42` under the "get" button which shows that the value is not zero.

Anyway, this is not a bug report or a feature request so I'm closing this. Please drop in at the [#solidity](https://gitter.im/ethereum/solidity) channel if you want more help with this.

**Closed as completed by cameel** 2021-10-31 13:49 UTC

**Comment by seantw1974** [comment] 2021-10-31 16:26
what VM you choose？
I can sure I set value

Kamil Śliwak ***@***.***>於 2021年10月31日 週日，下午9:49寫道：

**Comment by cameel** [comment] 2021-10-31 17:08
Everything left at defaults, i.e. compiler version 0.8.7 and the compiler's default for EVM which is `london` in 0.8.7.
