### ISSUE TITLE
`Assembly exception for bytecode` occurs when compiling with via-ir

### ISSUE THREAD

**Issue by lum7na** [ethereum/solidity#15248] opened 2024-07-08 07:11 UTC
## Description

Using solc 0.8.25, `Assembly exception for bytecode` occurs when compiling the following code with via-ir and optimization enabled.

I noticed a similar open issue on https://github.com/ethereum/solidity/issues/15004#issue-2234103337, but it was triggered by a whole repo. Thus, I've provided a smaller code snippet. I hope this is triggered for the same reason and aids in identifying the cause of the issue.

Additionally, I've observed that changing the function name to something shorter allows for successful compilation.

```solidity
contract C {
  uint256 immutable x;
  uint256 immutable y;
  mapping(uint => uint) public m;

  function f_32930() public payable returns(uint256) {
    uint[] memory arr = new uint[](3);
    arr[0] = 1;
    for (uint i = 0;y < arr.length; ++i) {
      arr[i] = i + 1;
    }
    arr[1] = 2;
    arr[2] = 3;
    return arr.length;
  }


  function f_88824(uint256 n, uint256 delta) private returns(uint256) {
    if (n < delta) {
      return 0;
    }
    uint256 dev = n % delta;
    return n;
  }

  function f_91785() public payable returns(uint256) {
    return f_88824(y, y);
  }
  
  function f_54386(uint256 a, uint256 b) public payable returns(uint256) {
    return 42 - b;
  }

  function f_64304(uint256 a, uint256 b) public payable returns(uint256) {
    return 18 > x ? b : a;
  }

  function f_15731(uint256 a, uint256 b) public payable returns(uint256) {
    return (((uint256(keccak256(abi.encodePacked(y)))) > x ? x : 1) > b) ? b : a;
  }

  function f_01593(uint256 amount) public payable returns(uint256 bal) {
    uint256 v = 20;
    if (f_54386(((y - 1) > f_64304(y, v) ? v : f_64304(0, 18) - f_64304(v, f_64304(0, v))), 42) > 0) 1;
    
    for (uint a = 0; 0 < 10; a = 42 + 1) {
      if ((x > (x + 1) ? (f_15731(2, 42) - f_01593(x)) > x ? x : f_15731(y, y) : 0) > 0) amount = 0x1;
      break;
    }
    return amount;
  }

  function f() public payable returns(uint256, uint256) {
    return ((1 > y ? y : 42), y);
  }

  constructor (uint _a) {
    x = 42;
    y = 23;
    m[_a] = 7;
    new uint[](4);
  }

}
```

Compiling with `solc-0.8.25 out.sol --via-ir --optimize --bin`:

```
Internal compiler error:
/solidity/libsolidity/interface/CompilerStack.cpp(1410): Throw in function void solidity::frontend::CompilerStack::assembleYul(const solidity::frontend::ContractDefinition&, std::shared_ptr<solidity::evmasm::Assembly>, std::shared_ptr<solidity::evmasm::Assembly>)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Assembly exception for bytecode
[solidity::util::tag_comment*] = Assembly exception for bytecode
```

## Environment

- Compiler version: 0.8.25

**Comment by matheusaaguiar** [comment] 2024-08-23 02:48
Thanks for the report @lum7na !
This specific issue stopped happening after version `0.8.26` release (this [PR](https://github.com/ethereum/solidity/pull/15030) more specifically) so I am closing this.
We are aware that the root cause of it still persists and that hopefully will be fixed by #15354.

**Closed as completed by matheusaaguiar** 2024-08-23 02:48 UTC
Labels: bug :bug:
