### ISSUE TITLE
bug(compiler): Insufficient checks for storage access in `pure` functions

### ISSUE THREAD

**Issue by 0xPhaze** [ethereum/solidity#14039] opened 2023-03-10 11:19 UTC
## Description

The compiler does not catch the case when a struct pointer is converted from `storage` location to `memory`.
This allows a storage variable to be read in a pure function 

## Steps to Reproduce
```solidity
pragma solidity ^0.8.0;

struct Settings {
    uint256 a;
    uint256 b;
}

contract MyContract {
    Settings settings;

    constructor() {
        getSettingsDS().a = 0xa;
        getSettingsDS().b = 0xb;
    }

    function getSettingsDS() internal pure returns (Settings storage s) {
        assembly {
            s.slot := 0x1234
        }
    }

    /// @notice This returns a compiler error:
    /// ```
    /// Compiler run failed
    /// error[2527]: TypeError: Function declared as pure, but this expression (potentially) reads from the environment or state and thus requires "view".
    /// ```
    // function getSettings() public pure returns (Settings memory) {
    //     return settings;
    // }

    /// @notice So does this.
    // function getSettingsA() public pure returns (uint256 a) {
    //     return getSettingsDS().a;
    // }

    /// @notice This compiles.
    function getSettings() public pure returns (Settings memory) {
        return getSettingsDS();
    }
}
```

**Comment by cameel** [comment] 2023-03-10 20:58
Thanks for reporting!

This has actually been reported already so I'm closing as a duplicate of #11573.

**Closed as not planned by cameel** 2023-03-10 20:58 UTC
