### ISSUE TITLE
`UnusedStoreEliminator` step missing in documentation

### ISSUE THREAD

**Issue by pcaversaccio** [ethereum/solidity#13511] opened 2022-09-08 22:06 UTC
## Summary

In the current documentation on the [Yul-based optimizer steps](https://docs.soliditylang.org/en/latest/internals/optimizer.html#optimizer-steps), the step `UnusedStoreEliminator` is missing.

**Comment by hrkrshnn** [comment] 2022-09-09 00:18
Actually, duplicate of https://github.com/ethereum/solidity/issues/13497

**Closed as completed by hrkrshnn** 2022-09-09 00:18 UTC
Labels: documentation :book:, annoys users :cry:, easy difficulty, optimizer
