### ISSUE TITLE
compile time constant variable declaration should allow use of pure functions

### ISSUE THREAD

**Issue by thegostep** [ethereum/solidity#9292] opened 2020-07-02 12:39 UTC
## Description

compile time constant variable declaration should allow use of pure functions

## Environment

- Compiler version: 0.6

## Steps to Reproduce

```solidity
// current
uint256 public constant ATTRIBUTE_ID = uint256(keccak256(bytes("attribute")));

// expected
uint256 public constant ATTRIBUTE_ID = stringToUint("attribute");

function stringToUint(string memory attribute) public pure returns (uint256 attributeID) {
	return uint256(keccak256(bytes(attribute)));
}
```

**Comment by chriseth** [comment] 2020-07-02 12:59
Duplicate of https://github.com/ethereum/solidity/issues/3122
The reason we did not implement this yet is mainly because the keyword `pure` does not really mean the same thing as "compile-time constant" - it just means "does not read blockchain state".

**Closed as completed by chriseth** 2020-07-02 12:59 UTC
