### ISSUE TITLE
Events used in external library functions are not included in calling contract ABI

### ISSUE THREAD

**Issue by davidbrai** [ethereum/solidity#14245] opened 2023-05-18 10:02 UTC
Hi, it looks like events emitted by libs in functions that are called externally are not included in the calling contract's ABI.
This is when using solc 0.8.20

Here's example code:

```
pragma solidity ^0.8.20;

library L {

    event E_external(uint256 n);
    event E_internal(uint256 n);
    event E_using_external(uint256 n);
    event E_using_internal(uint256 n);

    function f_external() external {
        emit E_external(5);
    }

    function f_internal() internal {
        emit E_internal(5);
    }

    function f_using_external(uint256 x) external {
        emit E_using_external(x);
    }

    function f_using_internal(uint256 x) internal {
        emit E_using_internal(x);
    }
}

contract Counter {
    uint256 public number;

    using L for uint256;

    event E_event(uint256 n);

    function g(uint256 x) public {
        L.f_external();

        L.f_internal();

        emit E_event(7);

        x.f_using_external();

        x.f_using_internal();
    }
}

```

The ABI for `Counter` includes the following events:
`E_event`, `E_internal`, `E_using_internal`

But not:
`E_external` & `E_using_external`

**Comment by cameel** [comment] 2023-05-18 17:12
That's by design. The compiler can't be sure what events may be emitted by an external call. It's not just for events - it's been working like this with errors for quite a while now.

Even if the source is available, in a general case there's no way for the compiler to ensure that at the time the call is executed the address will really contain the contract/library built from that source. It can be easily changed during deployment.

Even if the compiler assumed that it must match the source, in many cases the source is not available anyway - e.g. when you call a contract via an interface or make a low-level call. In those cases the list of events would still be incomplete.

**Comment by davidbrai** [comment] 2023-05-19 07:14
@cameel I see. thanks for the quick reply.

Is there any best practice on how to deal with it?
Currently we're copy-pasting the event definitions from the library to the calling contract.

**Comment by cameel** [comment] 2023-05-19 13:32
The event is reported in the ABI of the library so I guess if you're interested in that information, you can get it from there if you know your contract uses that library.

This is potentially something that could be made easier at a higher level, i.e. in frameworks, which actually know how and where the contract gets deployed and therefore can make more assumptions.

By the way, what is your use case? What specifically do you use that information for? And what do you do when your contract calls another contract that emits an event you know nothing about? Especially when you have no access to the source or ABI of that contract.

**Comment by NunoFilipeSantos** [comment] 2023-05-19 18:06
If this is by design, let's close it.
Feel free to reference it on any of our communication channels.

**Closed as not planned by NunoFilipeSantos** 2023-05-19 18:06 UTC
Labels: bug :bug:
