### ISSUE TITLE
Support constant identifiers in array declarations.

### ISSUE THREAD

**Issue by eepstein** [ethereum/solidity#3143] opened 2017-10-28 18:41 UTC
It would be v nice if code like this compiled:

    contract Foo {

        uint8 constant _max_sz = 16;

        address[_max_sz] public bar;

       ...
    }

But the compiler gives:

`TypeError: Invalid array length, expected integer literal.`

Can this feature be added to the language: support for `constant` size (vs. a literal size value) when declaring a fixed length array.

**Comment by axic** [comment] 2017-10-28 19:44
Duplicate of #716.

**Closed as completed by axic** 2017-10-28 19:44 UTC
