### ISSUE TITLE
`abi.encodeWithSignature()` not working on testnet or mainnet

### ISSUE THREAD

**Issue by awaissakhi11** [ethereum/solidity#12292] opened 2021-11-17 07:54 UTC
Hello everyone, i am stuck on one problem. i am trying to deploy multisign with wbtc code but when i generated data which required in multi contract from   function getData() public view returns (bytes memory){
        return abi.encodeWithSignature("mint(address,uint256)","0x02F2bDf4F8E0FC6E17CA66a9EeBbEa5Ad4bfe712",10000000000);
    },   its working on EVM, but its when i tried on ropsten and binance test chain its giving me response but when i am giving passing to multisign contract there its saying false.

https://etherscan.io/address/0x2260fac5e5542a773aa44fbcfedf7c193bc2c599#code
https://etherscan.io/address/0xd409db68d0e6e97e1cb1f3eb0bd38de278bc3c68#code
 i am using these contracts

**Comment by cameel** [comment] 2021-11-17 17:25
I'm not sure I understand the problem. Can you describe it in more detail and also explain what indicates that it's a bug in the compiler and not just a mistake in your code? There are many reasons why you might get the wrong response on mainnet and more often than not it's caused by wrong addresses, insufficient balances and stuff like that rather than an issue in the compiler itself.

It would be best if you could provide a small self-contained contract that reproduces the problem.

**Comment by cameel** [comment] 2021-11-17 17:33
By the way, the way you call `abi.encodeWithSignature()` is incorrect. `"0x02F2bDf4F8E0FC6E17CA66a9EeBbEa5Ad4bfe712"` is not an `address` literal. It's a string literal and is not equivalent. To encode an address you must use `0x02F2bDf4F8E0FC6E17CA66a9EeBbEa5Ad4bfe712` (i.e. without quotes).

**Comment by cameel** [comment] 2021-12-01 11:28
I'm going to close it since there's no feedback and I think the problem was actually caused by the incorrect use of `abi.encodeWithSignature()` I mentioned above.

If you still think there's a problem in the compiler, feel free to provide more details and reopen.

**Closed as completed by cameel** 2021-12-01 11:28 UTC
Labels: waiting for more input
