### ISSUE TITLE
[isoltest] Command-line options are not validated

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11916] opened 2021-09-09 12:05 UTC
## Description
[CommonOptions::validate()](https://github.com/ethereum/solidity/blob/v0.8.7/test/Common.cpp#L112-L137) is responsible for validating command-line options passed to `soltest` and `isoltest`. It only runs in `soltest` though. In `isoltest` command-line parameters are not validated.

## Environment
- Compiler version: `0.8.8-develop.2021.9.9+commit.f6eecb8c.mod.Linux.g++`
- Operating system: Arch Linux

## Steps to Reproduce

In `soltest` it works as expected:
```bash
soltest -- --enforce-gas-cost --evm-version spuriousDragon
```
```
Test setup error: /solidity/test/Common.cpp(127): Throw in function virtual void solidity::test::CommonOptions::validate() const
Dynamic exception type: boost::wrapexcept<solidity::test::ConfigException>
std::exception::what: Gas costs can only be enforced on latest evm version.
[solidity::util::tag_comment*] = Gas costs can only be enforced on latest evm version.
```
But for some reason it is not executed in `isoltest`:
```bash
isoltest --enforce-gas-cost --evm-version spuriousDragon
```
```
Running tests...
```

**Comment by hawkess** [comment] 2021-09-17 13:53
I'd like to handle this issue, but I have some questions about intended behavior. 

Currently, there are flags that are [hardcoded](https://github.com/ethereum/solidity/blob/20ca5c13617b923e559044213c49445d365511d4/test/tools/IsolTestOptions.cpp#L79-L81) to always default to a certain value in the IsolTestOptions class regardless of command line arguments. Is this intended behavior that should be preserved? 

If so, that introduces another bug as the parse function would always overwrite the enforceGasTest boolean such that the CommonOptions validation would never print a message even if there were an evm version mismatch because the command line flag would just be toggled off and the test would run anyway. So should that behavior be changed while leaving the other two defaults intact, or should all values be set based solely on the command line flags to allow for full validation and customization at the expense of current default behavior?

**Comment by cameel** [comment] 2021-09-17 15:21
@hawkess Good observation. This is not how these options were meant to work :) We should remove these hard-coded values and just set them as defaults. All values should come from command-line flags. I don't think people expect the current behavior. I surely didn't :)

I think it was done this way because option definitions are in `CommonOptions` and that's where you would need to add defaults. So we should either find a way to change them after the fact (not sure if `program_options` allows that) or just pass the defaults we want as arguments to `CommonOptions` constructor.

**Comment by hawkess** [comment] 2021-09-17 19:29
After tackling this for a while, it seems that the command line options interface in its current form cannot support `true` defaults for a boolean option without rendering the option obsolete. For `bool_switch`es (which all options currently use), the created value_semantic won't accept any explicit value. If the option is present on the command line, the value will be `true` and you can't supply `false`, meaning a `bool_swtich()->default_value(true)` is always on, in which case moving the defaults as an argument to the `CommonOptions` constructor does little to solve the problem. 

A small hack using `enforceGasTest = enforceGasTest || (evmVersion() == langutil::EVMVersion{});` will produce the expected errors for validation and retain current default behavior, but for the long-term a change to the `CommonOptions` such that each option is a `value<bool>` so they accept explicit boolean values appears to be the most rational approach. However that modifies the user-facing cli and seems out of scope for this issue.

**Comment by cameel** [comment] 2021-09-20 13:53
> but for the long-term a change to the `CommonOptions` such that each option is a `value<bool>` so they accept explicit boolean values appears to be the most rational approach. However that modifies the user-facing cli and seems out of scope for this issue.

You mean something like `isoltest --enforce-gas-cost true`/`isoltest --enforce-gas-cost false`? That would be inconsistent with how `solc` does it. I think it's more typical for CLI programs to have a `--no-XXX` version of the flag as I suggested in https://github.com/ethereum/solidity/pull/11996#discussion_r712128764.

**Comment by hawkess** [comment] 2021-09-20 14:41
There is a `program_options` method for setting implciit values, so you could still use `--enforce-gas-cost` with no argument or `--enforce-gas-cost=false`, but it does alter the auto-generated help signature to show `--enforce-gas-cost arg` which might not be desirable since the arg is actually optional.

**Comment by cameel** [comment] 2021-09-20 17:02
I think we could live with these booleans being listed on the help screen. That's actually a nice idea. Less hassle than having to define the `--no-` variants separately. I'm not sure if we'd go for that in `solc` but `soltest` is an internal tool so I would not be against changing it here.

**Closed as completed** 2021-09-22 15:43 UTC
Labels: bug :bug:, easy difficulty, testing :hammer:
