### ISSUE TITLE
Can recover (supposedly) truncated integer using assembly

### ISSUE THREAD

**Issue by ssadler** [ethereum/solidity#13729] opened 2022-11-19 23:15 UTC
## Description

Assembly code can recover integer data that was supposedly truncated, for example, if `uint40 d = uint40(imBiggerThanUint40)`, regular solidity code will see `d` as truncated to 40 bits wheras assembly will not.

## Environment

- Compiler version: 0.8.17
- Target EVM version (as per compiler settings): not specified
- Framework/IDE: Hardhat
- EVM execution environment / backend / blockchain client: hardhat node
- Operating system: ubuntu 22.04

## Steps to Reproduce

```solidity
function recoverTruncated() public view returns (uint, uint) {
  uint d = 336;                                               
  d = (d << 40) + d;                                          
                                                              
  uint40 d40 = uint40(d);                                     
                                                              
  uint b;                                                     
  assembly {                                                  
    b := d40                                                  
  }                                                           
  return (d40, b);                                            
}                                          
                   
// (336, 369435906933072)
```

**Comment by cameel** [comment] 2022-11-20 21:42
That's by design. From docs on [Variable Cleanup](https://docs.soliditylang.org/en/latest/internals/variable_cleanup.html):
> Ultimately, all values in the EVM are stored in 256 bit words. Thus, in some cases, when the type of a value has less than 256 bits, it is necessary to clean the remaining bits. The Solidity compiler is designed to do such cleaning before any operations that might be adversely affected by the potential garbage in the remaining bits.

> Note that access via inline assembly is not considered such an operation: If you use inline assembly to access Solidity variables shorter than 256 bits, the compiler does not guarantee that the value is properly cleaned up.

It would only be a bug if you managed to observe these dirty bits without using inline assembly. Inline assembly lets you peek behind the scenes and see the raw values of the stack slots where local variables are stored and these are 256-bit long, regardless of the types assigned to them at the Solidity level. The fact that these higher bits are still copied and remain dirty (and are not instead cleared when the value is stored) should be considered an implementation detail. E.g. it might change between compiler versions or different code generators.

**Closed as not planned by cameel** 2022-11-20 21:42 UTC

**Comment by ssadler** [comment] 2022-11-20 22:44
Right, understood, thanks for the answer. I would add though that you can recover the garbage bits even from a function call parameter, so referential transparency isnt provided in that case, which is a bit of a gotcha. Some kind of indication could be useful :slightly_smiling_face: .

**Comment by cameel** [comment] 2022-11-20 23:17
It is, as long as you stick to Solidity types and do not poke into the extra bits of the stack slot using inline assembly. The compiler takes care to ensure that the content of the visible bits of any value returned or stored by the function does not depend on them so the referential transparency is preserved for any high-level type. Technically, it's not even guaranteed that these extra bits are even there. In storage where multiple smaller values can be packed into a single slot, there may be no unused bits even with smaller types. They're only "wasted" in memory or on stack because reusing them costs more than using a separate slot for each value.

If you care about these bits and want to preserve this high-level behavior, in inline assembly, you have to do the cleanup yourself. The compiler won't try to modify your Yul code and automatically inject any kind of cleanup code automatically in between instructions in your inline assembly.

**Comment by ssadler** [comment] 2022-11-21 00:32
> The compiler won't try to modify your Yul code and automatically inject any kind of cleanup code automatically in between instructions in your inline assembly.

Just so I'm sure we're talking about the same thing, I'm referring to a case like the following:

```solidity
function someDecode(uint40 d) internal pure returns (...) {
    assembly {
        // Some operation that assumes that d is already truncated
    }
}
```

In order for the above to work as expected, you need to truncate manually before the assembly block. In my case, I found it in testing, but I could also imagine it being missed. It's just a bit of a rough edge :slightly_smiling_face:. The language tries hard to protect you from overflow in the typical case, but in this case it's easy to make the wrong assumption.

I wouldn't suggest that the language should modify YUL code; if anything, I think it could detect this particular case where sub-word integers are being read inside an assembly block and truncate them automatically. I could even take a stab at it, if it would be a welcome change.

**Comment by cameel** [comment] 2022-11-21 02:01
The language doesn't protect you here because you're using the assembly to explicitly step outside of the bounds of the language :) If you do that, the implicit assumption is that you know what you're doing and you're aware of how things work internally. It's easy to make a mistake, so having a thorough set of tests to check your assumptions, as you did, is very strongly recommended.

The compiler tries to be very hands-off once you go down to assembly level because it's hard to tell what's a genuine mistake and what is a clever use of assembly that carefully steps around compiler's mechanisms. There are cases like the memory escalator (that moves variables to memory to prevent "stack too deep" errors), where we have to actually know that but we can only rely on the developer telling us  - which is why the concept of [memory safe assembly](https://docs.soliditylang.org/en/latest/assembly.html#memory-safety) exists. Even then, unsafe assembly is not wrong, it just signals to the compiler that certain optimizations must not be performed.

In this particular case, I don't think a warning is warranted. You don't really *have to* truncate. Depending on what you do with the value these extra bits might not affect the relevant 40 bits of your result at all and it might be cheaper to just let them be. And it's also allowed to actually read or write them. It may lead to undefined behavior but does not have to and ensuring that it doesn't is up to the developer.
