### ISSUE TITLE
Cancun Support

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#14739] opened 2023-12-20 10:42 UTC
Prerequisites:
- [x] Bump [evmc version to 11.0.0](https://github.com/ethereum/evmc/releases/tag/v11.0.0) and evmone to the upcoming 11.0.0 release (promised for Dec 21st  2023)
  Tracked in https://github.com/ethereum/solidity/issues/14744 @nikola-matic

We need full support for the [EIPs of Cancun](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/cancun.md):

- [x] [EIP-1153: Transient storage opcodes](https://eips.ethereum.org/EIPS/eip-1153)
  PR: https://github.com/ethereum/solidity/pull/14737 @matheusaaguiar 
- [x] [EIP-4788: Beacon block root in the EVM](https://eips.ethereum.org/EIPS/eip-4788)
  TODO: verify if there's anything for us to do here. @r0qs 
- [x] [EIP-4844: Shard Blob Transactions](https://eips.ethereum.org/EIPS/eip-4844)
  Tracked in https://github.com/ethereum/solidity/issues/14740 @r0qs 
- [x] [EIP-5656: MCOPY - Memory copying instruction](https://eips.ethereum.org/EIPS/eip-5656) @cameel
  Tracked in https://github.com/ethereum/solidity/issues/14741
- [x] [EIP-6780: SELFDESTRUCT only in same transaction](https://eips.ethereum.org/EIPS/eip-6780) @r0qs 
  This will mean documentation adjustment, so falls together with https://github.com/ethereum/solidity/issues/13889.
  We should also add the change in behaviour to the deprecation warning.
- [x] [EIP-7516: BLOBBASEFEE opcode](https://eips.ethereum.org/EIPS/eip-7516)
  Tracked in https://github.com/ethereum/solidity/issues/14742 @nikola-matic 

Additionally we will need to:
- [x] Adjust our documentation with sufficent details about Cancun. (https://github.com/ethereum/solidity/pull/14705#pullrequestreview-1756419513 and check if anything else needs to be done)
- [x] Publish a blog post about transient storage

**Comment by r0qs** [comment] 2023-12-26 23:34
>     * [ ]  [EIP-4788: Beacon block root in the EVM](https://eips.ethereum.org/EIPS/eip-4788)
>       TODO: verify if there's anything for us to do here.

Regarding this item, I did some research, and it appears that the current proposal does not require any changes in the compiler. Instead, it involves modifications to the execution and consensus clients. Although, while reading the EIP I thought that the `parent_beacon_block_root` would be exposed at the language level, but this does not seem to be the case according to the current specification. 

Originally, the EIP was drafted requiring a new opcode (`BEACON_STATE_ROOT` at `0x4A`, now used by `BLOBBASEFEE`), but it was later modified to incorporate a ["stateful" precompile](https://github.com/ethereum/EIPs/commit/d810df00b8aa8f21741a93fd9391e703d69fcd37). More recently, another change was made, the "stateful" precompile idea was dropped, and now the EIP proposes the use of what is now referred to as a ["system contract"](https://github.com/ethereum/EIPs/commit/46f8d5bc9593f096cd92f66692e115218ec1c633). As per the current specification, the `parent_beacon_block_root` would be passed as calldata to the system contract (which would have the bytecode directly deployed at the given system address), and the execution clients would write to or read from the EVM state through a system transaction. I may have misunderstood something, so it would be helpful if someone else could confirm this as well.

**Comment by cameel** [comment] 2024-01-05 18:32
I can confirm @r0qs analysis, there's nothing for us to do there. It's implemented as a system contract and does not add any new opcodes. The fact that EIP-4788 is never mentioned in [evmc 10.1...11 diff](https://github.com/ethereum/evmc/compare/v10.1.1...v11.0.0) (including the changelog) confirms that.

BTW, thanks for digging into the history of this EIP. Reading it now, I see no mention that it went from opcode, to precompile, to system contract, so that's useful to know.

**Comment by cameel** [comment] 2024-01-05 19:05
Actually, maybe absence of this in evmc does not really confirm it (e.g. MCOPY does not require any changes there either).

On the evmone side the change was done in https://github.com/ethereum/evmone/pull/709. Still, looks like this does not require any special compiler support. The VM automatically executes the system call that updates the circular buffer with block roots before every block. It does not deploy the system contract on its own, but, as far as I understand the EIP, it's not really the responsibility of the VM. Presence of the contract is optional.

It might at most affect our testing if we wanted to include contracts that call this system contract. For that I guess we'd have to deploy it when we set up the test environment? That does not seem like something we need right now though.

**Comment by cameel** [comment] 2024-01-12 15:53
For `EIP-6780: SELFDESTRUCT only in same transaction` we may need some changes in tests. At least the self-destructed contracts should no longer be cleared: https://github.com/ethereum/solidity/blob/fbbac9c1969c054071d9d6456e5151cb4ae53c19/test/EVMHost.cpp#L186-L187

This might not be the only change.

**Comment by k06a** [comment] 2024-02-22 23:13
Any plans to have `transient` modifier for variables?

**Comment by cameel** [comment] 2024-02-23 10:25
It's planned but not a priority at the moment. Other things, especially the new type system and improving the IR pipeline before we enable it by default, take precedence.

**Comment by cameel** [comment] 2024-03-13 23:12
#13889 was the last thing to do here and it's done so I'm closing the issue.

**Closed as completed by cameel** 2024-03-13 23:12 UTC
Labels: selected for development, medium effort, high impact
