### ISSUE TITLE
[SMTChecker] ICE in SMTEncoder::initFunction

### ISSUE THREAD

**Issue by gitpushOmnik** [ethereum/solidity#9764] opened 2020-09-09 05:03 UTC
## Description

    pragma experimental SMTChecker;
    function calculate(uint x) returns(uint){
      return ~x;
    }
    contract C{
       uint x;
      constructor(){
        x = calculate(1)-calculate(2);
      }
     }

throws

  

> [solidity/libsolidity/formal/SMTEncoder.cpp](https://github.com/ethereum/solidity/blob/f964966090f7e3571e20144fd4aa0b6391aea26e/libsolidity/formal/SMTEncoder.cpp#L709)
Line 709

Error produced :

    Throw in function void solidity::frontend::SMTEncoder::initFunction(const solidity::frontend::FunctionDefinition &)
    Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
    std::exception::what: 
    [solidity::util::tag_comment*] = 
## Environment

- Compiler version:latest develop
- Target EVM version (as per compiler settings): -
- Framework/IDE (e.g. Truffle or Remix): -
- EVM execution environment / backend / blockchain client: - 
- Operating system: MacOS

## Steps to Reproduce

    $ solc test.sol

**Comment by bshastry** [comment] 2020-09-09 10:38
This is likely a duplicate of #9654

**Comment by gitpushOmnik** [comment] 2020-09-09 10:50
It is one of the free function related issues. Same error is being thrown for many issues :)

**Comment by axic** [comment] 2020-10-30 18:22
This is now tracked by #9636.

**Closed as completed by axic** 2020-10-30 18:22 UTC
