### ISSUE TITLE
Find Position of Calldata Variable

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#9762] opened 2020-09-08 13:59 UTC
Currently there is no way to find the starting position of a calldata variable in calldata. This prevents easily parsing calldata with `calldataload`.

Example:
```Solidity
function myfunction(bytes[] calldata info) {
        for(uint i; i < info.length; i++) {
            bytes calldata item = info[i];
            // No way to get the starting position of item in order to
            // parse it with calldataload
        }
    }
```
You might ask why not just use array slices and `abi.decode`.  The answer is that the calldata might not be ABI encoded.  It might be using `abi.encodePacked` and so `abi.decode` cannot be used to decode it.

**Comment by leonardoalt** [comment] 2020-09-08 14:05
@mudgen sorry, but I don't fully understand it. For which variable are you trying to get the position?

**Comment by chriseth** [comment] 2020-09-08 14:09
The planned way to get access is via inline assembly in a similar way as access to storage slot and offset is provided. Is this what you are requesting?

**Comment by mudgen** [comment] 2020-09-08 15:05
@leonardoalt In the example above the `item` variable.

@chriseth Yes, that sounds great.

**Comment by ekpyron** [comment] 2020-10-08 18:09
Just to be clear: the idea now (IIUC) is to add ``x.offset`` and (for dynamically sized arrays ``x.length``) to all calldata variables when accessed in inline assembly, just the way we have ``x.slot``, when ``x`` is in storage.

**Comment by chriseth** [comment] 2020-10-08 18:11
Actually this is a duplicate of https://github.com/ethereum/solidity/issues/8917

**Closed as completed by chriseth** 2020-10-08 18:11 UTC
