### ISSUE TITLE
[Bug] Includes aren't relative to the include's current directory

### ISSUE THREAD

**Issue by Nielsbishere** [ethereum/solidity#12337] opened 2021-11-27 18:04 UTC
## Description

It seems when the following folder structure is used, solc doesn't know it should find files relative to the current directory of the file that is being included.

## Environment

- Compiler version: 0.8.10
- Target EVM version (as per compiler settings): ^
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: ^
- Operating system: N/A

## Steps to Reproduce

File structure:
```
MainContract.sol
inc/MyInclude.sol
myDependency/MainContract.sol
myDependency/inc/MyInclude1.sol
```

./MainContract:
```
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.8.9;

import "./inc/MyInclude.sol";
import "./myDependency/MainContract.sol";

contract Test {

    function test() external {

    }
}
```

MyInclude and MyInclude1 in both myDependency/inc and inc/ respectively (Empty for testing purposes)
```
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.8.9;
```
myDependency/MainContract.sol:
```
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.8.9;

import "./inc/MyInclude1.sol";
```

To demonstrate this takes the root directory, MyInclude1 can be changed to MyInclude and it will include ./inc/MyInclude instead of ./myDependency/inc/MyInclude1.sol. This works in remix with solc 0.8.10

**Comment by cameel** [comment] 2021-11-28 07:45
I cannot reproduce this. This compiles just fine on 0.8.10 for me:
```bash
mkdir -p inc/ myDependency/inc/

echo "contract A {}" > inc/MyInclude.sol
echo "contract B {}" > myDependency/inc/MyInclude1.sol

cat <<EOF > MainContract.sol
import "./inc/MyInclude.sol";
import "./myDependency/MainContract.sol";
contract C is A {}
EOF

cat <<EOF > myDependency/MainContract.sol
import "./inc/MyInclude1.sol";
contract D is B {}
EOF

solc MainContract.sol
```

No errors. If you check metadata, it shows that the files get the right names in the internal VFS and have the right content:
```bash
solc MainContract.sol --metadata --metadata-literal | sed -e 's/^Metadata:$//' | sed -e 's/^=======.*=======$//' | jq
```
```json
  "sources": {
    "MainContract.sol": {
      "content": "import \"./inc/MyInclude.sol\";\nimport \"./myDependency/MainContract.sol\";\ncontract C is A {}\n",
      "keccak256": "0x72d4b71e81255655a2e2773fa2c383c945ffab621f0a5580b98e441ab8027329"
    },
    "inc/MyInclude.sol": {
      "content": "contract A {}\n",
      "keccak256": "0x883c1af8f1ad6d7cdfb8aaed151eebcdd940c8dae0a659cb38054c7ec32ce890"
    },
    "myDependency/MainContract.sol": {
      "content": "import \"./inc/MyInclude1.sol\";\ncontract D is B {}\n",
      "keccak256": "0x6de7bce3e4feb9bda5ae841c12db677055d8a248862254aca7a54ced63734266"
    },
    "myDependency/inc/MyInclude1.sol": {
      "content": "contract B {}\n",
      "keccak256": "0xdeedc4bc3a740226a6e739585f4032a88e95bfab8f96cbf3632299f597143a9d"
    }
  },
```
If I change `import "./inc/MyInclude1.sol";` to `import "./inc/MyInclude.sol";` in `myDependency/MainContract.sol` the compiler does not use `inc/MyInclude.sol`. Instead I get an error:
```
Error: Source "myDependency/inc/MyInclude.sol" not found: File not found.
 --> myDependency/MainContract.sol:1:1:
  |
1 | import "./inc/MyInclude.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Nielsbishere** [comment] 2021-11-28 11:06
You're right I seem unable to reproduce it in that way too now. However if I remove the ./ before the include path it doesn't take a relative path it seems like. My project used that so that's why it didn't compile, now it works fine. Though this might still be an issue

**Comment by cameel** [comment] 2021-11-28 13:39
It's not a bug, it's by design. `import "a.sol"` is not just a shorter version of `import "./a.sol"`. Imports starting with `./` or `../` (relative imports) are relative to the path of the importing file while others (direct imports) are taken as is. It's explained in detail in [Import Path Resolution > Imports](https://docs.soliditylang.org/en/latest/path-resolution.html#imports).

**Comment by Nielsbishere** [comment] 2021-11-28 14:01
Hmm that's a bit confusing though, as other languages like C/C++ do allow this syntax. What's the reason for having absolute paths? I understand the use of @<myLib> but don't really understand the use of the other.

**Comment by cameel** [comment] 2021-11-28 16:25
C++ actually has the same exact mechanism, just with a different syntax - `#include "..."` is relative to the header path and `#include <...>` is resolved with respect to a predefined directory path, just like `--base-path` in Solidity.

Direct imports are not absolute the way you might be thinking about them. They're absolute in compiler's VFS but the VFS does not work with paths. They're just arbitrary IDs (source unit names). You specify them freely in Standard JSON - for example `/`,  `"` or `http://` are all valid names even though you might not be able to create files on disk under these names on some platforms.

The thing is that when you do not provide the content for these IDs explicitly via Standard JSON and the compiler has to load it from disk, it has to interpret the IDs. This is the job of an import callback. The native binaries have a callback that loads stuff from the filesystem so it interprets them as paths - **relative paths**. They're always relative to either the base directory or one of the include paths. So if base path is `/project/` and you do `import "a/b/c.sol"`, the compiler will load `/project/a/b/c.sol`. Note that if your import contains an ID that looks like an absolute path (e.g. `import "/a/b/c.sol"`) it's still relative to base path so you'll get `/project/a/b/c.sol` as well. The only way to have `import "/a/b/c.sol"` actually load `/a/b/c.sol` is to set the base path to an empty value. This happens to be the default value of base path for convenience but keep in mind that it's just a single corner case. Using absolute paths this way is not recommended.

`@` has no special meaning to the compiler. It's just that many projects adopted it as a naming convention and chose to name their directories in npm packages that way. E.g. if OpenZeppelin named their package `openzeppelin`, you could import stuff from it as `import "openzeppelin/contracts/..."` and the compiler would not care that there's no `@` in it..

What do you think about the docs page I linked? Have you read it? If something's not clear please submit a documentation issue and we'll clarify.

**Comment by Nielsbishere** [comment] 2021-11-28 17:06
Ah that makes sense now, it's just a bit confusing that import "./x" and import "x" are basically two different expressions in what they do. `#include <x>` clarifies that it's not relative. I have read it but it seemed confusing that virtual and local files are mixed in this way, but seems useful nonetheless

**Closed as completed** 2021-12-10 23:03 UTC
