### ISSUE TITLE
Event overloading not working with Solidity 0.50+

### ISSUE THREAD

**Issue by mrdavey** [ethereum/solidity#5970] opened 2019-02-12 09:30 UTC
## Description
Solidity event overloading (i.e. using the same name for an event, with different parameters) does not seem to be working correctly in v 0.5.0+.
This issue may be related to #1215 

## Environment

- Compiler version: ^0.5.0
- Target EVM version (as per compiler settings): 10d17f24
- Framework/IDE (e.g. Truffle or Remix): Tested in Remix and Truffle
- Operating system: MacOS

## Steps to Reproduce

Example code:

```
pragma solidity ^0.5.0;

contract Events {
    function emitEvent(bytes32 _eventName, bool _isTrue) public {
        emit LogEvent(_eventName, _isTrue);
    }
    
    function emitEvent(bytes32 _eventName, address _account) public {
        emit LogEvent(_eventName, _account);
    }
    
    event LogEvent(
        bytes32 eventName,
        bool isTrue
    );

    event LogEvent(
        bytes32 eventName,
        address account
    );
}
```

_On Remix:_
When calling `emitEvent(bytes32 _eventName, address _account)`, the correct `LogEvent` (with `address` parameter is **not** emitted. 
When calling `emitEvent(bytes32 _eventName, bool _isTrue)`, the correct `LogEvent` (with `bool`) **is** emitted.

_In Truffle:_
Only the `LogEvent` (with `bool`) is emitted when both `emitEvent` functions are executed.

**Comment by chriseth** [comment] 2019-02-12 09:53
Thanks for reporting! We have a test for overloaded events and it is not failing, so my first suspicion would be that this could be a bug in Remix or perhaps with the ABI.

This is the output I get from remix:

First function:
```
[
	{
		"from": "0xef55bfac4228981e850936aaf042951f7b146e41",
		"topic": "0xde917497ceaa39dc0a52414d0578e7c571f4bfaf40af19cc4e401b6d2f26c630",
		"event": "LogEvent",
		"args": {
			"0": "0x6162630000000000000000000000000000000000000000000000000000000000",
			"1": true,
			"eventName": "0x61626300000000[{"address":"0xef55bfac4228981e850936aaf042951f7b146e41","data":"0x61626300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001","topics":["0xde917497ceaa39dc0a52414d0578e7c571f4bfaf40af19cc4e401b6d2f26c630"],"rawVMResponse":[{"type":"Buffer","data":[239,85,191,172,66,40,152,30,133,9,54,170,240,66,149,31,123,20,110,65]},[{"type":"Buffer","data":[222,145,116,151,206[{"address":"0xef55bfac4228981e850936aaf042951f7b146e41","data":"0x61626300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001","topics":["0xde917497ceaa39dc0a52414d0578e7c571f4bfaf40af19cc4e401b6d2f26c630"],"rawVMResponse":[{"type":"Buffer","data":[239,85,191,172,66,40,152,30,133,9,54,170,240,66,149,31,123,20,110,65]},[{"type":"Buffer","data":[222,145,116,151,206,170,57,220,10,82,65,77,5,120,231,197,113,244,191,175,64,175,25,204,78,64,27,109,47,38,198,48]}],{"type":"Buffer","data":[97,98,99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]}]}],170,57,220,10,82,65,77,5,120,231,197,113,244,191,175,64,175,25,204,78,64,27,109,47,38,198,48]}],{"type":"Buffer","data":[97,98,99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]}]}]00000000000000000000000000000000000000000000000000",
			"isTrue": true,
			"length": 2
		}
	}
]
```

Second function:
```
[
	{
		"from": "0xef55bfac4228981e850936aaf042951f7b146e41",
		"data": "0x6162630000000000000000000000000000000000000000000000000000000000000000000000000000000000ef55bfac4228981e850936aaf042951f7b146e41",
		"topics": [
			"0x7465347ef066ca479e5437a3cf221261cca1fccc04005bd5af9ee2d15ca2a772"
		]
	}
]
```

So it looks like Remix was just not able to properly decode the data from the second event. The topic is different, which means Solidity at least emits a different event - I haven't checked the actual hash, though.

**Comment by chriseth** [comment] 2019-02-12 09:56
Hm, I cannot see anything wrong with the ABI either. @yann300 could you please check if this might be a problem on the remix side? Thanks!

**Comment by leonardoalt** [comment] 2019-05-13 10:11
Closing since the issue is not related to the compiler.

**Closed as completed by leonardoalt** 2019-05-13 10:11 UTC
Labels: bug :bug:
