### ISSUE TITLE
FR: Initializing constants with pure functions should be possible

### ISSUE THREAD

**Issue by migoldfinger** [ethereum/solidity#13232] opened 2022-07-01 10:10 UTC
## Abstract

At the moment it is impossible to use pure functions to initialize constants.

## Motivation

Pure functions return based on the parameters if any always the same value regardless of time or status of the contract. In a way they are acting like static functions in C# for example.
Therefore it should be possible to use pure functions to initialize constant variables.

## Specification

For gas optimization the compiler should calculate the return value of a pure function used for constant initialization and replace the call with the returned value. Thinking ahead the compiler should do that with the complete expression right of the = operator if not already the case.

## Backwards Compatibility

There should be no breaking changes.

## Example
```solidity
contract TestContract
{
	uint256 private constant _MAX_SUPPLY = (1000000000 * (10**decimals()));

	function decimals() override public pure virtual returns (uint8)
	{
		return 18;
	}
}
```

**Comment by hrkrshnn** [comment] 2022-07-01 13:23
In theory, this is great. Unfortunately, our current definition of `pure` is rather broad. For example, you can have external calls in pure functions! That already makes constants incompatible with pure.

**Comment by nishant-sachdeva** [comment] 2022-07-15 14:46
@hrkrshnn , in that case, should we close this issue ?

**Comment by cameel** [comment] 2022-07-19 10:36
Duplicate of #3122.

> For gas optimization the compiler should calculate the return value of a pure function used for constant initialization and replace the call with the returned value.

You're thinking of `pure` as something that has zero side-effects but that's not the case in Solidity. Currently it only means that the function cannot read and write storage. It can still freely read and write memory and calldata, use `codecopy` or, as mentioned by @hrkrshnn,  even make external calls. We have a whole discussion about it (#8153), but at the moment I think it's unlikely that we'll change it to the point of making it mean "side-effect free". It's more likely that we'll just introduce a new visibility level for such functions. That's actually something we have on our roadmap for the near future (#3157).

**Closed as not planned** 2022-07-19 10:36 UTC
Labels: language design :rage4:
