### ISSUE TITLE
[Codegen] ICE in ContractCompiler visit of inline assembly

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11929] opened 2021-09-10 13:22 UTC
```
contract C{
  struct S{int m;}
  function f(S calldata s) public returns(int r) {assembly{s:=r} }
}
```

throws

https://github.com/ethereum/solidity/blob/dea1b9ec7995ff7f16cdee7925a5858c5ce33982/libsolidity/codegen/ContractCompiler.cpp#L864-L867

```
$ solc test.sol
```

**Comment by cameel** [comment] 2021-09-12 17:13
Duplicate of #11680.

And it affects not only structs. There's a repro for static arrays too in that issue.

**Closed as completed** 2021-09-14 14:16 UTC
Labels: bug :bug:, should compile without error
