### ISSUE TITLE
ICE when passing test names separated by a semicolon to `isoltest --test`

### ISSUE THREAD

**Issue by sergiuiacob1** [ethereum/solidity#13070] opened 2022-05-26 08:11 UTC
## Description

Tried running multiple unit tests using `isoltest` like so:
```
sergiuiacob@Sergius-MacBook-Pro solidity % build/test/tools/isoltest --test "yulSyntaxTests/*;objectCompiler/*"
Unhandled exception caught.
/solidity/test/tools/IsolTestOptions.cpp(99): Throw in function virtual void solidity::test::IsolTestOptions::validate() const
Dynamic exception type: boost::wrapexcept<solidity::test::ConfigException>
std::exception::what: Invalid test unit filter - can only contain '[a-zA-Z0-9_/*]*: yulSyntaxTests/*;objectCompiler/*
[solidity::util::tag_comment*] = Invalid test unit filter - can only contain '[a-zA-Z0-9_/*]*: yulSyntaxTests/*;objectCompiler/*
```

As I understood from @cameel, the `;` separator syntax should be supported for `--test` values, but it caused the error above. The following worked just fine:
```
sergiuiacob@Sergius-MacBook-Pro solidity % build/test/tools/isoltest --test "yulControlFlowGraph/*"
```

## Environment

- Compiler version: 0.8.14
- Framework/IDE (e.g. Truffle or Remix): CLI
- Operating system: MacOS

Possibly linked issue: https://github.com/ethereum/solidity/issues/11916

**Comment by cameel** [comment] 2022-05-27 18:00
> As I understood from @cameel, the `;` separator syntax should be supported for `--test` values, but it caused the error above. 

Just to be clear: this issue is about the fact that this validation error causes an  ICE. It should just print a normal message to stderr.

As for the semicolon - looks like the right separator is actually a colon according to [Test unit filtering > Absolute specification](https://www.boost.org/doc/libs/1_79_0/libs/test/doc/html/boost_test/runtime_config/test_unit_filtering.html#boost_test.runtime_config.test_unit_filtering.absolute_specification).

**Comment by ywon0925** [comment] 2022-06-12 17:39
@cameel 
Since this issue is marked as 'good first issue', I would like to try to solve it.

If you could give me a general idea of how to fix the issue, it would be much appreciated.

Additionally, what do you mean by 'ICE' & 'normal message'?

**Comment by cameel** [comment] 2022-06-15 21:27
@ywon0925 ICE means Internal Compiler Error and we basically use this term to refer to any error that's reported the way you see in the description (even if it's not actually the `InternalCompilerError` class). ICE usually means a failed assertion.

By a normal message I mean that the user should see only this part:
```
Invalid test unit filter - can only contain '[a-zA-Z0-9_/*]*: yulSyntaxTests/*;objectCompiler/*
```
without all the other cruft.

Basically, the problem is that the exception thrown in https://github.com/ethereum/solidity/blob/7e0665752ff98825816daca80a82b27ca4652851/test/tools/IsolTestOptions.cpp#L95-L99 does not get caught by https://github.com/ethereum/solidity/blob/f617d27f2b94e3a050560a70d5f765cbe51c11c1/test/boostTest.cpp#L294-L298. And I think that it's because that `catch` block is in `soltest`. `isoltest` is a separate tool and has its own exception handling here: https://github.com/ethereum/solidity/blob/7e0665752ff98825816daca80a82b27ca4652851/test/tools/isoltest.cpp#L195-L212

**Comment by cameel** [comment] 2022-06-15 21:29
By the way, @ekpyron, wouldn't it make sense to rename `boostTest.cpp` to `soltest.cpp`?

**Comment by ekpyron** [comment] 2022-06-15 21:45
> By the way, @ekpyron, wouldn't it make sense to rename `boostTest.cpp` to `soltest.cpp`?

Yep, definitely.

**Comment by ywon0925** [comment] 2022-06-17 02:33
@cameel Thank you for the detailed explanation.

So, I should add the `catch` block to `isoltest`, and rename the `boostTest.cpp` to `soltest.cpp` as well?

**Comment by cameel** [comment] 2022-06-23 20:06
Done in #13167.

**Closed as completed by cameel** 2022-06-23 20:06 UTC
Labels: bug :bug:, good first issue, easy difficulty, testing :hammer:, should report better error
