### ISSUE TITLE
Unable to disambiguate shadowed function pointers

### ISSUE THREAD

**Issue by wolflo** [ethereum/solidity#12296] opened 2021-11-17 15:35 UTC
## Description

Attempting to pass a function pointer where the name of the function being passed is shadowed results in `Error: No matching declaration found after variable lookup`.

In theory, the compiler should be able to disambiguate which version of the function is being passed based on the type definition where the function pointer is used.

## Environment

- Compiler version: 0.8.10

## Steps to Reproduce
Pointer.sol
```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.10;

contract Pointer {
    function shadowed(uint256 a) internal {}
    function shadowed(uint256 a, uint256 b) internal {}
    function passFn() internal {
        takeFn(shadowed);
    }
    function takeFn(function(uint256) internal fnPtr) private {
        fnPtr(0);
    }
}
```

```bash
$ solc --version
Version: 0.8.10+commit.fc410830.Linux.g++

$ solc Pointer.sol
Error: No matching declaration found after variable lookup.
 --> Pointer.sol:8:16:
  |
8 |         takeFn(shadowed);
  |                ^^^^^^^^
```

Removing the shadowing function (`shadowed(uint256, uint256)`) results in a compile-able contract.

Because `takeFn()` explicitly accepts a function pointer of type `shadowed(uint256)`, it should be possible to determine which version of the method is being passed.

In cases where this isn't possible, it could be nice to have some syntax at the callsite to differentiate which version of a function is expected, though this may be a significant syntactic change. To steal from rust's turbofish operator as an example:
```rust
fnPtr::<&shadowed(uint256)>(100);
```

**Comment by chriseth** [comment] 2021-11-17 15:44
Solidity only performs overload resolution when a function is called, and not later during type checks. We are thinking about allowing explicit disambiguation, but this is currently not on our roadmap, also because we think that this problem does not occur often.

**Comment by cameel** [comment] 2023-01-27 21:58
Closing as a duplicate of #3556.

**Closed as not planned by cameel** 2023-01-27 21:58 UTC
Labels: language design :rage4:
