### ISSUE TITLE
Operators for user defined value types.

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#11969] opened 2021-09-15 13:24 UTC
This came up in https://github.com/ethereum/solidity/issues/9211#issuecomment-911705547

**Proposal**:

```solidity
type MyInt is int;
using {add as +} for UncheckedInt;
function add(MyInt a, MyInt b) view returns(MyInt c) { ... }
// MyInt.wrap(5) + MyInt.wrap(10) will now call add(...)
```

---

### Allowing mixed types

```solidity
using {addInt as +} for UncheckedInt;
function addInt(MyInt a, int b) view returns(MyInt c) { ... }
// MyInt.wrap(5) + 10 will now call addInt(...)
```

Useful for fixed points (`Fixed * uint`), duration type system (`Timestamp + Duration = Timestamp`, `Timestamp + Timestamp` is error), elliptic curve multiplication (`Point * uint`), etc.  Also can make code less verbose: see in example how we can write `MyInt.wrap(5) + 10` instead of `MyInt.wrap(5) + MyInt.wrap(10)`.

Problems: 
1. associativity of operators can be problematic (see https://github.com/ethereum/solidity/issues/9211#issuecomment-918392653 and  https://github.com/ethereum/solidity/issues/9211#issuecomment-915922517). May actually be solved by enforcing parenthesis for expressions that can be vague.
2. @ekpyron argues that this will cause issues with generics in the future.

### Disallowing mixed types

All types will have the type: `'a -> 'a -> 'a`, i.e., only operate on the same type.

To allow applications mentioned before, allow defining user defined operators.
```solidity
infix function <*>(UFixed18 a, uint b) returns (uint) { ... }
```

Problems: might complicate our parser, we'll need to assign left / right binding to operators, precedence etc. May be easier for the language to introduce new operators like `+', *'` or force fixed delimiters for new operators.

#### Allowing implicit conversions

If we only allow operators of type  `'a -> 'a -> 'a`, one way to do `Fixed * uint` would be to have a mechanism that allows implicit `uint -> Fixed` conversion. Thus, this would bind to the `* :: Fixed -> Fixed -> Fixed`. This is similar to how the compiler already implements arithmetic: for example `uint(5) + uint8(20)`.

Problem: the duration type system may not work in this case. Assuming we defined `Duration + Duration = Duration`, this allows `Timestamp + Duration = Duration`. **TODO**.

### Checked and Unchecked operator

If we allow custom operators, then should `unchecked` block affect it?

One solution is to make it a type error if used inside `unchecked`.

Or allow calling two different functions depending on whether the scope is checked / unchecked. Syntax proposals:

```solidity
using {add as unchecked+} for MyInt;
unchecked { using {add as +} for MyInt;}
using { unchecked {add as +}} for MyInt;
```

**Comment by chriseth** [comment] 2021-09-15 14:00
As I commented on the other issue: The worries of Daniel can be fixed by requiring a trait system as rust has it, with the downside that there are some places where you have to specify a trait while it could be automatically inferred in Daniel's system (I think this is a plus). Also note that rust allows mixed types, but it resolves custom operators only based on the left operand. I'm not sure if this is a strict requirement or if this is just to make it uniform with regards to how functions on custom types are resolved.

**Comment by ekpyron** [comment] 2021-09-15 14:29
It really isn't a plus not *to be able to* infer types. Even if you are able to infer types, you can still either choose to mention types or even force people to mention types (at all times or in some situations). The point is that type inference being possible is generally a stronger type-safety property. If you *can't* infer types you have to be careful that the explicit mentions of types this implies won't get excessive and you will end up with a system in which generics become unreadable due to excessive typing that doesn't provide any gain. I'm not saying this *has* to happen, but it takes dedicated effort to avoid (if only by rules like "return types are fully determined by argument types" and "operators have to be defined on the exact type of the left operand", etc.).

Also type inference can protect against specifying types that are incorrect in some contexts and for example imply undesired implicit conversions. Explicit types in generics are not *always* the better choice.

Also monoidal operators are also traits and using them generically will also work and only work via a trait - you can't really define operators using parametric polymorphism, you need adhoc polymorphism, i.e. type classes/traits for that anyways. But it's significantly simpler traits in that they only require a single free type variable. Does defining traits containing functions that return types with specified other traits work in Rust? Stuff like that quickly becomes complex, so I'd be very careful in just assuming that traits just solve this stuff in all cases smoothly.

**Comment by chriseth** [comment] 2021-09-15 15:27
@ekpyron and me also briefly discussed how to do `++` and `+=`, but I think we concluded that the problem is that we do not have explicit references, and you would need them to do this properly. It might make sense to disallow to define them and auto-derive them from `add(CustomType, uint)`, if this is desired.

**Comment by chriseth** [comment] 2021-10-12 13:32
Having talked to @axic who is also unsure about mixed types I would say that we implement operators only for fixed type signatures for now in order to get some progress and feedback from the community.

I'm still of the opinion that user-defined operators should be illegal inside `unchecked` blocks. I think we can also agree that this is a good first step and we can wait for feedback.

Another question is whether we want `type X is Y; using {...} for X;` or just contract this to `type X is Y using { ... };`. The latter would have the benefit that the valid operators for a user defined type are very easy to find. I would also be fine with just having a convention that the operators should be the next statement, though.

**Comment by chriseth** [comment] 2021-10-25 11:20
The final question about a first and nice to use implementation is about how to make this work with literals. It would be great to be able to do `a = a + 1;`. For this, we would need to define an implicit conversion from literals to custom types. As we discussed earlier, implicit conversions from the underlying type to the user defined type should rather not be allowed.

Every literal expression is assigned a type from our type system. This can be `bool`, "rational number" or "string literal".
The problem is that neither rational number or string literal are "nameable types", so we cannot have functions with parameters of that type.

Summing this up, my first proposal would be the following:

Add something like "using {f as fromLiteral} for Type;" where `f` is a user-defined function that is overloaded for several types. Whenever the type system is asked for an implicit conversion from a literal, it checks if the target type has such a "fromlLiteral" function. Then it performs overload resolution with another implicit conversion from the literal type to the parameter type of the candidate functions. If exactly one candidate remains, the implicit conversion is allowed.

**Comment by cameel** [comment] 2021-10-27 12:56
Another idea would be to allow something like [user-defined literals in C++](https://en.cppreference.com/w/cpp/language/user_literal). Not sure what the best syntax for declaring them would be but for use it would be `a = a + 1_suffix` or maybe `a = a + 1:suffix`.

**Comment by chriseth** [comment] 2021-10-27 15:13
We already have `_` as a separator in numbers, so I think supporting such suffixes is a good idea. Also it reads nicely as `10_km` or `100_ether`, `10_dai` or `7_fixed`.

How do we mark functions that can be used as these prefixes?

**Comment by ekpyron** [comment] 2021-11-01 09:53
> Another question is whether we want `type X is Y; using {...} for X;` or just contract this to `type X is Y using { ... };`. The latter would have the benefit that the valid operators for a user defined type are very easy to find. I would also be fine with just having a convention that the operators should be the next statement, though.

If we ever decide to have some kind of abstract types (resp. type classes/sorts) for generics (and want to reuse similar declarations for them), then those would have to have their (unimplemented) operators defined in place at declaration in order to work smoothly, so I'd tend to also require them to be named at declaration for normal user-defined types now, i.e. I'd go for requiring `type X is Y using { ... };` at least until there are complaints about it.

> Add something like "using {f as fromLiteral} for Type;" where `f` is a user-defined function that is overloaded for several types. Whenever the type system is asked for an implicit conversion from a literal, it checks if the target type has such a "fromlLiteral" function. Then it performs overload resolution with another implicit conversion from the literal type to the parameter type of the candidate functions. If exactly one candidate remains, the implicit conversion is allowed.

Would this really be ``fromLiteral`` then or actually just an implicit conversion function? We should also make sure that this is forward compatible to introducing a proper literal type. It stands to reason that I would always want to implement an implicit conversion function from the least special type possible, i.e. if I want literals *and* integers to work, I use ``uintX`` with the highest feasible size ``X``, if I *only* want literals to work I'd e.g. use ``rational`` (which would only be possible once we introduce that). It would even make sense to disallow defining multiple implicit conversions from types that are implicitly convertible between each other at the same type. If we make it ``fromLiteral`` instead of an implicit conversion, then we're getting into a mess once we also allow implicit conversions from types that are implicitly convertible from literals themselves.

**Comment by ekpyron** [comment] 2021-11-01 10:02
The question of ``type X is Y using { ... };`` also makes me wonder:
Will user-defined types only ever be able to define *from* what types they are implicitly convertible or also *to* which types? Probably both, right? I'm wondering since if we allow defining both, then defining another type ``type Z is X using { ..everything X has plus another operator I want plus trivial implicit conversions from and to X.. }`` and then just using ``Z`` instead of ``X`` should always be an (arguably better) alternative for situations in which I *might* want to use an out-of-declaration ``using``.

**Comment by chriseth** [comment] 2021-11-01 12:36
As far as the "literal conversion through suffix" is concerned: The main thing that  sets this apart from actually just bound functions (`using f for *; 1.f()`) is that we do not need to call the function. So maybe we could just resort to `using` with a special type at the right hand side to say it applies to literals and does not need the function call and maybe also uses `_` instead of `.`.

**Comment by chriseth** [comment] 2021-11-11 15:57
Related https://github.com/ethereum/solidity/issues/12273

**Closed as completed** 2023-02-22 10:58 UTC
Labels: language design :rage4:, selected for development, high effort, high impact

**Comment by hellwolf** [comment] 2023-02-28 16:05
> Having talked to [@axic](https://github.com/axic) who is also unsure about mixed types I would say that we implement operators only for fixed type signatures for now in order to get some progress and feedback from the community.

Okay, fair enough, but I can't use it in a library because of this :( And we are left with:

```solidity
    function mul(FlowRate r, Time t) internal pure returns (Value) {
        return Value.wrap(FlowRate.unwrap(r) * int(uint(Time.unwrap(t))));
    }
```



Fwiw, in contrast, that's what I would do in modern c++:

```c++
#include <cstdio>

struct Value { int v; };
struct FlowRate { int v; };
struct Time { int v; };

Value operator*(const FlowRate& r, const Time& t) {
    return Value{r.v * t.v};
}

int main() {
    FlowRate r = {10};
    Time t = {5};
    printf("r * t = %d\n", (r * t).v);
}
```

**Comment by hellwolf** [comment] 2023-02-28 16:07
May I reopen the issue?

**Comment by ekpyron** [comment] 2023-03-07 10:44
@hellwolf We are aware of the limitations of only allowing monoidal multiplication, i.e. multiplication with the same arguments. However, just allowing free mixed operators has various implications on the type system, in particular it breaks unambiguous type inference. We are still in the process of designing our future type class/trait system that will need to capture the definitions of these operators conceptually - we will be weighing in the pros and cons of more restrictive and more general approaches including cases in which mixed (resp. vector-space-like) multiplication would be handy.
Given all that, we won't just add mixed type operators for the time being to keep our options open for multiple variants of generic type systems - as such reopening this issue for the time being won't really be helpful. The general issue is already on our design agenda.
