### ISSUE TITLE
Question: Is there a difference between "argument" and "parameter"?

### ISSUE THREAD

**Issue by typedarray** [ethereum/solidity#14604] opened 2023-10-12 05:20 UTC
## Page

https://docs.soliditylang.org/en/v0.8.21/abi-spec.html#events

## Abstract

Solidity's documentation appears to use "parameter" and "argument" interchangeably in the context of events (logs):

```
Given an event name and series of event parameters ...

... the canonical type of a given argument, e.g. for uint indexed foo, it would return uint256

... trade-off between fast search for predetermined values (if the argument is indexed)

... the Keccak hash of a special in-place encoded value (see Encoding of Indexed Event Parameters)
```

Is there a semantic difference between "parameter" and "argument" in this context? It seems like there is a subtle distinction, but it's lost on me. Perhaps someone who knows the history can help me understand. Thanks in advance!

**Comment by r0qs** [comment] 2023-10-16 11:08
Hi @0xOlias, as far as I can tell, there is no difference between them. What is the subtle distinction that you think they have?

**Comment by divyasshree-BQ** [comment] 2023-11-01 04:36
I have updated the docs explaining the difference in this pull request [#14647](https://github.com/ethereum/solidity/pull/14647)  . Waiting for review

**Comment by Divyn** [comment] 2023-11-01 12:57
I have updated the docs explaining the difference in this pull request https://github.com/ethereum/solidity/pull/14647 . Waiting for review

**Comment by r0qs** [comment] 2023-11-01 13:48
Hello @Divyn, thank you for your contribution. Before we proceed with any changes to the documentation, it's important to clearly understand the specific issue that @0xOlias pointed out. Could you please elaborate on what exactly needs to be clarified in that section?

Strictly speaking, parameters refer to variables in event definitions, while arguments denote the values assigned to those variables during event instantiation. Upon re-reading the documentation, it appears that indeed these terms are used interchangeably. Personally, I don't believe this impacts readability within the given context. So, for me, it is fine to use them interchangeably there. However, as English is not my native language, I am open to suggestions on how to enhance this section for better clarity.

**Comment by Divyn** [comment] 2023-11-21 06:24
@r0qs  I agree that it might not make a huge difference to those who are familiar with the concepts of arguments/parameters.
But, I also see the value in using more precise terminology to avoid any potential ambiguity, especially for readers who are new to Solidity. English is not my first language either.

These are the changes I made:
1.  In the section explaining the encoding of indexed event parameters, replace "parameters" with "event arguments" to maintain consistency and avoid confusion.
    
2.  Briefly explain the concept of function arguments and their encoding differences compared to indexed event argument encoding. This will help emphasize the distinct purposes of these two encoding schemes.

**Comment by mehtavishwa30** [comment] 2023-12-12 09:29
Thank you for raising the original question and for participating in the discussion. After going through the references from the documentation the issue is pointing to, the usage of the terms interchangeably doesn't seem to have a huge impact on our readers' understanding of the concepts and the overall readability of the documentation as pointed out by @r0qs earlier.

I will be closing this and will only circle back in case of future instances where this might potentially be a topic of ambiguity among readers.

**Closed as completed by mehtavishwa30** 2023-12-12 09:29 UTC
Labels: documentation :book:
