### ISSUE TITLE
Add support to --allow-paths for relative paths

### ISSUE THREAD

**Issue by conor10** [ethereum/solidity#2928] opened 2017-09-19 09:41 UTC
The ```--allow-paths``` command line option for *solc* only works with absolute paths. It would be useful if it could be used with relative paths such as ```../``` and the current working directory(```.```).

**Comment by axic** [comment] 2017-10-06 13:15
@q3k is this something you are also looking into?

**Comment by HaleTom** [comment] 2017-10-26 09:21
Here's a demonstration of the issue:

```
$ pwd
/home/ravi/repo/ico/contracts
$ cat Test.sol
pragma solidity ^0.4.17;
import '../node_modules/zeppelin-solidity/contracts/token/StandardToken.sol';
$ strace -fs60 solc Test.sol |& egrep 'stat.*zeppelin'
stat("/home/ravi/repo/ico/contracts/node_modules/zeppelin-solidity/contracts/token/StandardToken.sol", 0x7ffd7c7adcd0) = -1 ENOENT (No such file or directory)
```
Note the expected path is:
```
/home/ravi/repo/ico/node_modules/zeppelin-solidity/contracts/token/StandardToken.sol
```
That is, `contracts/` should be removed via `../`.

The same output with `--allow-paths`:

```
$ strace -fs60 solc --allow-paths /home/ravi/repo/ico/node_modules Test.sol |& egrep 'stat.*zeppelin'
stat("/home/ravi/repo/ico/contracts/node_modules/zeppelin-solidity/contracts/token/StandardToken.sol", 0x7ffff33ede90) = -1 ENOENT (No such file or directory)
```

@q3k  @conor10  this is blocking anyone using vim and syntax checking (via syntastic) from seeing full errors/warnings.

**Comment by k06a** [comment] 2018-04-19 10:38
Any progress?

**Comment by axic** [comment] 2018-04-19 10:51
@ekpyron @chriseth were the latest changes to file handling fixing this?

**Comment by chriseth** [comment] 2018-04-23 13:16
@k06a @axic This is not really related to `--allow-paths`, but rather to the fact how relative paths are resolved.

The issue is that the compiler creates a virtual filesystem that contains the source files. The location of the source files in this virtual filesystem is used for resolving import statements and the paths are also used for the metadata in the contract.

Since we obviously do not want weird directories like `/home/ravi/repo/ico` leading up to the contract to be part of the metadata (due to both privacy and reproducibility reasons), files that are named with relative path are put at the root of that virtual filesystem.

So if you want `..` to work properly here, you have to either specify the absolute path, use remappings or at least name the source file starting from the position where it should be in the virtual path `contracts/Test.sol`

**Comment by chriseth** [comment] 2018-04-23 13:16
Please tell me if this resolved the issue or if there is still something that can be improved.

**Comment by axic** [comment] 2018-07-28 13:24
Ping @conor10

**Comment by chriseth** [comment] 2018-09-04 11:32
The example given above should be fixed by either using remappings or by calling solc using `solc contracts/Test.sol` in the directory one level higher. Reaching below the root path in the virtual filesystem of the compiler is not supported in imports.

@HaleTom we can talk about how to fix vim in a separate issue.

**Closed as completed by chriseth** 2018-09-04 11:32 UTC
Labels: waiting for more input
