### ISSUE TITLE
solc does not work on osx

### ISSUE THREAD

**Issue by debris** [ethereum/solidity#569] opened 2016-05-13 16:10 UTC
I''ve installed solc

```
solc --version
solc, the solidity compiler commandline interface
Version: 0.3.2-9e36bdda/Release-Darwin/appleclang/Interpreter
```

using brew

```
brew info ethereum
ethereum/ethereum/ethereum: stable 1.4.4 (bottled), devel 1.5.0 (bottled)
https://github.com/ethereum/go-ethereum
/usr/local/Cellar/ethereum/1.4.4 (8 files, 52.9M) *
  Poured from bottle on 2016-05-13 at 17:57:40
From: https://github.com/ethereum/homebrew-ethereum/blob/master/ethereum.rb
```

on osx 10.11.1

```
uname -amnprsv
Darwin Mareks-MacBook-Pro.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64 i386
```

and expected to compile this contract successfully:

```
contract Foo {
    function bar() {}   
}
```

using 

```
solc --abi test.sol
```

but instead I got an error

```
[1]    35719 segmentation fault  solc --abi test.sol
```

Tried different options / contracts but solc always finishes with segfault.

**Comment by VoR0220** [comment] 2016-05-13 17:45
known issue. We're working on it.

**Comment by bobsummerwill** [comment] 2016-05-13 21:07
So this is a dupe of https://github.com/ethereum/solidity/issues/490?
If so, let's close this one, and you can join in the "fun" over there, @debris!

**Closed as completed by bobsummerwill** 2016-05-13 21:07 UTC
