### ISSUE TITLE
Error during instalation on Ubuntu

### ISSUE THREAD

**Issue by payvint** [ethereum/solidity#10644] opened 2020-12-17 10:28 UTC
## Description

Trying to install solc compiler on ubuntu 18.04.5. Faced with issue
`The following packages have unmet dependencies:`
` solc : Depends: libc6 (>= 2.29) but 2.27-3ubuntu1.3 is to be installed`

It could be solved by upgrading libc6 to required version. On ubuntu 18.04.5 - 2.27 it is a standard version
https://packages.ubuntu.com/bionic/libc6

## Environment

- Compiler version: 0.8.0
- Operating system: Ubuntu 18.04.5

## Steps to Reproduce

Ubuntu 18.04.5 Machine
`sudo add-apt-repository ppa:ethereum/ethereum`
`sudo apt-get update`
`sudo apt-get install solc`

**Comment by axic** [comment] 2020-12-17 12:41
@ekpyron is it possible to downgrade libc6 in the ppa cross-build?

**Comment by ekpyron** [comment] 2020-12-17 14:11
Apparently, there's something wrong with the static ppa builds in general. They should not depend on libc of any version at all...

**Comment by ekpyron** [comment] 2020-12-17 14:27
The problem is that we don't only package ``solc``, but also ``solidity-upgrade`` and ``yul-phaser`` in the package and while ``solc`` as we build it works with any libc version, the other two won't - so we'll either need to remove them from that installation or build them statically as well, otherwise ubuntu's ppa dependency autotracking will prevent installation.

**Comment by axic** [comment] 2020-12-17 14:50
I don't think we need to ship `yul-phaser`, but building `solidity-upgrade` statically would be nice.

**Comment by axic** [comment] 2020-12-17 14:50
And I would say it is fine if we fix these for 0.8.1 (and perhaps make a 0.7.7 release for it).

**Comment by ekpyron** [comment] 2020-12-17 14:54
We should definitely have a 0.8.0 ~~and 0.7.6~~ release package that works, shouldn't we? And it's just build settings, it's no problem just rebuilding them properly.

**Comment by axic** [comment] 2020-12-17 14:55
If it doesn't need a change in the repo, that's even better. But is only the ubuntu thing affected or stuff in solc-bin too?

**Comment by ekpyron** [comment] 2020-12-17 14:58
It's only the ubuntu PPA releases for <20.04. I just uploaded a new build for 0.8.0 in the static repo on launchpad already, though - if that works out and is properly static, we just need to copy that over to the old distros.

**Comment by ekpyron** [comment] 2020-12-17 16:15
@payvint we just published a new PPA build. Can you confirm that the problem no longer occurs?

**Comment by ekpyron** [comment] 2020-12-17 16:22
At least I now can successfully install 0.8.0 from the PPA repo in a ubuntu 18.04 docker image, so I think we can close this.

**Closed as completed by ekpyron** 2020-12-17 16:22 UTC

**Comment by payvint** [comment] 2020-12-18 15:41
Yeap - that works - thanks!
