### ISSUE TITLE
ICE due to internal function pointer in a calldata struct parameter of a public function

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#12028] opened 2021-09-26 11:59 UTC
```
pragma abicoder v2;

contract C {
struct S { function() internal a; }
function f(S[2] calldata) public {}
}
```

throws

https://github.com/ethereum/solidity/blob/3c8846e669ef7963bf9a84a856786b7d1d7dd01c/libsolidity/ast/Types.cpp#L2149

**Comment by hrkrshnn** [comment] 2021-09-27 09:39
The fix is more involved than I thought.

https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L1624

Needs to change `ArrayType const*` to `ReferenceType const*`. However, since function types are not a reference type and since `StructType::isValidForLocation` only checks members which are reference type, that fix wouldn't work. 

https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L2347

Somehow, internal function types should almost be treated like a reference type.

**Comment by cameel** [comment] 2021-09-27 21:07
Duplicate of #11610.

**Comment by cameel** [comment] 2022-09-27 00:08
Closing since #11610 has been fixed. Now the example from the description generates a proper error:
```
Error: Internal type is not allowed for public or external functions.
 --> test.sol:5:12:
  |
5 | function f(S[2] calldata) public {}
  |            ^^^^^^^^^^^^^
```

**Closed as completed by cameel** 2022-09-27 00:08 UTC
Labels: bug :bug:, should report better error
