### ISSUE TITLE
Reenable style checks for docs for 0.6.0

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7944] opened 2019-12-10 01:15 UTC
Revert #7435.

**Comment by christianparpart** [comment] 2019-12-11 13:05
We're using an external tool [solhint](https://github.com/protofire/solhint), so new features break our CI.
For reference I'm linking the tracking issue from the other side: https://github.com/protofire/solhint/issues/170.

**Comment by axic** [comment] 2021-01-14 23:57
I guess this is done :)

**Comment by cameel** [comment] 2021-01-15 10:36
@axic Looks like it's not done yet.

PR #7962 was just closed, not merged and the check seems to be still disabled on `develop`: https://github.com/ethereum/solidity/blob/804bd8f6dd117b7dec62e179cde663d29a31fc85/.circleci/config.yml#L981

**Comment by cameel** [comment] 2021-11-08 17:07
I think this is actually a duplicate of #7436.

**Closed as completed** 2021-11-08 17:09 UTC
Labels: documentation :book:, build system :building_construction:
