### ISSUE TITLE
Equally named contracts cause internal compiler error

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1120] opened 2016-09-26 14:41 UTC
On `develop`, when I do the following, I see `boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>`.  I think this error should be replaced with a more informative one.

```
$ $SOLC --version
solc, the solidity compiler commandline interface
Version: 0.4.3-develop.2016.9.26+commit.c06ba011.Linux.g++
$ cat HashRegistrar.sol 
pragma solidity ^0.4.0;

contract Deed {
}

contract Registrar {
    function newBid(bytes32 sealedBid) payable {
        Deed newBid = new Deed();
    } 
}
$ cat HashRegistrarSimplified.sol 
pragma solidity ^0.4.0;


contract Deed {
}

contract Registrar {
}
$ ls
HashRegistrarSimplified.sol  HashRegistrar.sol
$ $SOLC *.sol
Internal compiler error during compilation:
/home/yh/src/solidity/libsolidity/codegen/CompilerContext.cpp(76): Throw in function const dev::eth::Assembly& dev::solidity::CompilerContext::compiledContract(const dev::solidity::ContractDefinition&) const
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: std::exception
[dev::tag_comment*] = Compiled contract not found.
```

**Comment by roadriverrail** [comment] 2016-11-18 09:27
I've been taking a crack at this one over the past couple of days.  It appears to be caused by the CompilerStack's parsing functions uncritically stuffing the second contract over the first; this eventually leads to the code generation of the Registrar looking for the first Deed contract and only being able to find the second one.  I added some guard code to throw a descriptive exception when the second contract would clobber the first.

It seems to work, but I wanted to check in about the library_name_clash_with_contract test.  According to the test system, the code in that test should compile just fine, and it's okay to have a library and contract named the same thing.  Is that intended to be the case?  I might be mistaken, but don't libraries get ContractDefinitions, and thus wouldn't the library clobber the contract in that case?

**Comment by pirapira** [comment] 2016-11-18 10:01
I would say a contract and a library under the same name should throw as well.  @chriseth what is your opinion?

@roadriverrail would you open a pull-request already with your fixes?  Thank you.

**Comment by roadriverrail** [comment] 2016-11-18 15:43
Done.  I'll add more commentary there.

**Comment by chriseth** [comment] 2016-11-24 15:05
The correct fix is to prefix the contract name by the source file that contains it. This is planned to go together with the json input/output.

**Comment by roadriverrail** [comment] 2016-11-25 14:43
Ah.  I can certainly change that around; I was really just coding to the issue.  Or, since I'm not sure what you mean about "[going] together with the json input/output," there might be more to the story that I missed.

Is the prefixing of the source file purely for collision avoidance, or should a contract be able to reference another contract in another file via "source:contract" notation?

**Comment by chriseth** [comment] 2016-11-25 15:30
The prefixing is only for collision avoidance as far as the interface to the compiler is concerned, i.e. for naming the output files, for assigning addresses to libraries and so on.

I'm not sure how to correctly solve the issue on a filesystem level, i.e. I'm not sure how to correctly name the `.bin` file for contract name collinions, because the file name would have to include the full path to the contract. A solution would be to convert `/` to e.g. `_` in files and of course only add the path prefix in case of a clash.

Contracts can reference other contracts using
```js
import ContractName from "path/to/other/file";
```

**Comment by roadriverrail** [comment] 2016-12-01 06:08
It's been a little over a week, so I just want to mention that I am still actively looking at this one; the Thanksgiving holiday and the fact that I'm traveling heavily for work has just meant I haven't had regular nights to work.  I'll be updating the PR soon; I've got most of this working as discussed, with the exception that, right now, I'm recording the file path always and not only in the event of a clash.  I hope to have something in another couple of days.

**Comment by chriseth** [comment] 2016-12-01 11:39
nice!

**Comment by roadriverrail** [comment] 2016-12-05 18:44
Quick note that I got the file naming stuff done; I was going to sit down
on the plane last night and run the test suite to see what I broke,
and...well, let's just say it's now in the Atlanta airport lost-and-found.
I should get it back Saturday, and I'll get it committed on my branch so
that I don't lose it again.

**Comment by pirapira** [comment] 2016-12-06 09:44
@roadriverrail good luck!

**Comment by roadriverrail** [comment] 2016-12-11 22:21
Laptop recovered and I checked my work in just in case.  It's functional for what limited personal tests I did; will try to run the testsuite soon.

**Comment by chriseth** [comment] 2017-01-20 13:56
Thanks again for fixing this, @roadriverrail !

**Closed as completed by chriseth** 2017-01-20 13:56 UTC
Labels: bug :bug:
