### ISSUE TITLE
Filter library functions with "internal" types for ABI output

### ISSUE THREAD

**Issue by debris** [ethereum/solidity#3409] opened 2018-01-18 20:57 UTC
please look at the issue: https://github.com/paritytech/ethabi/issues/75

imo `DLL.Data storage` is an invalid type. Am I wrong?

**Comment by chriseth** [comment] 2018-01-19 17:06
Can you provide a bit more details, please? It is a valid type that is used internally in Solidity but should not be used by things like web3.js.

**Comment by debris** [comment] 2018-01-19 17:24
solidity contract:
[DLL.sol.txt](https://github.com/paritytech/ethabi/files/1644283/DLL.sol.txt)

produces the following abi:
[DLL.abi.txt](https://github.com/paritytech/ethabi/files/1644281/DLL.abi.txt)

which contains `type: DLL.Data storge`

```json
{
		"constant": true,
		"inputs": [
			{
				"name": "self",
				"type": "DLL.Data storage"
			},
			{
				"name": "_curr",
				"type": "uint256"
			}
		],
		"name": "getNext",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	}
```

**Comment by chriseth** [comment] 2018-01-19 23:29
Sure, but where does the error come from? The contract in the source is a library, its ABI should be irrelevant.

**Comment by debris** [comment] 2018-01-20 10:14
error doesn't come from solc. it comes from `ethabi` - library which uses abi files to generate rust bindings for solidity and which encodes rust types into abi compatible byte vectors.

**Comment by axic** [comment] 2018-01-20 12:50
I think the bug is here is that we should only generate ABI for `view`/`pure` functions and they should only use external types. Admittedly the resulting ABI is not very useful, but libraries are a Solidity concept and are NOT supposed to be used by anything else.

Perhaps we shouldn't even output an ABI for libraries or should have an marker in the ABI stating it is a library ABI.

**Comment by akuanti** [comment] 2018-01-20 14:31
@axic if libraries are not supposed to be used by anything else, how are you supposed to deploy a contract that uses a library? It seems like you need to be able to deploy the library first so that the contract that depends on it can refer to it. The solidity docs indicate that all linking does is replace the placeholders in the bytecode with the address of the library.

**Comment by axic** [comment] 2018-01-20 14:32
Compiling a contract which uses a library **must have** access to the source code of the library during compilation time. It never uses the ABI JSON for anything.

**Comment by akuanti** [comment] 2018-01-20 14:37
It's starting to sound like the issue is actually that deploying a library shouldn't involve `ethabi` (or any ABIs) at all, and should just involve sending a transaction with the library's bytecode. Am I understanding this correctly?

**Comment by axic** [comment] 2018-01-20 14:45
I am not sure what `ethabi` does, but a library should be just deployed and their deployment address + source code must be given to the compiler when compiling a contract using that given library.

**Comment by chriseth** [comment] 2018-01-23 17:17
@akuanti yes, that sounds about right. A library cannot have a constructor, so you cannot even pass arguments at deploy time, which means the ABI is not even needed there. Yes, you should just send a transaction containing the library's bytecode.

**Comment by axic** [comment] 2018-01-26 10:55
@chriseth:

> Perhaps we shouldn't even output an ABI for libraries or should have an marker in the ABI stating it is a library ABI.

This is an actual question we should consider. After #3203 we could consider only outputting view/pure which can be called without `DELEGATECALL`. That also means those functions won't have internal types and the resulting ABI will be valid.

**Comment by chriseth** [comment] 2018-01-26 13:11
@axic Yes, I agree. We should filter the ABI for a library and remove anything that is not view or pure and anything that has a storage pointer type as parameter or return parameter.

**Comment by chriseth** [comment] 2018-05-14 10:43
I would say this can be done as a non-breaking change, since it is a bugfix. Moving to 0.5.1, please revert the change if you think otherwise, @axic.

**Closed as completed** 2019-03-11 16:39 UTC
Labels: bug :bug:, protocol design :crystal_ball:
