### ISSUE TITLE
A change of comment causes more diff than cbor metadata

### ISSUE THREAD

**Issue by zhiqiangxu** [ethereum/solidity#14331] opened 2023-06-16 07:54 UTC
## Description

Theoretically, a change of comment should only change the cbor metadata at the end of bytecode; This holds normally but I found an exception for the following `ThemisFactory` contract.

## Environment

- Compiler version: 0.5.16
- Operating system: mac osx

## Steps to Reproduce

[This](https://gist.github.com/zhiqiangxu/85b4df89f7cb74802d81288b6297fdd8) is the solidity file for reproducing.

This is the command to compile: `solc --bin ThemisFactory-new.sol --optimize --optimize-runs 200`

Notice the `//xx` at the end of the solidity file? If I change the comment a bit, it will cause more diff than the `cbor metadata` at the end, which can be easily verified at [sourcify](https://playground.sourcify.dev/). 

(For my experiment the bytecode for `ThemisFactory` is [this](https://gist.github.com/zhiqiangxu/52835cd23a262ead5f98c07a04c29da7) vs [this](https://gist.github.com/zhiqiangxu/b213c8ed7a988664a12ce44d642e726e) after a change of comment at the end of file)

This is abnormal so I suspect it's either a compiler bug or some hidden feature to clarify?

**UPDATE**

I guess that there're two metadata is because the `ThemisFactory` actually contains two contract, so the real question should be: is there some reliable way to identify all metadatas from only the bytecode?

**Comment by kuzdogan** [comment] 2023-08-11 04:55
Hi, just came across this. 

Correct that if you have factories you might have nested CBOR metadata hashes in the bytecode. There is not foolproof way to know where exactly the nested CBOR part will be. This might change with EOF. For now, a good workaround is to add a small comment in the nested contract (factory) and compare the first bytecode against the one with the comments. The differences should be in the factory contract's metadata hash and the main contract's.

**Comment by nikola-matic** [comment] 2024-01-10 09:27
Closing as not a bug; thanks to @kuzdogan who elaborated above.

**Closed as completed by nikola-matic** 2024-01-10 09:27 UTC
Labels: bug :bug:
