### ISSUE TITLE
solc broke everything on ubuntu 

### ISSUE THREAD

**Issue by primehat23** [ethereum/solidity#852] opened 2016-08-09 20:04 UTC
I wanted to scan my computer for viruses, so I did freshclam. It though most of the chain was a virus, it also got rid of some things in wine. but now I can't even install things right. 
I got the following. I think solc is broken I have not been able to get it working once in 2 years. Any help. I just want to write dapps on my computer and not on cloud 9

"
Preparing to unpack .../solc_1%3a0.3.5-nightly-2016-08-08-ffl-c3ed550-0ubuntu4~trusty_amd64.deb ...
Unpacking solc:amd64 (1:0.3.5-nightly-2016-08-08-ffl-c3ed550-0ubuntu4~trusty) over (1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/solc_1%3a0.3.5-nightly-2016-08-08-ffl-c3ed550-0ubuntu4~trusty_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/libevmasm.so', which is also in package libethereum:amd64 1.2.9-SNAPSHOT--20160630-f09ff00~trusty-0ubuntu1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/solc_1%3a0.3.5-nightly-2016-08-08-ffl-c3ed550-0ubuntu4~trusty_amd64.deb
Error in function: 
"

**Comment by primehat23** [comment] 2016-08-09 20:13
I can not uninstall CPP-ethereum either. each time I just get the above error. 
I can't use the software centre too.  Could this be malware?

**Comment by primehat23** [comment] 2016-08-09 20:14
I can not even install updates.

root@goldhat00-desktop:/home/goldhat00#  apt-get install -f
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  checkbox-ng checkbox-ng-service kde-l10n-engb libandroid-properties1
  libechonest2.1 libhud2 libntdb1 libqt5positioning5
  libqt5webkit5-qmlwebkitplugin libqtweetlib1.0 libthumbnailer0
  libufe-xidgetter0 libunity-action-qt1 linux-headers-3.13.0-92
  linux-headers-3.13.0-92-generic linux-image-3.13.0-92-generic
  linux-image-extra-3.13.0-92-generic plainbox-provider-checkbox
  plainbox-provider-resource-generic plainbox-secure-policy python-ntdb
  python3-checkbox-ng python3-checkbox-support python3-plainbox
  python3-pyparsing qml-module-qtquick-localstorage qml-module-qtwebkit
  qtdeclarative5-accounts-plugin qtdeclarative5-dialogs-plugin
  qtdeclarative5-localstorage-plugin qtdeclarative5-privatewidgets-plugin
  qtdeclarative5-qtquick2-plugin
  qtdeclarative5-ubuntu-ui-extras-browser-plugin-assets
  qtdeclarative5-unity-action-plugin qtdeclarative5-window-plugin
  ubuntu-ui-toolkit-theme
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  solc
The following packages will be upgraded:
  solc
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/2,062 kB of archives.
After this operation, 14.9 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
(Reading database ... 342508 files and directories currently installed.)
Preparing to unpack .../solc_1%3a0.3.5-nightly-2016-08-08-ffl-c3ed550-0ubuntu4~trusty_amd64.deb ...
Unpacking solc:amd64 (1:0.3.5-nightly-2016-08-08-ffl-c3ed550-0ubuntu4~trusty) over (1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/solc_1%3a0.3.5-nightly-2016-08-08-ffl-c3ed550-0ubuntu4~trusty_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/libevmasm.so', which is also in package libethereum:amd64 1.2.9-SNAPSHOT--20160630-f09ff00~trusty-0ubuntu1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/solc_1%3a0.3.5-nightly-2016-08-08-ffl-c3ed550-0ubuntu4~trusty_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@goldhat00-desktop:/home/goldhat00#

**Comment by bobsummerwill** [comment] 2016-08-09 20:15
Looks like you are hitting the same issue as https://github.com/ethereum/solidity/issues/851 for the PPA.   Try uninstalling cpp-ethereum and then solc should work.

Let us know if that works.    If not, hold tight.   @chriseth has been actively working on the PPAs and we will get them fixed in the next few days.

**Comment by bobsummerwill** [comment] 2016-08-09 20:17
If you cannot uninstall cpp-ethereum, again, sit tight.    We're working on the PPAs.

It's all part of the ongoing splitting of solidity out of webthree-umbrella to make all this stuff easier.

**Comment by primehat23** [comment] 2016-08-09 21:10
I can not even install updates.

root@goldhat00-desktop:/home/goldhat00#  apt-get install -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  checkbox-ng checkbox-ng-service kde-l10n-engb libandroid-properties1
  libechonest2.1 libhud2 libntdb1 libqt5positioning5
  libqt5webkit5-qmlwebkitplugin libqtweetlib1.0 libthumbnailer0
  libufe-xidgetter0 libunity-action-qt1 linux-headers-3.13.0-92
  linux-headers-3.13.0-92-generic linux-image-3.13.0-92-generic
  linux-image-extra-3.13.0-92-generic plainbox-provider-checkbox
  plainbox-provider-resource-generic plainbox-secure-policy python-ntdb
  python3-checkbox-ng python3-checkbox-support python3-plainbox
  python3-pyparsing qml-module-qtquick-localstorage qml-module-qtwebkit
  qtdeclarative5-accounts-plugin qtdeclarative5-dialogs-plugin
  qtdeclarative5-localstorage-plugin qtdeclarative5-privatewidgets-plugin
  qtdeclarative5-qtquick2-plugin
  qtdeclarative5-ubuntu-ui-extras-browser-plugin-assets
  qtdeclarative5-unity-action-plugin qtdeclarative5-window-plugin
  ubuntu-ui-toolkit-theme
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  solc
The following packages will be upgraded:
  solc
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/2,062 kB of archives.
After this operation, 14.9 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
(Reading database ... 342508 files and directories currently installed.)
Preparing to unpack .../solc_1%3a0.3.5-nightly-2016-08-08-ffl-c3ed550-0ubuntu4~trusty_amd64.deb ...
Unpacking solc:amd64 (1:0.3.5-nightly-2016-08-08-ffl-c3ed550-0ubuntu4~trusty) over (1.2.9-SNAPSHOT--20160628-6a05dd7~trusty-0ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/solc_1%3a0.3.5-nightly-2016-08-08-ffl-c3ed550-0ubuntu4~trusty_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/libevmasm.so', which is also in package libethereum:amd64 1.2.9-SNAPSHOT--20160630-f09ff00~trusty-0ubuntu1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/solc_1%3a0.3.5-nightly-2016-08-08-ffl-c3ed550-0ubuntu4~trusty_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@goldhat00-desktop:/home/goldhat00#

**Comment by primehat23** [comment] 2016-08-09 21:14
Im gonna go play doom while this gets worked out. If your dev team needs anything just message me. I have been working on this project since 2011(sortof). Can I get more involved with the team. I am really the best at python. Who should I email if I want to help serpent? I also have a fleshed out DAPP idea. I just can't get anything to work! before this year I was using windows, which is taken care of like an adopted child. Now that I am on ubuntu I have run into all sorts of kerfuckles. I would hold developers to a higher standard, but this time we are dealing with a sort of self aware network. What the deal with geth? can it play music yet?

**Comment by bobsummerwill** [comment] 2016-08-09 21:20
Thanks for the offer!    Yep - Doom it up :-)   That's the best idea.

All of the development chat is happening using Gitter, which just uses your GitHub account, so just head over to an appropriate group (often 1-1 with repos) and offer your help.

Serpent is an interesting one.   Piper Merriam has just been reviving it, and updating it to work with Python 3.0, and I am sure they would love more hands on deck there.

For example:
- https://gitter.im/ethereum/cpp-ethereum
- https://gitter.im/ethereum/go-ethereum
- https://gitter.im/ethereum/pyethereum
- https://gitter.im/ethereum/pyethapp
- https://gitter.im/ethereum/serpent
- https://gitter.im/ethereum/solidity

**Comment by chriseth** [comment] 2016-08-10 11:01
Closing as duplicate of #851

**Closed as completed by chriseth** 2016-08-10 11:01 UTC
Labels: bug :bug:

**Comment by primehat23** [comment] 2016-08-11 11:38
I think you guys did this on purpose to halt all people wanting to support eth(POW, prisoner of war/(proof of work) chain). Really good war strat. I think napoleons ;) brother told him to do that same tactic.  really smart. If people have a chain (from the before times) they can catch up and use a geth --clean geth --update and still run the kigigger. Though if new buckets(think south korea backing the dao strike with new nvida 10 series for 3 years(i mean your team would just fall apart on that. as would the geth eth economy. thus it would be as profitable as lisk.)) where to pop up they would need to be gendered right away, eth or that which goes by many names. either way get me more involved. I never get a google+ poke. I would love to create a FART circle on google plus for KGB like goals in your solc(think cccp) government.

**Comment by primehat23** [comment] 2016-08-11 11:41
DO YOU KNOW WHO I AM?
WHO THE TELL DO YOU THINK I AM.
ky-GO
