### ISSUE TITLE
Assembly libraries

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#13472] opened 2022-09-01 22:17 UTC
## Abstract

We have assembly/yul functions but can't reuse them among assembly blocks. Let's have assembly libraries!

## Motivation

Would allow us to reuse assembly code

## Specification

Let's have it like this:
```solidity
assembly library AsmERC20 {
    function approve(token, to, amount) {
        // ...
    }
    function transfer(token, to, amount) {
        // ...
    }
}
```

and use it like this:
```solidity
assembly {
    AsmERC20.transfer(token, to, amount);
}
// ...
assembly {
    AsmERC20.approve(token, to, amount);
}
```

## Backwards Compatibility

Not required

**Comment by duanxiao0805** [comment] 2022-09-02 03:15
what tpken

**Comment by ekpyron** [comment] 2022-09-02 11:21
Do you agree that this is a duplicate of https://github.com/ethereum/solidity/issues/9282?
The idea there was to allow file level inline assembly blocks that would allow to define reusable functions. Being able to namespace those would of course be nice - but that could be done via the import mechanism, resp. is part of the more general issue of allowing inner-file-namespacing.

So given that I think there's no need for assembly libraries as special construct and file-level assembly blocks are the simpler and more consistent option for this.

I'll go ahead and close this as duplicate and maybe re-triage https://github.com/ethereum/solidity/issues/9282 - but if you disagree, feel free to reopen!

**Closed as completed by ekpyron** 2022-09-02 11:21 UTC
Labels: language design :rage4:

**Comment by k06a** [comment] 2022-09-02 13:26
@ekpyron any idea when we could have any of these?

**Comment by cameel** [comment] 2022-09-05 11:11
As @ekpyron said, we're going to retriage #9282, which will involve figuring out where it fits in our short- and long-term roadmap. So no decision yet but the way I see it personally: there are enough important features in the short-term that we won't get to it very soon but it's also important enough to be considered a core feature and be somewhere on the roadmap.

Unless... @chriseth did you consider #9282 to be a part of #13319? :)

**Comment by k06a** [comment] 2022-09-05 13:00
@cameel @ekpyron I am not sure having global assembly block is same good as having assembly library. Assembly library could allow to have only assembly functions declarations. Please consider this idea.

**Comment by ekpyron** [comment] 2022-09-05 16:08
A global assembly block would also only allow function declarations in it (I don't see what anything but function definitions in them would mean) - and those would be globally available.
So the only actual difference I see is that an assembly library would implicitly introduce a namespace for them. That's of course nice, but part of the larger issue of namespacing globally-scoped items in general. This can right now be achieved using the import mechanism, but we may also provide a file-local mechanism in the future.

Given that - what remaining advantage would assembly libraries have concretely?

**Comment by ekpyron** [comment] 2022-09-05 16:09
I.e. from what I understand the plan to have global assembly blocks is exactly your suggestion of assembly libraries minus namespaces - and the issue of namespaces is best solved uniformly together with namespacing free functions, etc., isn't it?
