### ISSUE TITLE
[Sol->Yul] Invalid IR generated during copy of dynamically sized storage arrays of function type

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#12057] opened 2021-09-29 14:33 UTC
```
contract C {
  function() external [] s0;
  function() external [] s1;
  constructor() {
    s0 = s1;
  }
  receive() external payable {}
}
```

throws

https://github.com/ethereum/solidity/blob/e5eed63a3e83d698d8657309fd371248945a1cda/libsolidity/codegen/ir/IRGenerator.cpp#L107

To repro, do

```
$ solc --experimental-via-ir test.sol
```

**Comment by nishant-sachdeva** [comment] 2021-11-24 18:01
Okay, so I put the test mentioned here in a .sol file of it's own and ran the following commands 

1. solc --ir test.sol 2> only_ir.txt

2. solc --strict-assembly  only_ir.txt 2> error.txt

I got the following error description
`Error: Function "convert_t_function_external_nonpayable$__$returns$__$_to_t_function_external_nonpayable$__$returns$__$" expects 2 arguments but got 1.
   --> only_ir.txt:236:38:`

`Error: Variable count mismatch for declaration of "itemValue": 1 variables and 2 values.
   --> only_ir.txt:236:21:`

`Error: Function "prepare_store_t_function_external_nonpayable$__$returns$__$" expects 2 arguments but got 1.
   --> only_ir.txt:239:34:`


![Screenshot from 2021-11-24 23-36-19](https://user-images.githubusercontent.com/32475507/143291970-23255aaf-967f-4828-822b-75af7678dc28.png)

**Comment by cameel** [comment] 2021-11-25 01:46
Yeah, that's the issue. Yul code generated by the compiler should not have syntax errors.

To find the cause I'd start looking around the code that processes assignments in the IR codegen: https://github.com/ethereum/solidity/blob/71f8576b86e7c2f9161683bf2c6c7129f624f182/libsolidity/codegen/ir/IRGeneratorForStatements.cpp#L434-L489

It adds a conversion for the value being assigned. We have a helper that generates the conversion function you see in the error messages and that function apparently gets too few arguments. My guess would be that it's because external function pointers take one slot in storage but two slots on the stack and the code that inserts a call to it does not take that into account: https://github.com/ethereum/solidity/blob/71f8576b86e7c2f9161683bf2c6c7129f624f182/libsolidity/ast/Types.cpp#L3103-L3151

Please make sure it does not happen with other types that take two slots on the stack as well. AFAIK the only other one is a calldata array slice. But this bug only seems to happen when the variable on the right side is a storage variable so I did not manage to reproduce it with slices. For example this compiles just fine via IR:
```solidity
contract C {
    uint[] a;

    function f(uint[] calldata b) public {
        a = b[:];
    }
}
```

**Comment by chriseth** [comment] 2021-11-29 15:52
It complains about IR code of the form `let itemValue :=...`. If you search for that in the compiler source code, you end up in YulUtilFunctions.cpp, in the function `copyValueArrayStorageToStorageFunction`, so I think it has to be changed there. The code there looks a bit intimidating, but we can go through it together if you like.

**Comment by chriseth** [comment] 2021-11-29 15:56
I'm actually not sure if we should call `convert` there at all. The problem is that `extractFromStorageValue` does not return something of the actual type - external function pointers for example are always compressed.

**Comment by chriseth** [comment] 2021-11-29 15:58
Can you test if this breaks for copying such a storage array to memory? I don't see a similar protection for `copyArrayFromStorageToMemoryFunction` either.

**Comment by nishant-sachdeva** [comment] 2021-12-03 15:31
`
contract C {
    function() external [] s0;
    function numbers (uint[] memory s1) public {
        s1 = s0;
    }
}
`

I'm not sure if this correctly tests it or not. But on running the command `solc --ir test.sol 2> test_ir.txt` , I got the error statement as `Error: Type function () external[] storage ref is not implicitly convertible to expected type uint256[] memory.
 --> test2.sol:4:14:`

On the other hand, using the below code seems to compile perfectly 

`
contract C {
    uint [] s0;
    function numbers (uint[] memory s1) public view {
        s1 = s0;
    }
}
`


Again, not sure if this correctly tests what @chriseth  was asking for. So, do let me know if any changes need to be made!

**Comment by nishant-sachdeva** [comment] 2021-12-05 17:53
On the other hand, using the below code seems to compile perfectly 

`contract C {
    uint [] s0;

    function numbers (uint[] memory s1) public view {
        s1 = s0;
    }
}
`

**Comment by chriseth** [comment] 2021-12-15 19:06
Fixed by https://github.com/ethereum/solidity/pull/12372

**Closed as completed by chriseth** 2021-12-15 19:06 UTC
Labels: bug :bug:, codegen error
