### ISSUE TITLE
Solc Compiler Crash on a very long SPDX comment

### ISSUE THREAD

**Issue by CarlosAndresRamirez** [ethereum/solidity#14656] opened 2023-10-30 13:11 UTC
## Description
A crash can be triggered in the Solidity compiler inside the std::regex library when trying to parse malcrafted source code related to the SPDX-License-Identifier. The issue takes place due to insufficient input checks inside source file Parser.cpp function Parser::findLicenseString() of libsolidity.

Considering source files can be imported remotely, a DoS attack on the Solidy compiler is possible by providing a malcrafted src input. Attack vector is via local or remote inclusion of source files using the "import" directive (ie. attacker controlled source file).  Impact seems to be limited to security principle of Availability.

## Environment

- Compiler version: Latest version
- Target EVM version (as per compiler settings): ANY
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Linux

## Steps to Reproduce
// Compile / import the following source. NOTE: Google form limits the size, try growing it over 50KB:
// SEE ATTACHED PoC input

// SPDX-License-Identifier: GPL-3.0-or-latwwwwwwwwwwwwwwwwwwwwwwwwwwww///\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\99\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4;\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4\F4...
[in-crash.zip](https://github.com/ethereum/solidity/files/13205438/in-crash.zip)

**Comment by nikola-matic** [comment] 2023-11-27 10:19
Closing as a duplicate of https://github.com/ethereum/solidity/issues/12208

**Closed as completed by nikola-matic** 2023-11-27 10:19 UTC
Labels: bug :bug:
