### ISSUE TITLE
Encoding type "struct Decimal.decimal memory" not yet implemented

### ISSUE THREAD

**Issue by KimiWu123** [ethereum/solidity#9893] opened 2020-09-25 10:19 UTC
## Description
 I call `latestRoundData` from Chainlink aggregator and then covert the price to our own defined struct `Decimal` and it shows `Encoding type "struct Decimal.decimal memory" not yet implemented` error. as the following snippet,
 
```
// Decimal.sol
library Decimal {
    struct decimal {
        uint256 d;
    }
}

// priceFeed.sol
using Decimal for Decimal.decimal;

    function update(bytes32 _priceFeedKey) external {
        AggregatorV3Interface aggregator = getAggregator(_priceFeedKey);
        (
            uint80 roundId,
            int256 price, 
            uint256 decimals, 
            uint256 timestamp, 
            uint80 answeredInRound
        ) = aggregator.latestRoundData();

        rootBridge.updatePriceFeed(
            priceFeedL2Address, 
            _priceFeedKey, 
            Decimal.decimal(uint256(price))),
            timestamp, 
            roundId
        );
    }
```

If I add a dummy function with `Decimal.decimal` argument as the following 
```
function dummy(Decimal.decimal calldata empty) external {}
```
and then everything goes well. Do you have any ideas? Thanks.

## Environment

- Compiler version: 0.6.7
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): oz
- EVM execution environment / backend / blockchain client: na
- Operating system: Mac

**Comment by cameel** [comment] 2020-09-25 14:31
I can't tell for sure without seeing the rest of your code but I think you're calling a function from a file that uses ABIEncoderV2 while your file is not using it. Try adding `pragma experimental ABIEncoderV2;` at the beginning of your file.

Your error is the same as #5659 and the cause is probably the same as in #8379. If that's the case then your code should not compile anyway but the compiler should report an error instead of crashing. The fix for that is on the way (#9835).

**Comment by KimiWu123** [comment] 2020-09-26 01:48
Thanks for your reply. I do have `pragma experimental ABIEncoderV2;` at the beginning of the file, but I just realized that the derived contract doesn't have it, just like #8379. The compiler doesn't crash (I guess), but the message is not clear enough. Thanks!

**Comment by KimiWu123** [comment] 2020-09-26 01:53
Thanks for your reply. I do have `pragma experimental ABIEncoderV2;` at the beginning of the file, but I just realized that the derived contract doesn't have it, just like #8379.  Thanks!

**Comment by cameel** [comment] 2020-09-26 20:10
Great! In that case I'm closing this as a duplicate of #8379.

**Closed as completed by cameel** 2020-09-26 20:10 UTC
Labels: bug :bug:, should report better error
