### ISSUE TITLE
Array of static structures have strange `memory` layout

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#13818] opened 2022-12-19 12:17 UTC
## Description

We discovered that array of static structs have pretty strange `memory` layout comparing to `calldata` layout.

## Environment

- Compiler version: 0.8.17

## Steps to Reproduce

We expected the following code to have almost the same layouts for calldata and memory and avoid any huge reencoding on the way from `calldata` to `memory` and back to `calldata` for subcall.

```solidity
contract Test {
    struct Data {
        address token;
        uint256 amount;
    }

    function f(Data[] calldata items) external {
        Data[] memory copied = items;
        target.g(copied);
    }
}
```

But currently memory location contain array of offsets of all the static items:
```
[[0x1, 2], [0x3, 4], [0x5, 6]]
```

`calldata`:
```
0000000000000000000000000000000000000000000000000000000000000003 <= items.length
0000000000000000000000000000000000000000000000000000000000000001 <= items[0]
0000000000000000000000000000000000000000000000000000000000000002
0000000000000000000000000000000000000000000000000000000000000003 <= items[1]
0000000000000000000000000000000000000000000000000000000000000004
0000000000000000000000000000000000000000000000000000000000000005 <= items[2]
0000000000000000000000000000000000000000000000000000000000000006
```

`memory`:
```
0000000000000000000000000000000000000000000000000000000000000003 <= items.length
0000000000000000000000000000000000000000000000000000000000000060 <= offsets of items[0]
00000000000000000000000000000000000000000000000000000000000000a0 <= offsets of items[1]
00000000000000000000000000000000000000000000000000000000000000e0 <= offsets of items[2]
0000000000000000000000000000000000000000000000000000000000000001 <= items[0]
0000000000000000000000000000000000000000000000000000000000000002
0000000000000000000000000000000000000000000000000000000000000003 <= items[1]
0000000000000000000000000000000000000000000000000000000000000004
0000000000000000000000000000000000000000000000000000000000000005 <= items[2]
0000000000000000000000000000000000000000000000000000000000000006
```

**Comment by axic** [comment] 2022-12-19 12:30
Didn't you swap the `calldata`/`memory` labels in your description? Offsets for dynamic types in calldata could be expected, but not in memory.

**Comment by hrkrshnn** [comment] 2022-12-19 12:39
@k06a The encoding of `Data[]` in calldata doesn't look right

> cast abi-encode "f((address,uint)[])" "[(0xfeebabe6b0418ec13b30aadf129f5dcdd4f70cea,2),(0xfeebabe6b0418ec13b30aadf129f5dcdd4f70cea,4),(0xfeebabe6b0418ec13b30aadf129f5dcdd4f70cea,6)]"

```
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000003
000000000000000000000000feebabe6b0418ec13b30aadf129f5dcdd4f70cea
0000000000000000000000000000000000000000000000000000000000000002
000000000000000000000000feebabe6b0418ec13b30aadf129f5dcdd4f70cea
0000000000000000000000000000000000000000000000000000000000000004
000000000000000000000000feebabe6b0418ec13b30aadf129f5dcdd4f70cea
0000000000000000000000000000000000000000000000000000000000000006
```

The encoding you provided looks like it is for `Data[3]`. 

Also, the layout in calldata and the layout in memory for the same types *are* different.

**Comment by k06a** [comment] 2022-12-19 13:16
@hrkrshnn I provided memory layouts, not abi encodings - it is a bit different thing, but part of your message. I expected memory layout to be same as calldata layout, because it is simpler, shorter and non-redundand.

**Comment by hrkrshnn** [comment] 2022-12-19 16:25
@k06a So what does the code listing with `calldata` in the issue title refer to?

Anyway, unlike `calldata` (ABI) and `storage`, memory layout does not need to be standardized. The compiler can technically do whatever it wants. Regardless of that, memory layout should be consistent.

**Comment by k06a** [comment] 2022-12-19 16:34
@hrkrshnn there are no issues with `calldata`, I see issue with `memory`. With all what you wrote I see we could improve memory layout for such objects to avoid storing offsets for static structures.

**Comment by hrkrshnn** [comment] 2022-12-19 17:51
@k06a I meant the following:

> `calldata:`
> 
> ```
> 0000000000000000000000000000000000000000000000000000000000000003 <= items.length
> 0000000000000000000000000000000000000000000000000000000000000001 <= items[0]
> 0000000000000000000000000000000000000000000000000000000000000002
> 0000000000000000000000000000000000000000000000000000000000000003 <= items[1]
> 0000000000000000000000000000000000000000000000000000000000000004
> 0000000000000000000000000000000000000000000000000000000000000005 <= items[2]
> 0000000000000000000000000000000000000000000000000000000000000006
> ```

What is that encoding supposed to be?

**Comment by k06a** [comment] 2022-12-19 20:19
@hrkrshnn I like `calldata` layout which you and me showed, I dislike `memory` layout. I'm not sure why you read my initial message that way that you think I see any problem in `calldata` layout. It is totally fine, I would prefer to have `memory` layout to be the same as `calldata` layout.

**Comment by cameel** [comment] 2022-12-20 08:56
Yeah, the memory layout may be different from calldata even for static types. IIRC the compiler just always stores pointers for reference types and allocates them separately. That seems to be what you're seeing in your example. The dynamic array of structs is really an array of pointers to structs here.

So this is not a bug - it works as designed. It's different because trade-offs for memory are different from calldata and storage. I think that the efficiency of copying between calldata and memory wasn't high on the list of priorities back when this was designed. Probably still wouldn't be now.

I recall @ekpyron saying that we will likely be changing the memory layout in the future though, so if you think it should be different, the discussion is open. For that I'd suggest to drop by on one of the design calls though.

**Comment by ekpyron** [comment] 2022-12-20 12:42
It's tricky... the memory layout allows it to easily switch out pointers to sub-structures, i.e. in ``uint[100][1] memory x;``, since everything is pointers, I can switch ``x[0]`` to point to a different memory location without copying. Which is a good property for memory, but useless for (read-only) calldata.
The current situation in which calldata and memory have different layouts is rather unfortunate, but we can't really break the calldata layout and it doesn't always fit the requirements of an optimal memory layout, unless we simultaneously change a lot of e.g. the current reference semantics.
What we'll likely change at some point anyways, is the layout of memory types on stack, i.e. have a pointer to a data area and a length on stack like for calldata types, since that allows slicing of memory types. When doing that, we can consider further changes in the memory layout.

**Comment by ekpyron** [comment] 2022-12-20 12:45
But yeah, as for this issue: I think this clarifies that the memory layout in such cases is intentional and not without reason (i.e. the reason being to be able to switch out sub-structures without copying)?
Since given that, I'd close the issue (but feel free to reopen).

**Closed as completed by ekpyron** 2022-12-20 12:45 UTC

**Comment by k06a** [comment] 2022-12-21 08:02
@ekpyron I see why array of arrays have array of offsets, but not sure array of static structures need this benefit of fast swap. If someone want to achieve this, they could have array of indices and swap those indices.

**Comment by ekpyron** [comment] 2022-12-21 11:29
@k06a That's maybe right - but changing this would be a rather severe breaking change. E.g. in the following:
```
struct S { uint256 x; }
function f() public pure returns (uint256)
{
  S[2] memory s = [S(1), S(2)];
  S memory t = S(3);
  s[0] = t;
  t.x = 42;
  return s[0].x; // returns 42 now - would return 3 with a different layout
}
```
Now whether the current behaviour here is a good thing is arguable - but I don't think we'll break it without some further changes like more explicit copy vs. reference behaviour.
In principle, we could - in the long run - even have different types for pointers/references to memory and for statically inlined types.

I think a good point in time to consider changing any of this and how exactly, will be shortly after we have built an initial generic type system and start moving the implementation of these types to "user code"/standard library.
