### ISSUE TITLE
Function pointer comparison is inconsistent

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15010] opened 2024-04-12 11:50 UTC
## Description

If we compare two internal functions with different names but identical content, under normal compilation conditions, the result is false. However, when optimization is enabled, the comparison result is true.

## Environment

- Compiler version: 0.8.25
- Target EVM version (as per compiler settings): No restrictions
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: None
- Operating system: None

## Steps to Reproduce

```solidity
contract C {
    function f() internal {}
    function g() internal {}

    function test() public pure returns (bool) {
        return C.f == C.g;
    }
}
```
### origin
![1712922625711](https://github.com/ethereum/solidity/assets/147013944/e19c619d-0e80-458a-8c4e-38a33d754cf8)
### optimize
![1712922649225](https://github.com/ethereum/solidity/assets/147013944/270a40f2-0c08-4fff-8198-3f649c58f698)

**Comment by cameel** [comment] 2024-04-12 16:02
This is a duplicate of #13969.

The compiler also issues a warning to highlight the issue:
```
Warning: Comparison of internal function pointers can yield unexpected results in the legacy pipeline with the optimizer enabled, and will be disallowed entirely in the next breaking release.
 --> test.sol:6:16:
  |
6 |         return C.f == C.g;
  |                ^^^^^^^^^^
```

**Closed as not planned by cameel** 2024-04-12 16:02 UTC
Labels: bug :bug:
