### ISSUE TITLE
Support structs, enums and tuples in sha3() and other "accept arbitrary parameters" functions

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#980] opened 2016-08-31 08:45 UTC
- [ ] support structs
- [ ] support enums
- [ ] support tuples
- [ ] support contracts (encoded as addresses)
- [ ] disallow anything else as part of the type checker

```
contract test {

    struct TestStruct {
        uint a;
    }

    function test() {
        TestStruct memory testing = TestStruct({a: 1});
        sha3(testing);
    }
}
```

(Follow up from #332)

**Comment by chriseth** [comment] 2016-09-01 18:03
This is most likely a duplicate of https://github.com/ethereum/solidity/issues/595

**Comment by pirapira** [comment] 2016-09-05 14:47
I added "tuples" in the description because the title says "tuples".

**Comment by chriseth** [comment] 2018-06-13 07:31
Since we only support `bytes memory` in those functions in the future, and everything else has to use `abi.encode`, this can be closed.

**Closed as completed by chriseth** 2018-06-13 07:31 UTC

**Comment by krzkaczor** [comment] 2019-03-21 09:07
If anyone is still wondering how to do this, use `abi.encodePacked`:

```solidity
keccak256(abi.encodePacked(struct.a, struct.b, struct.c));
```
