### ISSUE TITLE
Assembly: assignment symbol can have whitespace

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4185] opened 2018-05-23 23:33 UTC
The following is accepted without warnings:

```
contract C {
  function f() returns (bool success) {
    assembly {
      success : = 1
    }
  }
}
```

I think it would make sense requiring no whitespace to be between `:` and `=`.

The same happens with stack assignments:
```
assembly {
  = : success
}
```

**Comment by Marenz** [comment] 2019-02-18 10:48
After clarification with @chriseth: Should become an actual error and is not a breaking change as the documentation never said it's possible

**Comment by Marenz** [comment] 2019-02-18 10:48
@leonardoalt if you are not actively working on this, I'd take over?

**Comment by Marenz** [comment] 2019-02-18 11:31
Leo verbally confirmed in the meeting, taking over.

**Comment by Marenz** [comment] 2019-02-19 09:19
@axic your second example

```
    contract C {
      function f() public {
        assembly {
                = : success
        }
      }
    }
```
Results in `    DeclarationError: (58-65): Multiple matching identifiers. Resolving overloaded identifiers is not supported.`
for me, no matter whether I use a space between `=` and `:` or not

**Comment by chriseth** [comment] 2019-02-19 13:09
@Marenz even if you write `function f() public pure returns (bool success)`?

**Comment by Marenz** [comment] 2019-02-19 17:19
```
    contract C {
		function f() public pure returns (bool success) {
        assembly {
                = : success
        }
      }
    }
```
results in 
```
test.sol:4:17: Error: The use of stack assignment is disallowed. Please use assignment in functional notation instead.
                = : success
                ^---------^
test.sol:3:18: Error: Unbalanced stack at the end of a block: 1 missing item(s).
        assembly {
```

No matter if with ` ` or without

**Comment by axic** [comment] 2019-02-19 20:35
You could coerce it with, but still get other errors:
```
    contract C {
		function f() public pure returns (bool success) {
        assembly {
                1
                = : success
        }
      }
    }
```

However the main point is that if the parser would reject whitespace between `=:` then you would get a parser error, but instead you are getting analysis errors.

**Comment by Marenz** [comment] 2019-02-19 20:53
I can look into why it is accepted

**Comment by chriseth** [comment] 2019-02-20 09:30
I'm actually not sure whether we should waste so much time on `=:`...

**Comment by Marenz** [comment] 2019-02-20 09:46
Well, I checked and the answer is simple.. it's different from normal assignment because that is `:=` not `=:`. I didn't touch `=:` because I didn't notice that it is different

**Closed as completed** 2019-02-21 13:43 UTC
Labels: language design :rage4:
