### ISSUE TITLE
Converting a solidity AST back to solidity Source Code

### ISSUE THREAD

**Issue by tharindu1992** [ethereum/solidity#5802] opened 2019-01-17 07:41 UTC
Is there a way to convert AST back to Solidity Source code. 

The use case is to mutate the AST and recreate the Solidity Source code for optimization and testing purposes.

**Comment by chriseth** [comment] 2019-01-21 09:37
Currently, there is no way. There is initial work on re-importing an AST, though, which could be of interest: #2096

**Comment by axic** [comment] 2019-01-21 11:24
Duplicate of #2165?

**Comment by chriseth** [comment] 2019-01-21 11:27
I think both issues need to be further clarified :)

**Comment by axic** [comment] 2019-01-21 11:31
Clarified it a bit there, not sure how much more it can be clarified :)

Closing this here.

**Closed as completed by axic** 2019-01-21 11:31 UTC

**Comment by ryanfalzon** [comment] 2022-02-18 08:57
Has there been any updates on this? I need to make use of this feature.

**Comment by cameel** [comment] 2022-02-18 19:19
No, the compiler can parse an AST from JSON but currently does not offer a feature to synthesize code back from that. There are external tools that can do that though. Check out [solc-typed-ast](https://github.com/ConsenSys/solc-typed-ast).

**Comment by cameel** [comment] 2022-02-18 19:20
BTW, this issue has been closed because it's a duplicate. The feature request is now tracked in #2165. I'm locking this thread - please post any related comments there.
