### ISSUE TITLE
examples/safe-remote.rst error

### ISSUE THREAD

**Issue by chenzuoli** [ethereum/solidity#7592] opened 2019-10-31 03:15 UTC
hi, in this project, I found there is an error in the solidity/docs/examples/safe-remote.rst  file, count from bottom to top the second row:
`buyer.transfer(value);`
should be like this:
`buyer.transfer(msg.value);`
because at the top of the file, you have already valued the `value` as `msg.value/2`.

```  
/// Confirm that you (the buyer) received the item.
    /// This will release the locked ether.
    function confirmReceived()
        public
        onlyBuyer
        inState(State.Locked)
    {
        emit ItemReceived();
        // It is important to change the state first because
        // otherwise, the contracts called using `send` below
        // can call in again here.
        state = State.Inactive;
        // NOTE: This actually allows both the buyer and the seller to
        // block the refund - the withdraw pattern should be used.
        buyer.transfer(value);
        seller.transfer(address(this).balance);
    }
```

Is it right?

**Comment by bshastry** [comment] 2019-10-31 08:35
@chenzuoli Thanks for the report. I think you are right, with a minor modification: it should be `value * 2` and not `msg.value` since `confirmReceived` is just a purchase confirmation and not the actual purchase (i.e., msg.value for `confirmReceived` should be zero).

@ChrisChinchilla I'm tagging this as docs. If you think this is incorrect, please let me know. Also, an ack of what I said/correction would be useful here :-)

**Comment by bshastry** [comment] 2019-10-31 14:08
@chenzuoli I noticed that you closed the issue, we usually keep the issue open until it is resolved. I'm reopening it for now.

**Comment by chenzuoli** [comment] 2019-10-31 14:12
ok, sorry I don't know that.

**Comment by bshastry** [comment] 2019-11-01 11:21
@chenzuoli would you like to work on a PR to fix this?

**Comment by chenzuoli** [comment] 2019-11-02 07:50
Hi, I don't know what is PR, can you tell me something about it? or you can help me fix this problem. thanks.

**Comment by bshastry** [comment] 2019-11-04 08:15
@chenzuoli No problem, a PR is essentially a proposal for change. I'll create a PR for this issue.

**Comment by ChrisChinchilla** [comment] 2019-11-04 08:25
Closed by https://github.com/ethereum/solidity/pull/7613#pullrequestreview-310920680

**Closed as completed by ChrisChinchilla** 2019-11-04 08:25 UTC
Labels: documentation :book:

**Comment by bshastry** [comment] 2019-11-04 11:28
@chenzuoli actually, the original code is correct.

Seller and buyer "stake" 2x the value of item on sale
Once the purchase is made and delivery of item confirmed, the seller obtains `value`, and buyer loses `value`

Here's a blog post I found useful in understanding the economics of escrow: https://jacksonng.org/Safe-Remote-Purchase-1

**Comment by chenzuoli** [comment] 2019-11-04 13:32
Yeah, get it, I really appreciate you.
