### ISSUE TITLE
Compiler mode to reimport assembly json.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#11787] opened 2021-08-11 12:45 UTC
The compiler can output the state of ``Assembly`` containing evmasm assembly items (``AssemblyItem``) in json using ``solc --asm-json``. (The main exporting logic is in ``Assembly::assemblyJSON``)
Since there are projects that use this assembly json, externally optimize it, and output a new, compatible assembly json, we want to be able to reimport assembly in this format.

So we want a command line interface mode, e.g. ``solc --asm-json-import`` that can parse the output of ``solc --asm-json`` and can continue compilation down to bytecode.

Exporting assembly json and then importing it, should produce exactly the same bytecode as compiling directly to bytecode.

The assembly json will contain nested subassemblies, auxiliary data and tags, etc., which should be sufficient to fill all members of ``Assembly`` correctly.

**Comment by chriseth** [comment] 2021-08-11 12:46
Duplicate of https://github.com/ethereum/solidity/issues/11254

**Comment by hrkrshnn** [comment] 2021-08-11 12:50
@lightclient Pinging since you may be interested in this feature. In short, this should allow solidity to be used as an assembler.

**Comment by lightclient** [comment] 2021-08-11 12:51
:fire:

**Closed as completed** 2023-10-24 17:41 UTC
Labels: protocol design :crystal_ball:, selected for development, high effort, medium impact, feature
