### ISSUE TITLE
Copyright year is 2016-2023 instead of 2016-2024

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#15201] opened 2024-06-17 17:12 UTC

**Comment by mehtavishwa30** [comment] 2024-06-18 09:17
Hey @0xdochev! We appreciate you taking the time to open an issue. However, it is difficult to understand what the issue is without specific details about appropriate description and links. Additionally, we are currently not seeking reports for trivial typo/grammar/language fixes in the docs or Solidity org website.

I will be closing this on these grounds.

**Closed as completed by mehtavishwa30** 2024-06-18 09:17 UTC
Labels: documentation :book:
