### ISSUE TITLE
Solidity compiler issue: error while loading shared libraries (unexpected reloc type 0x03)

### ISSUE THREAD

**Issue by OpenSFL** [ethereum/solidity#4316] opened 2018-06-19 13:20 UTC
I was able to build the solidity compiler from source. 
`$which solc`
`/usr/local/bin/solc`

However, when I run it or check its version
`$solc`
`$solc --version`
I got: 
> solc: error while loading shared libraries: /usr/lib/arm-linux-gnueabihf/libz3.so.4: unexpected reloc type 0x03

It was built on beaglebone black with debian stretch:
`$uname -a`

> Linux beaglebone 4.9.78-ti-r94 #1 SMP PREEMPT Fri Jan 26 21:26:24 UTC 2018 armv7l GNU/Linux

Any help and suggestions? Thank you!

**Comment by leonardoalt** [comment] 2018-06-19 13:23
Hi @OpenSFL, how did you install Z3? Did you build it from the sources?

**Comment by OpenSFL** [comment] 2018-06-19 13:44
Hi @leonardoalt, I followed this [https://solidity.readthedocs.io/en/latest/installing-solidity.html#external-dependencies](url) for installing the external dependencies:
`./scripts/install_deps.sh`

For installing Z3, the install_deps.sh says:

>                 sudo apt-get -y install \
                    build-essential \
                    cmake \
                    g++ \
                    gcc \
                    git \
                    libboost-all-dev \
                    unzip \
                    "$install_z3"

>                      #stretch
                        echo "Installing solidity dependencies on Debian Stretch (9.x)."
                        install_z3="libz3-dev"
Thanks!

**Comment by leonardoalt** [comment] 2018-06-19 14:11
Unfortunately I don't have access to an ARM at the moment to try and reproduce the problem. It could be that the Z3 package wasn't compiled properly.
Z3 is not a critical dependency and what you can do for the moment is to uninstall Z3 from your system and rerun the compilation steps from the `cmake ..` point.

**Comment by leonardoalt** [comment] 2018-07-06 09:11
I'm closing this issue since there is no official support to arm and it seems to be a problem in Z3 lib's distribution.

**Closed as completed by leonardoalt** 2018-07-06 09:11 UTC
Labels: build system :building_construction:
