### ISSUE TITLE
Solidity realtime compiler crash

### ISSUE THREAD

**Issue by LianaHus** [ethereum/solidity#44] opened 2015-09-03 08:22 UTC
https://github.com/ethereum/wiki/issues/26

**Comment by LianaHus** [comment] 2015-09-03 09:45
I've reproduced the issue also on my computer(ubuntu/Firefox). I've checked with solidity compiler - there are no problems in solidity part so this is really only the realtime compiler issue.

**Comment by itsnotlupus** [comment] 2015-09-03 19:33
3 issues in one. fun.

1: This is an infinite loop. The web vm deals poorly with those, probably because it's being given too much gas to play with.    
2: Given an array of any type `a`, `a[a.length]` will always throw an exception. But `a[a.length++]` does not. That's weird. At best, things are not happening in the right order.  
3: in the code given, it looks like testing1.length++ is actually incrementing both testing1.length and testing.length. No idea what could even cause that.

**Comment by cozylife** [comment] 2015-09-03 22:26
"1: This is an infinite loop. The web vm deals poorly with those, probably because it's being given too much gas to play with."

How is it an infinite loop? Is it strictly because of your third point or am I missing something Solidity specific? As for incrementing the length, I did that because the following code doesn't work properly.

```
function test() public returns(uint8)
    {
        uint8[] testing;
        testing[0] = 1;
        testing[1] = 2;
        testing[2] = 3;
        
        delete testing[1];
        
        uint8[] testing1;
        uint8 k = 0;
        for (uint8 i = 0; i < testing.length; i++) {
            if (0 != testing[i]) {
                testing1[k++] = testing[i];
            }
        }
        
        return testing1[0];
    }
```
For some reason the method fails (returns 0) right after the `testing[0] = 1;` portion. Thus, I'm still confused if I'm supposed to increment the length of the array or if Solidity changes the length when I set a value to a new location. One or the other must work so the dynamic array gets appropriately resized.

**Comment by itsnotlupus** [comment] 2015-09-03 23:15
Yes, it's only infinite because testing.length itself keeps increasing when you're incrementing another array's length.

The way Solidity is intended to work, as I understand it, the length of the array must be set before an item on that array is accessed. Otherwise, an exception should be thrown.

So a[a.length++] should never work, since it accesses an item at an index beyond the array's current size before adjusting the array's length.  
If you split things into two statements, like
```
    if (0 != testing[i]) {
        testing1.length += 1;
        testing1[testing1.length - 1] = testing[i];
    }
```
then you're not accessing an array out of bound. 
Unfortunately, incrementing the length of `testing1` still increments the length of `testing`.
That's definitely broken, and a bit annoying to work with, but you can get by with something like:
```
contract c {
    
    function test() public returns(uint8) {
        uint8[] testing;
        testing.length = 3;
        testing[0] = 1;
        testing[1] = 2;
        testing[2] = 3;

        delete testing[1];

        uint8[] testing1;
        uint len = testing.length;
        for (uint8 i = 0; i < len; i++) {
            if (0 != testing[i]) {
                testing1.length += 1;
                testing1[testing1.length -1 ] = testing[i];
            }
        }

        return testing1[0];
    }    
}
```

To split the problematic behaviors seen here into minimal reproducible bits, here's a contract with a few methods showing each problem:
```
contract c {
    function throwsCorrectly() returns (bool) {
        int[] a;
        a[a.length];
        return true;
    }
    
    function shouldThrowButDoesnt() returns (bool) {
        int[] a;
        a[a.length++];
        return true;
    }
    
    function shouldReturnZeroButDoesnt() returns (uint) {
        int[] a;
        int[] b;
        a.length = 6;
        return b.length;
    }
}
```

**Comment by cozylife** [comment] 2015-09-04 01:10
Is `testing1.length += 1;` equivelent to `testing1.length++;` in Solidity?

**Comment by itsnotlupus** [comment] 2015-09-04 03:07
As a standalone statement, yes. They literally compile to the same bytecode.

**Comment by androlo** [comment] 2015-09-06 14:57
This size error holds for storage-backed arrays as well.  `Version: 0.1.2-0/Release-Linux/g++/int`

```
contract c {

    int[] sA;

    function shouldReturnZeroButDoesnt() returns (uint) {
        int[] b;
        sA.length = 6;
        return b.length;
    }
}
```

**Comment by chriseth** [comment] 2015-09-07 13:52
Two points:
1. You have to distinguish between `a.length++` and `++a.length`. The code `a[a.length++] = ...` is perfectly fine and probably even idiomatic.
2. If you use things like `int[] b` you create a local variable that points to storage. Not assigning it is an error (which is not yet detected by the compiler) and will result in it pointing to the first storage variable. This is why you see these effects. What you probably want is `int[] memory b`.

**Comment by chriseth** [comment] 2015-09-07 14:25
Concerning the crash: I would assume this is the strain put on the Javascript runtime created by the storage trie.

**Closed** 2015-09-07 14:27 UTC
Labels: bug

**Comment by cozylife** [comment] 2015-09-07 15:52
"You have to distinguish between a.length++ and ++a.length."

The latter is pre-incremented, thus it won't allow for access to the 0 index when used in that context. That's why I told Solidity to use the value before incrementing it.

"What you probably want is int[] memory b."

I'll give that a shot. Thank you.
