### ISSUE TITLE
Incorrect source mappings of inline statements

### ISSUE THREAD

**Issue by Doryanni** [ethereum/solidity#9896] opened 2020-09-25 16:25 UTC
## Description

The compiler generates some source maps of inline statements that have no match with nodes of the AST output. 

## Environment

- Compiler version: 0.4.24
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): None
- Operating system: Ubuntu 18

## Steps to Reproduce

An example is the [Fomo3D contract](https://etherscan.io/address/0xa62142888aba8370742be823c1782d17a0389da1).
On line 278, the source mapping corresponding to the solidity opcode EXTCODESIZE is **15759:18:0**, but no node can be found on the compiler's AST with such a source range.

**Comment by chriseth** [comment] 2020-09-25 16:27
Thanks for reporting! Since 0.4.24 is really old, there is a good chance that this has been fixed in the meantime. Do you have example code that is a bit shorter and can be easily translated to 0.7.x?

**Comment by Doryanni** [comment] 2020-09-25 16:32
Sorry, no I don't. This is just a random test I stumbled upon whilst working on a project of mine.

**Comment by chriseth** [comment] 2021-06-22 12:55
I'm closing this. Source locations inside inline assembly work in 0.4.26 as well in the latest version, so I assume that this might be connected to the optimizer, but it is hard to reproduce like that.

**Closed as completed by chriseth** 2021-06-22 12:55 UTC
Labels: bug :bug:, codegen error
