### ISSUE TITLE
4-byte-selector of function with struct argument differs between contract and library

### ISSUE THREAD

**Issue by gsalzer** [ethereum/solidity#7523] opened 2019-10-07 20:51 UTC
## Description

Given a function with an argument of type struct, its four byte function selector is computed differently depending on whether the function appears in a contract or a library, where the selector in the library is the unexpected one.

Expected behaviour: the four byte function selector should depend only on function name and argument types, but not on the context.

## Environment

- Compiler version: 0.5.12
- Target EVM version (as per compiler settings): default (petersburg)
- Framework/IDE (e.g. Truffle or Remix): command line
- EVM execution environment / backend / blockchain client: none
- Operating system: Linux

## Steps to Reproduce

In a contract, the four byte selector of the function `F` consists of the first four bytes of `keccak 256('F((address))'),` i.e. `0xa0b61132`.

```
# cat c.sol
pragma solidity 0.5.12;
pragma experimental ABIEncoderV2;
contract C {
  struct S {address a;}
  function F(S calldata) external pure returns (uint256) {
    return 0;
  }
}
# solc --asm c.sol
...
    tag_1:
        /* "c.sol":58:173  contract C {... */
      pop
      jumpi(tag_2, lt(calldatasize, 0x04))
      shr(0xe0, calldataload(0x00))
      dup1
      0xa0b61132
      eq
      tag_3
      jumpi
...
```

In a library, the four byte selector of the function `F` is computed differently as `0xe2a2daa1`

```
# cat l.sol
pragma solidity 0.5.12;
pragma experimental ABIEncoderV2;
library L {
  struct S {address a;}
  function F(S calldata) external pure returns (uint256) {
    return 0;
  }
}
# solc --asm l.sol
...
sub_0: assembly {
        /* "l.sol":58:172  library L {... */
      eq(address, deployTimeAddress())
      mstore(0x40, 0x80)
      jumpi(tag_1, lt(calldatasize, 0x04))
      shr(0xe0, calldataload(0x00))
      dup1
      0xe2a2daa1
      eq
      tag_2
      jumpi
...
```

**Comment by gsalzer** [comment] 2019-10-09 09:48
Someone on ethereum.stackexchange pointed out that `0xe2a2daa1` are the first four bytes of the hash of `F(L.S)`. So it's probably not a bug but a feature. Is there any documentation (other than the source code of the compiler) explaining under which circumstances a type is normalized and when user-defined types are retained?

**Comment by gsalzer** [comment] 2019-10-09 19:42
Seems to be the same issue as #6420 .
It would still be nice if this was documented somewhere.

**Comment by haltman-at** [comment] 2019-10-15 21:31
Not one of the developers, but I happen to know the answer to this question -- it happens precisely for user-defined types (structs, enums, contract types).  Everything else works the same as in the usual ABI.

**Comment by chriseth** [comment] 2019-10-16 07:12
Closing as duplicate of https://github.com/ethereum/solidity/issues/6420

**Closed as completed by chriseth** 2019-10-16 07:12 UTC
