### ISSUE TITLE
Compiler doesn't recognise declared variable scope

### ISSUE THREAD

**Issue by radek1st** [ethereum/solidity#3480] opened 2018-02-10 13:52 UTC
```
pragma solidity ^0.4.19;

contract ScopeBug {

  struct MyStruct {
    uint amount;
    address target;
  }

  function outOfScope() public {
    if (false) {      
      MyStruct memory st = MyStruct(0, address(this));
      st.amount = 100;
      st.target = msg.sender;
    } else {
      st.amount = 10;
      st.target = address(this);
    }
  }
}
```
The declaration of `MyStruct st` happens inside of `if` branch that will never execute. Yet, other parts of the code reference `st` and the code still compiles in Remix (0.4.19+commit.c4cbbb05.Emscripten.clang). I would expect the compilation to fail.

**Comment by axic** [comment] 2018-02-10 16:35
It is not a "bug", but by design. It follows the Javascript scoping rules.

This will be changed soon with #1679.

Closing this as it was covered with multiple issues before.

**Closed as completed by axic** 2018-02-10 16:35 UTC
