### ISSUE TITLE
SOL-007 Error-prone Multi-Assignment with empty LValues

### ISSUE THREAD

**Issue by mvglasenapp** [ethereum/solidity#3326] opened 2017-12-14 11:06 UTC
**Description**

Solidity has a multi-assignment feature. This works for lists (or tuples) created explicitly or from function return values. A function can return a list of values and the caller can assign each returned value to a different variable (LValue).

Some examples are:

function return2E() returns(uint,uint) {
return (1,2);
}
...
var (a1,a2,a3) = (V0,V1,V2);
var (h1,) = return2E();

Solidity has three special assignment modes for these tuples: head empty LValue, tail empty LValue, and positional empty LValue. The tail empty LValue applies when the number of elements of the destination list is smaller than the number of elements of the source list, and the rightmost destination element is empty. This means that additional elements to the right (the tail) will be ignored after being computed. The head empty LValue applies when the number of elements of the destination list is smaller than the number of elements of the source list, and the leftmost destination element is empty. This means that the additional leftmost elements (the head) will be ignored after being computed. The positional empty LValue is the one normally expected: if the number of elements in the destination list is equal to the number of elements in the source list, then any empty source element means to ignore the element at that particular position.

Example of positional empty LValue:
var (,y,) = (V0,V1,V2);

Example of tail empty LValue:
var (g1,) = (return1(),return2());

Example of head empty LValue:
var (,d1, d2) = (V0,V1,V2,V3,V4,V5,V6);

However, if two or more positions are empty at one side, but the number of elements in source
and destination list differs, it still means a head/tail empty LValue, as this example shows. This
assignment corresponds to e2 = v3 and e3 = v4, even if it suggests e2=v2 and e3=v3:
var ( , ,e2, e3) = (V0,V1,V2,V3,V4);

**Recommendations**

We recommend that in case of head/tail empty LValues, no other side empty LValue can be
specified. We also recommend that head/tail empty LValues are marked with three dots to
differentiate from positional empty LValues, as in here:
var ( ... , e3, e4) = (V0,V1,V2,V3,V4);

**Comment by chriseth** [comment] 2017-12-14 14:08
Related: https://github.com/ethereum/solidity/issues/3314

**Comment by axic** [comment] 2018-02-21 23:26
Closing this as a duplicate of #3314 as it has more details about an actual solution.

**Closed as completed by axic** 2018-02-21 23:26 UTC
