### ISSUE TITLE
[TypeChecker] Null pointer dereference on every use of a built-in unary operator

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#14001] opened 2023-02-23 07:00 UTC
```
contract C {
  int8 public s = -1;
}
```

derefs null pointer here

https://github.com/ethereum/solidity/blob/58c1cc6bde14b6ff6e97c9fb6fc4176577ab57b6/libsolidity/analysis/TypeChecker.cpp#L1783

Repro requires solc compiled with UBSan

**Comment by cameel** [comment] 2023-02-23 23:07
True, `_operation.userDefinedFunctionType()` is `nullptr` when the operator is built-in, so accessing `returnParameterTypes()` on it is a null dereference. Interestingly, it does not seem to crash, which is why it slipped through. Could be because we only ever touch the value it returns in the non-null case.

Still, it's clearly a bug and should be fixed. It would normally be more serious, but fortunately until we see an actual crash in a release binary the impact is low.

**Comment by cameel** [comment] 2023-03-06 18:24
Just for completeness, here's how to reproduce it with the example from the description (named `test.sol` here):

```bash
cmake -DSANITIZE=undefined -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
make
solc/solc test.sol
```
Output:
```
libsolidity/analysis/TypeChecker.cpp:1783:83: runtime error: member call on null pointer of type 'solidity::frontend::FunctionType'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior libsolidity/analysis/TypeChecker.cpp:1783:83 in
```

**Closed as completed** 2023-03-07 22:42 UTC
Labels: bug :bug:, low effort, low impact, must have
