### ISSUE TITLE
Use immutable in pure function

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#12829] opened 2022-03-21 20:27 UTC
## Abstract

`immutable` is defined as:

> The contract creation code generated by the compiler will modify the contract’s runtime code before it is returned by replacing all references to immutables by the values assigned to the them. 
>
> https://docs.soliditylang.org/en/v0.8.13/contracts.html?highlight=immutable#immutable

So I was expecting this to work since it does not access state:

```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.7.0 <0.9.0;

contract Ballot {
    uint256 immutable count;
    constructor() {
        count = 5;
    }
    function getCount() external pure returns(uint256) {
        return count;
    }
}
```

**Comment by chriseth** [comment] 2022-03-22 14:17
Duplicate of https://github.com/ethereum/solidity/issues/9554 - it works if you write `uint immutable count = 4`.

**Closed as completed by chriseth** 2022-03-22 14:17 UTC

**Comment by fulldecent** [comment] 2022-03-22 15:23
I do not consider this a duplicate.

Passing in the variables in the constructor will result in the variables (immutable) getting written to the bytecode. And so that function should be able to be pure.

**Comment by ekpyron** [comment] 2022-04-04 08:36
It's in a sense a duplicate of https://github.com/ethereum/solidity/issues/8153, though - ``pure`` is still in limbo between the stronger "can be compile-time evaluated" and the weaker mere "does not read from storage"...
In the past I argued for strengthen it to the former, which would mean the case at hand is not pure. However, in the meantime I'd also be fine to weaken it to the latter (in which case the example in this issue would indeed become pure) and either make "can be compile-time evaluated" merely an implicit analysis result or add new explicit syntax for it...
But in general, it seems we're stuck on a definite decision on this, so we should probably should do *something* about it...
