### ISSUE TITLE
Unexpected results are produced when fetching Struct across contracts

### ISSUE THREAD

**Issue by nishuzumi** [ethereum/solidity#14114] opened 2023-04-12 16:23 UTC
## Description
I encountered a very strange problem, unexpected results are produced when fetching Struct across contracts
## Environment

- Compiler version: 0.8.18
- Target EVM version (as per compiler settings):0.8.18+commit.87f61d96
- Framework/IDE (e.g. Truffle or Remix):Remix
- EVM execution environment / backend / blockchain client:Remix
- Operating system:Remix

## Steps to Reproduce

```
pragma solidity ^0.8.0;

interface IStorage{
    struct Filed{
        uint id;
        string name;
    }
}

contract Storage is IStorage {
    mapping(uint256 => Filed) public store;

    constructor(){
        store[1] = Filed(1,"Bot");
        store[0] = Filed(0,"Gun");
        store[2] = Filed(3,"Love");
    }
}

interface IStorageExtra is IStorage{
    function store(uint id) external view returns(Filed memory);
}

contract Query {
    IStorageExtra public storageContract;
    constructor(){
        storageContract = IStorageExtra(address(new Storage()));
    }

    function query() public view returns(Storage.Filed[] memory){
        uint max = 2;
        Storage.Filed[] memory data = new Storage.Filed[](max);
        for(uint i = 0; i < max ;i++){
            data[i] = storageContract.store(i);
        }
        return data;
    }

    function query2() public view returns(Storage.Filed[] memory){
        Storage.Filed[] memory data = new Storage.Filed[](1);
        data[0] = storageContract.store(2);
        return data;
    }

    function query3() public view returns(Storage.Filed memory){
        Storage.Filed memory data = storageContract.store(2);
        return data;
    }


    function query4OK() public view returns(Storage.Filed memory){
        Storage.Filed memory data = storageContract.store(0);
        return data;
    }

    function query5OK() public view returns(Storage.Filed[] memory){
        uint max = 1;
        Storage.Filed[] memory data = new Storage.Filed[](max);
        for(uint i = 0; i < max ;i++){
            data[i] = storageContract.store(i);
        }
        return data;
    }
}
```
I can deploy this code to run on Remix. When I execute the query method in Query, this line of code will give an error, where `query`, `query2`, `query3` will all give an error, while `query4`, `query5` will not give an error.

**Comment by 0xAWM** [comment] 2023-04-13 02:11
``` solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract Storage {
    struct Filed {
        uint256 id;
        string name;
    }

    mapping(uint256 => Filed) public store;

    function storeOK(uint256 _id) external view returns (Filed memory) {
        return store[_id];
    }
}

contract Query {
    Storage public storageContract;

    constructor() {
        storageContract = new Storage();
    }

    function query() public view {
        Storage.Filed memory errData = storageContract.store(0); // It will trigger an error from the compiler.
        Storage.Filed memory data = storageContract.storeOK(0); // fine
    }
}

```

```
TypeError: Different number of components on the left hand side (1) than on the right hand side (2).
  --> box.sol:25:9:
   |
25 |         Storage.Filed memory errData = storageContract.store(0);
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: Type uint256 is not implicitly convertible to expected type struct Storage.Filed memory.
  --> box.sol:25:9:
   |
25 |         Storage.Filed memory errData = storageContract.store(0);
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by nishuzumi** [comment] 2023-04-13 03:47
> ```solidity
> // SPDX-License-Identifier: UNLICENSED
> pragma solidity ^0.8.13;
> 
> contract Storage {
>     struct Filed {
>         uint256 id;
>         string name;
>     }
> 
>     mapping(uint256 => Filed) public store;
> 
>     function storeOK(uint256 _id) external view returns (Filed memory) {
>         return store[_id];
>     }
> }
> 
> contract Query {
>     Storage public storageContract;
> 
>     constructor() {
>         storageContract = new Storage();
>     }
> 
>     function query() public view {
>         Storage.Filed memory errData = storageContract.store(0); // It will trigger an error from the compiler.
>         Storage.Filed memory data = storageContract.storeOK(0); // fine
>     }
> }
> ```
> 
> ```
> TypeError: Different number of components on the left hand side (1) than on the right hand side (2).
>   --> box.sol:25:9:
>    |
> 25 |         Storage.Filed memory errData = storageContract.store(0);
>    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> TypeError: Type uint256 is not implicitly convertible to expected type struct Storage.Filed memory.
>   --> box.sol:25:9:
>    |
> 25 |         Storage.Filed memory errData = storageContract.store(0);
>    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```

Any best practice code tells us not to directly import contracts but to interface.
Second, this code works fine in a new case.
```
pragma solidity ^0.8.0;

interface IStorage{
    struct Filed{
        uint id;
        uint name;
    }
}

contract Storage is IStorage {
    mapping(uint256 => Filed) public store;

    constructor(){
        store[1] = Filed(1,1);
        store[0] = Filed(0,2);
        store[2] = Filed(3,4);
    }
}

interface IStorageExtra is IStorage{
    function store(uint id) external view returns(Filed memory);
}

contract Query {
    IStorageExtra public storageContract;
    constructor(){
        storageContract = IStorageExtra(address(new Storage()));
    }

    function query() public view returns(Storage.Filed[] memory){
        uint max = 2;
        Storage.Filed[] memory data = new Storage.Filed[](max);
        for(uint i = 0; i < max ;i++){
            data[i] = storageContract.store(i);
        }
        return data;
    }

    function query2() public view returns(Storage.Filed[] memory){
        Storage.Filed[] memory data = new Storage.Filed[](1);
        data[0] = storageContract.store(2);
        return data;
    }

    function query3() public view returns(Storage.Filed memory){
        Storage.Filed memory data = storageContract.store(2);
        return data;
    }


    function query4OK() public view returns(Storage.Filed memory){
        Storage.Filed memory data = storageContract.store(0);
        return data;
    }

    function query5OK() public view returns(Storage.Filed[] memory){
        uint max = 1;
        Storage.Filed[] memory data = new Storage.Filed[](max);
        for(uint i = 0; i < max ;i++){
            data[i] = storageContract.store(i);
        }
        return data;
    }
}
```
Now, all query is working well. @THaGKI9 @0xAWM

**Comment by r0qs** [comment] 2023-04-13 11:57
Hi @nishuzumi if I get correctly the main issue here, the problem is that the generated public getter returns the members of the struct as tuple instead of returning the struct itself. This is a know long-standing issue that is currently kept for compatibility reasons. Please see these comments here: https://github.com/ethereum/solidity/issues/6337#issuecomment-475170052 and https://github.com/ethereum/solidity/issues/14106#issuecomment-1503060644 for more information.

We don't have concrete plans to add support to it though. But we may consider it for the `0.9.0` release: https://github.com/ethereum/solidity/issues/6337#issuecomment-1140000320

In case you need to return the struct for your use case, you will need to define your own getter for `store` as in the example posted by @0xAWM: https://github.com/ethereum/solidity/issues/14114#issuecomment-1506226071.

So for now, I'm closing this issue. Please, feel free to reopen in case I misunderstood the problem and there is anything else to add.

Also, thanks @THaGKI9 and @0xAWM for the constructive discussions and examples :)

**Closed as completed by r0qs** 2023-04-13 11:57 UTC
Labels: bug :bug:
