### ISSUE TITLE
[LoadResolver] Invalid gas tier for instruction CREATE

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11801] opened 2021-08-16 09:02 UTC
```
{
  for {} addmod(keccak256(0x0,create(0x0, 0x0, 0x0)), 0x0, 0x0) {} {}
}
// ----
// step: loadResolver
//
```

throws

https://github.com/ethereum/solidity/blob/1a68228c28e4e7f7a62e32cb310bce6377565aac/libevmasm/GasMeter.cpp#L272

**Comment by bshastry** [comment] 2021-08-16 11:03
```
for {} addmod(keccak256(sload(0x0),0x0), 0x0, 0x0) {} {}
```

throws the same assertion for `sload`.

**Comment by chriseth** [comment] 2021-08-30 12:36
Essentially duplicate of https://github.com/ethereum/solidity/issues/11803

**Closed as completed by chriseth** 2021-08-30 12:36 UTC
Labels: bug :bug:, optimizer, should compile without error
