### ISSUE TITLE
Compiler thinks variable is unused when used from inline assembly

### ISSUE THREAD

**Issue by tymat** [ethereum/solidity#2251] opened 2017-05-09 04:51 UTC
```
    function is_contract(address _contract) 
                         public
                         constant
                         returns (bool _is_contract)
    {
      uint32 _code_length;

      assembly {
        _code_length := extcodesize(_contract)
      }

      if(_code_length > 1) {
        _is_contract = true;
      } else {
        _is_contract = false;
      }
      
      return _is_contract;
    }
```

When compiled produces a warning:

```
ACConditions.sol:84:26: : Unused local variable
    function is_contract(address _contract)
                         ^---------------^
```

**Comment by roadriverrail** [comment] 2017-05-11 13:55
I'm looking at this now.

**Comment by chriseth** [comment] 2017-05-17 09:41
Duplicate of #2249

**Closed as completed by chriseth** 2017-05-17 09:41 UTC
