### ISSUE TITLE
Does it incur any issues if I change state variable visibility in ERC20Pausable?

### ISSUE THREAD

**Issue by SaifAtom** [ethereum/solidity#13601] opened 2022-10-03 10:23 UTC
I have an issue with a function which need to access `_balances` mapping in parent contract - ERC20Pausable - but since it's declared private in that said parent contract i cannot access it.
my question is if i change it to public, does it have any serious repercussions ? or is it safe ?

**Comment by cameel** [comment] 2022-10-04 14:21
You'll need to ask OpenZeppelin. This is a bug tracker for the Solidity compiler. We do not develop the ERC20 contracts.

Since this is not a bug report or a feature request, I'm closing it. Please try [OpenZeppelin forum](https://forum.openzeppelin.com/).

**Closed as not planned by cameel** 2022-10-04 14:21 UTC
