### ISSUE TITLE
Assignments from `memory` to `memory` do not always creates references, only when editing value at specific index

### ISSUE THREAD

**Issue by CJ42** [ethereum/solidity#14109] opened 2023-04-11 18:40 UTC
## Description

The Solidity docs state that when a variable specified with `memory` as data location is assigned as a value another variable specified with `memory` as data location, that **this creates only references**.

From my understanding and what one might expect, these are basically "2 pointers to the same place in `memory`". So changing the value to one of the variable changes the value at the specific location in memory the variable points to. This should in turn propagate to the other `memory` variable, that points to the same memory location.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/31145285/231256315-74673314-94ca-4511-9ca2-9e90d936f28e.png">

https://docs.soliditylang.org/en/v0.8.19/types.html#data-location-and-assignment-behaviour

I have found one code snippet where this is the case and it creates a reference and editing the value at a specific index of a `bytes memory` piece of data propagate to the other reference.

However, when editing the whole piece of data (assigning a whole new `bytes` value like `hex"f00df00d"`), it does not actually creates a reference, but instead it allocate the second `bytes memory data` to a new location in memory and copy the value of `bytes memory greetings` to it.

Maybe I am missing something or not understanding the docs or the behaviour of Solidity + the intricacies of `memory` to `memory` references. It might be good to clarify it, or investigate in the case this is a bug in assignment behaviour.

## Steps to Reproduce

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.0;

import "hardhat/console.sol";

contract Playground {

    function test() public view returns (bytes memory, bytes memory) {
        bytes memory data;
        bytes memory greetings = hex"cafecafe";

        data = greetings;
        data[0] = 0x00;
        data[1] = 0x00;

        console.logBytes(data); // 0x0000cafe
        console.logBytes(greetings); // 0x0000cafe
        
        return (data, greetings);
    }

    function anotherTest() public view returns (bytes memory, bytes memory) {
        bytes memory data;
        bytes memory greetings = hex"cafecafe";

        data = greetings;
        data = hex"f00df00d";

        console.logBytes(data); // 0xf00df00d
        console.logBytes(greetings); // 0xcafecafe
        
        return (data, greetings);
    }

}
```

<img width="254" alt="image" src="https://user-images.githubusercontent.com/31145285/231258401-bb0ab401-7643-4906-ba0f-c83ba8db401c.png">

## Environment

- Compiler version: 0.8.19
- Framework/IDE (e.g. Truffle or Remix): Remix

**Comment by ekpyron** [comment] 2023-04-11 18:51
This is not a bug. When you're assigning a value to a ``memory`` variable, you change where it points to as reference.
I.e.
```
        // data points to the zero-sized array
        data = greetings;
        // data points to the memory at greetings
        data = hex"f00df00d";
        // data points to the newly allocated memory for hex"f00df00d"
```
If you have any suggestion for improving the docs on this, feel free to open a PR, but since this is not a bug, I'm closing this issue.

**Closed as completed by ekpyron** 2023-04-11 18:51 UTC
Labels: bug :bug:

**Comment by CJ42** [comment] 2023-04-11 19:01
So @ekpyron to make sure I understand:
- assigning a new value to `data` allocates new memory and completely changes the reference?

- but editing something **within** `data` keeps the reference?

Is this not misleading? I am aware there might be the `copyof` keyword introduced. Maybe there could be the distinction between these two statements in the future to allow to be more explicit with `memory` to `memory` references.

```solidity
bytes memory data;
bytes memory greetings = hex"cafecafe";

// this create a reference that points to the same place in memory
data = greetings;

// this allocate a new place in memory and copy the whole content of `greetings` into the newly allocated memory
data = copyof greetings;
```

Wouldn't that make it more explicit?

**Comment by ekpyron** [comment] 2023-04-12 09:28
Yep - the way this works right now is suboptimal and there's several ideas to improve the situation, one of which is an explicit keyword like ``copyof``, there is no ultimate fixed decision about this yet, though, since we generally plan some major reworkings of the type system and likely more explicit copy- and reference-semantics will happen as part of that larger effort.
