### ISSUE TITLE
`--standard-json` does not filter output fields

### ISSUE THREAD

**Issue by cag** [ethereum/solidity#2256] opened 2017-05-09 16:31 UTC
I provide the following as input with the `--standard-json`:

```
{
  "language": "Solidity",
  "sources":
  {
    "contracts/codec/ECCConversion.sol": {
      "content": "import {Curve} from ..."
    },
    ...
  },
  "settings":
  {
    "remappings": [ "github.com/androlo/standard-contracts/contracts/src/=contracts/" ],
    "optimizer": {
      "enabled": true,
      "runs": 500
    },
    "metadata": {
      "useLiteralContent": false
    },
    "outputSelection": {
      "*": {
        "*": [ "abi", "evm.bytecode.link_references", "evm.bytecode.object", "devdoc", "metadata", "userdoc" ]
      }
    }
  }
}
```

I expect the `outputSelection` section to cause the output to be restricted to those items specified, but instead, everything is outputted.

**Comment by axic** [comment] 2017-05-11 08:21
This feature is not implemented yet, but will come at a later point.

**Comment by chriseth** [comment] 2017-05-17 09:24
Closing as not a bug.

**Closed as completed by chriseth** 2017-05-17 09:24 UTC
