### ISSUE TITLE
Computing gas stipend for calls to precompiles could use an underflow guard (post-Byzantium)

### ISSUE THREAD

**Issue by veox** [ethereum/solidity#3687] opened 2018-03-08 11:21 UTC
Has been [brought up on /r/ethdev](https://www.reddit.com/r/ethdev/comments/82p78k/two_identical_arguments_for_function_call_one/); most relevant to `solc` is likely [this sub-thread](https://www.reddit.com/r/ethdev/comments/82p78k/two_identical_arguments_for_function_call_one/dvc8bbh/).

In short: when preparing for a `CALL` to a precompile (`ecrecover` in this case), the compiler generates code that allocates a gas stipend of `post_compile_const - GAS`, and then doesn't check if the result wrapped around 0 by chance (i.e. `post_compile_const < GAS`).

@chriseth [says](https://gitter.im/ethereum/solidity-dev?at=5aa056417685a046389c5f8b) that pre-Byzantium, this would fail.

/u/Figs999 links the [code block](https://github.com/ethereum/solidity/blob/14b12ae7452388516d0c4eb833b0c83fe5156b44/libsolidity/codegen/ExpressionCompiler.cpp#L1769) where the computation is done.

**Comment by chriseth** [comment] 2018-03-08 12:24
Duplicate of https://github.com/ethereum/solidity/issues/3680 :)

**Comment by veox** [comment] 2018-03-08 12:24
X_X

Closing as duplicate.

**Comment by chriseth** [comment] 2018-03-08 12:25
Actually this one has much more details :)

**Comment by chriseth** [comment] 2018-03-09 15:44
It turns out that this is already correct for byzantium VMs. So if you compile for pre-Tangerine Whistle and run it on pre-Tangerine Whistle, it works fine, if you compile for Tangerine Whistle and run it on Tangerine Whistle it is fine, the only problem is if you compile for pre-Tangerine Whistle and run it on Tangerine Whistle.

What we could do is implement a check if the gas computaiton wraps around, but the cost for that computation would have to be included in the number that is subtracted, so it gets even more messy.

I would just ignore this very specific problem. It is fixed in latest solidity because it defaults to a byzantium VM.

Are there any situations where this could be used to fool users?

@axic what do you think?

**Comment by veox** [comment] 2018-03-09 17:18
Somewhat OT:

@axic mentions in https://github.com/ethereum/solidity/pull/2673#issuecomment-319183436:

> I think the best solution would be forwarding the maximum gas possible to ecrecover/sha256/ripemd160 and disallowing overriding them.

Is this worth re-considering?..

**Comment by chriseth** [comment] 2018-03-12 14:00
@veox this is the case with a post-TangerineWhistle VM.

**Comment by axic** [comment] 2018-04-11 14:17
If we can trust that the compiler calculates that value properly, then no matter if it wrapped or not, it will run out of gas. Doesn't it?

**Comment by axic** [comment] 2018-04-11 14:20
> the only problem is if you compile for pre-Tangerine Whistle and run it on Tangerine Whistle.

If it wraps, then it will be a very large number, which tangerine whistle VMs just truncate to the max available gas, so it should be working?

**Comment by chriseth** [comment] 2018-04-11 14:34
Yes, I also think it is fine.

**Closed as completed by chriseth** 2018-04-11 14:34 UTC
Labels: bug :bug:

**Comment by axic** [comment] 2018-04-11 15:10
We could consider though adding test cases with limited gas supplied to verify these assumptions.
