### ISSUE TITLE
struct constants

### ISSUE THREAD

**Issue by wadealexc** [ethereum/solidity#4037] opened 2018-05-01 02:05 UTC
It would be very helpful to allow `constant` structs. Currently, the workaround is to define internal functions that return structs.

Example:
```Solidity
pragma solidity ^0.5.0

contract ConstStructs {

    struct SomeStruct {
        uint val1;
        bytes32 val2;
    }

    SomeStruct public constant CONST_STRUCT = SomeStruct({
       val1: 5,
       val2: bytes32(123)
    });
}
```

Forgot to post the workaround -

```Solidity
pragma solidity ^0.4.23;

contract ConstStructs {

    struct SomeStruct {
        uint val1;
        bytes32 val2;
    }
    
    function getSomeStruct() internal pure returns (SomeStruct memory) {
        return SomeStruct({
           val1: 5,
           val2: bytes32(123)
        });
    }

    uint public constant SOMESTRUCT_CONST_UINT = getSomeStruct().val1;
    bytes32 public constant SOMESTRUCT_CONST_BYTES32 = getSomeStruct().val2;
}
```

**Comment by chriseth** [comment] 2018-05-02 15:14
This also requires "immutability checks" to be implemented, because you obviously do not want `CONST_STRUCT.val1 = 7` to work.

**Comment by androlo** [comment] 2018-06-06 18:48
Awesome. Guess this would allow structs as arguments to external functions as well.

Seems like a big update, since it would require constant declaration (and behavior) to work for all possible reference types. Only arrays would be a great start imo. Maybe only constant size arrays at first, if that is simpler. Seems like that change would be easier to do, since immutability checks are already in place (for calldata arrays in external functions). Guess the only thing that would be needed is to make sure that constant arrays are only accessed by constant/literal numbers.

On a related note, a thing I would like to be able to do is to declare a constant array, but assign a non constant variable to it and load it into memory that way. It would be much cleaner then having to create a function, or to do it "on the spot". Not sure if any of this is a good idea for Solidity though, or worth the trouble.

```
contract C {
    uint[4] constant nums = [uint(1), 2, 3, 4];
    
    function something() public {
        uint[4] memory x = nums; // copies nums to memory
        uint varN = 2;

        x[2]; // allowed
        x[varN]; // allowed.
        x[2] = 5; // allowed, does not change 'nums'

        nums[2]; // allowed
        nums[varN]; // not allowed.
        nums[2] == 5; // not allowed
// ...
    }
}
```

Maybe constant types should be possible to declare inside of functions too, and behave the same way as regular constants.

```
contract C {
    uint[4] constant nums = [uint(1), 2, 3, 4];
    
    function something() public {
        uint[4] constant x = nums; // does not copy
        uint varN = 2;
        uint constant constN = 2; // would also be possible

        x[constN]; // allowed
        x[2]; // allowed
        x[varN]; // not allowed.
        x[2] = 5; // not allowed
        // ...
    }
}
```

Sorry for sperging, but I have had some thoughts around this.

**Comment by Pr0methean** [comment] 2019-09-25 05:58
The `pure` modifier isn't very useful without this feature: I've had to use `view` instead, just to avoid re-instantiating a zero BigNumber every time I use one.

**Comment by cameel** [comment] 2023-02-19 21:16
I think that having some form of constant structs is a very good idea, but I doubt we'll be able to implement them the way presented here.

The problem is that currently structs are passed around pretty much only by reference so such a constant would have to be stored in memory and nothing in memory is truly constant. In the worst case you can always modify it with inline assembly. This means that the compiler would not be able to really treat it as a compile-time constant.

If, on the other hand, we were to make struct constants work like the current value type constants (and avoid memory), their uses would be very limited. You'd only be able to pass them in to external functions or `abi.encode()`, where the function does not really need a reference to the original struct. Such constants could potentially become more usable in the future when we redo reference semantics in a way that would allow passing structs around by value, but that's uncertain and too vague to consider now.

There's good news though. There *is* a good way to add structs that are constant for most practical purposes - `immutable`. We already have plans to implement immutable reference types in the near future: #13323. This way the struct would be embedded in the bytecode and (after construction) truly immutable. Due to this I'm closing this particular proposal.

**Closed as not planned by cameel** 2023-02-19 21:16 UTC
Labels: language design :rage4:
