### ISSUE TITLE
Infinite gas estimation for `transfer()`

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#12156] opened 2021-10-16 11:46 UTC
I am getting this error every time I try to run this solidity code. Gas requirement of function SmartWallet1.withdrawMoney is infinite:  
```
pragma solidity ^0.5.17;

contract SmartWallet1{
    function withdrawMoney(address payable _to, uint _amount) public{
        _to.transfer(_amount);
    }
    function() external payable{
        
    }
}
```

**Comment by cameel** [comment] 2021-10-16 16:22
This does not appear to be an error message produced by the compiler. Please add more information to the issue. What tool are you using? What versions? What are the exact steps to reproduce the error? What do you expect to happen?

I tried running your example through the compiler, this is the estimation I get:
```bash
solc test.sol --gas
```
```
======= test.sol:SmartWallet1 =======
Gas estimation:
construction:
   99 + 48800 = 48899
external:
   fallback:    74
   withdrawMoney(address,uint256):      infinite
```
That's on 0.5.17. Version 0.8.9 (after replacing `function()` with `fallback()`) reports this:
```
======= test.sol:SmartWallet1 =======
Gas estimation:
construction:
   135 + 84800 = 84935
external:
   fallback:    85
   withdrawMoney(address,uint256):      infinite
```

The `infinite` estimation does seem unwarranted here (`transfer` only passes on a stipend of 2300 gas so the cost of the external case in this case is not unbounded). I think it's more of a missing feature than a bug. We can treat this report as a feature request to improve the estimation for `transfer()`.

If your report is about the error though - I think it's not the compiler that's returning it. I'm actually not sure why the tool does not let you run the function - the estimation is just a hint and you should still be able to run the function regardless of what the estimation says. Perhaps you should report it as a bug in the tool you're using.

**Comment by ghost** [comment] 2021-10-17 13:04
I am not sure if it's an error or a bug. I am running this code on remix-ethereum. The debug console shows this warning and does not allow transferring any funds, though the contract is deployed.

![image](https://user-images.githubusercontent.com/92217664/137628329-ea10cb99-bd3e-4038-ae67-59ec63aff9a7.png)

**Comment by ghost** [comment] 2021-10-17 14:41
![image](https://user-images.githubusercontent.com/92217664/137632348-1eed2002-a661-472e-b7e6-ea2699ee2390.png)

Here is the error message that is sent from the blockchain,  whenever I try to transact through the contract.

**Comment by cameel** [comment] 2021-10-19 16:21
I don't think the warning and error you're showing above are related. Gas estimation can't cause a revert. 

I suspect that the account you're trying to transfer from might simply not have enough funds to make the transfer and that's why it reverts. The warning you see on the console would probably be there even if the transaction succeeded (simply because the gas estimator returns an infinite estimation for transfer).

In any case this does not seem to be a bug in the compiler. If you need support in solving this, please try asking on the [#remix](https://gitter.im/ethereum/remix) channel. I'm closing this now but feel free to reopen if you determine that it actually is a compiler problem - make sure to include a reproducible example using just the compiler (rather than Remix) or at least precisely explain why you think the problem lies in the compiler.

And if you'd like to request the proper gas estimation to be implemented for `transfer()`, please [submit a feature request](https://github.com/ethereum/solidity/issues/new?template=feature_request.md).

**Closed as completed by cameel** 2021-10-19 16:21 UTC
