### ISSUE TITLE
InternalCompilerError in `ContractCompiler.cpp` when calling an interface function via `super`

### ISSUE THREAD

**Issue by adjisb** [ethereum/solidity#12143] opened 2021-10-14 17:27 UTC
The following contract produces an InternalCompilerError: Internal compiler error (/solidity/libsolidity/codegen/ContractCompiler.cpp:1391)

```solidity
//SPDX-License-Identifier: MIT
pragma solidity 0.8.2;

contract A1 {
    function f() public virtual {}
}

interface A2 {
    function f() external;
}

contract B is A1, A2 {
    function f() public override(A1, A2) {
        super.f();
    }
}
```

**Comment by cameel** [comment] 2021-10-14 17:36
Duplicate of #11445.

This has already been fixed in 0.8.5.

**Closed as completed by cameel** 2021-10-14 17:36 UTC
Labels: bug :bug:, should compile without error
