### ISSUE TITLE
Error message: Assembly can't access storage variables by name

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#488] opened 2016-04-07 21:06 UTC
This fails:

```
    uint b;
    function a() {
        assembly {
            b := 1
        }
    }
```

with `Error: Identifier "b" not found, not unique or not lvalue.`

This works:

```
    uint b;
    function a() {
        uint _b;
        assembly {
            _b := 1
        }
        b = _b;
    }
```

Well basically there's no way to access storage variables by name?

Also separately, using `sstore` returns an error message which could be improved:

```
    bytes b;
    function a() {
        assembly {
            sstore(b, 1)
        }
    }
```

It says: `Error: Expected instruction(s) to deposit 1 item(s) to the stack, but did deposit 2 item(s).`

(`sstore` expects a storage location)

**Comment by chriseth** [comment] 2016-04-08 10:07
It is actually all in the documentation: https://solidity.readthedocs.org/en/latest/control-structures.html#assignments
You cannot assign to storage variables, you have to use `sstore`, this is due to the low-level nature of inline assembly, `:=` _always_ translates into a swap/pop combination.

The docs also say that if you access state variables in an rvalue context, the will occupy two slots on the stack: https://solidity.readthedocs.org/en/latest/control-structures.html#access-to-external-variables

I don't see a way how to improve the error message and still retain the flexibility of the inline assembly system itself. If you want, you can add that to the FAQ, though.

**Comment by axic** [comment] 2016-04-09 20:17
In case 1) the error (if possible) should say something along the lines of `Indentifier "b" is a storage location. It cannot be used directly in inline assembly.`

In the case of `sstore(b, 1)` and `sload(b)` I think using `b` should refer to the storage location. Similarly how memory locations are handled in inline assembly.

**Comment by chriseth** [comment] 2016-05-09 08:55
I agree that the error message could be improved, but there are actually a number of other identifiers that are not available like this in inline assembly. I'll think about it.

For the second part of your comment above: The problem is that `b` takes 33 bytes (32 bytes for the storage location plus one byte for the offset inside the storage slot). It could be an option to remove the intra-slot offset if it is zero, but that will complicate the rules, I would say.

**Comment by axic** [comment] 2016-05-19 14:11
> The problem is that b takes 33 bytes (32 bytes for the storage location plus one byte for the offset inside the storage slot).

I'm not fully aware how storage is handled by Solidity, but I think you refer to the case when multiple variables are packed and stored in the same location? Wouldn't `uint` in the example above have its own single storage slot?

For packed variables, doesn't that basically equals to `add(location, offset)` in the eye of `sstore`?

So basically this:

```
    bytes b;
    function a() {
        assembly {
            sstore(b, 1)
        }
    }
```

would become:

```
PUSH <storage location>
PUSH <storage offset>
ADD
PUSH 1
SSTORE
```

**Comment by axic** [comment] 2016-05-19 16:13
To clarify:
- any storage variable which has an offset (i.e. is smaller than 256 bits) will have both the storage location + offset on the stack
- any variable which is at least 256 bits wide will have its location on the stack - therefore case 3 above could/should work

Having a proper error message printed in case 1 would be useful, but perhaps it requires too many changes regarding processing.

**Closed as completed** 2016-08-05 15:29 UTC
