### ISSUE TITLE
A Segmentation Fault Caused by (f()) = f()

### ISSUE THREAD

**Issue by haoyang9804** [ethereum/solidity#14720] opened 2023-12-05 08:44 UTC
This code reveals a segmentation fault:
```Solidity
contract C
{
	function f() internal pure returns (uint, uint) {
		return (2, 3);
	}
	function g() public pure {
		uint x;
		uint y;
		(f()) = f();
	}
}
```

Changing `(f()) = f();` into an ill-formed function caller `(f(1, 2)) = f();` still triggers this error.
Removing the assignment and only remaining the `(f())` will not trigger such error.

Seems that the semantic analyzer cannot decently analyze a function call inside a tuple on the left-hand side in an assignment

**Comment by nikola-matic** [comment] 2023-12-06 10:35
This is the same problem as in https://github.com/ethereum/solidity/issues/14719, right?

**Comment by haoyang9804** [comment] 2023-12-06 10:41
> This is the same problem as in #14719, right?

I think so.

**Comment by nikola-matic** [comment] 2023-12-06 10:48
@haoyang9804 yup, just checked, it's the same issue. I've re-posted this repro in the original issue, and will be closing this one as a duplicate of https://github.com/ethereum/solidity/issues/14719.

**Closed as completed by nikola-matic** 2023-12-06 10:48 UTC
Labels: bug :bug:
