### ISSUE TITLE
Seems like an incorrect type inference...

### ISSUE THREAD

**Issue by haoyang9804** [ethereum/solidity#15197] opened 2024-06-12 17:46 UTC
The following two statements are of the same functions:
```
int256 a = 22;
int256 a2 = true ? 22 : 23;
```
However, the second statement throws an error with message: `Error: Type uint8 is not implicitly convertible to expected type int256`. Seems that Solidity compiler misunderstood the type of 22 and cannot take it as a int256 literal as it did for the first statement.

This bug (or, this feature) is kind of confusing and causes a little inconvenience.

**Comment by PeterYang03110** [comment] 2024-06-13 23:24
int256 a = 22;
int256 a2 = true ? int256(22) : int256(23);

**Comment by haoyang9804** [comment] 2024-06-14 01:32
> int256 a = 22; int256 a2 = true ? int256(22) : int256(23);

Oh thx. I think it's a solution. But is it not a bug? I expect the type checker can infer the type of 22 and 23 in this scenario.

**Comment by mehtavishwa30** [comment] 2024-06-18 12:30
@haoyang9804 This behaviour is not a bug and is in fact the normal behaviour ([see docs for reference](https://docs.soliditylang.org/en/v0.8.26/types.html)).  The type system does infer types in cases that are currently limited. However, we are aware of all the cases, the likes of above, that aren't covered well by the current type system and are working on bringing a better experience through the new type system in Solidity.

For now, I will be closing this issue given the above reasoning.

**Closed as not planned by mehtavishwa30** 2024-06-18 12:30 UTC
Labels: bug :bug:
