### ISSUE TITLE
Avoid copying unused returndata on .call family of functions

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#13352] opened 2022-08-05 20:57 UTC
For some reason I thought this had been fixed in https://github.com/ethereum/solidity/pull/12684 but it doesn't seem to be the case...

When the return data of a call is not stored in a variable (or more generally, when it's not used), it shouldn't be copied to memory. See https://github.com/ethereum/solidity/issues/12647 for a discussion on why this is important.

The snippet below emits `returndatacopy` for the entirety of the returndata size.
```solidity
(book ok, ) = target.call();
```

**Comment by transmissions11** [comment] 2022-08-21 10:42
++ we just encountered this today in our 0xMonaco ctf.

**Comment by transmissions11** [comment] 2022-08-21 10:43
the compiler also shouldn't copy unused returndata for higher level calls too no? 

devs shouldn't have to use low level calls to avoid opening themselves up to major DoS footguns.

**Comment by transmissions11** [comment] 2022-08-21 10:47
> the compiler also shouldn't copy unused returndata for higher level calls too no?

ah i believe this already covered by https://github.com/ethereum/solidity/issues/12306?

**Comment by frangio** [comment] 2022-08-22 14:10
> the compiler also shouldn't copy unused returndata for higher level calls too no?

For high level calls I think this was fixed in https://github.com/ethereum/solidity/pull/12684?
**Edit:** Maybe I misunderstood your comment. That PR fixed "unused returndata" in the sense of returndata past the size of the expected return type. But if a return value is not used it may still be copied (and decoded?). This is not a DoS vector though.

I hadn't seen #12306 but it looks like this issue is a duplicate of it.

**Comment by transmissions11** [comment] 2022-08-23 06:31
> This is not a DoS vector though.

Not necessarily for every contract, sure. But in some cases where you don't want a function to use beyond a certain gas limit it can be.

**Comment by Marenz** [comment] 2022-08-29 14:19
Closing as duplicate of #12306

**Closed as completed by Marenz** 2022-08-29 14:19 UTC
Labels: optimizer
