### ISSUE TITLE
Error "Trying to create an instance of an abstract contract." for standard token.

### ISSUE THREAD

**Issue by ed-ilyin** [ethereum/solidity#606] opened 2016-05-27 20:47 UTC
Hi,

When I try to create a new instace of the [standard token](https://ethereum.org/token), compiler throws an error:
Error: Trying to create an instance of an abstract contract.         new token()

I suppose it is due to abstract receiveApproval function specified in [standard token](https://ethereum.org/token):
contract tokenRecipient { function receiveApproval(address _from, uint256 _value, address _token, bytes _extraData); }

if I'm right, then how to deploy standard token contract from within another contract?

**Comment by Neurone** [comment] 2016-05-30 12:30
Hi Ed, you can find the answer to your question at [StackExchange](http://ethereum.stackexchange.com/questions/4360/error-trying-to-create-an-instance-of-an-abstract-contract-for-standard-token/4377). This is not a bug of Solidity, so you can close this issue.

**Closed as completed** 2016-05-30 13:05 UTC

**Comment by tom-field** [comment] 2017-03-27 06:40
i also have this
