### ISSUE TITLE
Interfaces: require external visibility

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#3442] opened 2018-01-28 17:00 UTC
The [Ethereum ABI specification](https://solidity.readthedocs.io/en/develop/abi-spec.html) does not make a distinction between `external` and `public` functions. Therefore the `Interface` keyword likewise should not so distinguish.

Currently `private` and `internal` are disallowed in `interfaces`s.

For clarity, only `external` functions should be allowed in `interface`s.

**Comment by chriseth** [comment] 2018-01-29 12:37
@axic why did we not disallow public in interfaces?

**Comment by axic** [comment] 2018-01-29 12:46
I thought it only supports `external`. I think it only should support `external`.

Removing the visibility specifier would be a bad idea because we require it everywhere else (starting 0.5.0) and that would create an exception, which could be confusing.

**Comment by fulldecent** [comment] 2018-01-29 15:11
Understood, issue updated

**Comment by axic** [comment] 2018-01-29 22:35
Actually it seems this is a duplicate of #2330.

**Comment by fulldecent** [comment] 2018-01-30 00:58
This issue regards requiring `external` in `Interface` functions. 

Issue #2330 regards subclassing ("implement"?, "overriding"?) interfaces with a public function.

**Comment by axic** [comment] 2018-01-30 01:09
Right, it seems to be a mix, though there's this also: https://github.com/ethereum/solidity/issues/2330#issuecomment-333915829

**Comment by axic** [comment] 2018-01-31 04:21
Actually #3038 has implemented this a while back for 0.5.0 mode.

We can however make `public` a warning now (that change allowed `public` in non-0.5.0 mode).

**Closed as completed** 2018-02-01 12:54 UTC
