### ISSUE TITLE
Support for Converting Array Literals to Dynamically Sized Memory Arrays

### ISSUE THREAD

**Issue by kaihiroi** [ethereum/solidity#15580] opened 2024-11-21 06:57 UTC
## Abstract

Solidity currently doesn't allow converting array literals to dynamically sized memory arrays. This restriction makes initializing dynamic arrays with literals more complex and less intuitive. According to the [v0.8.28 documentation](https://docs.soliditylang.org/en/v0.8.28/types.html#array-literals), this restriction is planned for removal. I would like to know if there are plans to implement this change.

## Motivation

Developers need to write extra code to initialize dynamic arrays, which can lead to longer and harder-to-read code. 

**Current**:
```
uint[] memory _uintArray = new uint[](3);
_uintArray[0] = 1;
_uintArray[1] = 3;
_uintArray[2] = 4;

someFunctionWithMemoryArrayParam({
    uintArray: _uintArray    
});
```

**Proposed**:
```
someFunctionWithMemoryArrayParam({
    uintArray: [uint(1), 3, 4]
});
```

## Specification

Modify the Solidity compiler to allow the assignment of array literals directly to dynamically sized memory arrays, enabling more intuitive and concise array initialization.

## Backwards Compatibility

This change is backward compatible as it only introduces new syntax, ensuring that existing codebases remain unaffected and current methods for initializing dynamic arrays continue to function as before.

**Comment by mehtavishwa30** [comment] 2024-11-25 12:25
Hey @kaihiroi!

This report is a duplicate of https://github.com/ethereum/solidity/issues/11879. I believe [the last comment](https://github.com/ethereum/solidity/issues/11879#issuecomment-1952836738) under the linked issue summarizes the current situation accurately.

I will be closing this to avoid redundancy. Feel free to keep an eye on the original issue to track the further developments on it.

**Closed as completed by mehtavishwa30** 2024-11-25 12:25 UTC
Labels: feature
