### ISSUE TITLE
File-level functionname shadows functionname in Interface

### ISSUE THREAD

**Issue by gitpusha** [ethereum/solidity#10154] opened 2020-10-29 15:29 UTC
I am using `solidity version 0.7.4` . 

I am making use of the new free function feature. 

In the same file I want to declare some `Interfaces` and some `functions`. 

I noticed that the compiler warns me about `This declaration shadows an existing declaration.` for functions that have the same name, even if one of them is wrapped in an interface and the other one is file-level. 

![image](https://user-images.githubusercontent.com/36712489/97595247-ceb31900-1a03-11eb-97e8-752ff0cf1cd3.png)

Feature or bug ?

**Comment by chriseth** [comment] 2020-10-29 15:37
Duplicate of https://github.com/ethereum/solidity/issues/10155

**Closed as completed by chriseth** 2020-10-29 15:37 UTC
