### ISSUE TITLE
Feature request: Allow initialize array

### ISSUE THREAD

**Issue by drortirosh** [ethereum/solidity#14527] opened 2023-08-31 14:35 UTC
Currently, there is no easy way to initialize an array:
```js
uint256[] memory b = [1,2,3];
```
yields:
`Type uint8[3] memory is not implicitly convertible to expected type uint256[] memory`

The only alternative is:
```js
uint256[] memory a = new uint256[](3);
a[0] = 1;
a[1] = 2; 
a[2] = 3;
```

## Solution:

Actually, there are 2 separate issues here:
1. allow "automatic upsizing" of array types. That is, allow initializing `uint256[3]` with `[1,2,3]`, instead of requiring the developer to do `[uint(1),2,3]`
2. generate the code to initialize a dynamic array (that is, initialize `uint256[]` from `uint256[3]`), effectively by performing the one-by-one initialization described above

**Comment by drortirosh** [comment] 2023-11-30 12:15
I think this issue deserves some attention, and would make code (even if mostly for tests) much more readable and usable.

**Comment by ekpyron** [comment] 2023-12-18 14:55
True, but we're close this as a duplicate of https://github.com/ethereum/solidity/issues/11879, which has more details

**Closed as completed by ekpyron** 2023-12-18 14:55 UTC
Labels: feature
