### ISSUE TITLE
Test Cases failing with an invalid checksum error while running `scripts/tests.sh`

### ISSUE THREAD

**Issue by anujajakhade** [ethereum/solidity#6890] opened 2019-06-04 10:04 UTC
## Description

I have build Solidity v0.5.9 on Ubuntu 18.04 (Linux). While running the test cases I am facing the below error
```
 Error: This looks like an address but has an invalid checksum. Correct checksummed address: "0xd5F9d8D94886e70B06E474C3Fb14fD43e2f23970". If this is not used as an address, please prepend '00'
``` 
## Environment
- v0.5.9
- Linux  /Ubuntu 18.04
## Steps to Reproduce

```solidity
Facing test case failures while runnig
bash scripts/tests.sh
```

**Comment by leonardoalt** [comment] 2019-06-05 09:14
I can't reproduce the problem on ArchLinux.
@bshastry you use Ubuntu, right? Could you take a look?

**Comment by bshastry** [comment] 2019-06-05 09:34
@anujajakhade Thanks for the report, could you please paste more lines from the log file. Do you already know which test failed?

Another question: Are you using ubuntu 19.04 or 18.04?

**Comment by anujajakhade** [comment] 2019-06-06 07:02
@bshastry I am working on Ubuntu 18.04.
Below is my failure log
``` 
./scripts/tests.sh
- corion/
Unexpected compilation result:
Expected failure: 0 - Expected warning / error output: 1
Was failure: 1
"*/*.sol" is not found. Skipping.
multiOwner.sol:41:53: Warning: This declaration shadows an existing declaration.
    function ownersForChange() public view returns (uint256 owners) {
                                                    ^------------^
multiOwner.sol:7:5: The shadowed declaration is here:
    mapping(address => bool) public owners;
    ^------------------------------------^
provider.sol:372:25: Warning: This declaration shadows an existing declaration.
    function allowUsers(address provider, address[] calldata addr) isReady external {
                        ^--------------^
provider.sol:8:1: The shadowed declaration is here:
contract provider is module, safeMath, announcementTypes {
^ (Relevant source part starts here and spans across multiple lines).
provider.sol:390:28: Warning: This declaration shadows an existing declaration.
    function disallowUsers(address provider, address[] calldata addr) isReady external {
                           ^--------------^
provider.sol:8:1: The shadowed declaration is here:
contract provider is module, safeMath, announcementTypes {
^ (Relevant source part starts here and spans across multiple lines).
provider.sol:408:27: Warning: This declaration shadows an existing declaration.
    function joinProvider(address provider) isReady external {
                          ^--------------^
provider.sol:8:1: The shadowed declaration is here:
contract provider is module, safeMath, announcementTypes {
^ (Relevant source part starts here and spans across multiple lines).
provider.sol:448:9: Warning: This declaration shadows an existing declaration.
        address provider = clients[msg.sender].providerAddress;
        ^--------------^
provider.sol:8:1: The shadowed declaration is here:
contract provider is module, safeMath, announcementTypes {
^ (Relevant source part starts here and spans across multiple lines).
provider.sol:486:60: Warning: This declaration shadows an existing declaration.
    function getReward(address beneficiary, uint256 limit, address provider) isReady external returns (uint256 reward) {
                                                           ^--------------^
provider.sol:8:1: The shadowed declaration is here:
contract provider is module, safeMath, announcementTypes {
^ (Relevant source part starts here and spans across multiple lines).
ico.sol:344:27: Warning: This declaration shadows an existing declaration.
    function checkPremium(address owner) internal {
                          ^-----------^
ico.sol:30:5: The shadowed declaration is here:
    address payable public owner;
    ^--------------------------^
premium.sol:276:72: Error: This looks like an address but has an invalid checksum. Correct checksummed address: "0xA636a97578D26A3B76b060Bbc18226D954Cf3757". If this is not used as an address, please prepend '00'. For more information please see https://solidity.readthedocs.io/en/develop/types.html#address-literals
        require( from != address(0x00) && to != address(0x00) && to != 0xa636A97578d26A3b76B060Bbc18226d954cf3757 );
                                                                       ^----------------------------------------^
token.sol:328:72: Error: This looks like an address but has an invalid checksum. Correct checksummed address: "0xA636a97578D26A3B76b060Bbc18226D954Cf3757". If this is not used as an address, please prepend '00'. For more information please see https://solidity.readthedocs.io/en/develop/types.html#address-literals
        require( from != address(0x00) && to != address(0x00) && to != 0xa636A97578d26A3b76B060Bbc18226d954cf3757 );
                                                                       ^----------------------------------------^
While calling:
"/root/solidity/build/solc/solc" --optimize --ignore-missing --combined-json abi,asm,ast,bin,bin-runtime,compact-format,devdoc,hashes,interface,metadata,opcodes,srcmap,srcmap-runtime,userdoc announcementTypes.sol ico.sol module.sol moduleHandler.sol multiOwner.sol owned.sol premium.sol provider.sol publisher.sol safeMath.sol schelling.sol token.sol tokenDB.sol */*.sol
Inside directory:
/root/solidity/test/compilationTests/corion
Commandline tests FAILED
```

```
./scripts/soltest.sh --no-ipc -t Checksum
Running 6 test cases...
/root/solidity/test/libdevcore/Checksum.cpp(65): fatal error: in "Checksum/calculate": 0x52908400098527886E0F7030069857D2E4169EE7
/root/solidity/test/libdevcore/Checksum.cpp(70): error: in "Checksum/regular": check passesAddressChecksum("0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed", true) has failed
/root/solidity/test/libdevcore/Checksum.cpp(71): error: in "Checksum/regular": check passesAddressChecksum("0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359", true) has failed
/root/solidity/test/libdevcore/Checksum.cpp(72): error: in "Checksum/regular": check passesAddressChecksum("0xdbF03B407c01E7cD3CBea99509d93f8DDDC8C6FB", true) has failed
/root/solidity/test/libdevcore/Checksum.cpp(73): error: in "Checksum/regular": check passesAddressChecksum("0xD1220A0cf47c7B9Be7A2E6BA89F429762e7b9aDb", true) has failed
/root/solidity/test/libdevcore/Checksum.cpp(86): error: in "Checksum/regular_invalid_length": check passesAddressChecksum("0x9426cbfc57389778d313268E7F85F1CDc2fdad60", true) has failed
/root/solidity/test/libdevcore/Checksum.cpp(88): error: in "Checksum/regular_invalid_length": check passesAddressChecksum("0x08A61851FFa4637dE289D630Ae8c5dFb0ff9171F", true) has failed
/root/solidity/test/libdevcore/Checksum.cpp(90): error: in "Checksum/regular_invalid_length": check passesAddressChecksum("0x00c40cC30cb4675673c9ee382de805c19734986A", true) has failed
/root/solidity/test/libdevcore/Checksum.cpp(92): error: in "Checksum/regular_invalid_length": check passesAddressChecksum("0xC40CC30cb4675673C9ee382dE805c19734986a00", true) has failed
/root/solidity/test/libdevcore/Checksum.cpp(98): error: in "Checksum/homocaps_valid": check passesAddressChecksum("0x52908400098527886E0F7030069857D2E4169EE7", true) has failed
/root/solidity/test/libdevcore/Checksum.cpp(99): error: in "Checksum/homocaps_valid": check passesAddressChecksum("0x8617E340B3D01FA5F11F306F4090FD50E238070D", true) has failed
/root/solidity/test/libdevcore/Checksum.cpp(100): error: in "Checksum/homocaps_valid": check passesAddressChecksum("0xde709f2102306220921060314715629080e2fb77", true) has failed
/root/solidity/test/libdevcore/Checksum.cpp(101): error: in "Checksum/homocaps_valid": check passesAddressChecksum("0x27b1fdb04752bbc536007a920d24acb045561c26", true) has failed

```

**Comment by ekpyron** [comment] 2019-06-06 12:33
I'm closing this, since this was due to the system being big endian (see https://github.com/ethereum/solidity/issues/6907), right? Please reopen, if I'm wrong.

**Closed as completed by ekpyron** 2019-06-06 12:33 UTC
