### ISSUE TITLE
`UnimplementedFeatureError` with no line indication when copying an array of structs to storage

### ISSUE THREAD

**Issue by barakman** [ethereum/solidity#12783] opened 2022-03-12 07:52 UTC
## Description

I am getting an error with no indication of which line it refers to:
```
UnimplementedFeatureError: Copying of type struct MyStruct memory[] memory to storage not yet supported.
```

## Environment

- Compiler version: 0.8.12

## Steps to Reproduce

Well, I need to dig through my code in order to find it, but on the compiler side, the problem is probably in ArrayUtils.cpp:
```
solUnimplemented("Copying of type " + _sourceType.toString(false) + " to storage not yet supported.");
```

Thanks :)

**Comment by wechman** [comment] 2022-07-14 13:07
@barakman  Thank you for your ticket! Could you share the code we can use to reproduce the issue? Hope you have managed to find it. Otherwise, even if we made adjustments you suggest, we wouldn't be sure the problem is fixed.

**Comment by cameel** [comment] 2022-07-14 16:05
This looks like the same thing as #3446.

And it probably won't be implemented in the current syntax but #2435 will provide a different mechanism for the same thing.

I think we should replace the `UnimplementedFeatureError` with a proper error at the analysis stage. Letting it blow up in the codegen is not a great user experience. And even when we have `copyof` syntax will be different so will still need to block this case.

**Comment by barakman** [comment] 2022-07-14 18:15
> @barakman Thank you for your ticket! Could you share the code we can use to reproduce the issue? Hope you have managed to find it. Otherwise, even if we made adjustments you suggest, we wouldn't be sure the problem is fixed.

With no line indication on your side, all I can do is paste my entire project here, which you'll probably agree is senseless.
I suggest that you add a line indication on your side (as pointed out in my initial message), then similar issues in the future will also include a short snippet of the client code (solidity) causing the problem.

As you might understand, the main issue in this context is not the compilation error itself, but rather the message issued by the compiler, which lacks the information required for the developer to fix (or workaround) the error.

**Comment by cameel** [comment] 2022-07-14 18:20
Yeah, the error should be better.

But just to help you locate it in your particular case - you can try commenting out lines that assign something of type `MyStruct` stored in memory to a storage variable. If doing this makes the error go away, it's the same issue.

**Comment by timweri** [comment] 2022-07-20 20:44
I'm interested in fixing this. Will start digging to see what I can find.

**Comment by barakman** [comment] 2022-10-02 20:21
So what's the status on this? Still getting it on solc 0.8.17.

**Comment by cameel** [comment] 2022-10-04 10:24
Sorry, no one is working actively on this due to other tasks with higher priorites.

If anyone wants to pick it up and work on it, feel free. It should be relatively easy to plug with an extra check in the type checker.

**Comment by barakman** [comment] 2022-10-04 10:32
There are actually two different problems embedded in this issue:
1. `UnimplementedFeatureError` reported by the compiler with no line indication
2. No support by the compiler for copying an array of structs into storage

One the one hand, I guess that you could consider both as low-priority, since 1 only requires a bit of a "dig through" in order to find the error in the code, and 2 can be worked-around by copying struct by struct into storage.

On the other hand, both are rather annoying when you (I) encounter them...

Thanks

**Comment by cameel** [comment] 2022-10-04 11:51
I'm only speaking about the error message here. Copying is actually high priority and is one of the roadmap issues. It's just that it we don't think it's a good idea to allow doing it implicitly through an assignment. In #2435 we want to introduce special syntax for it to make it explicit.

**Comment by grapevinegizmos** [comment] 2023-02-22 14:46
Just to add my feedback that, for developers, getting an error message which gives no indication of the line of source that spawns the error can be quite tedious in a large code base.  You spend a lot of time hunting in the code trying to figure out where you did such a thing, 

This error was opened about a year ago and appears to be relatively low effort fix (with significant impact for those who run into it).  Hope that it gets some attention.

**Comment by ekpyron** [comment] 2023-03-06 13:37
The error should really just tell people to use ``--via-ir`` these days (which has the feature implemented for a long time).

**Comment by cameel** [comment] 2023-03-06 14:50
@ekpyron But it still should not be a failing assert. It should at the very least go through an error reporter.

**Comment by ekpyron** [comment] 2023-03-06 14:52
If the message for the assert is good enough, it is fine to keep it. We plan to drop legacy code generation anyways. The assertion message just has to be clear about what can and should be done to get around it.

**Comment by cameel** [comment] 2023-03-26 21:11
I don't think an assert is ever good enough when it comes to reporting errors. It's an internal mechanism to catch bugs and very unfriendly as a way of reporting errors to tools and users.

> The error should really just tell people to use `--via-ir` these days (which has the feature implemented for a long time).

By the way, I just realized that you must have confused this issue with #12449 (maybe I referred to it as such by mistake somewhere? I thought it was that too until I took a closer look now). This one is about the inability to copy structs, not "stack too deep". Here it's very easy for us to give the user the exact location of the error if we detect this during analysis and issue a proper error. For whatever reason we're not doing that and letting it blow up in the codegen.

**Comment by barakman** [comment] 2023-07-06 12:37
Closed as not planned? Why not just fix it?

This issue (a compilation error with no line indication) is clearly a compiler issue.

**Comment by dannydoritoeth** [comment] 2023-09-22 00:04
The error message is not helpful at all at guiding you for where to start looking for in your code for what is causing it. 

It would be good to just make the error bit clearer even its not going to be fixed.

**Comment by PaulRBerg** [comment] 2024-04-05 12:53
Why has this issue been closed as not planned, @cameel, @NunoFilipeSantos?

**Comment by peexledev** [comment] 2024-05-21 10:38
fix this

**Closed as completed** 2024-09-16 12:50 UTC
Labels: bug :bug:, medium difficulty, should report better error, low effort, medium impact, should have
