### ISSUE TITLE
[SMTChecker] Does not support `new bytes(..)`

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8745] opened 2020-04-22 17:50 UTC
```
Warning: Assertion checker does not yet implement this type of function call.
  --> Blake2bTest.sol:41:32:
   |
41 |         bytes memory scratch = new bytes(128);
   |                                ^^^^^^^^^^^^^^
```

**Comment by leonardoalt** [comment] 2020-04-22 18:11
Duplicate of https://github.com/ethereum/solidity/issues/6050?

**Closed as completed** 2020-04-22 18:15 UTC
