### ISSUE TITLE
Unable to run a for loop

### ISSUE THREAD

**Issue by DiegoCoyote** [ethereum/solidity#6557] opened 2019-04-18 16:56 UTC
Hello. I'm quite new in solidity and in GitHub, so I hope this issue can fit here.
I'm just making simple smart contracts to test what I'm learning, and I can't run a for loop.
The code I'm trying to run is:
```
pragma solidity ^0.5.0;
contract test {
  function forLoopTest(uint a) public pure returns (uint) {
    uint y = 1;
     for (uint i = 0; i < a; i++) {
      y = 2 * y;
  }
  return y;
  }
}
```
I have used on line Remix to test mi code, and I got this warning:
>Gas requirement of function test.forLoopTest(uint256) high: infinite. If the gas requirement of a function is higher than the block gas limit, it cannot be executed. Please avoid loops in your functions or actions that modify large areas of storage (this includes clearing or copying arrays in storage)

When I try to run this code locally in my Windows 10, using the Truffle suite (Truffle v5.0.12 (core: 5.0.12); Solidity v0.5.0 (solc-js); Node v10.15.1; Web3.js v1.0.0-beta.37; Ganache V 2.0.1) I get the next error when I pass any number as parameter "a", i.e. 10.
>Error: Returned error: VM Exception while processing transaction: revert
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\diego\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2-cookies\dist\xml-http-request.js:318:1)
    at XMLHttpRequest._setReadyState (C:\Users\diego\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2-cookies\dist\xml-http-request.js:208:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\diego\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2-cookies\dist\xml-http-request-event-target.js:34:1)
    at XMLHttpRequest.request.onreadystatechange (C:\Users\diego\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\~\web3-providers-http\src\index.js:96:1)
    at C:\Users\diego\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:112:1
    at C:\Users\diego\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3-eth-contract\~\web3-core-requestmanager\src\index.js:140:1
    at Object.ErrorResponse (C:\Users\diego\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3-eth-contract\~\web3-core-helpers\src\errors.js:29:1)

I don't know why I get a warning about infinite gas use in the Remix editor, and that error using Truffle, because the loop is quite small. What's more, I get the same warning in Remix and the same error in Truffle when I write this code where the loop is set to 10, without, IMO, any possibility of an infinite loop:
```
function forLoopTestTwo() public pure returns (uint) {
    uint a = 10;
    uint y = 1;
    for (uint i = 0; i < a; i++) {
      y = 2 * y;
  }
  return y;
  }
```
I have run some Truffle tutorials and other test contracts to try, for example, add, divide and so on, and those worked perfectly, so I guess my development environment is set up properly.

I'd be glad if anyone could help me to write a 'for loop' (or any other loop, because I've got the same problems with a 'while loop'), and to explain me what I'm doing wrong.
Thanks in advance.

**Comment by chriseth** [comment] 2019-04-18 20:39
At a first glance, your code seems fine. You can ignore the warning given by Remix, it is just a reminder that this could be dangerous. Imagine passing `2**255` for the argument of the function. It is not possible to complete the loop before the universe ends and you could certainly not pay for the execution. The warning is also present for the second loop just because the algorithm to determine that is not too clever.

Unfortunately, I cannot help you with the truffle error, though.

**Comment by DiegoCoyote** [comment] 2019-04-19 08:09
Thanks for clarify me about the warning (and for the possible error my code may produce), and for tell me that the code seems OK, I'll keep on trying to get my code working. I'll create a totally new project, just in case there were something wrong in the environment I were using.

**Comment by leonardoalt** [comment] 2019-04-19 09:11
@DiegoCoyote I ran your code on Remix (with the JavaScript VM) and it worked fine, so this does seem related to truffle and/or the truffle setup. It's probably easier to open an issue on the Truffle project and ask there.

Closing since the issue is likely related to Truffle. Please reopen otherwise.

**Closed as completed by leonardoalt** 2019-04-19 09:11 UTC
