### ISSUE TITLE
Solc Binary not working for Linux arm64 machines

### ISSUE THREAD

**Issue by NickSneo** [ethereum/solidity#13887] opened 2023-01-25 12:09 UTC
## Description
Facing error when using solc bin on linux arm64. Using Linux arm64 as VM on MacOS (M2 chip)
`Error - -bash: ./solc-static-linux: cannot execute binary file: Exec format error`
Seems it is architecture problem, bin not supported on linux arm64

Is there a workaround to fix this? or are we going to release bin for arm64 too?

## Environment

- Compiler version: 0.8.9
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): 
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu arm64 VM on MacOS (M2 chip)

## Steps to Reproduce
download solc bin and run.
`./solc --help`

**Comment by cameel** [comment] 2023-01-25 17:43
Yeah, this is an x86 binary, it won't work on ARM. We do not provide official ARM builds yet, we're planning to do so in the future. For now your only option is to build from source. If you're on macOS, try installing via Homebrew.

Closing as a duplicate of #11351 or #12291.

**Closed as not planned by cameel** 2023-01-25 17:43 UTC
