### ISSUE TITLE
zeroTest throws invalid opcode

### ISSUE THREAD

**Issue by vongohren** [ethereum/solidity#2258] opened 2017-05-09 22:06 UTC
I recieved some troubles when I wrote a zeroTest using truffle 0.4.11 and truffle test.
The zeroTest goes like this.
```
modifier zeroTest() { require(0>0); _; }
function zeroTestFunc() zeroTest {
     broadCastInt(69);
}
```
When i call this from my truffle tests I get:
`Error: VM Exception while processing transaction: invalid opcode`

But if i switch to if, instead of require, it works well, atleast without VM exception

The error is reported from truffle in my node_modules.
I started at the gitter for truffle and they sent me her.

**Comment by axic** [comment] 2017-05-10 07:22
@vongohren can you please post your code using `if`?

**Comment by vongohren** [comment] 2017-05-10 21:54
@axic its pretty the same, this atleast doesnt crash through a VM exception

```
modifier zeroTest() { if(0>0) _; }
function zeroTestFunc() zeroTest {
     broadCastInt(69);
}
```

**Comment by axic** [comment] 2017-05-11 08:24
Thanks. There is a difference though, I do not think in your second example the event is broadcasted as `0>0` is always false.

In your second example, simply the body of the function is not executed, while using `require` will actually abort execution with the `revert` opcode, which is not supported yet, hence it ends up as an invalid code. The result of invalid opcode is pretty much the same and this is intended. Once `revert` is supported, `require` will cost less as it will not consume all the remainder gas, but still abort.

**Comment by chriseth** [comment] 2017-05-17 09:23
Closing as not a bug, please reopen if you disagree.

**Closed as completed by chriseth** 2017-05-17 09:23 UTC
