### ISSUE TITLE
`solc --hashes` does not print selectors of `private` and `internal` functions

### ISSUE THREAD

**Issue by shawnwbts** [ethereum/solidity#11752] opened 2021-08-06 07:44 UTC
sorry to bother you, when I use the command **"solc --help"**, its introduction to **solc --hahses** is Function signature hashes of the contracts".It does not seem to be able to generate function signatures for the following contract.
contract CrowdsaleWPTByRounds{
 function _deliverTokens(address _beneficiary, uint256 _tokenAmount) internal {
    token.safeTransfer(_beneficiary, _tokenAmount);
  }
}
Can a function modified by the private or internal modifier become a function signature?

**Comment by cameel** [comment] 2021-08-06 14:16
Only external functions are a part of the ABI and thus have documented signatures.

`internal` and `private` functions can have parameter of types that can't be expressed in the ABI - for example this function is perfectly legal when marked as `internal` or `private`:
```solidity
function f(mapping(uint => uint) storage _map) internal {}
```
but it can't be `external` or `public` so it does not really have a selector (hash).

In some cases, when an internal function is only using parameter types that are valid for external functions, the compiler could compute the hash for you but then it could be misleading (you might think such a function is part of contract's ABI while it's not). Since the selector is useless to you unless the function is actually `external`/`public` why not make it such? If it's not you won't be able to use it to call the function anyway.

Closing, since this is not a bug report or a feature request. If you have general questions about the compiler or need help with your contracts please feel free to ask at the [#solidity](https://gitter.im/ethereum/solidity) Gitter channel.

**Closed as completed by cameel** 2021-08-06 14:16 UTC
