### ISSUE TITLE
Allow public functions overwrite external function (with memory / calldata types)

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5350] opened 2018-11-06 07:46 UTC
@axic is there a duplicate for this?

**Comment by leonardoalt** [comment] 2018-11-16 13:54
Duplicate of https://github.com/ethereum/solidity/issues/4832?

**Comment by axic** [comment] 2018-11-16 15:09
I think so, lets close for now.

**Comment by ekpyron** [comment] 2018-11-16 15:19
@axic: @leonardoalt already closed #4832 in favor of this one - we should keep at least one of them open ;-).

**Comment by ekpyron** [comment] 2018-11-16 15:20
Or wait - now #4832 is open again? Confusing :-D. Ok, then I close this again :-).

**Comment by ekpyron** [comment] 2018-11-16 15:20
Ah Ok - the one leo closed was #4870 - which is also the same issue :-).

**Closed as completed by ekpyron** 2018-11-16 15:20 UTC

**Comment by leonardoalt** [comment] 2018-11-16 15:22
I closed an old PR that I had with a hack, but kept the old issue with the bug label.
