### ISSUE TITLE
Function types are not displayed correctly in ternary resolution error

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#13098] opened 2022-06-06 19:49 UTC
```solidity
contract C {
   function f(bool a) {
     a ? a : f(true);
   }
}
```

```
Error: True expression's type bool does not match false expression's type tuple().
 --> test.sol:3:6:
  |
3 |      a ? a : f(true);
  |      ^^^^^^^^^^^^^^^
```

The `type tuple()` should state it is a function.

Interestingly if the return type mismatches it claims that it can't be resolved (also happens on `a ? a : g()` if it is a separate function):
```solidity
contract C {
   function f(bool a) external returns (uint256) {
     a ? a : (f(true));
   }
}
```

```
Error: Undeclared identifier. "f" is not (or not yet) visible at this point.
 --> test.sol:3:15:
  |
3 |      a ? a : (f(true));
  |               ^
```

**Comment by ekpyron** [comment] 2022-06-07 13:03
What exactly is the error message in the first example supposed to say? The type in question is *not* a function type, but the type of the return value of the function (which is an empty tuple)...
I've seen some confusion about this elsewhere recently, though, maybe we should emit a dedicated error message for "function call to a function without return value is used in a complex expression" or something like that...

In the second example, the error message is correct: ``f`` is external and thus not visible as plain ``f(...)``... making it public or using ``this.f`` does have a nice error message complaining that ``bool`` and ``uint256`` do not match...

**Comment by cameel** [comment] 2022-06-07 13:03
> The `type tuple()` should state it is a function.

I think the message is correct. The function does not return anything so technically it returns an empty tuple. You'd get the message you expect if you gave it a value of a function type:

```solidity
a ? a : f;
```
```
Error: True expression's type bool does not match false expression's type function (bool).
 --> test.sol:3:6:
  |
3 |      a ? a : f;
  |      ^^^^^^^^^
```

I originally wanted to suggest that maybe we could make this error more comprehensible by just stating that you cannot put a function that does not return anything there. But turns out that you can. This is valid: `a ? f(false) : f(true)`.

> Interestingly if the return type mismatches it claims that it can't be resolved (also happens on `a ? a : g()` if it is a separate function):

That's because it's an external function. If you do a simple `f(true);`, the compiler will no find it either.

**Comment by ekpyron** [comment] 2022-06-07 13:05
The part with the empty tuple type as the return type of a call to a function that returns nothing being confusing was already reported here: https://github.com/ethereum/solidity/issues/13017

**Comment by ekpyron** [comment] 2022-06-07 13:09
Closing this as a duplicate of #13017 then - feel free to reopen, if you disagree :-).

**Closed as completed by ekpyron** 2022-06-07 13:09 UTC
Labels: bug :bug:
