### ISSUE TITLE
Segmentation fault when trying to use `--ast` on an interface

### ISSUE THREAD

**Issue by rmeissner** [ethereum/solidity#5501] opened 2018-11-25 21:35 UTC
## Description

I am trying to use `solc --ast contracts/interface/ISignatureValidator.sol` (https://www.github.com/gnosis/safe-contract) and receive a segmentation fault. This also causes failure for contracts that make use of this file (e.g. `contracts/GnosisSafe.sol`)

Other outputs work(e.g. `solc --bin` or `solc --asm`). Also for other contracts it is possible to perform generate the `--ast` output (tested with `solc --ast /=/ contracts/base/BaseSafe.sol`).

## Environment

- Compiler version: 0.5.0+commit.1d4f565a.Darwin.appleclang (installed via brew)
- Target EVM version (as per compiler settings): default (byzantium)
- Operating system: MacOS Mojave (10.14.1)

## Steps to Reproduce

1) checkout https://github.com/gnosis/safe-contracts
1) run `solc --ast contracts/interface/ISignatureValidator.sol`

## Source of ISignatureValidator.sol
- `contract` was changed to `interface` for correctness, but yields the same result
```
pragma solidity ^0.5.0;

interface ISignatureValidator {
    /**
    * @dev Should return whether the signature provided is valid for the provided data
    * @param _data Arbitrary length data signed on the behalf of address(this)
    * @param _signature Signature byte array associated with _data
    *
    * MUST return a bool upon valid or invalid signature with corresponding _data
    * MUST take (bytes, bytes) as arguments
    */ 
    function isValidSignature(
        bytes calldata _data, 
        bytes calldata _signature)
        external
        returns (bool isValid); 
}
```

## Notes
- A work around is to add an empty body to `isValidSignatures` (and convert the `interface` to a `contract`)
- Might be related to #3718

**Comment by erak** [comment] 2018-11-27 10:12
@rmeissner Thanks for reporting your issue. This indeed seems to be related to #3718 and should have been fixed by https://github.com/ethereum/solidity/pull/4166. I think we need to take a look again.

**Comment by axic** [comment] 2018-11-27 10:21
It is still happening on the Mac, tried it.

**Comment by rmeissner** [comment] 2018-11-27 16:45
This was working with the 0.4.x compilers, this just started with the new 0.5.0 compiler for me

**Comment by erak** [comment] 2018-11-27 18:42
@rmeissner This was already present in the 0.4.x series, but couldn't be reproduced deterministically until isolated and fixed by @alibabe with https://github.com/ethereum/solidity/pull/4166. As we are currently discussing the removal of the gas estimation from the text output, I'd kindly invite you to take part in that discussion: https://github.com/ethereum/solidity/pull/5515 :)

**Comment by erak** [comment] 2018-11-27 18:50
Oh sorry, this is missing some background: it was probably reintroduced with https://github.com/ethereum/solidity/pull/5225. Unfortunately, this seems to be a bug in libc++: https://bugs.llvm.org/show_bug.cgi?id=30449, and #4166 was more or less only a workaround for.

**Comment by erak** [comment] 2018-11-28 13:47
It turned out that the crash was caused by a defect and does not seem related to #3718. I'll close https://github.com/ethereum/solidity/pull/5515 in favor of https://github.com/ethereum/solidity/pull/5530.

**Closed as completed** 2018-11-28 15:33 UTC
Labels: bug :bug:
