### ISSUE TITLE
"Stack too deep" error when pass tuple elements into another function. Depends on element position in the tuple.

### ISSUE THREAD

**Issue by ByKraB** [ethereum/solidity#4255] opened 2018-06-10 23:42 UTC
> Which version of Solidity you are using

0.4.24

> What was the source code (if applicable)

```
pragma solidity ^0.4.24;

contract StackTooDeepTest {

    function returnTupple() public returns (uint, uint, uint, uint, uint) {
        return (1,2,3,4,5);
    }
    
    function test() {
        var (tupple1, tupple2, tupple3, tupple4, tupple5) = returnTupple();
        
        uint localVariable = 123;
        
        // compiles without error
        doSomething(
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            tupple5
        );
        
        
        // Stack too deep, try removing local variables.
        doSomething(
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            localVariable,
            tupple4  // the same for tupple1/2/3
        );
    }
    
 
    
    function doSomething(
        uint arg1,
        uint arg2,
        uint arg3,
        uint arg4,
        uint arg5,
        uint arg6,
        uint arg7,
        uint arg8,
        uint arg9,
        uint arg10,
        uint arg11,
        uint arg12,
        uint arg13,
        uint arg14
    ) {
        
    } 
    
}
```

> Which platform are you running on

mac os 10.13.4

> How to reproduce the issue

Call in terminal `truffle compile`

> What was the result of the issue

```
CompilerError: Stack too deep, try removing local variables.
```
> What the expected behaviour is

Successful compilation

**Comment by chriseth** [comment] 2018-06-26 17:55
Duplicate of https://github.com/ethereum/solidity/issues/3457

**Closed as completed by chriseth** 2018-06-26 17:55 UTC
