### ISSUE TITLE
Infinite loop in view functions

### ISSUE THREAD

**Issue by ZigBalthazar** [ethereum/solidity#14381] opened 2023-07-04 15:34 UTC
## Description

In Solidity View functions, by creating a loop, the code can be forced to repeat that loop many times, and this process creates free processing pressure for EVM.

## Environment

- Framework/IDE (e.g. Truffle or Remix): Remix / HardHat
- EVM execution environment / backend / blockchain client: blockchain 

## Steps to Reproduce

```solidity
pragma solidity ^0.8.0;

contract MyContract {
    uint[] myArray;

    function getMyArray() public view returns (uint[] memory) {
        uint[] memory result = new uint[](myArray.length);
        for (uint i = 0; i < myArray.length; i++) {
            result[i] = myArray[i];
        }
        return result;
    }
}
```

**Comment by cameel** [comment] 2023-07-05 16:13
I can't reproduce it. I just tried your code on 0.8.20 in Remix and it properly exits and returns an empty array.

Can you provide more details? Which version are you using? Are you using the legacy pipeline or via IR? What exactly are you seeing and what are you expecting?

**Comment by Sachin737** [comment] 2023-07-09 16:31
It's working fine. can you please elaborate on the issue?

**Comment by ZigBalthazar** [comment] 2023-07-24 10:08
Hi @Sachin737 , @cameel 

Write another function to push many items to the array in the above code(try to push a few hundred items to the array, for example)

Then, using the `getMyArray ` function, you can read all the items by creating a loop

Now, instead of a few hundred items, for example, several thousand items are in the array. In that case, does reading this information using `for` in a function with the `View` property not have high computational pressure?

**Comment by Derixtar54** [comment] 2023-09-27 09:22
Hi @ZigBalthazar 
I  think i have understood your  problem correctly , correct me if I am wrong
If you want to push a large number of items to the array and then read all of them using the getMyArray function, you may indeed encounter high computational pressure if the array becomes very large. Solidity view functions are executed locally on each node, and their execution time depends on the complexity of the code. Reading a large array in a view function using a loop can lead to higher gas consumption and longer execution times, which can be problematic if the array contains thousands of items.

Here's an example of how you can push items to the array and then read them using the getMyArray function:
pragma solidity ^0.8.0;

contract MyContract {
    uint[] myArray;

    function pushToMyArray(uint[] memory values) public {
        for (uint i = 0; i < values.length; i++) {
            myArray.push(values[i]);
        }
    }

    function getMyArray() public view returns (uint[] memory) {
        uint[] memory result = new uint[](myArray.length);
        for (uint i = 0; i < myArray.length; i++) {
            result[i] = myArray[i];
        }
        return result;
    }
}
In this example, the pushToMyArray function allows you to push an array of values into myArray. The getMyArray function reads the entire array using a loop.

As the size of myArray grows, the gas cost and execution time of the getMyArray function will increase. If myArray contains several thousand items, reading it in a view function could become computationally expensive and may exceed gas limits.

To handle large datasets more efficiently, you might consider using pagination or off-chain processing techniques. Additionally, keep in mind that Ethereum 2.0 and other scaling solutions aim to improve the scalability of the Ethereum network, which can help mitigate some of these issues in the future.
please reply asap

**Comment by nikola-matic** [comment] 2023-12-06 11:12
Closing this, as it's not really a compiler bug per-se, rather an EVM limitation.

**Closed as completed by nikola-matic** 2023-12-06 11:12 UTC
Labels: bug :bug:

**Comment by cameel** [comment] 2023-12-06 11:30
Exactly. If you loop over unbounded arrays you may easily run out of gas. That's common knowledge. The limitation is just that the EVM environment is very resource constrained and this will happen even for moderately sized ones. That's why there are patterns like "pull over push" that you use instead.

The compiler also tries to avoid forcing a loop in such cases to some extent - note for example that if you create a getter for an array, it will return items one by one, and not the whole array. But this is not without downsides and compiler can't force that in every place where arrays are used. Dealing with it requires assumptions about what is being built. Ultimately it's up to the programmer in most cases to design their contract in such a way that it avoids running into this kind of problem.
