### ISSUE TITLE
SMTCheck throw exception

### ISSUE THREAD

**Issue by sunriseup** [ethereum/solidity#5903] opened 2019-01-30 08:57 UTC
## Description

I ran solc with Z3 and CVC4 installed on some contracts including the rubixi contract(in myth_solidity_examples ), 

    solc rubixi.sol 
returns:

    Internal compiler error during compilation:
    solidity/libsolidity/formal/SMTChecker.cpp(1240): Throw in function void dev::solidity::SMTChecker::mergeVariables(const std::vector<const dev::solidity::VariableDeclaration*>&, const dev::solidity::smt::Expression&, const VariableIndices&, const VariableIndices&)
    Dynamic exception type: boost::exception_detail::clone_impl<langutil::InternalCompilerError>
    std::exception::what:
    [dev::tag_comment*] =

## Environment

- Compiler version:Version: 0.5.4-develop.2019.1.26+commit.628d6654.mod.Linux.g++ 
- Target EVM version (as per compiler settings):default 
- Framework/IDE (e.g. Truffle or Remix): command line solc 
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu 18.04.1 LTS 

## Steps to Reproduce

1. Download contracts from 
https://github.com/ConsenSys/mythril-classic/tree/develop/solidity_examples 
2. change the first line to "pragma solidity ^0.5.0;", append 
"pragma experimental SMTChecker; " before the first line.
3. run solc rubixi.sol or solc BECToken.sol or solc weak_random.sol

**Comment by leonardoalt** [comment] 2019-02-14 12:26
- [x] weak_random.sol - Caused by struct assignment, fixed in #6008
- [ ] rubixi.sol - Caused by no support to compound operators #6006

**Closed as completed** 2019-04-15 11:39 UTC
Labels: bug :bug:
