### ISSUE TITLE
Error handling of abi.decode

### ISSUE THREAD

**Issue by hellwolf** [ethereum/solidity#10933] opened 2021-02-09 21:07 UTC
## Abstract

Proposing the `abi.validate` function to provide a way for error handling before `abi.decode`.

## Motivation

When dealing with decoding input `bytes`, `abi.decode` is often used. It is often necessary to do sanity checks on user provided inputs, for example userData in ERC-777 or user data in [Superfluid protocol](https://github.com/superfluid-finance/protocol-monorepo/). However in current solidity, it is neither possible to check validity of the format before sending to `abi.decode`, nor possible to try/catch on `abi.decode` itself, hence making the sanity check of input data almost impossible (unless writing your own format check).

## Specification

In order to solve this problem, I propose a simple function `abi.validate(bytes, (abi types)` that will return a boolean on the validity of the format.

## Backwards Compatibility

This should be a new function, no backward compatibility issue.

**Comment by chriseth** [comment] 2021-02-09 23:45
Potential duplicate of #10381

**Comment by hellwolf** [comment] 2021-02-10 10:45
thanks @chriseth, it looks like so.  I am okay with any solutions you guys come up with, but do you think it would also be backported to 0.7.x or it is only for 0.8.x?

**Comment by chriseth** [comment] 2021-02-10 11:17
This is a very heavy change code change that I started already [here](https://github.com/ethereum/solidity/pull/10883/commits/7aa7e708f9e889cc0b0529654b0d2ae4bdaa153c#diff-c10bb1823788cdc6974420487177f1a6badb1a26da48fb36f0ad49d37422000d) and unfortunately would be a big amount of work to backport.

**Comment by cameel** [comment] 2022-09-26 20:54
No point keeping two issues for this so I'm closing this in favor of #10381.

**Closed as not planned by cameel** 2022-09-26 20:54 UTC
Labels: language design :rage4:
