### ISSUE TITLE
Compilation produces different bytecode depending on how it is called.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/solidity#168] opened 2015-10-22 23:50 UTC
If you take this directory of libraries https://github.com/pipermerriam/ethereum-alarm-clock/tree/d66ee63943e4145f9baf29e5d479963fc4b08c84/libraries

and compile the `GroveLib` library using the following two ways.
- `solc --optimize --bin --bin-runtime libraries/*`
- `solc --bin --bin-runtime --optimize libraries/GroveLib.sol`

you will get different bytecode outputs.

This is done using the following version of solc.

``` bash
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.1.5-e11e10f8/Release-Darwin/clang/JIT linked to libethereum-1.1.0-8e11a861/Release-Darwin/clang/JIT
```

**Comment by pipermerriam** [comment] 2015-10-23 00:23
The `--optimize` flag doesn't seem to matter.  It's different output with or without it.

Also, it isn't just the runtime that is different.  the binary is also different.

**Comment by chriseth** [comment] 2015-11-06 13:07
Sorry, I cannot reproduce this on Linux. Could you put the actual results you get on some github gist?
If the assembly is different, this would be really helpful.

**Comment by chriseth** [comment] 2015-12-08 11:45
Closing as not reproducible. Please reopen if the problem can be reproduced.

**Closed as completed by chriseth** 2015-12-08 11:45 UTC
