### ISSUE TITLE
IR-based compilation increase contract size when an internal function is called many times

### ISSUE THREAD

**Issue by fruiz08** [ethereum/solidity#13858] opened 2023-01-10 17:12 UTC
## Description

When calling an internal function many times using `viaIR=true`, the contract size increase drastically compared to using `viaIR=false`

With viaIR=true
```
 ·····················|··············|·················
 |  Test              ·      14.445  ·  
 ·····················|··············|·················
```
 With viaIR=false
```
  ·····················|··············|·················
 |  Test              ·       3.788  ·                │
 ·····················|··············|·················
```

## Environment

- Compiler version: 0.8.17
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): hardhat
- Operating system: macOS

## Steps to Reproduce
Here is an example and a repository to reproduce it
[Repo](https://github.com/fruiz08/viaIR-size-issue)

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.17;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract Test {

    ERC20 internal token1;

    function _function1(address address_) internal {
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
        token1.transfer(address_, 1000 ether);
    }   

    function function1() public {
        _function1(msg.sender);
    }

    function function1v2(address address_) public {
        _function1(address_);
    }

    function function1v10() public {
        _function1(address(10));
    }
    function function1v11() public {
        _function1(address(11));
    }
    function function1v12() public {
        _function1(address(12));
    }
    function function1v13() public {
        _function1(address(13));
    }
    function function1v14() public {
        _function1(address(14));
    }
    function function1v15() public {
        _function1(address(15));
    }
    function function1v16() public {
        _function1(address(16));
    }
    function function1v17() public {
        _function1(address(17));
    }
    function function1v18() public {
        _function1(address(18));
    }
    function function1v19() public {
        _function1(address(19));
    }
}
```
-->

**Comment by jmendiola222** [comment] 2023-01-11 13:39
Interesting, does the content of the internal function changes the outcome? I'm mean, for example if instead of making "external" calls to `token1` you just do some math. Does it change if instead of `internal` the function is public or private? :thinking:

**Comment by fruiz08** [comment] 2023-01-11 14:13
> Interesting, does the content of the internal function changes the outcome? I'm mean, for example if instead of making "external" calls to `token1` you just do some math. Does it change if instead of `internal` the function is public or private? 🤔

1. If you do anything else, like maths, instead of external calls the same thing happens
2. If you make _function1() public the size change very little

**Comment by ekpyron** [comment] 2023-02-07 11:59
This is probably ultimately a duplicate of https://github.com/ethereum/solidity/issues/13787 - can anyone confirm that?

**Comment by ekpyron** [comment] 2023-02-13 22:04
For the record:
Optimizing with a custom optimizer sequence of
``--yul-optimizations "dhfoDgvulfnTUtnIf[xa[r]EscLMcCTUtTOntnfDIulLculVcul[j]Tpeulxa[rul]xa[r]cLgvifCTUca[r]LSsTOtfDnca[r]Iulc]jmul[jul]VcTOculjmul"``
(that's the default optimizer sequence without the ``F`` for the function specializer)
doesn't suffer from the described problem, resulting in significantly lower compilation time and significantly smaller bytecode - confirming that this indeed is a duplicate of #13787.

**Closed as completed by ekpyron** 2023-02-13 22:04 UTC
Labels: optimizer
