### ISSUE TITLE
Provide Support for Inline Functions

### ISSUE THREAD

**Issue by toongeorges** [ethereum/solidity#13241] opened 2022-07-03 23:01 UTC
## Abstract

Functions calls in Solidity provide execution overhead versus running code inline.

There may be a trade off between writing efficient, complex inline code versus less efficient more readable code in functions.  If inline functions existed, this trade off would not need to exist and people could write efficient readable code.  Currently, internal functions are not always automatically converted to inline functions by the optimizer even if converting them to inline functions is always the best solution (e.g. in case the function is only used once and using the function inline does not cause a Stack too deep Error).

An example explanation of inline functions in C/C++ can be found [here](https://www.simplilearn.com/tutorials/cpp-tutorial/inline-function-in-cpp)

## Motivation
The code snippet is taken from [here](https://github.com/toongeorges/cryptoshares/blob/0cda8448beaed4d1e49cc73f2ec42208f160abff/solidity/contracts/base/CorporateAction.sol)

### Inline Code Example
The inline code looks like:
```solidity
if (decisionType < ActionType.RAISE_FUNDS) {
    if (decisionType < ActionType.WITHDRAW_FUNDS) {
        if (decisionType == ActionType.ISSUE_SHARES) {
            _mint(address(this), numberOfShares);
        } else { //decisionType == ActionType.DESTROY_SHARES
            _burn(address(this), numberOfShares);
        }
    } else {
        if (decisionType == ActionType.WITHDRAW_FUNDS) {
            safeTransfer(IERC20(currency), exchangeAddress, amount);
        } else { //decisionType == ActionType.CANCEL_ORDER
            IExchange(exchangeAddress).cancel(amount);
        }
    }
} else if (decisionType < ActionType.REVERSE_SPLIT) {
    if (decisionType < ActionType.ASK) {
        if (decisionType == ActionType.RAISE_FUNDS) {
            IExchange exchange = IExchange(exchangeAddress);
            increaseAllowance(exchangeAddress, numberOfShares);
            PackableAddresses.register(exchanges[address(this)], exchangeAddress);
            exchange.ask(address(this), numberOfShares, currency, numberOfShares*amount, optionalAmount);
        } else  { //decisionType == ActionType.BUY_BACK
            IExchange exchange = IExchange(exchangeAddress);
            IERC20(currency).safeIncreaseAllowance(exchangeAddress, numberOfShares*amount);
            PackableAddresses.register(exchanges[currency], exchangeAddress);
            exchange.bid(currency, numberOfShares*amount, address(this), numberOfShares, optionalAmount);
        }
    } else {
        if (decisionType == ActionType.ASK) {
            IExchange exchange = IExchange(exchangeAddress);
            IERC20(currency).safeIncreaseAllowance(exchangeAddress, amount);
            PackableAddresses.register(exchanges[currency], exchangeAddress);
            exchange.ask(currency, amount, optionalCurrency, optionalAmount, numberOfShares);
        } else  { //decisionType == ActionType.BID
            IExchange exchange = IExchange(exchangeAddress);
            IERC20(optionalCurrency).safeIncreaseAllowance(exchangeAddress, optionalAmount);
            PackableAddresses.register(exchanges[optionalCurrency], exchangeAddress);
            exchange.bid(currency, amount, optionalCurrency, optionalAmount, numberOfShares);
        }
    }
} else {
    //...
}
```

### Function Code Example
This code could be made more readable, but less efficient in the following way:

```solidity
if (decisionType < ActionType.RAISE_FUNDS) {
    if (decisionType < ActionType.WITHDRAW_FUNDS) {
        if (decisionType == ActionType.ISSUE_SHARES) {
            issueShares(numberOfShares);
        } else { //decisionType == ActionType.DESTROY_SHARES
            destroyShares(numberOfShares);
        }
    } else {
        if (decisionType == ActionType.WITHDRAW_FUNDS) {
            withdrawFunds(currency, amount, exchangeAddress);
        } else { //decisionType == ActionType.CANCEL_ORDER
            cancelOrder(exchangeAddress, amount);
        }
    }
} else if (decisionType < ActionType.REVERSE_SPLIT) {
    if (decisionType < ActionType.ASK) {
        if (decisionType == ActionType.RAISE_FUNDS) {
            raiseFunds(exchangeAddress, numberOfShares, currency, amount, optionalAmount);
        } else  { //decisionType == ActionType.BUY_BACK
            buyBack(exchangeAddress, numberOfShares, currency, amount, optionalAmount);
        }
    } else {
        if (decisionType == ActionType.ASK) {
            ask(exchangeAddress, currency, amount, optionalCurrency, optionalAmount, numberOfShares);
        } else  { //decisionType == ActionType.BID
            bid(exchangeAddress, currency, amount, optionalCurrency, optionalAmount, numberOfShares);
        }
    }
} else {
    //...
}

function issueShares(uint256 numberOfShares) internal {
    _mint(address(this), numberOfShares);
}

function destroyShares(uint256 numberOfShares) internal {
    _burn(address(this), numberOfShares);
}

function withdrawFunds(address currency, uint256 amount, address destination) internal {
    safeTransfer(IERC20(currency), destination, amount);
}

function cancelOrder(address exchangeAddress, uint256 orderId) internal {
    IExchange(exchangeAddress).cancel(orderId);
}

function raiseFunds(address exchangeAddress, uint256 numberOfShares, address currency, uint256 amount, uint256 maxOrders) internal {
    IExchange exchange = IExchange(exchangeAddress);
    increaseAllowance(exchangeAddress, numberOfShares);
    PackableAddresses.register(exchanges[address(this)], exchangeAddress);
    exchange.ask(address(this), numberOfShares, currency, numberOfShares*amount, maxOrders);
}

function buyBack(address exchangeAddress, uint256 numberOfShares, address currency, uint256 amount, uint256 maxOrders) internal {
    IExchange exchange = IExchange(exchangeAddress);
    IERC20(currency).safeIncreaseAllowance(exchangeAddress, numberOfShares*amount);
    PackableAddresses.register(exchanges[currency], exchangeAddress);
    exchange.bid(currency, numberOfShares*amount, address(this), numberOfShares, maxOrders);
}

function ask(address exchangeAddress, address currency, uint256 amount, address optionalCurrency, uint256 optionalAmount, uint256 maxOrders) internal {
    IExchange exchange = IExchange(exchangeAddress);
    IERC20(currency).safeIncreaseAllowance(exchangeAddress, amount);
    PackableAddresses.register(exchanges[currency], exchangeAddress);
    exchange.ask(currency, amount, optionalCurrency, optionalAmount, maxOrders);
}

function bid(address exchangeAddress, address currency, uint256 amount, address optionalCurrency, uint256 optionalAmount, uint256 maxOrders) internal {
    IExchange exchange = IExchange(exchangeAddress);
    IERC20(optionalCurrency).safeIncreaseAllowance(exchangeAddress, optionalAmount);
    PackableAddresses.register(exchanges[optionalCurrency], exchangeAddress);
    exchange.bid(currency, amount, optionalCurrency, optionalAmount, maxOrders);
}
```

### Requested Feature

The **inline** keyword could be reserved and used in place of the **internal** keyword for functions.  In this case, the code would be both readable and efficient and would look like:

```solidity
if (decisionType < ActionType.RAISE_FUNDS) {
    if (decisionType < ActionType.WITHDRAW_FUNDS) {
        if (decisionType == ActionType.ISSUE_SHARES) {
            issueShares(numberOfShares);
        } else { //decisionType == ActionType.DESTROY_SHARES
            destroyShares(numberOfShares);
        }
    } else {
        if (decisionType == ActionType.WITHDRAW_FUNDS) {
            withdrawFunds(currency, amount, exchangeAddress);
        } else { //decisionType == ActionType.CANCEL_ORDER
            cancelOrder(exchangeAddress, amount);
        }
    }
} else if (decisionType < ActionType.REVERSE_SPLIT) {
    if (decisionType < ActionType.ASK) {
        if (decisionType == ActionType.RAISE_FUNDS) {
            raiseFunds(exchangeAddress, numberOfShares, currency, amount, optionalAmount);
        } else  { //decisionType == ActionType.BUY_BACK
            buyBack(exchangeAddress, numberOfShares, currency, amount, optionalAmount);
        }
    } else {
        if (decisionType == ActionType.ASK) {
            ask(exchangeAddress, currency, amount, optionalCurrency, optionalAmount, numberOfShares);
        } else  { //decisionType == ActionType.BID
            bid(exchangeAddress, currency, amount, optionalCurrency, optionalAmount, numberOfShares);
        }
    }
} else {
    //...
}

function issueShares(uint256 numberOfShares) inline {
    _mint(address(this), numberOfShares);
}

function destroyShares(uint256 numberOfShares) inline {
    _burn(address(this), numberOfShares);
}

function withdrawFunds(address currency, uint256 amount, address destination) inline {
    safeTransfer(IERC20(currency), destination, amount);
}

function cancelOrder(address exchangeAddress, uint256 orderId) inline {
    IExchange(exchangeAddress).cancel(orderId);
}

function raiseFunds(address exchangeAddress, uint256 numberOfShares, address currency, uint256 amount, uint256 maxOrders) inline {
    IExchange exchange = IExchange(exchangeAddress);
    increaseAllowance(exchangeAddress, numberOfShares);
    PackableAddresses.register(exchanges[address(this)], exchangeAddress);
    exchange.ask(address(this), numberOfShares, currency, numberOfShares*amount, maxOrders);
}

function buyBack(address exchangeAddress, uint256 numberOfShares, address currency, uint256 amount, uint256 maxOrders) inline {
    IExchange exchange = IExchange(exchangeAddress);
    IERC20(currency).safeIncreaseAllowance(exchangeAddress, numberOfShares*amount);
    PackableAddresses.register(exchanges[currency], exchangeAddress);
    exchange.bid(currency, numberOfShares*amount, address(this), numberOfShares, maxOrders);
}

function ask(address exchangeAddress, address currency, uint256 amount, address optionalCurrency, uint256 optionalAmount, uint256 maxOrders) inline {
    IExchange exchange = IExchange(exchangeAddress);
    IERC20(currency).safeIncreaseAllowance(exchangeAddress, amount);
    PackableAddresses.register(exchanges[currency], exchangeAddress);
    exchange.ask(currency, amount, optionalCurrency, optionalAmount, maxOrders);
}

function bid(address exchangeAddress, address currency, uint256 amount, address optionalCurrency, uint256 optionalAmount, uint256 maxOrders) inline {
    IExchange exchange = IExchange(exchangeAddress);
    IERC20(optionalCurrency).safeIncreaseAllowance(exchangeAddress, optionalAmount);
    PackableAddresses.register(exchanges[optionalCurrency], exchangeAddress);
    exchange.bid(currency, amount, optionalCurrency, optionalAmount, maxOrders);
}
```

## Specification

Add a keyword **inline** that could be used instead of **internal** for functions.  Using the **inline** keyword would force the compiler to always make a function inline, wherever it is used.

## Backwards Compatibility

A new keyword is used, so in case there was an identifier that was exactly called **inline**, the code would break.  This can be solved by renaming the identifier.  There are no other breaking changes.

Technically, from the `function-definition` at  https://docs.soliditylang.org/en/v0.8.15/grammar.html , only a modifier with the name **inline** may cause code to be non backward compatible.

**Comment by Marenz** [comment] 2022-07-04 11:26
I would consider this issue a duplicate of https://github.com/ethereum/solidity/issues/12782 and any further arguing should happen in that issue..

**Closed as completed by Marenz** 2022-07-04 11:26 UTC
Labels: language design :rage4:

**Comment by CJ42** [comment] 2023-11-06 23:21
This would be a great feature for the Solidity language, as it could allow better code maintenance and readability while benefiting the runtime code for runtime cost and efficiency.

Voting to get this open again.
