### ISSUE TITLE
Support for call* functions when compiling to ewasm

### ISSUE THREAD

**Issue by loredanacirstea** [ethereum/solidity#8960] opened 2020-05-16 12:50 UTC
When compiling Yul -> ewasm, `call`, `staticcall`, `delegatecall` etc. are not included in the final bytecode, nor in the `.wat` output. No Ethereum Interface imports are added for them to the wasm module.

Example: https://gist.github.com/loredanacirstea/d8da062392b7c165976bbc25a183149e

```
object "TestWasm9" {
    code {
        datacopy(0, dataoffset("Runtime"), datasize("Runtime"))
        return(0, datasize("Runtime"))
    }
    object "Runtime" {
        code {
            let _calldata := 96
            calldatacopy(_calldata, 0, calldatasize())

            let addr := mslice(_calldata, 20)
            let input_ptr := add(_calldata, 20)

            // callStatic
            let success := staticcall(gas(), addr, input_ptr, 4, 0, 0)
            mstore(0, success)
            
            return (0, 32)
            
            function mslice(position, length) -> result {
              if gt(length, 32) { revert(0, 0) }
              result := div(mload(position), exp(2, sub(256, mul(length, 8))))
            }
        }
    }
}

```

**Comment by loredanacirstea** [comment] 2020-05-19 21:07
Revisited this.
When instantiating the wasm produced by the above contract, I get `CompileError: WebAssembly.Module(): Compiling function #11 failed: expected 1 elements on the stack for return, found 0 @+1271`

I see that the bytecode produced by the contract is significantly bigger than the bytecode produced by commenting out the `staticcall` : 
```
// let success := staticcall(gas(), addr, input_ptr, 4, 0, 0)
// mstore(0, success)
```
So, it may be that only imports are not included.

**Comment by loredanacirstea** [comment] 2020-05-19 21:24
Redid the example with the code in the constructor: https://gist.github.com/loredanacirstea/1589c00d473e025df7a0ccb72172d5d6 . Now `callStatic` is added as an import - at least in the `wat` source.

But instantiating the wasm module, I get: `CompileError: WebAssembly.Module(): Compiling function #11 failed: expected 1 elements on the stack for return, found 0 @+1059`

Commenting out the `staticcall` results in a valid wasm module.

**Comment by chriseth** [comment] 2020-05-25 21:24
This seems to be caused by `leave`, which is compiled to `(return)` - it ignores the return value (of the first return variable).

**Comment by chriseth** [comment] 2020-05-25 21:35
Can you check if this is fixed by https://github.com/ethereum/solidity/pull/9018 ? Thanks!

**Closed as completed** 2020-05-26 09:35 UTC
Labels: bug :bug:
