### ISSUE TITLE
Error Stack too deep

### ISSUE THREAD

**Issue by cryptonomicon46** [ethereum/solidity#13158] opened 2022-06-15 21:56 UTC
## Environment

- Compiler version: 0.8.13
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): Truffle No okay, Remix Okay
- EVM execution environment / backend / blockchain client:
- Operating system: Mac OSX

## Steps to Reproduce
Stack too deep error when trying to compile a function in Truffle in VS Code. 
But worked okay on Remix. 
 Some responses online were that there's a limit to the number of variables declared in a function. 
So I had to declare another struct with all the variables needed within the function so that they didn't need to be initiated in the function. This was the only way to get around the error message in Truffle/ VS Code. 

Is this a bug, or would it be possible to increase the capacity of a Solidity function to hold more variables. 
Or access variables via deep mappings like struct var -> map->array. 

Might also  
  function revealWinner(uint campaignId_,uint winningRacer_) 
        external    
        payable
        timedTransitions(campaignId_)
        atStage(campaignId_,Stages.RevealWinner) 
        onlyBy(owner)
        returns (Payment memory) {

        BettingCampaign storage b_camp = _getCampaign(campaignId_);
        // Payment memory payment;

        b_camp.payment.totalAmount = b_camp.totalAmount; //All proceeds from the campaign to winner , beneficiary and platform
        b_camp.payment.totalAmount = b_camp.totalAmount; //All proceeds from the campaign to winner , beneficiary and platform

        Bidder memory nextBidder;
        Bidder memory topBidder;
        // if (b_camp.bidders[winningRacer_].length ==0) revert InvalidOperation();
        topBidder.addr = b_camp.bidders[winningRacer_][0].addr;
        topBidder.amount = b_camp.bidders[winningRacer_][0].amount;
        topBidder.timeStamp = b_camp.bidders[winningRacer_][0].timeStamp;

        
        for (uint i=1; i< b_camp.bidders[winningRacer_].length; i++) {

            //Track amount and timestamp for conflict resolution
            nextBidder.addr = b_camp.bidders[winningRacer_][i].addr;
            nextBidder.amount = b_camp.bidders[winningRacer_][i].amount;
            nextBidder.timeStamp = b_camp.bidders[winningRacer_][i].timeStamp;
         

            if (nextBidder.amount > topBidder.amount) {
                topBidder.addr = nextBidder.addr;
                topBidder.amount = nextBidder.amount;
                topBidder.timeStamp=  nextBidder.timeStamp;
               
            }
            else if ( nextBidder.amount == topBidder.amount && nextBidder.timeStamp < topBidder.timeStamp){
                topBidder.addr = nextBidder.addr;
                topBidder.amount = nextBidder.amount;
                topBidder.timeStamp= nextBidder.timeStamp;
            }

**Comment by ekpyron** [comment] 2022-06-16 10:09
The easiest solution to most "stack too deep" errors these days is to switch to via-IR code generation and enable the optimizer.

Apart from saying that generally, there is little I can do to help without a full reproduction :-).

**Comment by cryptonomicon46** [comment] 2022-06-16 17:19
Thanks for your response @ekpyron. I went ahead and replicated the error message and have included links to the  .sol file, the config file , dependencies and the error message. 
 
Accordingly I've created gists to show the .sol file and my config file as follows:

1. Config Gist:  https://gist.github.com/cryptonomicon46/77474e794b9ff0fd1d33568a6a1f4db0
2. .SOL gist:  https://gist.github.com/cryptonomicon46/f74ad1a592d322450fb5946246b91e07#file-stacktoodeep

IDE: VS Code using Truffle to compile. Error message and dependencies are included in the comments under the gist. 

Error message:

Error Message:

Compiling your contracts...
===========================
> Compiling ./contracts/polygon/StackTooDeep.sol

CompilerError: Stack too deep, try removing local variables.
   --> project:/contracts/polygon/StackTooDeep.sol:177:42:
    |
177 |         for (uint i=1; i< b_camp.bidders[winningRacer_].length; i++) {
    |                                          ^^^^^^^^^^^^^

**Comment by ekpyron** [comment] 2022-06-16 18:10
Yeah, you have a lot of local variables in ``revealWinner``, which apparently is too much for the legacy code generation path to handle - this is a known issue 
If you add ``"viaIR": true,`` to the compiler settings in your config, i.e. switch to the new optimized via-IR code generation pipeline, the issue should vanish.

**Comment by ekpyron** [comment] 2022-08-12 12:46
So does my last comment solve your problem :-)? If so, we can close the issue.

**Comment by ekpyron** [comment] 2022-08-12 13:00
I'm assuming the issue is solved by that (i.e. "won't fix" in legacy code generation and fixed by via-IR plus optimizer). Feel free to re-open, if you disagree, though.

**Closed as completed by ekpyron** 2022-08-12 13:00 UTC
Labels: waiting for more input
