### ISSUE TITLE
New ABI only does a revert on string array input

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3294] opened 2017-12-08 10:06 UTC
```
pragma experimental ABIEncoderV2;

contract C {
  function f(string[]) public {
  }    
}
```

compiles without errors, but it only does a `REVERT` if executed in Remix.

Sample input (`[ "aa" ]`): `0xe9cc87800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000026161000000000000000000000000000000000000000000000000000000000000`

**Comment by chriseth** [comment] 2018-03-02 15:17
What do you mean by "only"? What is your expectation?

**Comment by axic** [comment] 2018-03-02 16:49
Don't do a revert?

**Comment by chriseth** [comment] 2018-03-05 15:18
The encoding is wrong, it should be
```
0x20,
1
0x20,
2
"aa"
```

**Comment by fubuloubu** [comment] 2018-06-20 22:36
Still a problem, just ran into this.

**Comment by chriseth** [comment] 2018-06-21 11:55
@yann300 which encoding library are you using? Ether.js or web3.js? This is a bug in one of them :)

**Comment by yann300** [comment] 2018-06-21 12:32
Ether.js since 2 months, I tried now (current remix.ethereum.org) and didn't get the REVERT, also the encoded input seemed good
```
0xe9cc878000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000026161000000000000000000000000000000000000000000000000000000000000
```
@fubuloubu could you post inputs parameters and sample input?

**Comment by fubuloubu** [comment] 2018-06-21 14:57
I was using web3py. I can try to make a MWE later today if I get a chance.

**Comment by fubuloubu** [comment] 2018-06-21 22:58
Ugh, can't reproduce it now. Remix works fine!

For reference, my thing looked something like this:
```solidity
pragma solidity ^0.4.24;
pragma experimental ABIEncoderV2;

contract A
{
    mapping(string => uint) store;
    
    event Bar(string[] a, uint[] b);
    
    function foo(string[] a, uint[] b) public {
        require(a.length == b.length);
        require(a.length > 0);
        for (uint i = 0; i < a.length; i++)
        {
            store[a[i]] = b[i];
        }
        emit Bar(a, b);
    }
}
```

**Comment by chriseth** [comment] 2018-06-26 15:38
Closing for now. Please reopen if it can be reproduced.

**Closed as completed by chriseth** 2018-06-26 15:38 UTC
