### ISSUE TITLE
`solc --hashes` does not generate bytes4 `error` selectors for errors defined at file level

### ISSUE THREAD

**Issue by CJ42** [ethereum/solidity#14083] opened 2023-03-30 10:58 UTC
## Abstract

I am using the `--hashes` option with the `solc` CLI to obtain the list of custom errors selectors defined across a repo.

However, the `--hashes` option provides an output only when the `error` is:
- defined within a `contract`, `library` or `interface` ✅ 
- but not when it is defined at file level ❌ 

Here is an example below on how to reproduce the error.

```solidity
// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.4;

// solc does not generate the error selector for that
error MyFirstError();

interface Example {
    // solc generates the error selector for this
    error MySecondError();
}
```

Output:

![image](https://user-images.githubusercontent.com/31145285/228812725-16f80a91-4897-4dc2-b9ca-fc8e5e16853f.png)

If I now place both custom errors inside the `interface`, `solc` will output the custom error selector of both errors

```solidity
// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.4;

interface Example {
    error MyFirstError();
    error MySecondError();
}
```

Output:
![image](https://user-images.githubusercontent.com/31145285/228813260-3debba9a-ca49-4b34-aad3-3a5c68dde6f8.png)

## Motivation

I suggest that `solc --hashes` enables parsing custom `error` defined at the file level, so their selector can be easily obtained.
Otherwise, this leads to having to rely on manually scraping + parsing the `solc` file to generate these custom errors.

This will make the `solc --hashes` more flexible. Otherwise we need to define custom errors within a `library` or `interface` so that the command line utility generate their error selector (see example of this workaround below)

This is not convenient, as it makes the syntax and structure of Solidity project more complex, and therefore does not encourage to define custom errors at file level.

```solidity
// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.4;

interface Errors {
    error MyFirstError();
    error MySecondError();
}

contract Example {
    function doSomething() public pure {
        revert Errors.MyFirstError();
    }
}

```

## Specification

I am suggesting to enable to parse + generate custom errors signatures at file level, and provide the output as shown below.

- in the header `===...===`: Custom errors defined at file level are just referenced by just the filename --> `FileName.sol`
- in the header `===...===`: Custom errors defined at `contract`, `library` or `interface` level are referenced by filename + contract/interface/library name --> `FileName.sol:ContractName`

```solidity
// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.4;

// solc does not generate the error selector for that
error MyFirstError();

interface Example {
    // solc generates the error selector for this
    error MySecondError();
}
```

_Suggested output:_

```
======= contracts/Example.sol=======
Function signatures:

Error signatures:
f59b1406: MyFirstError()

======= contracts/Example.sol:Example =======
Function signatures:

Error signatures:
4e8f4576: MySecondError()
```

**Comment by matheusaaguiar** [comment] 2023-03-31 14:11
I experimented a little with (hopefully) all possibilities and found that custom `error`s:
 * defined at file level, which are unused or used by an unused free function, do not get their selectors in the output of `--hashes` options;
 * defined inside `contract`/`library`/`interface`, even if unused, have their selector appear in the output;
 * defined at file level and used by a  `contract`/`library`/`interface` function, also have their selector in the output.

I used `errors` and `contracts` defined both in the same file as well as separate files.
I haven't investigated more, so this is only a guess, but maybe the selectors are ignored or discarded because unused (?) 
In any case, could you provide an example or context where it would be useful to have the selector of an unused custom `error`? (Assuming of course that I am not mistaken or missing a case in my previous analysis)

**Comment by matheusaaguiar** [comment] 2023-03-31 14:19
```solidity
// These don't show in --hashes output
error UnusedError();
error AnotherUnusedError();
// These **do** show, although also defined at file level
error UsedError();
error AnotherUsedError();
// Never used
function unusedFreeFunction() pure {
    revert AnotherUnusedError();
}
// Used by Contract
function usedFreeFunction() pure {
    revert UsedError();
}

interface I {
    error InterfaceError();
}

library L {
    error LibraryError();
}

contract C {
    error ContractError();
    function f() public pure {
        usedFreeFunction();
    }
    function g() public pure {
        revert AnotherUsedError();
    }
}
```

**Comment by CJ42** [comment] 2023-04-10 17:27
@matheusaaguiar 

Here is an example with inheritance where `solc --hashes` does not output the hash of a custom `error` defined at file level, although the custom error is used in the base contract.

_file 1: A.sol_

```solidity
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.0;

error MyError();

contract A {
    function _foo() internal pure {
        revert MyError();
    }
}
```

_file 2: B.sol_

```solidity
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.0;

import "./A.sol";

contract B is A {
    function _bar() internal pure {
        _foo();
    }
}
```

---

running the command:

```
solc --hashes contracts/A.sol
```

output:

```
======= contracts/A.sol:A =======
Function signatures:
```

**Comment by CJ42** [comment] 2023-04-10 17:30
If I do the same, but in `A.sol` define the custom error at the contract level, it works and `solc --hashes` output the error selector.

_file 1: A.sol_

```solidity
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.0;



contract A {
    error MyError();
    
    function _foo() internal pure {
        revert MyError();
    }
}
```

_file 2: B.sol_

```solidity
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.0;

import "./A.sol";

contract B is A {
    function _bar() internal pure {
        _foo();
    }
}
```

---

running the command:

```
solc --hashes contracts/A.sol
```

output:

```
======= contracts/A.sol:A =======
Function signatures:

Error signatures:
dd6c951c: MyError()
```

**Comment by matheusaaguiar** [comment] 2023-04-10 19:59
Thanks @CJ42 !

**Comment by matheusaaguiar** [comment] 2023-04-10 20:23
I just noticed that all the functions in your example are `internal`, which are not part of the ABI.
If any of the functions using the error is `public` or `external`, then, being part of the ABI, they will have a documented signature, including the errors.
This seems to be related to [#11752](https://github.com/ethereum/solidity/issues/11752).

**Comment by matheusaaguiar** [comment] 2023-04-10 20:30
I am closing this since it is not a bug.

**Closed as completed** 2023-04-10 20:31 UTC

**Comment by CJ42** [comment] 2023-04-10 20:32
@matheusaaguiar in my example, if you put the function _bar() as public, the same problem occurs.

**Comment by matheusaaguiar** [comment] 2023-04-10 20:38
What compiler version are you using?

**Comment by matheusaaguiar** [comment] 2023-04-10 20:56
@CJ42 , sorry. I guess I was too fast in closing it and only checked with version `0.8.19`.
The problem indeed occurs when using versions `0.8.4` to `0.8.11`.  The custom error signature is not printed, although the function signature is.
From `0.8.12` both signatures are printed.

**Comment by CJ42** [comment] 2023-04-10 21:06
I think I had the problem with 0.8.15. Will double check tomorrow

**Comment by CJ42** [comment] 2023-04-11 18:19
@matheusaaguiar so I can confirm that the same thing happen with either version `0.8.15` or version `0.8.19` of solc.

Here is my setup.

I run the command on the following contract: `LSP1UniversalReceiverDelegateUP`.

https://github.com/lukso-network/lsp-smart-contracts/blob/develop/contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol

This contract imports several libraries, including one called `LSP10Utils.sol`

<img width="833" alt="Screenshot 2023-04-11 at 18 58 41" src="https://user-images.githubusercontent.com/31145285/231248865-219f7992-5d4e-4f47-9be2-a527ccb15d4c.png">

In this library, several custom `error` are defined at the file level.

https://github.com/lukso-network/lsp-smart-contracts/blob/e478626c478e8749601659d558d6a549462bb8a1/contracts/LSP10ReceivedVaults/LSP10Utils.sol#L15-L41

<img width="845" alt="Screenshot 2023-04-11 at 19 00 15" src="https://user-images.githubusercontent.com/31145285/231249757-8d4571ad-bd07-42da-bf0a-aae10fef1a2d.png">

The command I run (which includes the remappings)

```
solc --hashes \
    @erc725/smart-contracts/=node_modules/@erc725/smart-contracts/ \
    @openzeppelin/=node_modules/@openzeppelin/ \
    solidity-bytes-utils/=node_modules/solidity-bytes-utils/ \
    contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
```

The output at the top that I get does not include any error selector from within `LSP10Utils.sol` (these custom `error` are definitely used within the `LSP10Utils` library contract.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/31145285/231253515-76d7aab6-3155-465d-91f6-9e500e907310.png">

However, if I move the custom `error` inside the `library`, as shown below, I get the custom `error` selector in the `--hashes` output. See the screenshot below from VS Code.

<img width="942" alt="image" src="https://user-images.githubusercontent.com/31145285/231254054-57d9f713-7c81-4738-ae52-2b4f9a1a5488.png">

So this definitely confirm the fact that the selector for custom `error` defined at file level is not given as an output.

**Comment by ekpyron** [comment] 2023-04-11 18:31
Do you have a minimal example triggering this issue with solc 0.8.19?

**Comment by CJ42** [comment] 2023-04-11 18:51
Yes I can reproduce the same error with something more minimal.

## ❌  Example when it does not work

_file 1: `A.sol` that contains a `library ALib`_

The custom error is defined at file level.

```solidity
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.0;

error MyError();

library ALib {
    function foo() internal pure {
        revert MyError();
    }
}
```

_file 2: `B.sol` that contains a `contract B` that import + use `ALib`_

```
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.0;

import {ALib} from "./A.sol";

contract B {
    function bar() internal pure {
        ALib.foo();
    }
}
```

running command on `B.sol`

```
solc --hashes ./contracts/B.sol
```

Does not output anything:

```

======= contracts/A.sol:ALib =======
Function signatures:

======= contracts/B.sol:B =======
Function signatures:
```

**Comment by CJ42** [comment] 2023-04-11 18:52
Now with exactly the same except the custom `error` defined within the `ALib` library, the `error` selector` comes in the output.

## ✅ Example when it works

_file 1: `A.sol` that contains a `library ALib`_

The custom error is defined at file level.

```solidity
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.0;

library ALib {

    error MyError();

    function foo() internal pure {
        revert MyError();
    }
}
```

_file 2: `B.sol` that contains a `contract B` that import + use `ALib`_

```
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.0;

import {ALib} from "./A.sol";

contract B {
    function bar() internal pure {
        ALib.foo();
    }
}
```

running command on `B.sol`

```
solc --hashes ./contracts/B.sol
```

Does not output anything:

```

======= contracts/A.sol:ALib =======
Function signatures:

Error signatures:
dd6c951c: MyError()

======= contracts/B.sol:B =======
Function signatures:
```

**Comment by ekpyron** [comment] 2023-04-11 18:57
As @matheusaaguiar noted earlier, emitting the event is only actually possible in ``B``, if ``bar()`` is ``public`` and in that case the error signature is outputted correctly.

In the case that the error is defined in the library, it is still not emitted as part of ``B``, but of `ALib` itself. For each contract/library all errors are reported that are either defined within the contract/library or can be emitted by it. Since an occurrence in an internal function only cannot actually emit the event, the absence of the error for ``B`` is correct. If ``bar`` is public, the error signature is also correctly outputted in either variant.
