### ISSUE TITLE
A possible lack of warning for no-effect statement "x + 2";

### ISSUE THREAD

**Issue by haoyang9804** [ethereum/solidity#15222] opened 2024-06-26 05:42 UTC
## Description

When I write a no-effect statement such as 1 + 2, Solidity compiler warns me that it has no effect. But when I substitute 1 with x, no warning is issued. Does "x + 2" have any side effect, such as changing the value of x or increase the memory cost?
## Environment

- Compiler version: 0.8.27-develop.2024.6.25+commit.ce4be6e1.Darwin.appleclang
- Operating system: Macos M2 Sonoma 14.5

**Comment by mehtavishwa30** [comment] 2024-11-25 11:48
Hey @haoyang9804!

This behaviour is not a bug, but rather intentional. It can also be deemed as a duplicate of https://github.com/ethereum/solidity/issues/13840. The compiler currently does issue a warning only for pure statements. We've briefly outlined the possibilities of extending this behaviour to accommodate cases like yours in [this comment](https://github.com/ethereum/solidity/issues/13840#issuecomment-1428759194) and shall keep the original issue open as a catch-all for similar issues.

Hence, I will be closing this one as a duplicate.

**Closed as completed by mehtavishwa30** 2024-11-25 11:48 UTC
