### ISSUE TITLE
Allow operator overloading in modifiers

### ISSUE THREAD

**Issue by Georgi87** [ethereum/solidity#1657] opened 2017-02-06 17:00 UTC
Type checker: Allow multiple modifiers of the same name (but with different argument types)

```
contract x {
    modifier notNull (uint x) {
        _;
    }
    
    modifier notNull (address x) {
        _;
    }
}
```

**Comment by chriseth** [comment] 2017-02-07 11:25
Duplicate of https://github.com/ethereum/solidity/issues/72

**Closed as completed by chriseth** 2017-02-07 11:25 UTC
