### ISSUE TITLE
Add description of events "imported" from libraries in a contract's ABI

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#12573] opened 2022-01-21 17:49 UTC
## Abstract

Contracts can emit events defined in libraries, either directly or using functions defined in these libraries. This works well, and the produced bytecode indeed emit the correct events, but the corresponding descriptions are not part of contracts's ABI

This results in potential difficulty to parse the events with tooling that relies on the ABI for event decoding.

## Motivation

Lets consider the following code
```solidity
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

library MyLibrary {
    event SomeEvent();

    function someFunction() internal {
        emit SomeEvent();
    }
}

contract MyContract {
    function doSomething() external {
        MyLibrary.someFunction();
    }

    function doSomethingElse() external {
        emit MyLibrary.SomeEvent();
    }
}
```

The ABI produced by the compiler is 

```json
[
	{
		"inputs": [],
		"name": "doSomething",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "doSomethingElse",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	}
]
```

I believe it would be better if it could include the description of `SomeEvent`

```json
	{
		"anonymous": false,
		"inputs": [],
		"name": "SomeEvent",
		"type": "event"
	},
```

## Specification

Whenever a contract emits an event or calls a function that can emit an event, then the event description should be added to the contract ABI. I'm not familiar with the compiler, but that might be done by adding "accessible event" metadata to functions/libraries and propagating that.

## Backwards Compatibility

This doesn't affect the produced bytecode, only the metadata. It only adds new entries to the ABI array. It doesn't remove or modify existing entries. Thus I believe it is fully backward compatible.

**Comment by hrkrshnn** [comment] 2022-01-24 11:56
This is a duplicate of https://github.com/ethereum/solidity/issues/9765, and is almost implemented in https://github.com/ethereum/solidity/pull/10996

The last I checked, this requires a breaking change in the NatSpec output. We can schedule this for 0.9.0.

**Comment by chriseth** [comment] 2022-02-07 10:39
Closing as duplicate.

**Closed as completed by chriseth** 2022-02-07 10:39 UTC

**Comment by zemse** [comment] 2022-03-20 19:57
> We can schedule this for 0.9.0.

Is there any approximate idea when 0.9 is going to be released?

**Comment by chriseth** [comment] 2022-03-24 13:40
Not really. Maybe this year.
