### ISSUE TITLE
[yul] nested object access error

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7399] opened 2019-09-10 22:51 UTC
## Description

```
object "object0" {
code {
{
datacopy(0x1fffffffffffffffffff, 0x1ffffffffffffffffffff, datasize("datablock"))
datacopy(0x1fffffffffffffffffffff, 0x1ffffffffffffffffffffff, dataoffset("object1.object2"))
datacopy(0x1fffffffffffffffffffffff, 0x1ffffffffffffffffffffffff, datasize("object0"))
datacopy(0x1fffffffffffffffffffffffff, 0x1ffffffffffffffffffffffffff, datasize("datablock"))
}
}
data "datablock" hex"1fffffffffffffffffffffffffff"
object "object1" {
code {
{}
}
data "datablock" hex"01ffffffffffffffffffffffffffff"
object "object2" {
code {
{
for {}
0x1fffffffffffffffffffffffffffff{}
{}
}
}
}
}
}
```

I am not sure why the nested access `object1.object2` within `object0`'s code section is deemed invalid.

```
$ solc --strict-assembly <test.yul>
test.yul:5:63: Error: Unknown data object "object1.object2".
datacopy(0x1fffffffffffffffffffff, 0x1ffffffffffffffffffffff, dataoffset("object1.object2"))
```

Such nested accesses are considered valid in the documentation: https://solidity.readthedocs.io/en/v0.5.11/yul.html?highlight=dataoffset#specification-of-yul-object

Identifiers in scope seem to be restricted to the current object, its subobject, or data block (see https://github.com/ethereum/solidity/pull/7236#discussion_r322782484)

**Comment by axic** [comment] 2020-05-12 23:47
Duplicate of #6739.

**Closed as completed** 2020-05-13 07:39 UTC
