### ISSUE TITLE
Unimplemented feature in void solidity::frontend::CompilerUtils::abiDecode(const TypePointers&, bool)

### ISSUE THREAD

**Issue by cakesoft-khushi** [ethereum/solidity#9728] opened 2020-09-02 08:24 UTC
## Description
I have a method in one contract that returns the array of strings ( ABIEncoderV2 enabled ). When I call that method in another contract that does not have ABIEncoderV2 enabled, it gives the following error in solc output.

>Unimplemented feature:
/home/dell/solidity/libsolidity/codegen/CompilerUtils.cpp(267): Throw in function void solidity::frontend::CompilerUtils::abiDecode(const TypePointers&, bool)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::UnimplementedFeatureError>
std::exception::what: Nested arrays not yet implemented.
[solidity::util::tag_comment*] = Nested arrays not yet implemented.

However, if I enable ABIEncoderV2 in the calling contract, it compiles.

## Environment

* Compiler Version : 0.7.0
* Operating system : Ubuntu
* EVM execution environment / backend / blockchain client : Ganache
* Framework/IDE : Remix

## Steps to Reproduce

contract1.sol :

    pragma solidity ^0.7.0;
    pragma experimental ABIEncoderV2;
    contract contract1 
    {  
    //string[]  array ;
    function compute() public returns (string[] memory arr)
    {}
    }

contract2.sol :

    import "contract1.sol";

    //pragma experimental ABIEncoderV2;

    contract contract2 {

        function A() public {
                contract1 ob;
                ob.compute();
        }
    }

If it is compiled, it will give the above error but if the calling contract has ABIEncoderV2 enabled it will work as expected.

**Comment by chriseth** [comment] 2020-09-03 09:37
The calling contract needs ABIEncoderV2 enabled for this to work. This is a duplicate of https://github.com/ethereum/solidity/issues/8379

**Closed as completed by chriseth** 2020-09-03 09:37 UTC
