### ISSUE TITLE
Performance issues of `solc --abi --via-ir`

### ISSUE THREAD

**Issue by klkvr** [ethereum/solidity#14917] opened 2024-03-06 23:24 UTC
## Description

It seems that requesting only ABI as output significantly speeds up compilation process which is useful when you don't need anything besides ABI or want to determine files which should be compiled depending on the contracts ABI.

Speed up in case of `solc --bin --abi` vs `solc --abi` is great, without `--bin` it is ~20 times faster on the project I am experimenting with.

However, for some reason `solc --abi --via-ir` runs much longer than `solc --abi` or `solc --bin`. I assume it's because of certain compilation steps not being skipped in IR pipeline which are getting skipped in default compilation mode.

**Comment by klkvr** [comment] 2024-03-06 23:32
It seems that this is not the case when compiling with `--standard-json` with only "abi" in `outputSelection.*.*`

**Comment by cameel** [comment] 2024-03-07 10:20
That's odd. Looking at how [`CommandLineInterface`](https://github.com/ethereum/solidity/blob/v0.8.24/solc/CommandLineInterface.cpp#L849-L873) decides whether to perform compilation, `--abi` is not one of the outputs that would trigger full compilation. And [actually producing the ABI is marked as requiring only analysis in `CompilerStack`](https://github.com/ethereum/solidity/blob/v0.8.24/libsolidity/interface/CompilerStack.cpp#L1032-L1049). So for both IR and legacy pipeline it should stop at analysis and analysis is the same in both cases. I'd expect any potential slowdown to be in code generation or, much more likely, optimization instead.

How much slowdown are you seeing? Is the repro big enough that the slowdown is not just caused by some small constant factors?

**Comment by klkvr** [comment] 2024-03-07 17:45
For the same command with different flags I am getting those results:
`solc ... --abi`: 1.32s
`solc ... --via-ir`: 162.409s
`solc ... --via-ir --abi`: 159.849s

Could it be the case that `--via-ir` always automatically triggers compilation? Sounds like this comment is about this issue: https://github.com/ethereum/solidity/blob/e11b9ed9f2c254bc894d844c0a64a0eb76bbb4fd/solc/CommandLineInterface.cpp#L848

**Comment by cameel** [comment] 2024-03-08 17:10
> Could it be the case that --via-ir always automatically triggers compilation? 

Well, your numbers show that it clearly must be triggering compilation in this case, but it does not seem to be due to the code in this spot at least. `--via-ir` corresponds to the `m_options.output.viaIR` flag and that is not used in the condition. The conditions there are correct. It must be something further down the stack.

> Sounds like this comment is about this issue

This comment is outdated. We should remove it. Looking at the original context, we used to just unconditionally compile everything: https://github.com/ethereum/solidity/blob/df82e26d5ad3eff2514c4461ff94ada8fa1ebd55/CommandLineInterface.cpp#L249-L255

Nowadays we decide based on the output flags whether to compile so that TODO has actually been fulfilled.

**Comment by cameel** [comment] 2024-03-08 17:30
Looks like this condition is probably the culprit: https://github.com/ethereum/solidity/blob/5a43a8b1e4123818c67b1b828c5ce05af28823a6/libsolidity/interface/CompilerStack.cpp#L739

**Comment by cameel** [comment] 2024-03-08 18:13
After figuring out what causes it the fix is actually trivial so I created a PR: #14926.

And this indeed does not affect Standard JSON - which in unexpected since the fix is in `CompilerStack`, which is used in that mode too. Turns out that CLI always runs `CompilerStack` and uses `enableEvmBytecodeGeneration()` and `enableIRGeneration()` to tell it whether compilation is needed (which I think is the more correct approach) while `StandardCompiler` completely skips `compile()` when no binary output is requested.

We should really unify the two, because it results in just such odd differences in behavior, but for now I stopped at just fixing the issue at hand.

**Closed as completed** 2024-03-11 15:37 UTC
Labels: bug :bug:, performance :racehorse:, low effort, low impact, must have eventually
