### ISSUE TITLE
eth_call block.blockhash(n) == sendTransaction block.blockhash(n+1)

### ISSUE THREAD

**Issue by wighawag** [ethereum/solidity#1305] opened 2016-10-30 12:47 UTC
I do not know whether it is a bug in solidity or the evm but it is quite serious
Basically code executed on an call differ from code executed as part of transaction in regard to blockhash

I created a gist for browser solidity here : https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.3+commit.2353da71.js&optimize=true&gist=2bd29ecb4148205918a55d2fed599c30

contract address : 0x56E67D215aB5Af9B2476c85881D9F19cF26ac064

call getBlockHash with a recent blockNumber and check the value
submit a tx for saveBlockHash with that same blockNumber as argument
call getSavedBlockHash and you ll see they are not the same while they should

It turns out that :

```
eth_call block.blockhash(n) == sendTransaction block.blockhash(n+1)
```

**Comment by axic** [comment] 2016-10-30 13:03
This seems to be working for me in the VM mode of latest browser-solidity. Note, the starting block number is 1150000.

My steps:
- create contract (that is in block 1150000)
- run `getBlockHash(1150000)` -> `0x18676e992055c057538d59b378271bb4eacdb7f6abf9e815fd63255dc11166b6`
- run `saveBlockHash(1150000)`
- run `getSavedBlockHash()` -> `0x18676e992055c057538d59b378271bb4eacdb7f6abf9e815fd63255dc11166b6`

And strictly speaking, this doesn't seem to be a Solidity bug at all. It would be very strange if it would be a bug in Solidity as the contract has no way telling it is running as part of an RPC eth_call or a real transaction.

**Comment by wighawag** [comment] 2016-10-30 13:11
I can confirm, using the VM, I get proper behavior. Using metamask on the testnet chain, I still get the issue. Might be an issue with metamask VM

**Comment by axic** [comment] 2016-10-30 13:14
Closing as it is not a bug in Solidity.

**Closed as completed by axic** 2016-10-30 13:14 UTC
