### ISSUE TITLE
ABI inconsistency

### ISSUE THREAD

**Issue by debris** [ethereum/solidity#990] opened 2016-09-01 08:34 UTC
Solidity version: `0.3.6-3fc68da5/Release-Emscripten/clang`

contract:

```
contract Foo {
}

contract Bar {
  event E(Foo x);
  function f(Foo x);
}
```

abi:

```
[
  {
    "constant": false,
    "inputs": [
      {
        "name": "x",
        "type": "address"
      }
    ],
    "name": "f",
    "outputs": [],
    "type": "function"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "x",
        "type": "Foo"
      }
    ],
    "name": "E",
    "type": "event"
  }
]
```

Please notice difference between event and function input types
- function: `"type": "address"`
- event: `"type": "Foo"`

Is it a bug or intended behaviour? If it is intended, how to handle custom ABI types?
Downstream issue: https://github.com/ethcore/ethabi/issues/7#issuecomment-244008264

**Comment by chriseth** [comment] 2016-09-01 08:38
This is a known issue: Parameters for events are not properly converted from internal to external types. Closing as duplicate of https://github.com/ethereum/solidity/issues/489

**Comment by chriseth** [comment] 2016-09-01 08:39
Thanks for reporting!

**Closed as completed by chriseth** 2016-09-01 08:38 UTC
