### ISSUE TITLE
`call`/`callcode` discrepancy

### ISSUE THREAD

**Issue by tom-seddon** [ethereum/solidity#283] opened 2015-12-07 21:57 UTC
The following contract's `makeTestCall2` function attempts to call its `testCall2` function using `callcode`, creating the calldata manually:

```
contract TestCall {
    bytes _tmpCalldata;
    uint public testArg0;
    uint public testArg1;
    function makeTestCall2() {
        _tmpCalldata.length=64; for(uint i=0;i<64;++i) _tmpCalldata[i]=0xff;
        TestCall(this).callcode(bytes4(0x0f682008),_tmpCalldata); // 0x0f682008=testCall2(uint256,uint256)
    }
    function testCall2(uint arg0,uint arg1) { testArg0=arg0; testArg1=arg1; }
}
```

(This code is in one contract for testing purposes; the eventual goal is for the callee to be in a library.)

Expected result: both `testArg0` and `testArg1` end up both set to 0xFFF(...)FFF.

Actual result: variable (when I run the above on ethersim, both are set to 0; but as part of my larger test, `testArg` was set to 4, and `testArg1`, 0.)

Using `call` rather than `callcode` gives the expected result.

--Tom

P.S. As mentioned on gitter: https://gitter.im/ethereum/solidity?at=5665c965981d328249333ac3

**Comment by chriseth** [comment] 2015-12-18 16:26
It seems callcode does not copy storage to memory.

**Comment by chriseth** [comment] 2015-12-21 16:45
Ok, right. It is on purpose that callcode does not copy storage to memory. The reason is that you can actually pass a storage pointer via callcode, as opposed to call. If you want to force copying to memory, assign the data to a local (memory) variable before calling.

Closing as not a bug.

**Closed as completed by chriseth** 2015-12-21 16:45 UTC
Labels: bug :bug:

**Comment by tom-seddon** [comment] 2016-01-14 00:58
Thanks - pretty sure I get what's going on now. Copying to a memory byte array does work.

I wonder if callcode should let you be more explicit about whether you're passing in a byte array (and you want to pass its address - obviously a memory array would then be an error), or you're passing in a byte array (and it contains the call data for the call - and a storage array would then be an error).

--Tom

**Comment by chriseth** [comment] 2016-01-14 10:33
My proposed solution to this would be to have a custom encoding function that handles this for you and returns a `bytes memory` that you can then pass to the callcode.
