### ISSUE TITLE
Compiler often creates different bytecode in different environments

### ISSUE THREAD

**Issue by LianaHus** [ethereum/solidity#17] opened 2015-08-20 14:41 UTC
(moved) see original issue here: https://github.com/ethereum/cpp-ethereum/issues/2841

**Comment by androlo** [comment] 2015-09-03 01:59
Not sure it helps, but me and some of my colleagues noticed this quite some time ago. I think even Serpent and LLL behaved the same way, e.g. sometimes you got slightly different bytecode when compiling on mac then on linux. Didn't cause any issues as far as I can remember.

**Comment by chriseth** [comment] 2015-09-15 15:04
Some months ago, randomness was used during compilation (also by LLL). This is no longer the case.

**Comment by jase1981** [comment] 2015-09-18 10:21
I ran the tests again on latest executables (linux solc-dev version: 0.1.2-0/Release-/g++/int; web: solc version: 0.1.2-5c3bfd4b*/.-/clang/int and windows cpp-ethereum 0.9.41 solc version: 0.1.1-cb61d09d/Release-Windows/msvc/JIT)

Results:

```
Created new hashfile hash/ExpRegistrar.lin.txt.hash.5fa158000942ea1895cd5766bbb3c205d38fc898ea5d9744e7183dd946d25215.len.9928.txt
Created new hashfile hash/ExpRegistrar.web.txt.hash.5fa158000942ea1895cd5766bbb3c205d38fc898ea5d9744e7183dd946d25215.len.9928.txt
Created new hashfile hash/ExpRegistrar.win.txt.hash.5fa158000942ea1895cd5766bbb3c205d38fc898ea5d9744e7183dd946d25215.len.9928.txt
Created new hashfile hash/Game.lin.txt.hash.f347d9a7b6c12d31b71d0cd7227b0a15cb90ba5859d5895346f5c8ed35d3b70b.len.12222.txt
Created new hashfile hash/Game.web.txt.hash.07ee78f1bf20cc1c29f90181199e79548417218e7cc361b510e68af4528eaca1.len.12222.txt
Created new hashfile hash/Game.win.txt.hash.f347d9a7b6c12d31b71d0cd7227b0a15cb90ba5859d5895346f5c8ed35d3b70b.len.12222.txt
Created new hashfile hash/Government.lin.txt.hash.3aff7d08497ef855415a0f387c224f892bce2ad7ac698e19e794b1f4bff4e5f2.len.5158.txt
Created new hashfile hash/Government.web.txt.hash.c24da3e5c3a6b96dbc4635d48c3c9a183098bc9de10b0fd9bf3e79e592f1a07d.len.5158.txt
Created new hashfile hash/Government.win.txt.hash.165d31667a858865a21e60a5c33ddb023556aafa79ca2e498fe640ac540b8000.len.5158.txt
Created new hashfile hash/Lotto.lin.txt.hash.092ee6d0cc2f7c70040fdc5f0bcd4c1b062b22ccc5afb68dfdb6180c27b33173.len.4730.txt
Created new hashfile hash/Lotto.web.txt.hash.3825dd0170df2615f10550a0d3ba554600fb06fae48725ea3deb4ac960a06dfe.len.4730.txt
Created new hashfile hash/Lotto.win.txt.hash.4af1260b882f51e393b621dc81f5b2259aeb1bea850263dac6df29ccf58a991c.len.4730.txt
Created new hashfile hash/SHA3compete.lin.txt.hash.7cb8c99988cc300e36e840a0b6ed9259266dc29652b2fbae96025f59c9432c8f.len.5998.txt
Created new hashfile hash/SHA3compete.web.txt.hash.d0db5a6f06449d0993b085363661dedc2f3a316368b99c917e878850a305646d.len.5998.txt
Created new hashfile hash/SHA3compete.win.txt.hash.7a4e59427bd9e4325239d446b16bb455a866a85dc0b483f393371fed05e1f0a8.len.5998.txt
Created new hashfile hash/dice.lin.txt.hash.a63c216e8187872e58b9f5b829043f5890b81612c10b880da0056ad1747bd059.len.7180.txt
Created new hashfile hash/dice.web.txt.hash.a63c216e8187872e58b9f5b829043f5890b81612c10b880da0056ad1747bd059.len.7180.txt
Created new hashfile hash/dice.win.txt.hash.11a865cf09b7e30412c69704ff8256a59100fdb59c5810a408c0eda830002448.len.7180.txt
Created new hashfile hash/fun_distributor.lin.txt.hash.01c37e9c48eac034f75f8e306612fc8553b2b3cc37e4aac74c7fdd3786720c4a.len.1284.txt
Created new hashfile hash/fun_distributor.web.txt.hash.01c37e9c48eac034f75f8e306612fc8553b2b3cc37e4aac74c7fdd3786720c4a.len.1284.txt
Created new hashfile hash/fun_distributor.win.txt.hash.01c37e9c48eac034f75f8e306612fc8553b2b3cc37e4aac74c7fdd3786720c4a.len.1284.txt
Created new hashfile hash/wallet.lin.txt.hash.10bac8eb2d7cc8339013549c1122104c290d4a669c03e8b0606747d1b7254458.len.12012.txt
Created new hashfile hash/wallet.web.txt.hash.10bac8eb2d7cc8339013549c1122104c290d4a669c03e8b0606747d1b7254458.len.12012.txt
Created new hashfile hash/wallet.win.txt.hash.10bac8eb2d7cc8339013549c1122104c290d4a669c03e8b0606747d1b7254458.len.12012.txt
```

Web and linux are the same version (0.1.2) and are sometimes not producing the same bytecode.
All testing contracts, scripts and outputs are available here: https://drive.google.com/file/d/0B27o9CYAlaNjaE9VQkEwdVZOcHc/view?usp=sharing

**Comment by chriseth** [comment] 2015-09-18 13:50
Please note that 0.1.2-0 is the tagged, released version and 0.1.2-5c3bfd4b\* is a non-tagged development version based on top of 0.1.2, even including local modifications (the asterisk).
It seems all three compilers were actually of different versions.

**Comment by jase1981** [comment] 2015-10-01 18:03
I finally managed to compile ethereum. Now all versions are a match (0.1.4-5f6c3cdf). Here's the output:

```
Created new hashfile hash/ExpRegistrar.lin.txt.hash.5fa158000942ea1895cd5766bbb3c205d38fc898ea5d9744e7183dd946d25215.len.9928.txt
Created new hashfile hash/ExpRegistrar.web.txt.hash.5fa158000942ea1895cd5766bbb3c205d38fc898ea5d9744e7183dd946d25215.len.9928.txt
Created new hashfile hash/ExpRegistrar.win.txt.hash.5fa158000942ea1895cd5766bbb3c205d38fc898ea5d9744e7183dd946d25215.len.9928.txt
Created new hashfile hash/Game.lin.txt.hash.f347d9a7b6c12d31b71d0cd7227b0a15cb90ba5859d5895346f5c8ed35d3b70b.len.12222.txt
Created new hashfile hash/Game.web.txt.hash.df0b2c89f4635462ebda7eeef9dcc01841c0b80b6b4bec0fde5cbe6c1ed4108c.len.12222.txt
Created new hashfile hash/Game.win.txt.hash.f347d9a7b6c12d31b71d0cd7227b0a15cb90ba5859d5895346f5c8ed35d3b70b.len.12222.txt
Created new hashfile hash/Government.lin.txt.hash.74c937cd5988ce45e8253aaa00fed9d2fe97162b14bed00494e8e489b2ec0962.len.5158.txt
Created new hashfile hash/Government.web.txt.hash.c24da3e5c3a6b96dbc4635d48c3c9a183098bc9de10b0fd9bf3e79e592f1a07d.len.5158.txt
Created new hashfile hash/Government.win.txt.hash.c24da3e5c3a6b96dbc4635d48c3c9a183098bc9de10b0fd9bf3e79e592f1a07d.len.5158.txt
Created new hashfile hash/Lotto.lin.txt.hash.092ee6d0cc2f7c70040fdc5f0bcd4c1b062b22ccc5afb68dfdb6180c27b33173.len.4730.txt
Created new hashfile hash/Lotto.web.txt.hash.092ee6d0cc2f7c70040fdc5f0bcd4c1b062b22ccc5afb68dfdb6180c27b33173.len.4730.txt
Created new hashfile hash/Lotto.win.txt.hash.092ee6d0cc2f7c70040fdc5f0bcd4c1b062b22ccc5afb68dfdb6180c27b33173.len.4730.txt
Created new hashfile hash/SHA3compete.lin.txt.hash.e99bc73ba308bad7ce13161cfe9526b7f3a682a3a67927c3764cf0f77e131827.len.5998.txt
Created new hashfile hash/SHA3compete.web.txt.hash.223851ae875e304824bb7f4af55f8fae73e91293a5e1fcc721364aa85de4a1c1.len.5998.txt
Created new hashfile hash/SHA3compete.win.txt.hash.d0db5a6f06449d0993b085363661dedc2f3a316368b99c917e878850a305646d.len.5998.txt
Created new hashfile hash/dice.lin.txt.hash.a63c216e8187872e58b9f5b829043f5890b81612c10b880da0056ad1747bd059.len.7180.txt
Created new hashfile hash/dice.web.txt.hash.a63c216e8187872e58b9f5b829043f5890b81612c10b880da0056ad1747bd059.len.7180.txt
Created new hashfile hash/dice.win.txt.hash.11a865cf09b7e30412c69704ff8256a59100fdb59c5810a408c0eda830002448.len.7180.txt
Created new hashfile hash/fun_distributor.lin.txt.hash.01c37e9c48eac034f75f8e306612fc8553b2b3cc37e4aac74c7fdd3786720c4a.len.1284.txt
Created new hashfile hash/fun_distributor.web.txt.hash.01c37e9c48eac034f75f8e306612fc8553b2b3cc37e4aac74c7fdd3786720c4a.len.1284.txt
Created new hashfile hash/fun_distributor.win.txt.hash.01c37e9c48eac034f75f8e306612fc8553b2b3cc37e4aac74c7fdd3786720c4a.len.1284.txt
Created new hashfile hash/wallet.lin.txt.hash.10bac8eb2d7cc8339013549c1122104c290d4a669c03e8b0606747d1b7254458.len.12012.txt
Created new hashfile hash/wallet.web.txt.hash.efee41c8e0fdd29ec0fa07119b6d1b292b1524675d5ea07e440f0269668a74da.len.12012.txt
Created new hashfile hash/wallet.win.txt.hash.22f58460b79e7a56f4941988dd8da51e5efa6e5ba792cd49b8ca059e6c3a9e8e.len.12012.txt
```

All testing contracts, scripts and outputs are available here:
https://drive.google.com/file/d/0B27o9CYAlaNjUHdhenc2anRzZWc/view?usp=sharing

**Comment by chriseth** [comment] 2016-04-29 15:41
As raw pointers are used to identify AST nodes, compilation results might depend on the way memory is allocated. The way to fix is to either use a different allocator (which might not be too hard and is planned anyway) or use a different ID.

If we switch the allocator, we should use one that only keeps a single reference counter tied to the root node.

**Comment by chriseth** [comment] 2016-05-06 16:36
This should be fixed, needs some testing.

**Comment by axic** [comment] 2016-05-24 15:43
@chriseth I wonder if emscripten in solc-js can introduce non-determinism additionally to the above?

**Comment by chriseth** [comment] 2016-05-31 22:32
Tested and confirmed that we should now have deterministic compilation, even across platforms.

**Closed by chriseth** 2016-05-31 22:32 UTC
Labels: active, bug

**Comment by jase1981** [comment] 2016-06-04 17:21
I tested it again and can confirm, all three versions are producing same output now. Thank you!!

```
Created new hashfile hash/ExpRegistrar.lin.txt.hash.61ea7d794f90e9a6542384f54a537690edfe7cf5252bb53fd417036232095d11.len.8268.txt
Created new hashfile hash/ExpRegistrar.web.txt.hash.61ea7d794f90e9a6542384f54a537690edfe7cf5252bb53fd417036232095d11.len.8268.txt
Created new hashfile hash/ExpRegistrar.win.txt.hash.61ea7d794f90e9a6542384f54a537690edfe7cf5252bb53fd417036232095d11.len.8268.txt
Created new hashfile hash/Game.lin.txt.hash.23ccb349d1af11a40546efeabdefcd1600e19a245ac099059d5adced5852628e.len.8864.txt
Created new hashfile hash/Game.web.txt.hash.23ccb349d1af11a40546efeabdefcd1600e19a245ac099059d5adced5852628e.len.8864.txt
Created new hashfile hash/Game.win.txt.hash.23ccb349d1af11a40546efeabdefcd1600e19a245ac099059d5adced5852628e.len.8864.txt
Created new hashfile hash/Government.lin.txt.hash.b8e66ddf97eda8c46c77bd9ae4638cc1e6b36ed523462c1bd27baa2d7e2cbe0d.len.3656.txt
Created new hashfile hash/Government.web.txt.hash.b8e66ddf97eda8c46c77bd9ae4638cc1e6b36ed523462c1bd27baa2d7e2cbe0d.len.3656.txt
Created new hashfile hash/Government.win.txt.hash.b8e66ddf97eda8c46c77bd9ae4638cc1e6b36ed523462c1bd27baa2d7e2cbe0d.len.3656.txt
Created new hashfile hash/Lotto.lin.txt.hash.7e89abcfcc5f99629f6749eda4729483b7b558d8b0989e4146e4388bac62538d.len.2946.txt
Created new hashfile hash/Lotto.web.txt.hash.7e89abcfcc5f99629f6749eda4729483b7b558d8b0989e4146e4388bac62538d.len.2946.txt
Created new hashfile hash/Lotto.win.txt.hash.7e89abcfcc5f99629f6749eda4729483b7b558d8b0989e4146e4388bac62538d.len.2946.txt
Created new hashfile hash/SHA3compete.lin.txt.hash.f8459b5272c86813810ec0118b975eb11a584907a3900d5f4e6b62e28543d060.len.4258.txt
Created new hashfile hash/SHA3compete.web.txt.hash.f8459b5272c86813810ec0118b975eb11a584907a3900d5f4e6b62e28543d060.len.4258.txt
Created new hashfile hash/SHA3compete.win.txt.hash.f8459b5272c86813810ec0118b975eb11a584907a3900d5f4e6b62e28543d060.len.4258.txt
Created new hashfile hash/dice.lin.txt.hash.c11aa5406e56fc65185a84ed7bd77325dbd50266a581c576f52c1f9f4c86c5b5.len.3946.txt
Created new hashfile hash/dice.web.txt.hash.c11aa5406e56fc65185a84ed7bd77325dbd50266a581c576f52c1f9f4c86c5b5.len.3946.txt
Created new hashfile hash/dice.win.txt.hash.c11aa5406e56fc65185a84ed7bd77325dbd50266a581c576f52c1f9f4c86c5b5.len.3946.txt
Created new hashfile hash/fun_distributor.lin.txt.hash.3b390b041f9128a018255e5c863e40d9e733fa5c519e03237f0a8ddd11279059.len.660.txt
Created new hashfile hash/fun_distributor.web.txt.hash.3b390b041f9128a018255e5c863e40d9e733fa5c519e03237f0a8ddd11279059.len.660.txt
Created new hashfile hash/fun_distributor.win.txt.hash.3b390b041f9128a018255e5c863e40d9e733fa5c519e03237f0a8ddd11279059.len.660.txt
Created new hashfile hash/wallet.lin.txt.hash.3898fd96e1658ecdc59a9d6460ed8d7abb0e4c145ad7ddf8a606e9f38931e991.len.8268.txt
Created new hashfile hash/wallet.web.txt.hash.3898fd96e1658ecdc59a9d6460ed8d7abb0e4c145ad7ddf8a606e9f38931e991.len.8268.txt
Created new hashfile hash/wallet.win.txt.hash.3898fd96e1658ecdc59a9d6460ed8d7abb0e4c145ad7ddf8a606e9f38931e991.len.8268.txt
```

https://drive.google.com/open?id=0B27o9CYAlaNjSGVXOW1PbExQTkE
I had to use optimized version, because browser-solidity always produces optimized, even if no checkbox.

**Comment by chriseth** [comment] 2016-06-04 19:24
WOHOOOO!

**Comment by VoR0220** [comment] 2016-06-04 21:43
Yus

**Comment by axic** [comment] 2016-07-27 16:06
Leaving this here as a reference: fixed by https://github.com/ethereum/solidity/pull/536
