### ISSUE TITLE
ICE: solidity::frontend::ArrayType::calldataEncodedSize(bool) const: Array size does not fit unsigned

### ISSUE THREAD

**Issue by Cancelll** [ethereum/solidity#11609] opened 2021-07-04 12:02 UTC
## Environment

- Compiler version: Version: 0.8.7-develop.2021.7.4+commit.f6cb933f.Linux.clang
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: Linux 5.4.0-77-generic x86_64 GNU/Linux

#### Test program: small.sol
```solidity
contract C {
  struct S {
    bytes32[1263941234127518272] a;
  }

  function f(S[] memory) public {}
}

```
#### Compiler Command
```bash
solc-trunk-asan_ubsan --optimize small.sol
```
#### Output
```
Internal compiler error during compilation:
/solidity/libsolidity/ast/Types.cpp(1683): Throw in function virtual unsigned int solidity::frontend::ArrayType::calldataEncodedSize(bool) const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Array size does not fit unsigned.
[solidity::util::tag_comment*] = Array size does not fit unsigned.
```

**Comment by rvantonder** [comment] 2021-07-08 05:55
FYI may be a duplicate of https://github.com/ethereum/solidity/issues/8382. I'm guessing the line number in `Types.cpp` is different because the code shifted a bit.

**Comment by cameel** [comment] 2021-07-12 02:14
Yes, it's the same issue and the error happens on the same line. So I'm going to close it since #8382 is still open.

**Closed as completed by cameel** 2021-07-12 02:14 UTC
Labels: bug :bug:, should report error
