### ISSUE TITLE
SMT test hangs with libz3 version 4.6.0

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3625] opened 2018-03-01 10:35 UTC
libz3 version 4.6.0 causes the test SMTChecker/division to hang indefinitely.

**Comment by chriseth** [comment] 2018-03-01 11:02
@leonardoalt would you like to take a short look into this? The problematic test seems to be the signed division overflow test.

**Comment by leonardoalt** [comment] 2018-03-01 16:40
Sure. I got the SMT formula (below) and tried on different versions of z3.
Version 4.5.0 solves it correctly (SAT) in 0.2s, whereas version 4.6.0 indeed hangs.
I'll open an issue and see what they say.

```
(declare-fun x_4 (Int) Int)
(declare-fun y_6 (Int) Int)
(declare-fun _9 (Int) Int)
(declare-fun expr_12 () Int)
(declare-fun expr_13 () Int)
(declare-fun expr_14 () Bool)
(declare-fun expr_17 () Int)
(declare-fun expr_18 () Int)
(assert (>= (x_4 0)
    (- 57896044618658097711785492504343953926634992332820282019728792003956564819968)))
(assert (<= (x_4 0)
    57896044618658097711785492504343953926634992332820282019728792003956564819967))
(assert (>= (y_6 0)
    (- 57896044618658097711785492504343953926634992332820282019728792003956564819968)))
(assert (<= (y_6 0)
    57896044618658097711785492504343953926634992332820282019728792003956564819967))
(assert (= (_9 0) 0))
(assert (= expr_12 (y_6 0)))
(assert (= expr_13 0))
(assert (= expr_14 (not (= expr_12 expr_13))))
(assert (or (not true) expr_14))
(assert (= expr_17 (x_4 0)))
(assert (= expr_18 (y_6 0)))
(assert (not (= expr_18 0)))
(assert (let ((a!1 (ite (>= expr_18 0)
                (div expr_17 expr_18)
                (- 0 (div expr_17 (- 0 expr_18)))))
      (a!2 (ite (>= expr_18 0)
                (- 0 (div (- 0 expr_17) expr_18))
                (div (- 0 expr_17) (- 0 expr_18)))))
  (and true
       (> (ite (>= expr_17 0) a!1 a!2)
          57896044618658097711785492504343953926634992332820282019728792003956564819967))))
(check-sat)
```

**Comment by chriseth** [comment] 2018-03-01 16:43
Wonderful, thanks! How did you extract the formula? We tried this morning but could not make it hang.

**Comment by leonardoalt** [comment] 2018-03-01 16:48
In `Z3Interface::check`, just `cout << m_solver << endl;`. Then I added `(check-sat)`.

**Comment by chriseth** [comment] 2018-03-01 16:54
*doh* I thought I remembered there was some kind of easy solution ;)

**Comment by leonardoalt** [comment] 2018-03-01 16:58
Hehe I've been using that to debug the encoding since I started contributing, perhaps I should have shared it somehow...

**Comment by chriseth** [comment] 2018-03-02 09:40
The issue in the z3prover repository: https://github.com/Z3Prover/z3/issues/1511

**Comment by leonardoalt** [comment] 2018-03-02 18:12
So, the current status is the following.
It was suggested that we use a `z3` option called `rewriter.pull_cheap_ite`.
When using this option to solve the formula as a standalone `smtlib2` file, `z3-4.6.0` is as fast as `z3-4.5.0` (~0.2s). This is done by adding `(set-option :rewriter.pull_cheap_ite true)` as the first line in the above formula.
BUT... when I added this option in the C++ API, the time improvement wasn't the same, as `Solidity+z3-4.6.0` takes almost 12s to compile the test (at least it doesn't hang forever), and `Solidity+z3-4.5.0` takes ~0.26s.
I'm still investigating...

**Comment by leonardoalt** [comment] 2018-03-04 11:04
This option is disabled when using incremental mode (which we do). The Z3 devs are looking into possible solutions.

**Comment by leonardoalt** [comment] 2018-03-04 13:50
The solution involves using the performance option mentioned before (https://github.com/ethereum/solidity/pull/3642) plus code changes in `z3` which are now in `z3`'s `master` branch. Unfortunately I guess this means we can't use version 4.6.0.

**Comment by leonardoalt** [comment] 2018-03-05 18:44
Can we close this issue?

**Comment by chriseth** [comment] 2018-03-05 19:01
Is it solved? Don't we have to wait for the 4.6 fix release?

**Comment by leonardoalt** [comment] 2018-03-12 19:40
The fix is in `z3`'s `master` branch.

**Comment by ekpyron** [comment] 2018-03-14 22:10
What do you think about adding a (generous) timeout for SMT solvers in general? In my experience SMT solvers can easily (virtually or actually) take forever and I think a solver error reporting a timeout might be much more helpful than checks that (seemingly or actually) run forever in such cases...

**Comment by chriseth** [comment] 2018-03-15 14:17
Yes, at some point we have to do that. Currently, the solver still takes virtually no time at all, but I fear that this might change :)

**Comment by leonardoalt** [comment] 2018-03-15 15:21
I also think it's a good idea. Ideally I think the user would also be able to override it.

Btw, what's required to close this issue?

**Comment by ekpyron** [comment] 2018-03-15 15:53
I can confirm at least that it doesn't hang with ``z3``'s ``master`` branch anymore, but it might make sense to keep this issue open at least until 4.6.1 is released? Otherwise users which use the current stable z3 version, i.e. 4.6.0, might reopen this issue or similar issues anyways - as long as it is open they might instead find this one.

**Comment by leonardoalt** [comment] 2018-03-15 16:16
That's true. The thing is, z3 doesn't seem to release a lot of versions. They asked in the issue there if we needed a tagged release, and I said no. I guess I can ask again :p

**Comment by axic** [comment] 2018-07-28 12:04
Timeout has been added in #4593.

**Closed as completed by axic** 2018-07-28 12:04 UTC
Labels: bug :bug:
