### ISSUE TITLE
Clarify implicit conversions between literals and bytesNN types.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3942] opened 2018-04-19 07:17 UTC
Extension of https://github.com/ethereum/solidity/issues/3786

The user should always be aware which side of the value is padded with zeros in the conversion. Conversion from hex literals (`0xff`), hex strings (`hex"ab"`) and strings (`"hello"') should be treated differently than conversion from decimal literals (`256`).

**Comment by ekpyron** [comment] 2018-05-09 15:38
In PR #4091, I disallow any conversions between literals (resp. ``RationalNumberTypes``) and ``bytesX``, if the sizes don't match. This is a side-effect of restricting conversions between integer and bytes types to require identical sizes.

This means that the following are valid:
  ``bytes1(0x1)``,   ``bytes1(0x12)``,  ``bytes2(0x123)``,  ``bytes2(0x1234)``, etc.

But these are invalid:
  ``bytes1(0x1234)``,  ``bytes1(0x123)``, ``bytes2(0x12)``, ``bytes2(0x0012)``, etc.

Instead you have to use:
  ``bytes1(uint8(0x1234))``, ``bytes2(uint16(0x12))``, ``bytes2(uint16(0x0012))``, etc.
resp.
 ``bytes2(bytes1(0x12))``,


I explicitly allow zero-initialization for all ``bytesX`` types, though, so ``bytesX(0)`` is still valid for all X (padding is not relevant in this case).

This could be further restricted to *only* allow conversions from zero and *always* to require to cast literals to sized integer types before conversion to bytes types.

So ``bytes1(0x12)`` would have to be replaced with ``bytes1(uint8(0x12))`` as well.

Any thoughts?

**Comment by chriseth** [comment] 2018-05-11 10:57
@ekpyron can we still make `bytes2(0x0012)` valid?

**Comment by ekpyron** [comment] 2018-05-11 11:53
@chriseth This may be difficult, since I think currently ``0x12`` and ``0x0012`` are not distinguishable in the code, but I can see what I can do.

Unfortunately, in the meantime I noticed that @meowingtwurtle had already started working on #3786 in PR #3899 without me realizing it, so #4091 is a duplicate of #3899.

Also, both #4091 and #3899 combine solving #3786 and this issue and I think it may be cleaner to do them in two separate steps.

So currently my plan is to adjust #4091, so that it does not change conversions between literals and bytes* types at all, but only changes conversions between integer types and bytes* type (as originally intended in #3786) and then this issue can be handled in a separate PR.

Do you agree that this is a good way to move forward?

**Comment by ekpyron** [comment] 2018-05-14 10:59
@chriseth One solution for still allowing ``bytes2(0x0012)`` would be to add a ``Literal const*`` member to ``RationalNumberType``. If the rational is directly parsed from a literal this member would point to that literal, whereas if it is the result of e.g. a binary operation it would be ``nullptr``. This way ``isExplicitlyConvertible`` could analyse the underlying literal in the case of ``bytes2(0x0012)`` and explicitly allow it (whereas ``bytes2(1*0x0012)`` would still be invalid). Not sure whether this is the most elegant solution, though.

**Comment by chriseth** [comment] 2018-05-14 18:59
@ekpyron I'm also not sure about literals. The best way would probably be to require the user to add a suffix to the literal `0x0012b` is `bytes2` and `0x0012` is integer, or use `hex"0012"` in the first place.

Perhaps it would be better to add a warning if a hex literal has leading zeros?

The failed address checksum warning suggestion would have to be changed in that case.

**Comment by chriseth** [comment] 2018-05-14 20:52
(hex literal in the previous comment refers to `0x0012`, not to `hex"0011"`. The latter should always be of bytes type.

**Comment by ekpyron** [comment] 2018-08-01 16:44
Current status:
Implicit conversions from any literal to any bytesNN types is allowed without warning or error, even though padding rules may not be clear (i.e. this Issue still needs to be fixed, only bytesNN to [u]intMM conversions were done in previous PRs, not literals).

To be discussed:
Which implicit conversions are allowed and how to specify the "intended" size, resp. type, resp. implicit convertability of a literal:
  - Should ``0x0012`` be implicitly convertible to ``bytes1`` only or to ``bytes2`` only or to both or to neither?
  - Do we want to introduce a suffix, s.t. ``0x0012b`` will be of type ``bytes2`` and ``0x0012`` will be an integer, that is implicitly convertible to ``bytes1`` only or not implicitly convertible to any ``bytesNN`` type?

**Comment by ekpyron** [comment] 2018-08-01 16:56
Also possible: Hex literals of the form ``0x0012`` are always integers (of the minimal size that the value fits in) and there is no suffix for bytes types, but only literals like ``hex"0012"`` are ``bytesNN`` (size determined by string length). So no implicit conversions from ``0x0012`` and similar to ``bytesNN`` at all.

Most radical would be to entirely decouple literals from integers in general, so the size *always* has to be specified, i.e. ``uint8 a = 1;`` is an error and you have to use ``uint8 a = uint8(1);``. I would actually consider that, but it may go too far.

**Comment by axic** [comment] 2018-08-01 18:05
I think the best approach is that the literal length and the `bytesNN` size must match. This gives an instant visibility of size. Then the user can up/downscale with explicit conversion.

**Comment by ekpyron** [comment] 2018-08-01 20:37
So ``bytes1(0x1)``, ``bytes1(0x01)``, ``bytes1(0x12)``, ``bytes2(0x0012)``, ``bytes2(0x123)``, ``bytes2(0x1234)`` are valid and ``bytes1(0x0023)``, ``bytes1(0x123);``, ``bytes2(0x1)``, ``bytes2(0x12345)`` are invalid?
We can argue about odd numbers of digits.
I'd be fine with that, if all agree.

We may consider an exception for ``bytesNN(0x0)``, since padding is irrelevant there.

**Comment by axic** [comment] 2018-08-01 21:09
> We can argue about odd numbers of digits.

I think odd numbers of digits is fine as long as it fits into the type of course.

> We may consider an exception for `bytesNN(0x0)`, since padding is irrelevant there.

That could be a good idea.

**Closed as completed** 2018-08-13 15:25 UTC
