### ISSUE TITLE
Allow concatenation of string constants

### ISSUE THREAD

**Issue by CodeSandwich** [ethereum/solidity#13462] opened 2022-08-31 09:56 UTC
## Abstract

It would be great to be able to concatenate string constants:
```solidity
string public constant FOO = "foo";
string public constant BAR = "bar";
string public constant FOOBAR = FOO BAR; // Illegal, but would be great
```

As of now one needs to explicitly write `FOOBAR = "foobar"`, which can be a source of bugs.

## Motivation

My use case for this feature is building an ERC-712 typehash of data containing structures. According to the standard if the type name of of the structures is this: `MyStruct(uint256 field1, uint256 field2)`, then the type name of the entire data needs to have the structure type name concatenated to itself: `MyData(MyStruct[] data)MyStruct(uint256 field1, uint256 field2)`. Hashes of both of these strings are needed when verifying the signature of the data. As of now it can be implemented only as
```solidity
string internal constant STRUCT_NAME = "MyStruct(uint256 field1, uint256 field2)";
bytes32 internal immutable structTypeHash = keccak256(STRUCT_NAME);
string internal constant DATA_NAME = "MyData(MyStruct[] data)MyStruct(uint256 field1, uint256 field2)";
bytes32 internal immutable dataTypeHash = keccak256(DATA_NAME);
```

It'd be very elegant and less bug prone if the type name of the data didn't need to repeat the type name of the structure and could simply concatenate it:

```solidity
string internal constant STRUCT_NAME = "MyStruct(uint256 field1, uint256 field2)";
bytes32 internal immutable structTypeHash = keccak256(STRUCT_NAME);
string internal constant DATA_NAME = "MyData(MyStruct[] data)" STRUCT_NAME; // would be great
bytes32 internal immutable dataTypeHash = keccak256(DATA_NAME);
```

There are probably other use cases which I'm not aware of.

## Specification

Currently Solidity allows concatenating string literals by writing one after another, e.g. `"foo" "bar"`. It'd be great if this syntax supported also constant names, e.g. `"foo" BAR`.

## Backwards Compatibility

There's no backwards compatibility issue.

**Comment by k06a** [comment] 2022-08-31 22:08
Related: https://github.com/ethereum/solidity/issues/13451

**Comment by CodeSandwich** [comment] 2022-09-01 07:42
This looks like a duplicate, sorry! I was looking for an existing issue, but I haven't found that one. Should we close this one and just copy this use case there?

**Comment by ekpyron** [comment] 2022-09-14 14:52
Closing this as a duplicate of https://github.com/ethereum/solidity/issues/13451, which I'm in turn closing as a special case of https://github.com/ethereum/solidity/issues/13318, as explained there.
Here, this would involve the use of ``string.concat`` together with compile-time constant expression evaluation.

**Closed as completed by ekpyron** 2022-09-14 14:52 UTC
Labels: language design :rage4:, nice to have
