### ISSUE TITLE
EVM calls have wrong jump direction markings in source map

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#5379] opened 2018-11-09 01:55 UTC
## Description

The Solidity compiler provides, as part of its source map, markings for whether a given jump instruction is a jump in, jump out, or neither.  These work for internal function calls, but do not interact well with EVM calls.  We may divide EVM calls into three types: (A) constructor calls; (B) calls to a method of a Solidity contract object or library; (C) calls to a method of an address object, such as `transfer` or `call`.  Currently, the Truffle debugger uses these markings to keep track of the current callstack depth, as well as to determine where to stop a "step out".

With types (A) and (C), both the call and the return appear to be unmarked.  (Since these are EVM calls, of course, it may not be *jump* instructions that would be marked, but it seems to me that in principle there's nothing preventing other sorts of instructions from being marked if appropriate.)  This seems slightly off, but is not in itself a problem.

The problem comes from calls of type (B).  With these, the call is not marked, but the return *is* marked as a jump out.  This means that, if we use these markings to keep track of our call depth (as the Truffle debugger currently does), then after returning from a call of type (B), our call depth counter has (incorrectly) decreased by 1.  Moreover, because of type (C), one cannot easily work around this by incrementing the call depth on each `CALL` or `DELEGATECALL` instruction, as that would cause the call depth counter to incorrectly *increase* by 1 after returning from a call of type (C), since calls of type (B) and (C) cannot readily be distinguished at the bytecode level.  I believe it may still be possible to work around this problem despite these issues, but it will be heavily hackish and not something we want to rely on.

What should happen instead is either one of two things:
1. EVM calls are never marked, either on the call or on the return; or,
2. EVM calls are always marked, both on the call and on the return.

I think solution (2) would be preferable (though it would probably require marking instructions that are not jumps -- I hope you're OK with that, I personally don't see any problem with it), but solution (1) would also be acceptable.

## Environment

- Compiler version: 0.4.25
- Framework/IDE (e.g. Truffle or Remix): Truffle
- EVM execution environment / backend / blockchain client: ganache-cli
- Operating system: Linux Mint 18.3 64-bit

## Steps to Reproduce

(Note: I didn't actually try it with the following Solidity code -- what follows is just a stripped-down version of things I did try it with.  I hope that's OK.)

```
pragma solidity ^0.4.25;

contract Outer {

  uint8 public x;

  function test() public
  {
    Innner inner = new Inner(107);
    x = inner.plusOne();
    address(inner).send(0);
  }
}

contract Inner {

  uint8 private y;

  constructor(uint8 n) public
  {
    y = n;
  }

  function plusOne() public view returns (uint8 incremented)
  {
    incremented = y + 1;
  }

  function() public payable
  {
  }
}

```

This code doesn't demonstrate that library calls have the same problem, of course, but in my testing, they do.

**Comment by chriseth** [comment] 2018-11-09 09:35
The reason we introduced in/out annotations is that you cannot see from a 'jump' instruction whether it is a jump to a subroutine or a return from a subroutine. For EVM calls, there is a clear distinction: call* goes in, and return/stop/revert goes out.

Could you provide an example annotation where a return is annotated with 'out'? I was not able to reproduce it and I also don't see a way for this to happen in the source code. Perhaps I just misunderstood the issue.

**Comment by haltman-at** [comment] 2018-11-09 20:01
Hi, sorry, yes, I think I didn't explain this properly.  I explained this in terms of the overall effect, rather than in terms of the actual markings.  It does not literally occur that a `RETURN` or `STOP` gets annotated as "out"; as you say, that is impossible.  I agree that there is no need to mark such instructions, as their direction is obvious.

Rather the problem is that, when exiting an EVM call (of a contract method -- again, this does not happen with address methods or constructor calls), one encounters an additional "out" marking *overall*.  This out marking is not on the `RETURN` instruction, because those are not marked, but rather it occurs on a `JUMP` instruction prior to the `RETURN` instruction; it appears to be, as best I can tell -- but take this with a grain of salt as I haven't looked too closely at this and you know the relevant code better than I do -- when the function returns to some sort of dispatcher, which then does the `RETURN`.

The reason that this is a problem is because this "out" marking is not balanced by a corresponding "in" marking; that is why I described the out marking as extra or additional.  That is to say, exiting involves an out-marked `JUMP`, but entering the function does not involve an in-marked jump.  And so anything relying on these markings becomes unbalanced after a call to a contract method.

So, when I talked about making EVM calls and returns "marked" or "unmarked", I didn't necessarily mean the `CALL` (or `DELEGATECALL` or `CREATE`) or `RETURN` (or `STOP`) instructions themselves, but rather the overall effect of the call or return -- that is to say, I was including any `JUMP` instructions that are part of how the call or return is effected.

As mentioned above, the ideal would be if either:
1. The overall effect of every call was +1 and the overall effect of every return was -1, or
2. The overall effect of every call and of every return was 0.

However, as I was thinking this over last night, and how you seem to have implemented things (as best I can discern) I realized that achieving either of these might be a bit tricky.  So, let me just say that the most important thing is that every call should be *balanced* -- the number of "in" markings encountered on the way in should equal the number of "out" markings encountered on the way out.  If we have that, that's something we can work with!  Which, as mentioned, could be accomplished by adding the missing "in" markings somehow.

Indeed I realized that it's probably impossible to eliminate those seemily-extra "out" markings, since they're on the `JUMP` that causes the function to return, and that's the same instruction whether the dispatcher afterwards decides that this is an internal return or an EVM return!  That's probably just not something you can change.  But perhaps you could alter how your "in" markings work?  You would know better than me, of course, but offhand that seems like it might be possible.

One way or another though, ultimately, "in" should be balanced with "out".  Well, or we could work with it if it were consistently *unbalanced*, but that seems even harder to accomplish, since you'd have to somehow *unbalance* address methods!  (You wouldn't have to unbalance constructor calls since those are readily distinguished, as they use `CREATE` rather than `CALL` or `DELEGATECALL`.)

I guess the absolute bare minimum we need is this: That the net change in depth (i.e., number of `i`s encountered minus number of `o`s encountered), from the beginning of an EVM call to the end -- including all auxiliary `JUMP`s that goes into effecting that EVM call and its return, since after all those are the only instructions that are so marked -- should, for all EVM calls other than constructor calls, be a constant.  (Again, ideally 0, but if we're talking about the bare minimum here...)  Again, as noted above, presently it's 0 for address methods but -1 for contract (and library) methods.

Sorry for the inclarity, hope that's clearer, thanks again!

**Comment by haltman-at** [comment] 2018-11-10 00:43
A note: We do now have a workaround for this, but, as might be expected, it won't work in all cases.  Storing a contract method in a function-type variable and then calling that function variable later would still screw things up, for instance.

**Comment by chriseth** [comment] 2018-11-13 09:44
Ok, now I understood! The current structure of a contract is roughly as follows:

```
contract entrypoint:
sig == f? f();
sig == g? g();

f: ... jump out
g: ... jump out
```

If `g` calls `f`, it has  a "jump in", while the "jump out" is part of `f`.

The dispatch routine currently does not have a "jump in", but probably it would make sense to make it symmetric.

**Comment by haltman-at** [comment] 2018-11-13 19:51
OK, yes, that would do it!  Glad to know it's as easy as that.  Thanks a bunch!  Should I close this now that you've made a separate issue for this?

Edit: Oh wow looks like you already have a fix ready (even if it won't be released for a while).  Wonderful, thanks!

**Comment by chriseth** [comment] 2018-11-13 23:46
Yes, I'll close it as you seem to be satisfied with the resolution :)

**Closed as completed by chriseth** 2018-11-13 23:46 UTC
