### ISSUE TITLE
Comparing function pointers may yield unpredictable results

### ISSUE THREAD

**Issue by yantao0527** [ethereum/solidity#15129] opened 2024-05-22 08:29 UTC
## Description

Comparing function pointers may yield unpredictable results due to potential differences in the address space layout of functions across program executions

## Environment

- Compiler version: 0.8.x
- Target EVM version (as per compiler settings): No restrictions
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: None
- Operating system: None

## Steps to Reproduce

```solidity
contract C {
    function f() internal {}
    function g() internal {}

    function test() public pure returns (bool) {
        return C.f == C.g;
    }
}
```

**Comment by r0qs** [comment] 2024-05-23 11:51
Hi, this is a duplicate of https://github.com/ethereum/solidity/issues/13969 and since Solidity version `0.8.24` the compiler issue a warning about it.

**Closed as not planned by r0qs** 2024-05-23 11:51 UTC
Labels: bug :bug:
