### ISSUE TITLE
ABIEncoderV2 should be enabled when returning a struct from function.

### ISSUE THREAD

**Issue by cakesoft-khushi** [ethereum/solidity#10061] opened 2020-10-17 07:51 UTC
# Description :
### When I try to return a struct from a function, I get the error as:
    Error: This type is only supported in ABIEncoderV2. Use "pragma experimental ABIEncoderV2;" to enable the feature.
     --> practice.sol:7:35:
      |
    7 |     function foo() public returns(user memory _user){
      |                                   ^^^^^^^^^^^^^^^^^

But if I enable ABIEncoderV2, I get the warning as:

    Warning: This is a pre-release compiler version, please do not use it in production.

Returning a structure makes it more accessible when you want to return all the data stored in it rather than returning every item separately especially when you want to return more data and it gives the error stack too deep.

# Steps to Reproduce :

    pragma solidity ^0.7.0;
    contract A{
        struct user{
	        uint role;
	        string name;
        }
        function foo() public returns(user memory _user){
            //code
        }
    }

# Environment :
* Compiler Version : ^0.7.0
* Operating System : Ubuntu
* EVM execution environment / backend / blockchain client : 
* Framework/IDE :

**Comment by cameel** [comment] 2020-10-17 14:20
See my response in https://github.com/ethereum/solidity/issues/10060#issuecomment-711016668. The situation here looks exactly the same.

**Comment by cameel** [comment] 2020-10-27 15:13
I'm going to close this because, as currently reported, this is the expected behavior. Please feel free to reopen if you have more input.

**Closed as completed by cameel** 2020-10-27 15:13 UTC
Labels: waiting for more input
