### ISSUE TITLE
IR bug syntaxTests/*/base_contract.sol

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#10946] opened 2021-02-10 19:35 UTC
```
contract B {
    function f() external {}
    function g() public {}
}
contract C is B {
    function h() public returns (bytes4 fs, bytes4 gs) {
        fs = B.f.selector;
        gs = B.g.selector;
        B.g();
    }
}
```

```
: Internal compiler error during compilation:
: /solidity/libsolidity/codegen/ir/IRGeneratorForStatements.cpp(1699): Throw in function virtual void solidity::frontend::IRGeneratorForStatements::endVisit(const solidity::frontend::MemberAccess&)
: Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
: std::exception::what: Invalid use of .selector: function ()
: [solidity::util::tag_comment*] = Invalid use of .selector: function ()
  
```

`solc --ir`

**Comment by axic** [comment] 2021-02-10 19:39
Possibly duplicate of #10891

**Comment by bshastry** [comment] 2021-02-11 14:12
Related to https://github.com/ethereum/solidity/issues/10891#issuecomment-775103029

**Comment by axic** [comment] 2021-04-26 22:58
Fixed by #11015.

**Closed as completed by axic** 2021-04-26 22:58 UTC
Labels: bug :bug:, should compile without error
