### ISSUE TITLE
Novice needs help..........

### ISSUE THREAD

**Issue by qq597353** [ethereum/solidity#4452] opened 2018-07-06 14:56 UTC
pragma solidity ^0.4.18;

contract MyContract {
    /* Constructor */
    function MyContract() public {

    }
}
The above code will be wrong, how to modify it?

The error information is as follows.
Defining constructors as functions with the same name as the contract is deprecated. Use "constructor(...) { ... }" instead.
function MyToken(
^ (Relevant source part starts here and spans across multiple lines).

**Comment by erak** [comment] 2018-07-06 15:12
@qq597353 You can fix this by using ``contract MyContract { constructor() public {} }``. 

Please consider consulting https://gitter.im/ethereum/solidity or the documentation (http://solidity.readthedocs.io/en/v0.4.24/) for further questions regarding contract development.

**Comment by erak** [comment] 2018-07-06 15:29
@qq597353 I will close this as a duplicate of https://github.com/ethereum/solidity/issues/4451.

**Closed as completed by erak** 2018-07-06 15:29 UTC
