### ISSUE TITLE
Yul: disallow switch statements with only a default case

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4285] opened 2018-06-12 23:48 UTC
It made sense having them before `if` was introduced. Since `if` is supported this doesn't make too much sense anymore and for the sake of simplifying code, this could make sense.

(From https://github.com/ethereum/solidity/pull/3464/commits/027620766b6f531d89c12497207fa08b0a3f99c2#r185976506)

Reason against this: transformation steps could map single-case switch statements into if statements and vice versa. This may be beneficial for code generators, which opt to not implement if statements or which have an optimised implementation for if statements.

-> make this into a warning

**Comment by chriseth** [comment] 2018-10-02 13:52
Is this a duplicate of https://github.com/ethereum/solidity/issues/4111 ?

**Comment by axic** [comment] 2018-10-02 14:10
I think #4111 is an optimiser step.

**Comment by axic** [comment] 2019-12-10 23:59
I'd like to bring this up again for discussion.

**Comment by ekpyron** [comment] 2020-01-06 12:08
I agree with disallowing ``switch`` with only a default case. In fact, I don't understand when and why that would ever have been useful, independently of the introduction of ``if``...

Maybe there is a separate second question, namely whether to allow switches with only a single non-default case? Those are the ones that can theoretically be replaced by ``if``s. But for those I'd say it's fine to keep allowing them.

**Comment by ekpyron** [comment] 2020-01-06 12:10
The only "use case" for switch with only a default case would be during development with a big fat "// TODO: implement cases"...

**Comment by axic** [comment] 2020-01-06 14:01
> Maybe there is a separate second question, namely whether to allow switches with only a single non-default case? Those are the ones that can theoretically be replaced by ifs. But for those I'd say it's fine to keep allowing them.

Maybe I would argue that we could make Yul more regular by not allowing multiple syntactical options for the same thing.

**Comment by leonardoalt** [comment] 2020-01-21 12:55
I think this should still be discussed in a call instead of during a design round.

**Comment by axic** [comment] 2020-01-21 13:06
@leonardoalt are you suggesting the dreaded "to discuss" label?

**Comment by leonardoalt** [comment] 2020-01-21 13:08
Yes. Was it ever decided whether we want to do this or not?

**Comment by axic** [comment] 2020-01-21 13:15
Oh its actually marked to discuss already :)

**Comment by chriseth** [comment] 2020-02-05 14:58
Discussion: This might be too inflexible for auto-generated code, but it would be a good check for human-written code. Because of that, we should make this a warning instead of an error.

**Comment by axic** [comment] 2020-02-05 15:04
Suggestion (long term goal):
1) Warn in user submitted code (e.g. assembly block)
2) Have a step which replaces all of them with a simple switch
3) Remove any special cases from the code generator (e.g. assume switch always have multiple cases and generate code accordingly)

This way we could potentially simplify the codegen phase and have a "canonical" version which doesn't have default-case-only-switch statements.

**Closed as completed** 2020-06-09 12:58 UTC
