### ISSUE TITLE
How to submit a PR (with Documentation fixes) - Solved

### ISSUE THREAD

**Issue by anannyenaik** [ethereum/solidity#13271] opened 2022-07-13 11:14 UTC
Hey there! I have fixed some grammatical errors in `assembly.rst`. If someone could guide me on how to make a PR there, that would be helpful. 

Thank you!

**How to submit the PR:**
TL;DR -- After forking off the develop branch, in your forked repo: make a new  branch and commit your changes there. Then, in your forked repo, merge the changes. Finally, make a PR to the main repo (which essentially merges your `develop` branch to the main `develop branch`. 

*Note: Fork off of the latest version of the `develop branch`*

**Comment by Darlington02** [comment] 2022-07-14 00:45
You've committed your changes to the fork right?

**Comment by anannyenaik** [comment] 2022-07-14 01:50
Yes, I have the changes committed in my forked repo.

**Comment by cameel** [comment] 2022-07-20 10:28
Hello @krakxn! To submit a fix you need to create a feature branch off `develop` in your fork (give it some meaningful name) make changes in it, commit them and push the branch to your fork. Then, on the github page for your repo, go to Pull Requests and select "New Pull Request". It will let you select the target branch (it should be `develop` from `ethereum/solidity`) and your branch and create the PR.

But overall, if you need help contributing, please drop in on the [#solidity-dev](https://app.element.io/#/room/#ethereum_solidity-dev:gitter.im) channel. We can help you with git. This is a bug tracker so not the best place to ask questions like that. You can still comment here but I'm closing the issue since this is not a bug report or a feature request.

**Closed as not planned by cameel** 2022-07-20 10:28 UTC
Labels: documentation :book:

**Comment by anannyenaik** [comment] 2022-07-21 08:02
@cameel I see! So, for minor fixes like these I just make a PR directly instead of raising an issue?

**Also, about the fork:** after forking off the `develop` branch - I make a new (feature) branch and commit my changes there. Then, I push that branch to the forked repo. Finally, a PR here. Is this correct?

Sorry and thank you very much!

**Comment by cameel** [comment] 2022-07-21 15:58
> So, for minor fixes like these I just make a PR directly instead of raising an issue?

Yeah, if you intend to fix it right away, a separate issue is not necessary. But it helps if you're unsure how to fix it or if you just prefer to leave it up to someone else.

> **Also, about the fork:** after forking off the `develop` branch - I make a new (feature) branch and commit my changes there. Then, I push that branch to the forked repo. Finally, a PR here. Is this correct?

Yes, exactly.
