### ISSUE TITLE
(2000000000000*(10**18)/198602694960947175655554/10500000)*94231285718967064346338*3 RETURNED 0

### ISSUE THREAD

**Issue by pengchew** [ethereum/solidity#12279] opened 2021-11-13 16:50 UTC
omg this bug make the contract totally broken and unusable, how can such a simple calculation cannot be done on multi-billion dollar solidity program???

(2000000000000*(10**18)/198602694960947175655554/10500000)* 94231285718967064346338* 3

= 4.8802765837160098688270615812781e+7 (in windows calculator)

```
contract BUGS {
    uint256 public a; 
    uint256 public b; 
    uint256 public c; 
    uint256 public d; 
    uint256 public e; 
    uint256 public f; 
    
    
    constructor(){
        b=2000000000000*(10**18);
        c=198602694960947175655554;
        d=10500000;
        e=94231285718967064346338;
        f=3;
        
        a=(b/c/d)*e*f;
    }
}
```

a will return 0, but why???

found it on mintamount() at https://github.com/DurianFi/bsc_contract/blob/main/durianfi.sol

**Comment by cameel** [comment] 2021-11-13 19:09
You are performing calculations within an integer type so the intermediate results get rounded down to the nearest integer. `b / c / d` is ~0.959 so it gets rounded to 0. See the documentation about [division](https://docs.soliditylang.org/en/latest/types.html#division) in Solidity.

Please note that the same calculation done on [literals](https://docs.soliditylang.org/en/latest/types.html#rational-and-integer-literals) (i.e. `2000000000000 * 10**18 / 198602694960947175655554 / 10500000 * 94231285718967064346338 * 3`) would not truncate the intermediate results because operations on literals are performed in unlimited precision. You would not be able to assign the result to `a` without removing the fractional part first though because it's an integer variable.

If you want to perform operations on fractional numbers, please try using one of the fixed-point arithmetic libraries like [prb-math](https://github.com/hifi-finance/prb-math).

I'm closing this since this is the expected behavior and not a bug.

**Closed as completed by cameel** 2021-11-13 19:09 UTC
