### ISSUE TITLE
MacOS Distributable Binary?

### ISSUE THREAD

**Issue by prestonvanloon** [ethereum/solidity#4942] opened 2018-09-11 01:33 UTC
## Abstract

A distributable binary uploaded as part of the release set of files.

## Motivation

I want to download a solc binary for mac without having to build it or have dynamic libraries installed. This exists for linux and I believe also exists for Windows. 

## Specification

1) Create way to generate a distributable binary for Mac. (If there is already a way, then please create the documentation).
1) Distributable means download this file only and not need to install other deps.
1) Upload the distributable binary as part of the releases https://github.com/ethereum/solidity/releases

## Backwards Compatibility

N/A

-- 

Note: Currently we only have binaries that seem to require libz3.

**Comment by chriseth** [comment] 2018-09-11 07:27
We currently do not have the capacity to properly support macos. We are buliding for macos via CircleCI - if you have the required knowledge, could you check if this [binary](https://35078-40892817-gh.circle-artifacts.com/0/solc) binary would be sufficient for you? If not, would you like to propose changes to our build system? Thanks!

**Comment by prestonvanloon** [comment] 2018-09-12 01:07
This might be a dup of #3168

**Comment by prestonvanloon** [comment] 2018-09-12 01:38
@chriseth No, that binary appears to be built in the same manner that I tried. Here's a failure: https://travis-ci.org/prysmaticlabs/prysm/jobs/427477019

The specific failure is 
```
dyld: Library not loaded: /usr/local/opt/z3/lib/libz3.dylib
  Referenced from: /private/var/tmp/_bazel_travis/51eb962159b83b5e6d1437bd394e6ce1/sandbox/darwin-sandbox/2374/execroot/__main__/external/solc_sdk/solidity_compiler/solc
  Reason: image not found
external/solc_sdk/solidity_compiler/sol2go.sh: line 21: 13225 Abort trap: 6           $SOLCOMPILER --overwrite --bin --abi -o $OUTDIR $1
```

**Comment by chriseth** [comment] 2018-09-12 17:25
It tries to load a library that is optional during the build process. If you perform a source build and do not have z3 available, it should create a binary that does not require z3.

**Comment by axic** [comment] 2018-11-15 12:05
@prestonvanloon I think it is a duplicate of #3168. Can you please comment on it if any of the details from here are missing?

**Closed as completed by axic** 2018-11-15 12:05 UTC
Labels: build system :building_construction:, annoys users :cry:

**Comment by prestonvanloon** [comment] 2018-11-15 16:29
Yep, looks like a duplicate to me. Thanks! @axic 

I’ll follow that issue now
