### ISSUE TITLE
Overloaded Functions Cannot Be Assigned To Function Type Variables

### ISSUE THREAD

**Issue by toongeorges** [ethereum/solidity#13827] opened 2022-12-21 22:20 UTC
## Description

Functions that are overloaded cannot be assigned to a function type variable.

## Environment

- Compiler version: 0.8.17
- Target EVM version (as per compiler settings): Remix VM (London)
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu 21.10

## Steps to Reproduce

The 2 lines in the code example below that assign a value to an external function type variable and an internal function type variable cause a compilation error.  The compiler should have enough information (namely the parameter list from the function types) to know which of the overloaded functions to select.

If the functions with 3 arguments are removed so that `sum` and `product` are not overloaded anymore, the compilation errors go away.

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

contract Overloading {
    function sum(uint a, uint b) external pure returns (uint) {
        return a + b;
    }

    function sum(uint a, uint b, uint c) external pure returns (uint) {
        return a + b + c;
    }
}

contract SelectOverloadedFunction {
    Overloading private overloading;

    function(uint, uint) external pure returns (uint) extTwoArguments;
    function(uint, uint) internal pure returns (uint) intTwoArguments;

    constructor() {
        overloading = new Overloading();
        //causes compilation error: Member "sum" not unique after argument-dependent lookup in contract Overloading
        extTwoArguments = overloading.sum;
        //causes compilation error: No matching declaration found after variable lookup
        intTwoArguments = product;
    }

    function product(uint a, uint b) internal pure returns (uint) {
        return a * b;
    }

    function product(uint a, uint b, uint c) internal pure returns (uint) {
        return a * b * c;
    }

    function calculateExternal(uint a, uint b) external view returns (uint) {
        return extTwoArguments(a, b);
    }

    function calculateInternal(uint a, uint b) external view returns (uint) {
        return intTwoArguments(a, b);
    }
}
```

**Comment by cameel** [comment] 2023-01-27 22:03
Duplicate of #12296 and #3556. This is a long-standing problem with our syntax and the main issue tracking it is #3556. If you have any suggestions about your preferred solution, please post it there.

**Closed as not planned by cameel** 2023-01-27 22:03 UTC
