### ISSUE TITLE
Q: Import Callback

### ISSUE THREAD

**Issue by lmittmann** [ethereum/solidity#13748] opened 2022-11-28 09:01 UTC
Question:
I am trying to register an import callback function for the JS/WASM release ([v0.8.17](https://github.com/ethereum/solidity/releases/download/v0.8.17/soljson.js)). I haven't figured out how to do it yet and there seems to be no documentation on it.

**Comment by leonardoalt** [comment] 2022-11-28 09:21
You can see an example here: https://github.com/ethereum/solc-js#example-usage-with-import-callback

**Comment by lmittmann** [comment] 2022-11-28 09:51
Hi @leonardoalt, I saw that example, but I am not using plain JS. Basically I am trying to do what solc-js does in [v8go](https://github.com/rogchap/v8go).

So far I successfully connected the "solidity_compile" function:
```
Module.cwrap("solidity_compile", "string", ["string", "number", "number"])
```

And registered my custom callback function:
```
Module.addFunction(findImports, "viiiii")
```
The problem is, that my `findImports` function is never called.

**Comment by nikola-matic** [comment] 2022-11-29 18:36
Closing issue as it's not relevant to Solidity compiler development.
@lmittmann please consider asking questions in the [Solidity forum](https://forum.soliditylang.org/) or the [Ethereum stackexchange](https://ethereum.stackexchange.com/).

**Closed as completed by nikola-matic** 2022-11-29 18:36 UTC

**Comment by lmittmann** [comment] 2022-11-29 19:49
Hi @nikola-matic, my question is about the workings of undocumented parts of the Emscripten release. It would be very helpful to get some info on how it is working.

**Comment by nikola-matic** [comment] 2022-11-29 21:07
> Hi @nikola-matic, my question is about the workings of undocumented parts of the Emscripten release. It would be very helpful to get some info on how it is working.

Keep in mind that there are 1000+ open issues, and we're in house cleaning mode at the moment (most issues are likely to be closed soon), so at this point I'm only looking at how the issue is formulated. If it's a question, it gets closed with a redirect to the forum or stackexchange, which is better suited for questions.
On the other hand, if you think that a feature (or a portion of a feature) is not documented well, or even at all, feel free to open an issue, but then be clear in the issue title (there's even a `Documentation issue` template when you open a new issue) and the description that it is in fact an issue, and not just a question regarding feature specifics.

**Comment by ekpyron** [comment] 2022-11-30 09:40
Also note that usage of the emscripten builds without the solc-js wrapper is intentionally undocumented, since it's unsupported - and also not guaranteed to be stable, so if you want to bypass solc-js, you're basically on your own - if you can load solc-js into v8go, I'd strongly recommend doing that instead. If you still want to use soljson.js directly, the best reference would be the sources of the solc-js wrapper itself https://github.com/ethereum/solc-js (that's not that much code, so it should be feasible to read and find the relevant parts).
