### ISSUE TITLE
Generics/templates needed for code reusability.

### ISSUE THREAD

**Issue by bogomazov** [ethereum/solidity#3390] opened 2018-01-13 12:11 UTC
I need to implement iterable mapping, however, I always have different value types within different contracts.

**Comment by federicobond** [comment] 2018-01-14 02:32
Hi @bogomazov! This is a duplicate of #869. Please follow the discussion there.

**Comment by axic** [comment] 2018-01-24 02:51
Closing this now.

**Closed as completed by axic** 2018-01-24 02:51 UTC
