### ISSUE TITLE
Yul: return variable scoping

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2387] opened 2017-06-13 19:49 UTC
```
{
  let x:u256 := 1:u256
  function f() -> x:u256
  {
    x := 42:u256
  }
  x := f()
}
```

This fails with:
```
scope.jl:3:3: Error: Variable name x already taken in this scope.
  function f() -> x:u256
  ^
```

I think the return values are in the scope of the function body and therefore should be allowed.

**Comment by chriseth** [comment] 2017-06-13 19:55
Yes, and this is by design. We might lift the shadowing rules a bit, but you could also use the following code:

```
{
  function f() -> x:u256
  {
    x := 42:u256
  }
  {
    let x:u256 := 1:u256
    x := f()
  }
}
```

**Comment by chriseth** [comment] 2018-10-15 17:46
I'm closing this, this is just an effect of the strict shadowing rules.

**Closed as completed by chriseth** 2018-10-15 17:46 UTC
