### ISSUE TITLE
Different JSON ABI output between storage & memory struct function parameters

### ISSUE THREAD

**Issue by e-r-w** [ethereum/solidity#6147] opened 2019-03-01 02:51 UTC
## Description

Solidity ABI output produces different results for structs that have `memory` and `storage` location. This causes problems in code libraries interpreting the ABI (namely ethers-js). Structs specified in `memory` appear to have their type encoded as `tuple`s as expected, but if specified as storage, the type is changed  to the name of the struct (see example below)

## Environment

- Compiler version: 0.5.0
- Target EVM version (as per compiler settings): 0.5.0
- Framework/IDE (e.g. Truffle or Remix): n/a
- EVM execution environment / backend / blockchain client: n/a
- Operating system: macOS 10.13.6

## Steps to Reproduce

Given a library contract:

```
pragma solidity 0.5.0;
pragma experimental ABIEncoderV2;

library Foo {
    struct Bar {
        string baz;
    }

    function getBaz(Bar memory bar) public view returns (string memory) {
        return bar.baz;
    }
}
```

`solc --abi Foo.sol` produces:

```json
[
  {
    "constant": true,
    "inputs": [
      {
        "components": [{ "name": "baz", "type": "string" }],
        "name": "bar",
        "type": "tuple"
      }
    ],
    "name": "getBaz",
    "outputs": [{ "name": "", "type": "string" }],
    "payable": false,
    "stateMutability": "view",
    "type": "function"
  }
]
```

However when we change `getBaz(Bar memory bar)` to `getBaz(Bar storage bar)`, the output changes to:

```json
[
  {
    "constant": true,
    "inputs": [{ "name": "bar", "type": "Foo.Bar storage" }],
    "name": "getBaz",
    "outputs": [{ "name": "", "type": "string" }],
    "payable": false,
    "stateMutability": "view",
    "type": "function"
  }
]
```

Where the function parameter type is no longer described as a `tuple` but rather a `Foo.Bar storage`. I'm not entirely sure but this doesn't seem like the intended behaviour?

Thanks!

**Comment by axic** [comment] 2019-03-01 11:05
I think `getBaz(Bar storage bar)` shouldn't be allowed in contracts, only in libraries. This is the real bug here.

The point of this feature is to avoid copying to memory, but allowing helpers in libraries to be written over storage references. It is not possible to ABI decode this through external interaction with the contract.

**Comment by e-r-w** [comment] 2019-03-04 00:09
> I think getBaz(Bar storage bar) shouldn't be allowed in contracts, only in libraries. This is the real bug here.

While I can agree that storage arguments shouldn't be allowed in contracts, this behaviour will still cause bugs in client libraries interpreting the ABI of solidity libraries, for example:

```js
// inside of some javascript library that deals with solidity contracts
function parseAbi(abiJson) {
  // ...
  let type = '';
  switch(input.type) { // where input.type = 'Foo.Bar storage'
	case 'string':
	  type = Enum.StringType;
    case 'uint':
      type = Enum.UnsignedInt;
    // ... other known solidity types/tuples ...
    default:
      throw new Error('Do not understand this type:' + input.type);
    /* an error is thrown here because the client library obviously 
     doesn't know anything about our solidity library Foo types */
  }
}

```

If that behaviour is intended, then I'd file a bug with the client library to perhaps handle storage arguments being output like it currently does. Otherwise it sounds like the solidity compiler should output `tuple` types for storage arguments, although I've no idea what sort of knock-on effects that would have to the broader ecosystem?

**Comment by chriseth** [comment] 2019-03-04 10:29
I think this is a duplicate of https://github.com/ethereum/solidity/issues/3409

**Comment by chriseth** [comment] 2019-03-13 14:34
Closing as the duplicate is fixed now.

**Closed as completed by chriseth** 2019-03-13 14:34 UTC
Labels: bug :bug:
