### ISSUE TITLE
Segfault with `solc --error-recovery`

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#7787] opened 2019-11-26 15:01 UTC
## Description

Calling `solc --error-recovery` will segfault for a lot of contracts, because there are places in which we not always check for `nulllptr`. For example in `CompilerStack::analyze()` (`source->ast`) or `Types::transformParametersToExterna()` (`type`).

One could run `valgrind solc --error-recovery [input-file]` to find and fix all the places where an additional check is needed.

## Environment

- Compiler version:
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

Can be reproduced with various contracts in our syntax tests e.g.

`solc --error-recovery test/libsolidity/syntaxTests/parsing/return_var.sol`

**Comment by axic** [comment] 2020-07-14 12:20
I though this could be a duplicate of #9404, but even after it, this crashes.

**Comment by axic** [comment] 2020-10-30 21:51
While I didn't encounter crashes, there are plenty of exceptions.
```
$ solc/solc --error-recovery ../test/libsolidity/syntaxTests/parsing/declaring_fixed_and_ufixed_variables.sol
Unimplemented feature:
/Users/alex/Projects/solidity/libsolidity/codegen/CompilerUtils.cpp(766): Throw in function void solidity::frontend::CompilerUtils::convertType(const solidity::frontend::Type &, const solidity::frontend::Type &, bool, bool, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::UnimplementedFeatureError>
std::exception::what: Not yet implemented - FixedPointType.
[solidity::util::tag_comment*] = Not yet implemented - FixedPointType.

$ solc/solc --error-recovery ../test/libsolidity/syntaxTests/parsing/import_complex.sol
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/interface/CompilerStack.cpp(1125): Throw in function auto solidity::frontend::CompilerStack::resolveImports()::(anonymous class)::operator()(const solidity::frontend::CompilerStack::Source *) const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 

$ solc/solc --error-recovery ../test/libsolidity/syntaxTests/parsing/import_simple.sol
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/interface/CompilerStack.cpp(1125): Throw in function auto solidity::frontend::CompilerStack::resolveImports()::(anonymous class)::operator()(const solidity::frontend::CompilerStack::Source *) const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 

$ solc/solc --error-recovery ../test/libsolidity/syntaxTests/parsing/max_depth_reached_4.sol
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/parsing/Parser.cpp(127): Throw in function ASTPointer<solidity::frontend::SourceUnit> solidity::frontend::Parser::parse(const shared_ptr<solidity::langutil::Scanner> &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 

$ solc/solc --error-recovery ../test/libsolidity/syntaxTests/parsing/multiple_modifier_arg_trailing_comma.sol
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/ast/AST.h(820): Throw in function solidity::frontend::FunctionDefinition::FunctionDefinition(int64_t, const solidity::frontend::ASTNode::SourceLocation &, const ASTPointer<solidity::frontend::ASTString> &, solidity::frontend::Visibility, solidity::frontend::StateMutability, bool, solidity::langutil::Token, bool, const ASTPointer<solidity::frontend::OverrideSpecifier> &, const ASTPointer<solidity::frontend::StructuredDocumentation> &, const ASTPointer<solidity::frontend::ParameterList> &, std::vector<ASTPointer<ModifierInvocation> >, const ASTPointer<solidity::frontend::ParameterList> &, const ASTPointer<solidity::frontend::Block> &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 

$ solc/solc --error-recovery ../test/libsolidity/syntaxTests/parsing/single_modifier_arg_trailing_comma.sol
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/ast/AST.h(820): Throw in function solidity::frontend::FunctionDefinition::FunctionDefinition(int64_t, const solidity::frontend::ASTNode::SourceLocation &, const ASTPointer<solidity::frontend::ASTString> &, solidity::frontend::Visibility, solidity::frontend::StateMutability, bool, solidity::langutil::Token, bool, const ASTPointer<solidity::frontend::OverrideSpecifier> &, const ASTPointer<solidity::frontend::StructuredDocumentation> &, const ASTPointer<solidity::frontend::ParameterList> &, std::vector<ASTPointer<ModifierInvocation> >, const ASTPointer<solidity::frontend::ParameterList> &, const ASTPointer<solidity::frontend::Block> &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 

$ solc/solc --error-recovery ../test/libsolidity/syntaxTests/parsing/pragma_illegal.sol
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/analysis/SyntaxChecker.cpp(81): Throw in function virtual bool solidity::frontend::SyntaxChecker::visit(const solidity::frontend::PragmaDirective &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

**Comment by cameel** [comment] 2020-10-31 00:18
> ```
> $ solc/solc --error-recovery ../test/libsolidity/syntaxTests/parsing/declaring_fixed_and_ufixed_variables.sol
> Unimplemented feature:
> /Users/alex/Projects/solidity/libsolidity/codegen/CompilerUtils.cpp(766): Throw in function void solidity::frontend::CompilerUtils::convertType(const solidity::frontend::Type &, const solidity::frontend::Type &, bool, bool, bool)
> Dynamic exception type: boost::wrapexcept<solidity::langutil::UnimplementedFeatureError>
> std::exception::what: Not yet implemented - FixedPointType.
> [solidity::util::tag_comment*] = Not yet implemented - FixedPointType.
> ```

It causes an ICE even without the `--error-recovery` option.

> ```
> $ solc/solc --error-recovery ../test/libsolidity/syntaxTests/parsing/import_complex.sol
> Internal compiler error during compilation:
> /Users/alex/Projects/solidity/libsolidity/interface/CompilerStack.cpp(1125): Throw in function auto solidity::frontend::CompilerStack::resolveImports()::(anonymous class)::operator()(const solidity::frontend::CompilerStack::Source *) const
> Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
> std::exception::what: 
> [solidity::util::tag_comment*] = 
> 
> $ solc/solc --error-recovery ../test/libsolidity/syntaxTests/parsing/import_simple.sol
> Internal compiler error during compilation:
> /Users/alex/Projects/solidity/libsolidity/interface/CompilerStack.cpp(1125): Throw in function auto solidity::frontend::CompilerStack::resolveImports()::(anonymous class)::operator()(const solidity::frontend::CompilerStack::Source *) const
> Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
> std::exception::what: 
> [solidity::util::tag_comment*] = 
> 
> $ solc/solc --error-recovery ../test/libsolidity/syntaxTests/parsing/max_depth_reached_4.sol
> Internal compiler error during compilation:
> /Users/alex/Projects/solidity/libsolidity/parsing/Parser.cpp(127): Throw in function ASTPointer<solidity::frontend::SourceUnit> solidity::frontend::Parser::parse(const shared_ptr<solidity::langutil::Scanner> &)
> Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
> std::exception::what: 
> [solidity::util::tag_comment*] = 
> ```

These three are legit. ICE since 0.5.11 (0.5.14 was in develop at the time of this report). No ICE only on 0.5.10 which introduced the `--error-recovery` option. Not using `--error-recovery` makes the ICE go away in all versions I checked.

> ```
> $ solc/solc --error-recovery ../test/libsolidity/syntaxTests/parsing/multiple_modifier_arg_trailing_comma.sol
> Internal compiler error during compilation:
> /Users/alex/Projects/solidity/libsolidity/ast/AST.h(820): Throw in function solidity::frontend::FunctionDefinition::FunctionDefinition(int64_t, const solidity::frontend::ASTNode::SourceLocation &, const ASTPointer<solidity::frontend::ASTString> &, solidity::frontend::Visibility, solidity::frontend::StateMutability, bool, solidity::langutil::Token, bool, const ASTPointer<solidity::frontend::OverrideSpecifier> &, const ASTPointer<solidity::frontend::StructuredDocumentation> &, const ASTPointer<solidity::frontend::ParameterList> &, std::vector<ASTPointer<ModifierInvocation> >, const ASTPointer<solidity::frontend::ParameterList> &, const ASTPointer<solidity::frontend::Block> &)
> Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
> std::exception::what: 
> [solidity::util::tag_comment*] = 
>
> $ solc/solc --error-recovery ../test/libsolidity/syntaxTests/parsing/single_modifier_arg_trailing_comma.sol
> Internal compiler error during compilation:
> /Users/alex/Projects/solidity/libsolidity/ast/AST.h(820): Throw in function solidity::frontend::FunctionDefinition::FunctionDefinition(int64_t, const solidity::frontend::ASTNode::SourceLocation &, const ASTPointer<solidity::frontend::ASTString> &, solidity::frontend::Visibility, solidity::frontend::StateMutability, bool, solidity::langutil::Token, bool, const ASTPointer<solidity::frontend::OverrideSpecifier> &, const ASTPointer<solidity::frontend::StructuredDocumentation> &, const ASTPointer<solidity::frontend::ParameterList> &, std::vector<ASTPointer<ModifierInvocation> >, const ASTPointer<solidity::frontend::ParameterList> &, const ASTPointer<solidity::frontend::Block> &)
> Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
> std::exception::what: 
> [solidity::util::tag_comment*] = 
> ```

These two actually crash the compiler between 0.5.11 and 0.5.17 (segmentation fault). On 0.6.0 and 0.7.0 they recover and report compiler errors as expected. Since 0.7.1 they cause an ICE.

> ```
> $ solc/solc --error-recovery ../test/libsolidity/syntaxTests/parsing/pragma_illegal.sol
> Internal compiler error during compilation:
> /Users/alex/Projects/solidity/libsolidity/analysis/SyntaxChecker.cpp(81): Throw in function virtual bool solidity::frontend::SyntaxChecker::visit(const solidity::frontend::PragmaDirective &)
> Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
> std::exception::what: 
> [solidity::util::tag_comment*] = 
> ```

This one is legit too. Works on 0.5.10. ICE since 0.5.11.

**Comment by chriseth** [comment] 2020-11-02 09:30
Maybe we could just remove that feature again...

**Comment by axic** [comment] 2021-03-26 00:47
Isn't `--error-recovery` very useful for the LSP, @chriseth @christianparpart ?

**Comment by chriseth** [comment] 2021-03-26 11:05
It is useful, but I very much doubt that we can get it to work even remotely reliable.

**Comment by christianparpart** [comment] 2021-04-16 09:51
> Isn't `--error-recovery` very useful for the LSP, @chriseth @christianparpart ?

maybe not the way it works right now (I didn't invest into this much yet). Before I attempt to touch this, I want to make the lower hanging fruits workable.

> It is useful, but I very much doubt that we can get it to work even remotely reliable.

@chriseth I don't even think it (error-recovery) has to. In the context of code completion, what the user is interested in (I hope) is getting a completion when typing `.` on scoped objects.  But I think we can say more about that subject when we've tried to evaluate that (later).

**Comment by nikola-matic** [comment] 2023-11-30 08:49
Fixed by removing experimental `--error-recovery` in https://github.com/ethereum/solidity/issues/14395 and https://github.com/ethereum/solidity/pull/14479.

**Closed as completed by nikola-matic** 2023-11-30 08:49 UTC
Labels: bug :bug:, should report better error
