### ISSUE TITLE
Raise useful error message when using a dynamic type as a key in a mapping

### ISSUE THREAD

**Issue by bortzmeyer** [ethereum/solidity#633] opened 2016-06-06 15:23 UTC
```
% solc multi-valued-mappings.sol   
Internal compiler error during compilation:
/build/cpp-ethereum-F1MTmh/cpp-ethereum-1.2.5~xenial/solidity/libsolidity/codegen/ExpressionCompiler.cpp(102): Throw in function void dev::solidity::ExpressionCompiler::appendStateVariableAccessor(const dev::solidity::VariableDeclaration&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: std::exception
[dev::tag_comment*] = Accessors for mapping with dynamically-sized keys not yet implemented.

% solc --version
solc, the solidity compiler commandline interface
Version: 0.3.3-0/RelWithDebInfo-Linux/g++/Interpreter
```

The source code is attached.
[multi-valued-mappings.txt](https://github.com/ethereum/solidity/files/300712/multi-valued-mappings.txt)

**Comment by bortzmeyer** [comment] 2016-06-06 15:26
Removing "public" from the variable "data" allow the program to be compiled. But I would prefer a clear error message than an internal error.

**Comment by axic** [comment] 2016-08-02 21:19
@bortzmeyer the error message is there also:
`[dev::tag_comment*] = Accessors for mapping with dynamically-sized keys not yet implemented.`

**Comment by unipaul** [comment] 2016-11-16 11:42
@chriseth @bortzmeyer  Accessors for dynamic keys would really be handy. With that I could make my mapping public and thus displayable in the ethereum wallet. In this case I wouldn't need a webpage, web3 etc for my dApp.
When is "soon"? ;)

**Comment by axic** [comment] 2017-02-02 23:59
Duplicate of #498.

**Comment by Pipeliner** [comment] 2018-02-21 23:26
@axic I guess @bortzmeyer meant that it was not immediately obvious from the error message that removing `public` would work. A more friendly message would probably be very helpful here.

**Comment by axic** [comment] 2018-02-21 23:31
Actually it would be nice to raise this issue in the type checker so a proper error message can be displayed as opposed to an assertion.

**Closed as completed** 2018-08-16 13:56 UTC
Labels: bug :bug:
