### ISSUE TITLE
Wrong version for the 0.8.19 binary

### ISSUE THREAD

**Issue by istankovic** [ethereum/solidity#14075] opened 2023-03-28 09:21 UTC
Running `solc --version` obtained via https://github.com/ethereum/solidity/releases/download/v0.8.19/solc-static-linux
produces

```
solc, the solidity compiler commandline interface
Version: 0.8.18-ci.2022.12.9+commit.a9fe05e8.Linux.g++
```

**Comment by ekpyron** [comment] 2023-03-28 10:24
I'm not sure what precisely you were running there, but https://github.com/ethereum/solidity/releases/download/v0.8.19/solc-static-linux is the proper 0.8.19 release compiler
```
$ ./solc-static-linux --version
solc, the solidity compiler commandline interface
Version: 0.8.19+commit.7dd6d404.Linux.g++
```

I guess you must have run a compiler other than the downloaded one by mistake? Please, double-check!

Since this isn't reproducible, I'm closing the issue for now, but please reopen if you can confirm that this is actually the case.

**Closed as completed by ekpyron** 2023-03-28 10:24 UTC

**Comment by istankovic** [comment] 2023-03-28 11:54
Ok, I just checked again and the binary at https://github.com/ethereum/solidity/releases/download/v0.8.19/solc-static-linux is fine. I probably ran an older version I had lying around, sorry for the noise.
