### ISSUE TITLE
Documented explanation of gas costs and what is effective practice for gas usage

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#395] opened 2016-02-12 20:57 UTC
There's all sorts of weird things in Solidity that don't seem intuitive. Things like why a large uint is going to be more efficient gas wise than a small uint unless tightly packed into a struct. I think that much of the community could benefit from these things being well explained and for certain "best practices" to be made available in the documentation.

**Comment by sussegaduss** [comment] 2016-08-30 14:50
I am also struggling with all kinds of gas problems. I have many doubts about gas comsumption, how many parameters a function can have, what is the size in kbytes that a contract can have.. that kind of stuff..

**Comment by VoR0220** [comment] 2016-08-30 14:55
I wouldn't worry about kbytes.

**Comment by axic** [comment] 2016-08-31 00:47
@VoR0220:

Is this a duplicate of #509 ?

If not, in the current state this is a bit vague. Can you collect some examples you would like to have documented?

**Comment by VoR0220** [comment] 2016-08-31 00:50
That is tied in but I would say this is the bigger picture. Moreso documentation of simple patterns and what their base gas cost is, but probably would be better to show that via the opcodes, and then move onto simple operations (assigning a uint, state storage of a tightly packed cost, when or when not is it worth it).

**Comment by axic** [comment] 2016-08-31 01:12
I think it would be better to either have a list of patterns/quirks to be documented in this issue, or to open individual issues with those.

Someone then can easily pick up documenting them.

**Comment by VoR0220** [comment] 2016-08-31 03:06
great idea. Lets start with tight packing with structs and state variables.

**Comment by NunoFilipeSantos** [comment] 2022-10-06 13:25
Hi! 👋 This issue is stale, and for that reason we're closing it.
Feel free to reopen it or to [contribute with a PR](https://docs.soliditylang.org/en/latest/contributing.html#workflow-for-pull-requests).

**Closed as completed by NunoFilipeSantos** 2022-10-06 13:25 UTC
Labels: documentation :book:
