### ISSUE TITLE
Unable to compile sources on Windows  10 when sources have paths with backslashes

### ISSUE THREAD

**Issue by daniyarchambylov** [ethereum/solidity#6608] opened 2019-04-28 08:09 UTC
I'm passing input data to `solc.compile` where source paths have backslashes, because that's what `path.resolve` produces on Windows OS, but I get error. But when I pass sources with forward slashes as in Unix style sources compiled normally.

**Working example**
```javascript
const solc = require('solc');
const input = '{"language":"Solidity","sources":{"C:/MetaCoin/contracts/MetaCoin.sol":{"content":"pragma solidity >=0.4.25 <0.6.0;\\n\\nimport \\"./ConvertLib.sol\\";\\n\\n// This is just a simple example of a coin-like contract.\\n// It is not standards compatible and cannot be expec
ted to talk to other\\n// coin/token contracts. If you want to create a standards-compliant\\n// token, see: https://github.com/ConsenSys/Tokens. Cheers!\\n\\ncontract MetaCoin {\\n\\tmapping (address => uint) balances;\\n\\n\\tevent Transfer(address indexed _from, addre
ss indexed _to, uint256 _value);\\n\\n\\tconstructor() public {\\n\\t\\tbalances[tx.origin] = 10000;\\n\\t}\\n\\n\\tfunction sendCoin(address receiver, uint amount) public returns(bool sufficient) {\\n\\t\\tif (balances[msg.sender] < amount) return false;\\n\\t\\tbalance
s[msg.sender] -= amount;\\n\\t\\tbalances[receiver] += amount;\\n\\t\\temit Transfer(msg.sender, receiver, amount);\\n\\t\\treturn true;\\n\\t}\\n\\n\\tfunction getBalanceInEth(address addr) public view returns(uint){\\n\\t\\treturn ConvertLib.convert(getBalance(addr),2)
;\\n\\t}\\n\\n\\tfunction getBalance(address addr) public view returns(uint) {\\n\\t\\treturn balances[addr];\\n\\t}\\n}\\n"},"C:/MetaCoin/contracts/ConvertLib.sol":{"content":"pragma solidity >=0.4.25 <0.6.0;\\n\\nlibrary ConvertLib{\\n\\tfunction convert(uint amount,ui
nt conversionRate) public pure returns (uint convertedAmount)\\n\\t{\\n\\t\\treturn amount * conversionRate;\\n\\t}\\n}\\n"}},"settings":{"evmVersion":"byzantium","optimizer":{"enabled":false,"runs":200},"outputSelection":{"*":{"":["legacyAST","ast"],"*":["abi","evm.byte
code.object","evm.bytecode.sourceMap","evm.deployedBytecode.object","evm.deployedBytecode.sourceMap","userdoc","devdoc"]}}}}';
solc.compile(input);
```

**Not working**
```javascript
const solc = require('solc');
const input = '{"language":"Solidity","sources":{"C:\\\\MetaCoin\\\\contracts\\\\MetaCoin.sol":{"content":"pragma solidity >=0.4.25 <0.6.0;\\n\\nimport \\"./ConvertLib.sol\\";\\n\\n// This is just a simple example of a coin-like contract.\\n// It is not standards compatible and cannot
 be expected to talk to other\\n// coin/token contracts. If you want to create a standards-compliant\\n// token, see: https://github.com/ConsenSys/Tokens. Cheers!\\n\\ncontract MetaCoin {\\n\\tmapping (address => uint) balances;\\n\\n\\tevent Transfer(address indexed _fr
om, address indexed _to, uint256 _value);\\n\\n\\tconstructor() public {\\n\\t\\tbalances[tx.origin] = 10000;\\n\\t}\\n\\n\\tfunction sendCoin(address receiver, uint amount) public returns(bool sufficient) {\\n\\t\\tif (balances[msg.sender] < amount) return false;\\n\\t\
\tbalances[msg.sender] -= amount;\\n\\t\\tbalances[receiver] += amount;\\n\\t\\temit Transfer(msg.sender, receiver, amount);\\n\\t\\treturn true;\\n\\t}\\n\\n\\tfunction getBalanceInEth(address addr) public view returns(uint){\\n\\t\\treturn ConvertLib.convert(getBalance
(addr),2);\\n\\t}\\n\\n\\tfunction getBalance(address addr) public view returns(uint) {\\n\\t\\treturn balances[addr];\\n\\t}\\n}\\n"},"C:\\\\MetaCoin\\\\contracts\\\\ConvertLib.sol":{"content":"pragma solidity >=0.4.25 <0.6.0;\\n\\nlibrary ConvertLib{\\n\\tfunction conv
ert(uint amount,uint conversionRate) public pure returns (uint convertedAmount)\\n\\t{\\n\\t\\treturn amount * conversionRate;\\n\\t}\\n}\\n"}},"settings":{"evmVersion":"byzantium","optimizer":{"enabled":false,"runs":200},"outputSelection":{"*":{"":["legacyAST","ast"],"*
":["abi","evm.bytecode.object","evm.bytecode.sourceMap","evm.deployedBytecode.object","evm.deployedBytecode.sourceMap","userdoc","devdoc"]}}}}';
solc.compile(input);
```
Error message that I'm getting is:
```javascript
'{"contracts":{},"errors":[{"component":"general","formattedMessage":"C:\\\\MetaCoin\\\\contracts\\\\MetaCoin.sol:3:1: ParserError: Source \\"ConvertLib.sol\\" not found: File import callback not supported\\nimport \\"./ConvertLib.sol\\";\\n^------------------------^\\n"
,"message":"Source \\"ConvertLib.sol\\" not found: File import callback not supported","severity":"error","sourceLocation":{"end":60,"file":"C:\\\\MetaCoin\\\\contracts\\\\MetaCoin.sol","start":34},"type":"ParserError"}],"sources":{}}'
```

**Comment by chriseth** [comment] 2019-04-29 12:36
Please not that regardless of the platform, Solidity's internal directory separator is always `/`, so your examples are perfectly according to the specification. Please reopen if I misunderstood something.

**Comment by daniyarchambylov** [comment] 2019-04-30 03:46
@chriseth unlike Unix Windows uses backslash `\` as a directory separator. If we run following snippet on Windows

```javascript
const path = require('path');

console.log(path.join('C:/Users/Projects', 'smart-contracts'))
```
The output will be
```javascript
C:\Users\Projects\smart-contracts
```
For some reason compiler can't find  source file with path `C:\MetaCoin\contracts\ConvertLib.sol`, but has no problem with `C:/MetaCoin/contracts/ConvertLib.sol`

**Comment by chriseth** [comment] 2019-04-30 11:01
@daniyarchambylov I'm sorry, but I don't fully understand. In the initial issue description, you provided a solidity standard-json input string. This one only knows `/` as a directory separator. Furthermore, the paths inside this input string do not even have to exist on your system, they are mainly identifiers for use in the compiler.

Furthermore, `import` statements inside Solidity also only know `/` as a directory separator.

In the standard-json you provide two source files with the names `"C:/MetaCoin/contracts/MetaCoin.sol"` and `"C:/MetaCoin/contracts/ConvertLib.sol"`. The instruction `import "./ConvertLib.sol";` strips off the component after the last `/` of the current file name, replaces it by `Convertlib.sol` and searches in the standard json dictionary provided. It does not even take a look at your filesystem (becuse of "File import callback not supported").

**Comment by daniyarchambylov** [comment] 2019-05-01 06:48
@chriseth  Please look at this input
```
{"language":"Solidity","sources":{"C:\\Users\\dan\\MetaCoin\\contracts\\MetaCoin.sol":{"content":"pragma solidity >=0.4.25 <0.6.0;\n\nimport \"./ConvertLib.sol\";\n\n// This is just a simple example of a coin-like contract.\n// It is not standards compatible and cannot be expected to talk to other\n// coin/token contracts. If you want to create a standards-compliant\n// token, see: https://github.com/ConsenSys/Tokens. Cheers!\n\ncontract MetaCoin {\n\tmapping (address => uint) balances;\n\n\tevent Transfer(address indexed _from, address indexed _to, uint256 _value);\n\n\tconstructor() public {\n\t\tbalances[tx.origin] = 10000;\n\t}\n\n\tfunction sendCoin(address receiver, uint amount) public returns(bool sufficient) {\n\t\tif (balances[msg.sender] < amount) return false;\n\t\tbalances[msg.sender] -= amount;\n\t\tbalances[receiver] += amount;\n\t\temit Transfer(msg.sender, receiver, amount);\n\t\treturn true;\n\t}\n\n\tfunction getBalanceInEth(address addr) public view returns(uint){\n\t\treturn ConvertLib.convert(getBalance(addr),2);\n\t}\n\n\tfunction getBalance(address addr) public view returns(uint) {\n\t\treturn balances[addr];\n\t}\n}\n"},"C:\\Users\\dan\\MetaCoin\\contracts\\ConvertLib.sol":{"content":"pragma solidity >=0.4.25 <0.6.0;\n\nlibrary ConvertLib{\n\tfunction convert(uint amount,uint conversionRate) public pure returns (uint convertedAmount)\n\t{\n\t\treturn amount * conversionRate;\n\t}\n}\n"}},"settings":{"evmVersion":"byzantium","optimizer":{"enabled":false,"runs":200},"outputSelection":{"*":{"":["legacyAST","ast"],"*":["abi","evm.bytecode.object","evm.bytecode.sourceMap","evm.deployedBytecode.object","evm.deployedBytecode.sourceMap","userdoc","devdoc"]}}}}
```
The error is:
```
{ Error: C:\Users\dan\MetaCoin\contracts\MetaCoin.sol:3:1: ParserError: Source "ConvertLib.sol" not found: File import callback not supported
import "./ConvertLib.sol";
^------------------------^
    at CompileError.ExtendableError (C:\Users\dan\AppData\Roaming\npm\node_modules\truffle-security\node_modules\truffle-error\index.js:10:17)
    at new CompileError (C:\Users\dan\AppData\Roaming\npm\node_modules\truffle-security\compat\truffle-compile\compileerror.js:12:23)
    at supplier.load.then.solc (C:\Users\dan\AppData\Roaming\npm\node_modules\truffle-security\compat\truffle-compile\index.js:234:11)
  message:
   'C:\\Users\\dan\\MetaCoin\\contracts\\MetaCoin.sol:3:1: ParserError: Source "ConvertLib.sol" not found: File import callback not supported\nimport "./ConvertLib.sol";\n^------------------------^\n\u001b[31mCompilation failed. See above.\u001b[39m',
  stack:
   'Error: C:\\Users\\dan\\MetaCoin\\contracts\\MetaCoin.sol:3:1: ParserError: Source "ConvertLib.sol" not found: File import callback not supported\nimport "./ConvertLib.sol";\n^------------------------^\n    at CompileError.ExtendableError (C:\\Users\\dan\\AppData\\Roaming\\npm\\node_modules\\truffle-security\\node_modules\\truffle-error\\index.js:10:17)\n    at new CompileError (C:\\Users\\dan\\AppData\\Roaming\\npm\\node_modules\\truffle-security\\compat\\truffle-compile\\compileerror.js:12:23)\n    at supplier.load.then.solc (C:\\Users\\dan\\AppData\\Roaming\\npm\\node_modules\\truffle-security\\compat\\truffle-compile\\index.js:234:11)',
  name: 'CompileError' }
```
But ConverLib.sol file is present
```
$ ls  C:\\Users\\dan\\MetaCoin\\contracts
ConvertLib.sol  MetaCoin.sol  Migrations.sol
```

**Comment by chriseth** [comment] 2019-05-02 07:43
The binary you are using (or the way you are using it) does not support retrieving files from your filesystem on its own. All of the files have to be supplied as part of the input json structure.

**Comment by daniyarchambylov** [comment] 2019-05-02 08:31
Ok, so how come changing backslash to forward slash doesn't throw an exception?

**Comment by chriseth** [comment] 2019-05-02 08:49
If you have a file called `a/b/c`, then `import "./x";` will look for `a/b/x` in your json structure, while if it is called `a\b\c`, then it will look for just `x` (I think), since `\` is considered to be part of the file name.

**Comment by daniyarchambylov** [comment] 2019-05-02 09:09
You can't use import as `import ".\x" or `import ".\\x"' it's illegal. But we're using Windows OS for development and the way path  is resolved is that OS is using `\` for directory separator. So if we have "import ./x"  in a file called `a\b\c` it should search for `a\b\x`.  That's just how Windows behaves. But on unix `\` will be part of the filename.

**Comment by chriseth** [comment] 2019-05-02 09:21
I think we are turning a little in circles here. Solidity when used in standard-json mode is fully platform independent. This is a requirement so that you can re-compile the same source to the same binary on all platforms. Standard-json does not care about the directory separator on the platform in is used on. It will always use slash. If you are running a web server on windows, the URLs you use are still of the form `http://github.com/ethereum/solidity` and not `http:\\github.com\ethereum\solidity`. Relative links inside html files also follow the same pattern as import statements in solidity.

What do you use to create the standard-json input? This component should translate the back slashes to forward slashes.

**Comment by daniyarchambylov** [comment] 2019-05-02 09:41
It's not URL, it's file path. for source path I use something like 
```
const path = require('path');
sourcePath = path.join(contractsDir, solFilename);
```

**Comment by chriseth** [comment] 2019-05-02 09:45
Nice, so all you have to do is convert the windows path to the unix path before you feed it into solc-js!

**Comment by daniyarchambylov** [comment] 2019-05-02 10:21
Sure that's what I'm doing right now! But I thought solc-js should have supported windows path in the first place :sweat_smile:

**Comment by chriseth** [comment] 2019-05-02 10:30
Ok, I see! Supporting that would hurt reproducibility: https://github.com/ethereum/solidity/issues/6608#issuecomment-488607026

**Comment by cameel** [comment] 2021-02-19 16:19
I think the cause of the problem has been explained adequately here and the way it works is by design, not due to a bug (as @chriseth said, changing this would hurt reproducibility by allowing paths that work only on specific platforms) so I'm closing this.

**Closed as completed by cameel** 2021-02-19 16:19 UTC
