### ISSUE TITLE
"constants" expressions are expressions, not constants.

### ISSUE THREAD

**Issue by drortirosh** [ethereum/solidity#9232] opened 2020-06-18 15:24 UTC
Constant expressions are left as expressions, not constants.
## Description

a constant declared  as:
```
bytes32 public constant EIP712DOMAIN_TYPEHASH = keccak256(
    "EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"
);
```
Is re-calculated each time it is in use.

### expected
the value should be converted into a constant value at compile time.

###a ctual
The expression is re-calculated each time the constant is referenced.

### consequences:
- each usage of a "constant" costs ~100gas more on each access (it is still a little better than storing the result in storage, but not much..)
- since these are not real constants, they can't be referenced from a real constant environment (e.g. from assembly, or from another library )

## Environment

-- solc 0.6.10
-- checked in remix, with optimization enabled.

**Comment by chriseth** [comment] 2020-06-18 16:10
Duplicate of #4024  / #3157

**Comment by chriseth** [comment] 2020-06-18 16:11
Ah and by the way: You could use `immutable`s until the referenced issues are implemented, then you only pay the gas costs for the computation at deploy time.

**Closed as completed by chriseth** 2020-06-18 16:10 UTC
