### ISSUE TITLE
Memory Management in Solidity.

### ISSUE THREAD

**Issue by phyBrackets** [ethereum/solidity#12298] opened 2021-11-19 15:56 UTC
These days I'm hanging around memory management . And I come to know there is no memory management in solidity , not automatic or even manual memory management . But there is delete keyword  exist here but don't get the actual purpose , setting the value to deafult or null , it doesn't mean that we are freeing the memory.  And that can lead to memory leak in the future.

**Comment by cameel** [comment] 2021-11-19 16:20
Some kind of memory management is actually on our roadmap for 2022.

The main problem is that managing memory in many smart contracts would be just pure overhead and cost you more for absolutely no gain - why bother executing some elaborate allocation scheme that can deal with fragmentation or why deallocate memory at all if most calls are very short-lived and do not come even close to running out of memory. You pay more if you use more memory so cases where memory management would actually be of some benefit do exist, but that's always a trade-off.

As for memory leaks, this concept does not really make sense without a deallocation mechanism. You could say that technically all memory is "leaked" in Solidity because it's never freed during contract execution. It does not matter at all because all memory is automatically "freed" when the contract invocation ends.

`delete` is meant for freeing storage and memory in the sense of zeroing it (which can give you a refund) not deallocating it in the same sense as e.g. in C++. It might be repurposed when we actually do have memory management but I think it's more likely that some other construct will be introduced for freeing memory because it would be a breaking change.

Anyway, this is not a bug and is a bit too broad for a feature request (has no concrete specification) so I'm going to close it. It looks more like a general opinion. If you want to just discuss memory management in general feel free to open a topic on the [forum](https://forum.soliditylang.org). It would actually be interesting to get some opinions on this from the community and hear about real-life use cases that would benefit from memory management.

**Closed as completed by cameel** 2021-11-19 16:20 UTC
