### ISSUE TITLE
CompilerUtils.cpp:784:3: error: this statement may fall through [-Werror=implicit-fallthrough=]    }

### ISSUE THREAD

**Issue by moneroexamples** [ethereum/solidity#2420] opened 2017-06-17 21:38 UTC
This issue is based on this one for Arch/Manjaro:

https://github.com/moneroexamples/compile-cpp-ethereum-on-arch/issues/2

gcc version:

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 7.1.1 20170516 (GCC) 
```

Problem:
```
/home/kusayu/solidity/libsolidity/codegen/CompilerUtils.cpp: In member function ‘void dev::solidity::CompilerUtils::convertType(const dev::solidity::Type&, const dev::solidity::Type&, bool, bool)’:
/home/kusayu/solidity/libsolidity/codegen/CompilerUtils.cpp:784:3: error: this statement may fall through [-Werror=implicit-fallthrough=]
   }
   ^
/home/kusayu/solidity/libsolidity/codegen/CompilerUtils.cpp:786:2: note: here
  default:
  ^~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/build.make:543: libsolidity/CMakeFiles/solidity.dir/codegen/CompilerUtils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:275: libsolidity/CMakeFiles/solidity.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

A proposed solution form the comment in that issue:

New gcc seem not to allow switch cases to [fall through](https://gcc.gnu.org/onlinedocs/gcc/Statement-Attributes.html). 

A possible fix could be adding `__attribute__((fallthrough));` to the switch statements that it happens. This happens in two files:

1. ~/solidity/libsolidity/codegen/CompilerUtils.cpp

In line 784 add: `__attribute__((fallthrough));`, so this should look like:

```
			// stack: <address> <function_id>
			m_context << Instruction::POP;
			break;
		}
        __attribute__((fallthrough)); // <- this is added
	}
	default:
```

2. ~/solidity/libsolidity/codegen/ExpressionCompiler.cpp

In line 1046 add: `__attribute__((fallthrough));`, so this should look like:

```
				// not found in contract, search in members inherited from address
				alsoSearchInteger = true;
		}
		if (!alsoSearchInteger)
			break;
        __attribute__((fallthrough)); // <- this is added
	}
	case Type::Category::Integer:
```

Hope this helps.

**Comment by axic** [comment] 2017-06-22 11:53
Thanks! It is currently worked on in #2339.

Duplicate of #2344.

**Closed as completed by axic** 2017-06-22 11:53 UTC
