### ISSUE TITLE
Duplicate address sanitation for call parameter

### ISSUE THREAD

**Issue by wjmelements** [ethereum/solidity#8696] opened 2020-04-17 22:51 UTC
Version 0.6.6.
Command: `solc --asm --optimize --optimize-runs=20000 contracts/Demo.sol`
Demo.sol:
```
contract A {
    function b(A c, B f) external returns (A) {
        return f.get(c);
    }
}
interface B {
    function get(A) external returns (A);
}
```

Output includes:
```
        /* "contracts/Demo.sol":76:84  f.get(c) */
      mload(0x40)
      dup3
      0xffffffff
      and
      0xe0
      shl
      dup2
      mstore
      0x04
      add
      dup1
      dup3
      0xffffffffffffffffffffffffffffffffffffffff
      and
      0xffffffffffffffffffffffffffffffffffffffff
      and
      dup2
      mstore
```

The code twice sanitizes the address `c`. The optimizer does not fix this.

**Comment by chriseth** [comment] 2020-04-20 13:18
Could be duplicate of https://github.com/ethereum/solidity/issues/8670

**Closed as completed** 2020-04-23 10:25 UTC
