### ISSUE TITLE
Stray warnings on structs - BREAKING CHANGE

### ISSUE THREAD

**Issue by Tectract** [ethereum/solidity#2550] opened 2017-07-10 13:05 UTC
struct notarizedImage {
    string imageURL;
    uint timeStamp;
  }

> Warning: Variable is declared as a storage pointer. Use an explicit \"storage\" keyword to silence this warning.\n string imageURL;

  struct storage notarizedImage {
    string imageURL;
    uint timeStamp;
  }

> ParserError: Expected identifier, got 'Storage'\n struct storage notarizedImage

I can no longer compile this contract without warning:

https://raw.githubusercontent.com/Tectract/ethereum-demo-tools/master/GeektSolidity/contracts/Geekt.sol

This leads to the popular online tool "EthDeployer" not being able to compile and deploy MOST solidity smart contracts, even though they contain no errors.

http://www.enledger.io/EthDeployer/

This is a tool used by thousands of people to learn Solidity, since you guys removed the ability to COMPILE smart contracts from the node! Now it's broken.

**Comment by axic** [comment] 2017-07-10 13:28
Duplicate of #2549.

**Closed as completed by axic** 2017-07-10 13:28 UTC
