### ISSUE TITLE
Cannot call emit function

### ISSUE THREAD

**Issue by 3sGgpQ8H** [ethereum/solidity#3739] opened 2018-03-15 09:14 UTC
From code of my contract I'm calling function named `emit` of another already deployed contract.  My code successfully compiles under Solidity 0.4.20, but Solidity 0.4.21 outputs the following error:

    ParserError: Expected event name or path.

Looks like introducing new event logging syntax broke something.

**Comment by amiranagram** [comment] 2018-05-25 20:09
Hi, I have the same issue. Anyone found a solution to this?

**Comment by chriseth** [comment] 2018-05-28 17:50
Yes, please either use a newer compiler or do not use the `emit` pseudo-keyword.

**Comment by chriseth** [comment] 2018-05-28 17:50
Ah wait, this is something else. Can you post your code? If you use `emit(...)`, it should be fine. If there is a space after `emit`, it might not work.

**Comment by axic** [comment] 2018-06-11 11:36
@amiramieng can you please post your code?

**Comment by axic** [comment] 2018-07-28 11:48
Okay reproduced the issue:
```
contract C {
  function emit() public {}
}

contract D is C{
  function f() public {
    emit();
  }
}
```

This works however:
```
contract C {
  function emit() public {}
}

contract D is C{
  function f() public {
    (new C()).emit();
  }
}
```

Closing this however, since in 0.5.0 `emit` is a keyword and this problem goes away by disallowing `function emit()` in the first place.

**Closed as completed by axic** 2018-07-28 11:48 UTC
Labels: waiting for more input
