### ISSUE TITLE
Single return works but Multiple return fails outside a function

### ISSUE THREAD

**Issue by sebastiantf** [ethereum/solidity#15038] opened 2024-04-18 13:52 UTC
## Description

It seems, outside a function, single returns are possible, but multiple returns are not

## Environment

- Compiler version: v0.8.19, v0.8.25
- Target EVM version (as per compiler settings): Cancun
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: Remix VM Cancun
- Operating system: macOS 13

## Steps to Reproduce

```solidity
// SPDX-License-Identifier: MIT

pragma solidity 0.8.25;

contract MultipleReturnError {
    uint256 singleResult = singleReturn();

    // errors on next line: ParserError: Function, variable, struct or modifier declaration expected.
    (uint256 multipleResultA, uint256 multipleResultB) = multipleReturn();

    function singleReturn() public returns(uint256) {
        return 42;
    }

    function mutipleReturn() public returns(uint256,uint256) {
        return (42, 43)
    }
}

```

**Comment by mehtavishwa30** [comment] 2024-04-22 11:39
@sebastiantf This behaviour is not a bug in the compiler but rather a limitation of the Solidity language design that currently does not allow users to declare multiple state variables in one statement. If declared separately, they cannot be initialised with a single tuple. However, it is possible to initialise multiple state variables with a tuple in a constructor.

Please not that the new type system in Solidity will enable better tuple types in the future. I will be closing this issue as it is not a bug.

**Closed as not planned by mehtavishwa30** 2024-04-22 11:39 UTC
