### ISSUE TITLE
soljson 0.8.2 crashes with "TypeError: Cannot read property 'slice' of undefined"

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#11489] opened 2021-06-04 19:47 UTC
## Description

The soljson for Solidity 0.8.2 (just this specific version) seems to be broken.  For instance, when I try to compile using Solidity 0.8.2 with Truffle, I get the following error message, originating from within the soljson:

```
TypeError: Cannot read property 'slice' of undefined
    at convertJsFunctionToWasm (/home/sniffnoy/.config/truffle/compilers/node_modules/soljson-v0.8.2+commit.661d1103.js:1:4559)
    at addFunctionWasm (/home/sniffnoy/.config/truffle/compilers/node_modules/soljson-v0.8.2+commit.661d1103.js:1:5839)
    at addFunction (/home/sniffnoy/.config/truffle/compilers/node_modules/soljson-v0.8.2+commit.661d1103.js:1:6092)
    at runWithCallbacks (/home/sniffnoy/truffle/truffle/node_modules/solc/wrapper.js:143:14)
    at compileStandard (/home/sniffnoy/truffle/truffle/node_modules/solc/wrapper.js:207:14)
    at Object.compileStandardWrapper [as compile] (/home/sniffnoy/truffle/truffle/node_modules/solc/wrapper.js:214:14)
    at Object.parseImports (/home/sniffnoy/truffle/truffle/packages/compile-solidity/parser.js:41:23)
    at parseImports (/home/sniffnoy/truffle/truffle/packages/compile-solidity/profiler/loadParser.js:24:21)
    at Object.<anonymous> (/home/sniffnoy/truffle/truffle/packages/compile-common/src/profiler/getImports.ts:30:25)
    at Generator.next (<anonymous>)
    at /home/sniffnoy/truffle/truffle/packages/compile-common/dist/src/profiler/getImports.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sniffnoy/truffle/truffle/packages/compile-common/dist/src/profiler/getImports.js:4:12)
    at Object.getImports (/home/sniffnoy/truffle/truffle/packages/compile-common/dist/src/profiler/getImports.js:19:12)
    at /home/sniffnoy/truffle/truffle/packages/compile-common/src/profiler/resolveAllSources.ts:75:17
    at Generator.next (<anonymous>)
```

(Yes I've mentioned this before but figured I should file an actual issue so it doesn't get lost.)

Since Solidity 0.8.2 doesn't seem to be broken when invoked by other means, this might just be a matter of rebuilding the soljson or similar?  IDK, I don't know much about these things.  But, I thought I should file an issue.  Thanks!

## Environment

- Compiler version: 0.8.2
- Framework/IDE (e.g. Truffle or Remix): Truffle
- Operating system: Release Linux Mint 20.1 Ulyssa 64-bit

**Comment by cameel** [comment] 2021-06-05 21:59
Thanks for creating the issue. Yeah, there's always too much stuff going on so it's best to file an issue in any case :)

Looks this one is easy to reproduce:
```bash
npm install truffle@5.3.9
npx truffle init
npx truffle create contract C
echo 'module.exports.compilers.solc.version = "0.8.2";' >> truffle-config.js
npx truffle compile
```

Interestingly, `compile` does not fail in older versions of Truffle. Looks like it started in 5.3.3. Of the ones I tried:
- works on 5.2.4, 5.3.0, 5.3.1 and 5.3.2,
- fails on 5.3.3, 5.3.4, 5.3.5, 5.3.7 and 5.3.9.

The binary did pass bytecode comparison check in solc-bin. I.e. it produces the same exact JSON output, including bytecode, on all the ~5k test snippets from our repo as all the other binaries (excluding the Windows one, #11365) so I wonder if it isn't actually something in the input that throws it off.

I'll need to compare standard JSON input produced by Truffle in 5.3.2 and 5.3.3 and see if there's a difference. (BTW, I wish we already had https://github.com/trufflesuite/truffle/issues/3368).

EDIT: It actually started happening in Truffle 5.3.3 (I originally said 5.3.4).

**Comment by cameel** [comment] 2021-06-23 16:43
@haltman-at I managed to get to the bottom of it. The root cause is that Truffle (specifically its `compile-solidity` package) [depends on an old version of solc-js (0.6.0)](https://github.com/trufflesuite/truffle/blob/bd53ee4a4bdc107c12a2ddf50bab81036ccfccb7/packages/compile-solidity/package.json#L35).

The crash you're seeing is caused by a bug in solc-js that was fixed a year ago (https://github.com/ethereum/solc-js/pull/470). It was in `wrapper.js`: the second argument was missing in `addFunction(singleCallback, 'viiiii')`. This function is inside the compiled binary and calls other stuff that ultimately tries to call `.slice()` on the second argument, which should have been a string but was `undefined` instead.

Two things do not add up though. Why only solc 0.8.2 and Truffle >= 5.3.3?

### solc 0.8.2
Looks like in 0.8.2 `addFunction()` is defined slightly differently than in all the other 0.8.x ones:
- 0.8.1: `function addFunction(func,sig){sig=sig||"viiiii";return addFunctionWasm(func,sig)}`
- 0.8.2: `function addFunction(func,sig){return addFunctionWasm(func,sig)}`
- 0.8.3: `function addFunction(func,sig){sig=sig||"viiiii";return addFunctionWasm(func,sig)}`

As you can see, the other binaries have a default for `sig` which is why they do not fail. I suspect that this is somehow related to the fact that we updated to a newer emscripten version in 0.8.2 (#10751). Not sure why the default came back in 0.8.3 though.

### Truffle >= 5.3.3
In https://github.com/trufflesuite/truffle/pull/3975 the dependency on `solc` has been changed from `^0.6.0` to `0.6.0`. Bug was fixed in 0.6.9 so you effectively reverted to the buggy older version.

### Summary
So, well, it's true that the binary for 0.8.2 is different, but looks like it's not really broken so I'm closing this issue. I'll file a report about the outdated solc-js in Truffle's bugtracker.

**Closed as completed by cameel** 2021-06-23 16:43 UTC
Labels: bug :bug:, solcbin

**Comment by cameel** [comment] 2021-06-23 16:54
Reported in https://github.com/trufflesuite/truffle/issues/4134.

**Comment by cameel** [comment] 2021-06-23 17:11
For my own reference, here's the Standard JSON input passed to the compiler by Truffle (getting it was a bit tedious so pasting it here in case I need it later).

Turns out it's not a part of the actual compilation but instead a part of a parser class that detects imports in the file ([compile-solidity/parser.js](https://github.com/trufflesuite/truffle/blob/v5.3.11/packages/compile-solidity/parser.js)) by parsing them out of compilation error messages (BTW, @chriseth @haltman-at maybe a list of imports is something we could add to `outputSelection` to make such hacks unnecessary? These messages are likely to change soon: #11413, #11042).

### Truffle 5.2.4
JavaScript:
```javascript
{
    language: 'Solidity',
    sources: {
        'ParsedContract.sol': {
            content: '// SPDX-License-Identifier: MIT\n' +
                'pragma solidity >=0.4.22 <0.9.0;\n' +
                '\n' +
                'contract Migrations {\n' +
                '  address public owner = msg.sender;\n' +
                '  uint public last_completed_migration;\n' +
                '\n' +
                '  modifier restricted() {\n' +
                '    require(\n' +
                '      msg.sender == owner,\n' +
                `      "This function is restricted to the contract's owner"\n` +
                '    );\n' +
                '    _;\n' +
                '  }\n' +
                '\n' +
                '  function setCompleted(uint completed) public restricted {\n' +
                '    last_completed_migration = completed;\n' +
                '  }\n' +
               '}\n' +
               '\n' +
               '\n' +
               "import '__Truffle__NotFound.sol';\n"
          }
      },
    settings: { outputSelection: { 'ParsedContract.sol': [Object] } }
}
```
Serialized:
```json
{
    "language": "Solidity",
    "sources": {
        "ParsedContract.sol": {
            "content": "// SPDX-License-Identifier: MIT\npragma solidity >=0.4.22 <0.9.0;\n\ncontract Migrations {\n  address public owner = msg.sender;\n  uint public last_completed_migration;\n\n  modifier restricted() {\n    require(\n      msg.sender == owner,\n      \"This function is restricted to the contract's owner\"\n    );\n    _;\n  }\n\n  function setCompleted(uint completed) public restricted {\n    last_completed_migration = completed;\n  }\n}\n\n\nimport '__Truffle__NotFound.sol';\n"
        }
    },
    "settings": {
        "outputSelection": {
            "ParsedContract.sol": {
                "*": []
            }
        }
    }
}
```
### Truffle 5.3.4
The `content` here is different but I suspect it's just because files get processed in a different order. This one contains the empty contract I generated using `truffle create contract C`.

JavaScript:
```javascript
{
    language: 'Solidity',
    sources: {
        'ParsedContract.sol': {
            content: '// SPDX-License-Identifier: MIT\n' +
                'pragma solidity >=0.4.22 <0.9.0;\n' +
                '\n' +
                'contract C {\n' +
                '  constructor() public {\n' +
                '  }\n' +
                '}\n' +
                '\n' +
                '\n' +
                'import "__Truffle__NotFound.sol";\n'
        }
    },
    settings: { outputSelection: { 'ParsedContract.sol': [Object] } }
}
```
Serialized:
```json
{
    "language": "Solidity",
    "sources": {
        "ParsedContract.sol": {
            "content": "// SPDX-License-Identifier: MIT\npragma solidity >=0.4.22 <0.9.0;\n\ncontract C {\n  constructor() public {\n  }\n}\n\n\nimport '__Truffle__NotFound.sol';\n"
        }
    },
    "settings": {
        "outputSelection": {
            "ParsedContract.sol": {
                "*": []
            }
        }
    }
}
```

**Comment by haltman-at** [comment] 2021-06-23 21:53
> (BTW, @chriseth @haltman-at maybe a list of imports is something we could add to `outputSelection` to make such hacks unnecessary? These messages are likely to change soon: #11413, #11042).

Oh, yikes, good to know!

The thing of course is that anything added to the output will only exist in future Solidity versions, so we're still going to need to keep the old mechanism around to handle older versions.  But I suppose if the messages change at the same time as the new mechanism is added...?

Really there's already something of a new mechanism for this what with the `stopAfter: "parsing"` option that we don't currently use -- we could use that and get them out of the AST, I imagine -- but we don't use that because it requires passing a special option that doesn't exist on older Solidity versions.  It's possible it might be worth revisiting that though.  (Though of course something directly in `outputSelection` might be easier to use?)
