### ISSUE TITLE
"for each" iteration through arrays

### ISSUE THREAD

**Issue by lukehutch** [ethereum/solidity#13213] opened 2022-06-25 21:47 UTC
## Abstract

There is currently no "for each" notation for iterating through arrays in solidity. This should be added, either as a "for each" operator, or as an implicit iteration (if lambdas are supported at some point).

## Motivation

Currently the best means we have to iterate through an array in Solidity is:

```solidity
for (uint256 i = 0; i < arr.length; ++i) { ... }
```

This has a few problems:

1. It's wasteful on gas to evaluate `arr.length` every time, but the alternative is verbose and pollutes the namespace:
    ```solidity
    uint256 arrLen = arr.length;
    for (uint256 i = 0; i < arrLen; ++i) { ... }
    ```
    (See proposal [here](https://github.com/ethereum/solidity/issues/13212) for supporting multiple variables in the first clause of a `for` statement, which solves the namespace polluting problem, but it's still verbose.)
2. In Solidity ^0.8.x, all arithmetic is checked by default, so the `++i` is inefficient, and yet it's not possible to write
    ```
    for (uint256 i = 0; i < arr.length; unchecked { ++i; } ) { ... }
    ```
    Whereas in reality it would be impossibly expensive to create an array that is `type(uint256).max` in size, so the `++i` can be unchecked. This then requires the following format to eliminate this inefficiency:
    ```solidity
    for (uint256 i = 0; i < arr.length; ) {
        // ...
        unchecked { ++i; }
    }
    ```

Instead, the following notification (or similar) should be supported (for some appropriate element type `ELT_TYPE`):

```solidity
for (ELT_TYPE elt : arr) { ... }
```

`:` could also be `in` or similar, but it might be better to follow Java's lead and not reserve `in` as a keyword.

The compiler could then implement the iteration through the array with maximal efficiency (e.g. by not re-checking the array length on each iteration, if the array can't change size, and by using unchecked math).

In particular this will lead to much more efficient loops in eWasm, because the loop counter won't have to be a `uint256` if the array is small in size.

In future, if lambdas are supported in Solidity, then implicit iteration could be used:

```solidity
uint256 sum = 0;
arr.forEach(ELT_TYPE x => { sum += x; });
```

## Specification

In the basic implementation, a "for each" operator e.g. `:` would be added to Solidity's `for` syntax, as shown above.

## Backwards Compatibility

This would be backwards compatible, as it is a superset of current functionality.

**Comment by axic** [comment] 2022-06-28 10:14
I think this is a duplicate of #10162, which has a lot of discussion on the topic.

**Closed as completed by axic** 2022-06-28 10:14 UTC
Labels: language design :rage4:
