### ISSUE TITLE
Accessing constants in pure functions

### ISSUE THREAD

**Issue by RenanSouza2** [ethereum/solidity#6522] opened 2019-04-15 20:35 UTC
## Abstract

Make possible to access constants in pure functions

## Motivation

Pure functions cannot access environment variables, but constants are decided in compile time.

## Backwards Compatibility

If the function is pure bute call calls an old contract view function, being this view only due to a constant access, the new function needs to also be view

**Comment by chriseth** [comment] 2019-04-15 21:23
Can you give some example code, please?

**Comment by RenanSouza2** [comment] 2019-04-15 22:03
`pragma solidity ^0.5.7;

contract SomeContract {
    uint256 constant public ID = 0;
}

contract Test {
    SomeContract public some;
    
    function setSome (address _some)
    external {
        some = SomeContract(_some);
    }
    
    function getID ()
    external view returns (uint256) {
        return some.ID();
    }
}`

Shouldn't the getID() be pure as the ID cannot be changed

**Comment by RenanSouza2** [comment] 2019-04-15 22:07
```
    contract SomeContract {
        uint256 constant public ID = 0;
    }
```

```    

    contract Test {
        SomeContract public some;
        
        function setSome (address _some)
        external {
            some = SomeContract(_some);
        }
        
        function getID ()
        external view returns (uint256) {
            return some.ID();
        }
    }
```

Shouldn't the getID() be pure as the ID cannot be changed

**Comment by chriseth** [comment] 2019-04-17 09:01
This is a duplicate of https://github.com/ethereum/solidity/issues/1290 - I actually thought that was already implemented.

**Closed as completed by chriseth** 2019-04-17 09:01 UTC
