### ISSUE TITLE
Allow comments to ignore compiler warnings.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#2691] opened 2017-08-03 19:21 UTC
I would like the ability to disable compiler warnings on a per-line basis using something like comments or pragma.  C++ has a mechanism to also disable comments across a block using `#pragma push (disable: 1234)` and `#pragma pop`.  I'll leave it up to the language designers to decide the exact mechanism based on which one is most reasonable to implement.  The key is that I need to be able to disable any single specific warning in the source code that is generating that warning.

With `solc` becoming more and more opinionated with its compiler warnings, there needs to be a way to disable them selectively.  At the moment, we use `solc` compiler warnings/errors as a CI gate block but we are finding that some of the warnings _should_ be ignored, yet we don't have a reasonable way to do this right now.

For example, we have a `SafeMath` library that leverages `using SafeMath for <type>`.  This library does function overloading/shadowing so that it can have both `add(uint256,uint256)` and `add(int256,int256)` in the same library.  I appreciate the warning, but I need the ability to disable it on a case-by-case basis.  The same goes for a number of other warnings that have been added recently.  In general I think are all very valuable, but may not be able to be applied exhaustively to all code.

**Comment by axic** [comment] 2017-08-03 19:27
This is a duplicate of #2675. Please follow up on that thread.

Note: it falsely reports overloading as shadowing and that is being fixed (also addressed in a different issue).

**Comment by MicahZoltu** [comment] 2017-08-03 19:32
@axic I saw that, but it appears that discussion is around file-wide ignores, rather than per-line ignores.  Are you suggesting that you think both tasks would likely be solved at the same time?  Normally, when I'm running a GitHub project I prefer issues to be very specific as to the feature being requested and this feels like two separate features to me.  (per line ignore and per file ignore)

**Comment by axic** [comment] 2017-08-03 19:36
Sorry I didn't pick up you are suggesting a way to disable warnings on specific lines with adding a specific marker at that (like a comment). That is of course a different issue than #2675.  If so, please reopen this and explain your proposal.

However, if you read it carefully, there is a strong sentiment at the moment not to support any option to disable warnings. (We need to remove false negatives though.)

**Comment by MicahZoltu** [comment] 2017-08-03 19:42
I'll propose my arguments against no-disable option in the other issue.

I have updated the description of this issue to add clarity that I'm looking for a targeted in-source mechanism for disabling, but I don't have the access rights to re-open the issue.  Would you mind re-opening it for me if you believe the issue is clear enough now @axic?

**Comment by axic** [comment] 2017-08-03 19:43
Thanks, it is clear now!

**Comment by ryankc33** [comment] 2017-09-28 06:42
+1. The compiler warnings break backwards compatibility with many external libraries. This will be a great feature to have.

**Comment by lisuyong** [comment] 2017-11-23 13:07
Hi, there

What's this issue's status now? I'm so hopeful for this nice feature. 😺

**Comment by yarrumretep** [comment] 2018-02-12 01:48
+1 for this - it's hard when the compiler is printing warnings that you acknowledge and want to ignore.  It distracts from reading the warnings that may crop up but you don't want to ignore.  A comment mechanism as proposed here would allow one to express that they understand the risks.

**Comment by chriseth** [comment] 2018-02-12 09:30
@yarrumretep we take special care such that any warning given by the compiler can be removed by a small change to the source code. Could you please give an example where it would be easier to "remove" the warning by adding a comment instead of changing the source code to remove the risk altogether?

**Comment by axic** [comment] 2018-02-12 14:22
Actually a short term solution will be the 0.5.0 release turning most, if not all, these warnings into an error :wink:

**Comment by yarrumretep** [comment] 2018-02-12 18:36
@chriseth we are seeing `Warning: The "returndatacopy" instruction is only available after the Metropolis hard fork. Before that it acts as an invalid instruction.`  I am happy to have been notified of this, but would like to suppress this message as we are happy to proceed understanding that limitation.  Same for returndatasize, methinks.

We are also seeing `Warning: Jump instructions are low-level EVM features that can lead to incorrect stack access. Because of that they are discouraged. Please consider using "switch" or "for" statements instead.`  We are getting these from compiling Aracnid's string library - they are in functions we aren't using so we can prune them from our copy of the library.  But if `jump` is not going to be allowed shouldn't it be deprecated and eventually removed from the language?  BTW I don't have an opinion on this - just want to be able to get to a clean build when using the available features of the language.

**Comment by chriseth** [comment] 2018-02-12 19:05
@yarrumretep we are still debating how to handle different versions of the EVM, but I hope that we can resolve the returndatacopy issue soon - sorry that it takes so long.

Concerning jumps: Yes, please either remove the code or submit a pull request to the library turning it into code that does not use manual jumps.

We actually did deprecate them, but yes, that should probably be mentioned literally as part of the warning.

**Comment by yarrumretep** [comment] 2018-02-12 19:30
Thank you for the clarification @chriseth.  Maybe you could handle the hardfork thing with a compiler flag indicating what version of the EVM you want to target.  Then the returndatasize etc would error appropriately.

**Comment by chriseth** [comment] 2018-02-12 19:32
@yarrumretep yes, the question is basically whether we want to use a pragma or a compiler switch, but we will probably go with a compiler switch. Since this would be the first switch that affects code generation itself, it is a little tricky :)

**Comment by yarrumretep** [comment] 2018-02-12 20:45
@chriseth - interesting.  BTW, we are using those opcodes to grab a string return value b/c solidity currently doesn't return strings from calls.  Is this going to burn us or simply be unnecessary with future solidity versions?

**Comment by chriseth** [comment] 2018-02-12 21:00
We can hopefully merge the new abi decoder soon, then it will be automatic.

**Comment by chriseth** [comment] 2018-02-12 21:00
but you can of course also do it using inline asssembly

**Comment by celeduc** [comment] 2018-04-07 19:08
This has been particularly annoying since `var` was deprecated, since there is [presently no way](https://github.com/ethereum/solidity/issues/3301#issuecomment-376084616) to implement `var (,,,,,what,,evs,,,dude,) = lib.extFunc("arg")`.  I'd like to be able to silence these warnings until that is resolved, as it spits out a separate error for each variable (what, evs, dude) and makes it very hard to see real warnings.

**Comment by xuguojie** [comment] 2018-04-09 03:53
Agree with getting var warning suppressed.

**Comment by chriseth** [comment] 2018-04-10 14:25
@celeduc can you explain why `var (,,,,,what,,evs,,,dude,) = lib.extFunc("arg")` cannot be done without warnings anymore? `W what; E evs; D dude; (,,,,,what,,evs,,,dude,) = lib.extFunc("arg")` should work.

**Comment by celeduc** [comment] 2018-04-10 14:44
@chriseth Thank you for your note.

1) Solium already throws a style error for such a line: "  88:24    warning    Only use indent of 4 spaces.    indentation"
2) because it contains multiple statements in one line, it will _probably_ be considered unreadable by linting tools as they become more sophisticated
3) because it is an ugly hack, perhaps even uglier than `var (,,,,,what,,evs,,,dude,) = lib.extFunc("arg")`

I agree with previous commenters in #3301 that the syntax should be `(,,,,,W what,,E evs,,,D dude,) = lib.extFunc("arg")` if `var` is to be deprecated *without removing functionality*.

(This whole issue wouldn't be as important if external functions could return structs.)

**Comment by chriseth** [comment] 2018-04-11 20:50
@celeduc I was talking about a solution that has newlines and proper indentation. You mentioned that there is "presently no way" to do this. Can you please explain in more detail why it is not possible, since, as you say, a multi-assignment like `(,,,,,W what,,E evs,,,D dude,) = lib.extFunc("arg")` should solve the problem. I agree that external functions returning structs would be much nicer, but we are unfortunately not there yet.

**Comment by celeduc** [comment] 2018-04-11 21:15
@chriseth With `var` it was a single expression on one line. Without `var` it is four expressions on four lines. It is no longer concise. Deprecating `var` takes away a popular, concise solution, and the deprecation warning cannot be silenced. The *proposed* multi-assignment solution `(,,,,,W what,,E evs,,,D dude,) = lib.extFunc("arg")` does not compile ("ParserError: Expected token Comma, got 'Identifier'") with solc 0.4.21.

**Comment by chriseth** [comment] 2018-04-11 22:25
@celeduc it should be `(,,,,,what,,evs,,,dude,) = lib.extFunc("arg")` is in my first example.

**Comment by celeduc** [comment] 2018-04-14 10:23
Before `var` was deprecated we could use the single, concise, one-line expression:
```
var (,,,,,what,,evs,,,dude,) = lib.extFunc("arg");
```
But then `var` was deprecated, and the above line generates three separate warnings. To remove these warnings, we now have to use four expressions (on four lines) to do the same thing:
```
W what;
E evs;
D dude;
(,,,,,what,,evs,,,dude,) = lib.extFunc("arg");
```

It has been [proposed](https://github.com/ethereum/solidity/issues/3301) that the following syntax be supported (IMO it should have been before `var` was deprecated), which would again allow a single expression in one line, just like the original code which used `var`:
```
(,,,,,W what,,E evs,,,D dude,) = lib.extFunc("arg");
```

Reducing the total number of lines of code helps to increase the readability and clarity of a function, especially when a large number of redundant declarations makes it difficult to fit an otherwise small amount of code on the screen. We look forward to being able to return structs from external functions, but for the time being we are stuck with this syntax as our only recourse, and it sure would be nice if the language weren't moving backward on this front.

But, given that `var` has already been deprecated it would at least be good to avoid polluting our compilation logs with these warnings in the meantime.

**Comment by j-h-scheufen** [comment] 2018-05-06 18:48
@chriseth Following up on your comment from Feb. 12, I'm adding a couple of examples where it's impossible to get rid of warnings via code changes.

### ERC165
The examples to implement ERC165 contracts rely on calling `this` in the constructor to refer to function selectors: `supportedInterfaces[this.supportsInterface.selector] = true;`
However, the use of `this` in constructors is now flagged with a warning: https://github.com/ethereum/solidity/issues/583

While ultimately, the code inspection for this warning should be able to distinguish between "allowed" and "disallowed" uses, the 583 ticket discussed the complexity of it, so it's not likely to be implemented anytime soon. So, in the meantime, it would be a great help to be able to turn these warnings off selectively (i.e. by line comments).

### Abstract contracts
When using the OO concept of abstract contracts, you end up with multiple warnings for "unused var". Example (written off the cuff, no guarantee this compiles, only to make the point):
```
contract MyInterface {
   function processBytes32(bytes32 _param);
   function processAddress(address _param);
   function processUint(uint _param);
}

contract AbstractMyInterface is MyInterface {
   function AbstractMyInterface() internal {}
   function processBytes32(bytes32 _param) {}
   function processAddress(address _param) {}
   function processUint(uint _param) {}
}

contract MyCustomImpl is AbstractMyInterface {
   // custom impl chooses only to overwrite one function of the abstract contract
   function processBytes32(bytes32 _param) {
      // do something with bytes32
   }
}
```

In this example, the only way to avoid the "unused var" warnings is to not use the concept of abstract implementations at all and implement empty functions in all contracts implementing the interface. A programmer should not have to make such a design choice due to warnings being annoying. Having the ability to flag the abstract functions with a comment to ignore the warnings would therefore be very helpful.

**Comment by chriseth** [comment] 2018-05-07 06:08
@j-h the first one is a little tricky, yes. Since this part has both a high false positives and a high false negatives rate, you can use `ContractType self = this; supportedInterfaces[self.supportsInterface.selector] = self;`.

The second warning can be suppressed by either removing the variable names (only the name) or commenting it out.

**Comment by j-h-scheufen** [comment] 2018-05-07 06:22
Thanks @chriseth ! You just cleaned up my build log tremendously! I should've thought about the fact that the variable name is actually not needed for the abstract implementation. Never questioned it after the abstract contracts initially were made by copy/paste from the interface.

**Comment by nventuro** [comment] 2019-07-24 20:21
Are there any plans/spec for implementing this? I'd guess a major blocker would be coming up warning ids, so that only specific ones are suppressed.

False-positive warnings are currently a pain point when developing/using Solidity libraries (in the software engineering sense of the word, not a Solidity `library`): often, base contracts will have methods to be overridden by their children, like in [`OpenZeppelin's Crowdsale`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/crowdsale/Crowdsale.sol):

```
function _preValidatePurchase(address beneficiary, uint256 weiAmount) internal view {
    require(beneficiary != address(0), "Crowdsale: beneficiary is the zero address");
    require(weiAmount != 0, "Crowdsale: weiAmount is 0");
}
```

That function is `view` because overrides may require e.g. reading from storage in order to perform their task, but it doesn't need this attribute in the base contract - `pure` would suffice.

```
openzeppelin-solidity/contracts/crowdsale/Crowdsale.sol:138:5: Warning: Function state mutability can be restricted to pure
```

There's no workaround for this (relatively common) scenario, which emits warnings on both the library developer and user's workflows. Having a way to silence warnings selectively (e.g. `// solc-disable-line possible-stricter-mutability`) would be extremely helpful.

**Comment by ekpyron** [comment] 2019-08-01 15:02
@nventuro For this particular case you could use
```
function _preValidatePurchase(address beneficiary, uint256 weiAmount) internal view {
    require(beneficiary != address(0), "Crowdsale: beneficiary is the zero address");
    require(weiAmount != 0, "Crowdsale: weiAmount is 0");
    this; // silence state mutability warning without generating any additional byte code
}
```
EDIT: that is, unless we start warning about such a ``this;`` at some point :-).

**Comment by nventuro** [comment] 2019-08-01 20:17
Thanks, that works! Still, it'd be great to now have to rely on those hacks and have a proper way to signal a warning is a false positive.

**Comment by fulldecent** [comment] 2019-11-14 03:59
If a contract is marked as `abstract` then it cannot be compiled. And therefore any notes warnings (not errors) about state mutability don't matter. This is because they are going to be overridden and the mutability will be considered on the compilable version.

Would suppressing can-have-stricter-mutability-guarantees for abstracts solve @nventuro's issue?

**Comment by mudgen** [comment] 2020-06-16 13:38
What is the status of being able to disable a warning from a line?

**Comment by mudgen** [comment] 2020-06-16 13:39
I am getting the following warning that I need to suppress: "Return value of low-level calls not used."  How can I suppress this warning? I don't want to use the return value of the low level call.

**Comment by chriseth** [comment] 2020-06-16 13:40
There is no such plan, sorry. The way to disable the warning is to not ignore the return value.

**Comment by mudgen** [comment] 2020-06-16 13:54
Okay.  So I don't ignore the return value.  I assign it to a local variable.  Now solidity gives me this warning: "Unused local variable."   So now what I am I supposed to do? I have no need of this variable at all.  Do I do some useless thing with it just to get rid of the warning? Any suggestions?

**Comment by mudgen** [comment] 2020-06-16 13:57
Here is my code to get rid of the warning:
```
// success variable not need, only here to remove warning from compiler
(bool success,) = myaddress.call(abi.encodeWithSelector(0x3cfc70f7, _Id));
success;
```

**Comment by chriseth** [comment] 2020-06-16 13:59
```
bool success;
(success, ) = myaddress.call("");
```
would be another way.

**Comment by chriseth** [comment] 2020-06-16 14:00
You can also use
```solidity
try myaddress.realFunction(_id) { } catch {}
```

**Comment by mudgen** [comment] 2020-06-16 14:01
ah, these are better.  Much appreciated!

I like using try, catch to avoid low level calls.   Is there a gas difference?

**Comment by gorgos** [comment] 2020-12-29 20:31
Here's a simple use case for this feature:

Deploying a contract >24kb on a private chain to get rid of 'Warning: Contract code size exceeds 24576 bytes'.

**Comment by chriseth** [comment] 2021-01-12 14:49
@gorgos this sounds more like a feature for a compiler switch to me.

**Comment by gorgos** [comment] 2021-01-12 19:40
@chriseth Is `solc` not supposed to be used on private EVM chains?

**Comment by chriseth** [comment] 2021-01-12 19:45
@gorgos we cannot support all possible private chains because of the different configurations (think custom EVM opcodes), but we can add a setting that changes the allowed code size, even if this goes against the selected EVM version.

**Comment by chriseth** [comment] 2021-01-18 12:20
@gorgos are there any other aspects of the compiler that would be different on private chains?

**Comment by gorgos** [comment] 2021-01-18 22:08
> @gorgos are there any other aspects of the compiler that would be different on private chains?

@chriseth Just to be clear about the term 'private chain', this could of course be a publicly available chain, so 'custom chain' would be more accurate.

Otherwise in my use case there are no further differences. And as you said, supporting other opcodes makes no sense at this point.

**Comment by axic** [comment] 2021-02-15 18:22
The original proposal mentions the capability existing in C++ using pragmas:
> #pragma push (disable: 1234) and #pragma pop.

At the time we did not had any kind of error codes, but now we do (#9033). This is not displayed by default, but shown with `--error-codes` on the CLI.

While these error codes are convenient that they exists, I still do not feel easy about them and would prefer to avoid having them in the source codes. These errors are kind of fragile as they can change between releases, such as when the reporting of an error is moved to a different place of the pipeline, or when checks are extended and/or reconciled.

I personally do not like pragmas for this, but rather find the approach of various linters preferable: a comment preceding the given statement with a readable exclusion, i.e. `// solidity-ignore-address-checksum`. This approach also means we consciously need to add things which can be switched off, which perhaps helps in reducing the surface area.

**Comment by cameel** [comment] 2021-02-19 20:51
We talked about this on the last weekly call and the consensus for now is that we do not see a reason compelling enough to implement this. Most of the comments in this thread are pretty old and the problems they raise have already been addressed. During the 0.5.x release cycle there were many warnings that annoyed users but it seems to be happening much less with the recent releases. Our approach is to fix the underlying issues that lead to unnecessary warnings rather than have people suppress them. We looked through the bug tracker and there are hardly any reports that are still open. The ones that are closed look like they have been patched pretty quickly.

So I'm going to close this issue. If you find a situation where you need to suppress a particular warning, don't hesitate to report it and we'll try to find a solution. We don't want to stifle the discussion on this and more feedback is appreciated but for now I think that the thread I created on the forum is a better place for that: [Which compiler warnings do you ignore?](https://forum.soliditylang.org/t/which-compiler-warnings-do-you-ignore/89).

Also, note that this is only about disabling specific warnings on a case-by-case basis. We recognize that warnings caused by libraries (which have to support multiple compiler versions) are harder to avoid. This case is covered by a separate issue: #2675.

**Closed as completed by cameel** 2021-02-19 20:51 UTC

**Comment by cameel** [comment] 2021-02-19 21:09
@gorgos I have added a feature request for the code size limit flag: #10981. We can continue the discussion there.

**Comment by xlab** [comment] 2021-03-09 20:08
Another annoying Warning, that I started to get after upgrading to 0.8.x:

```
Warning: Visibility for constructor is ignored.
```

Which is cool in most cases, but I already have clean constructors. This warning is emitted when running `--combined-json ast,compact-format` and then `--import-ast`. And there is no easy way how to resolve this.

So I'll have to find a hack how to eat all warnings from solc using stderr redirect, until this resolves.

I've created an issue https://github.com/ethereum/solidity/issues/11077

**Comment by Elyx0** [comment] 2021-05-30 11:02
So doing
```js
abstract contract Context {
    function _msgSender() internal view virtual returns (address payable) {
        return msg.sender;
    }

    function _msgData() internal view virtual returns (bytes memory) {
        this; // silence state mutability warning without generating bytecode - see https://github.com/ethereum/solidity/issues/2691
        return msg.data;
    }
}
``` this; is the way?

**Comment by cameel** [comment] 2021-05-30 13:06
@Elyx0 Starting with 0.7.0 the compiler no longer issues this warning for virtual functions.

**Comment by simontianx** [comment] 2021-06-05 09:36
@cameel This is a great news. The use of `this` in the code below is one of first few moments that I got an impression that Solidity is a mysterious language. Good news to know it is back to normal.

```
function _msgData() internal view virtual returns (bytes calldata) {
    this; // silence state mutability warning without generating bytecode - see https://github.com/ethereum/solidity/issues/2691
    return msg.data;
}
```

**Comment by Qlio** [comment] 2022-11-29 12:27
I want to create a proxy contract that has a payable fallback function. But I want to keep the `receive` function in the implementation contract. But it's giving me the following warning: `Warning: This contract has a payable fallback function, but no receive ether function. Consider adding a receive ether function.` in the proxy contract. is there any way to disable it? or my whole logic is wrong?

```sol
// Proxy Contract
contract Proxy {
    fallback() external payable { // <-- this is where it gives me the warning.
         // some code that delegates the call.
    }
}

contract Implementation {
    receive() external payable {
        // some logic... Ex: emit event or something.
    }
}
```

Thanks!

**Comment by nventuro** [comment] 2022-11-29 13:10
@Qlio consider taking a look at the [`hardhat-ignore-warnings`](https://www.npmjs.com/package/hardhat-ignore-warnings) plugin by @frangio - it doesn't currently support that specific warning, but it should be trivial to add it.

**Comment by frangio** [comment] 2022-11-29 14:43
@Qlio I've added `missing-receive` as a warning id to the plugin, so you can write:

```solidity
// solc-ignore-next-line missing-receive
contract Proxy {
```

Alternatively use the config file as described in the [readme](https://github.com/frangio/hardhat-ignore-warnings#readme).

**Comment by Yhok13** [comment] 2023-02-22 04:55
Puedo usar el código de este contrato para crear mi token

**Comment by mesutt000** [comment] 2023-07-24 18:53
Mesutt000
