### ISSUE TITLE
"unchecked" code is not truly unchecked

### ISSUE THREAD

**Issue by drortirosh** [ethereum/solidity#12196] opened 2021-10-26 17:11 UTC
The `unchecked {}` construct is very beneficial, to prevent unnecessary  checks, where the developer knows these checks are already made elsewhere.
however, there are checks that still get into the code even if "unchecked" is specified.

e.g there is a call to EXTCODESIZE before each "call", to make sure the target is indeed a contract and not an EOA.
This is not always required, in case the code is expected to return specific return values, or in case multiple calls to the same contract are made.

### Suggestion

The `unchecked` semantics should be applied to all the checks injected by the compiler.
the only exception might be reverts from external calls (which can be handled with try/catch constructs)

**Comment by axic** [comment] 2021-10-26 17:19
I think this is a duplicate of #11125.

**Comment by hrkrshnn** [comment] 2021-10-27 09:00
> or in case multiple calls to the same contract are made.

Unless the contract was selfdestructed between. Maybe we can add an optimization rule where `extcodesize` would be an invariant as long as there are no state modifying operations in between (excluding `staticcall`, `sstore`?)

Note that since EIP-2929, the additional `extcodesize` check costs 100 (previously 800). 

I was somewhat against this idea in the past, but now that users are really writing code to avoid the `extcodesize` check, I'm having second thoughts. It might be true that the `returndata` checks may be enough for some cases; but need to think this through. The usual approach to get around this currently is `<address>.call(abi.encodeWithSelector(..., ...))`. Perhaps a reasonable middle ground would be a type safe encoding, such as https://github.com/ethereum/solidity/issues/11849?

**Comment by hrkrshnn** [comment] 2021-10-27 09:08
Currently, `unchecked` is used exclusively for arithmetic overflows--a replacement for the SafeMath libraries. For example, conversions are still unchecked currently. If we decide to go this route, `unchecked` might not be the right keyword for this.

**Comment by cameel** [comment] 2021-10-27 13:16
I'm going to close this as a duplicate. @hrkrshnn can you repost your comments in the other issue?

**Closed as completed by cameel** 2021-10-27 13:16 UTC
Labels: language design :rage4:

**Comment by hrkrshnn** [comment] 2021-10-27 14:13
A reasonable compromise is https://github.com/ethereum/solidity/issues/12204. Done automatically by the compiler.

**Comment by drortirosh** [comment] 2021-10-27 18:02
This solves some cases.
Still, a developer control is still needed.
As an example, we have another case where one contract makes multiple calls to another contract.
There is no need to repeat this check for extcodesize

**Comment by hrkrshnn** [comment] 2021-10-28 10:59
@drortirosh Would you consider https://github.com/ethereum/solidity/issues/11849 to be a way for the developer to control this? If you have a function `f` without returndata, then `<address>.call(abi.encodeCall(f, (args))` would be both typesafe, avoids the `extcodesize` check and hopefully not too clumsy. Currently, `<address>.call(abi.encodeWithSelector(...))` would also be a way to avoid the `extcodesize` check, although not as type safe.

IMO, having a syntax to avoid this `extcodesize` check adds more nuances / magic to the language. We generally want to avoid this. Also, doing this inside `unchecked` will make this feature a breaking change. I have a feeling that there will be a big push back against this from library authors.

**Comment by drortirosh** [comment] 2021-10-28 14:28
IMHO, requiring me to add a return value to a function signature just to make it cheaper doesn't seem right.  Just consider a case where a user want to use an existing ABI (e.g. token transfer)

I think that the current `unchecked` gives an impression that "no checks are done" - which is not exact
I think should have parameter one (or more) of:
- math
- call-target
- array index 
- all

For backward compatibility, the default should be `unchecked "math"`
BTW: I think this is default counter-intuitive, and the default assumption for a developer would be "all" - but that what is currently defined.

**Comment by hrkrshnn** [comment] 2021-10-28 15:03
@drortirosh Perhaps, it's better to add your concerns about `unchecked` in the other issue, i.e., https://github.com/ethereum/solidity/issues/11125

> IMHO, requiring me to add a return value to a function signature just to make it cheaper doesn't seem right.

Maybe I didn't communicate this clearly, the idea is that if we want to avoid the `extcodesize`, we use a low-level `call`. Either `address.call(...)` or inside inline assembly; it fits well with the philosophy that fine-grained control should be done using low-level syntax. A high-level call should have additional checks, to deal with generic cases.

**Comment by drortirosh** [comment] 2021-10-28 19:56
`address.call(...)` has its own set problems...
It is more expensive to do `address.call(abi.encodeWithSelector(...)` than it is to make a direct call. somehow, the encoding method is far less efficient than encoding for making an actual call
(the more parameters you add the more inefficient the code becomes.)

We make calls that get structure as parameters. it is possible to encode with abi.encodeWithSelector, but as I said, its inefficient.
encoding it with assembly is possible, but it is VERY error-prone. Also, referencing struct fields in assembly is highly tricky, since even the offsets of members within the struct are inaccessible in assembly. You have to use numeric constants, and manually handle dynamic parameter offsets, which is a pain.

**Comment by transmissions11** [comment] 2021-11-12 02:43
yes please we still dearly need a way to prevent extcodesize checks on no-returndata calls without using low level calls. as @drortirosh said its often more expensive to encode for low level calls— not to mention its gross and unsafe
