### ISSUE TITLE
Constant folding with arbitrary precision arithmetic?

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#3759] opened 2018-03-18 02:43 UTC
contract c {
function f() returns (int) {
return 4 ** 4 ** 2 ** 4 ** 4 ** 4 ** 4 ** 4 ** 4 ** 4 ** 4 ** 4 ** 4 * 2;

}

Causes the compiler to hang (surprisingly, not exceed memory limit) for hours.  Not sure a "bug," but worth reporting as sub-optimal.

**Comment by agroce** [comment] 2018-03-18 02:43
(same TSTL effort)

**Comment by chriseth** [comment] 2018-03-19 12:57
I think we detect that in the case of a single exponentiation, but not with multiple.

**Comment by agroce** [comment] 2018-03-23 19:23
This form also sends the compiler into a hang:

```
contract c {
function f() public payable returns (int) {
for (10 / 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10; 8 <= (10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10) ** 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 8; (10) * (10) * 8)
for (10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 8 * 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 8 ** (10); 8 > (10); (10) * (10) * 8 << 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 10 >> (10) >> (10) ** 10 >> (10) >> (10) ** 10 << 8)
for (10 >> (10) >> (10) ** 10 >> (10) >> (10); 10 <= 10 >> (10) >> (10) ** 10 >> (10) >> (10); 8)
return (8);




}

}
```

Same underlying problem, but different enough might be useful for fixing the detection.

**Comment by chriseth** [comment] 2018-03-27 13:12
@bit-shift please also add a test for the one above.

**Comment by erak** [comment] 2018-03-28 14:13
@chriseth Please have a look :) https://github.com/ethereum/solidity/pull/3793

**Comment by erak** [comment] 2018-03-28 14:17
Should we close this as duplicate of #3327? Slightly different scenario but both will be fixed with the same pull request.

**Comment by chriseth** [comment] 2018-03-29 07:46
If the pull request fixes both, then just add a "fixes" entry to the description of the pull request.

**Closed as completed** 2018-04-16 11:10 UTC
Labels: bug :bug:
