### ISSUE TITLE
Incorrect abi type generated for `enum` in library

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/solidity#12867] opened 2022-03-28 07:44 UTC
## Description

Solidity compiler doesn't generate the correct abi type for library. The enum should be mapped to `uint8`, it works for `contract` but not for `library`. Instead, the type is simply a user-defined value `"type": "mycontract.Field"`.

## Environment

- Compiler version: 0.8.13
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: default
- Operating system: default

## Steps to Reproduce

Compile the following code snippet and obtain the abi output from the remix

```solidity
// SPDX-License-Identifier: MIT

pragma solidity 0.8.13;

library mycontract {
  enum Field {
    F1
  }  
  function example(Field x) public view {}
}
```

The abi output I got 

```
[
	{
		"inputs": [
			{
				"internalType": "enum mycontract.Field",
				"name": "x",
				"type": "mycontract.Field"
			}
		],
		"name": "example",
		"outputs": [],
		"stateMutability": "view",
		"type": "function"
	}
]
```

**Comment by chriseth** [comment] 2022-04-11 14:06
This is correct and intentional. The ABI for libraries is differen than it is for contracts. Closing as duplicate of https://github.com/ethereum/solidity/issues/9278

**Closed as completed by chriseth** 2022-04-11 14:06 UTC
