### ISSUE TITLE
New function sighash to distinguish memory and calldata reference type arguments

### ISSUE THREAD

**Issue by deluca-mike** [ethereum/solidity#10495] opened 2020-12-04 05:00 UTC
## Abstract

Currently, `foo(bytes32[] calldata array)` and `foo(bytes32[] memory array)` result in the same sighash, and thus the function cannot be overloaded. Feature request is to have the `location` taken into account when determining the function signature, and thus sighash. 

## Motivation

Calldata is cheaper the memory, albeit readonly. If you'd like to build a library with an overloaded function (to provide a better developer experience) regardless if the developer calls with a calldata or memory array, you cannot. Right now, you are forced to do something like:
`function foo_c(bytes32[] calldata array) internal pure returns (bytes32 merkle_root);`
`function foo_m(bytes32[] memory array) internal pure returns (bytes32 merkle_root);`
and the caller must call either `foo_c` or `foo_m`, depending on the location of their array. And if they call foo_m with a calldata array, it will result in wasted gas copying the calldata to memory.

With the following
`function foo(bytes32[] calldata array) internal pure returns (bytes32 merkle_root);`
`function foo(bytes32[] memory array) internal pure returns (bytes32 merkle_root);`
resulting in different sighashes, the caller can call `foo` without needing to worry about additional details.

## Specification

Currently:
`function foo_c(bytes[] calldata array) internal pure returns (bytes32 merkle_root);`
`function foo_m(bytes[] memory array) internal pure returns (bytes32 merkle_root);`
`function foo_c(bytes32[] calldata array) internal pure returns (bytes32 merkle_root);`
`function foo_m(bytes32[] memory array) internal pure returns (bytes32 merkle_root);`
`function foo_c(uint256[] calldata array) internal pure returns (bytes32 merkle_root);`
`function foo_m(uint256[] memory array) internal pure returns (bytes32 merkle_root);`

Future:
`function foo(bytes[] calldata array) internal pure returns (bytes32 merkle_root);`
`function foo(bytes[] memory array) internal pure returns (bytes32 merkle_root);`
`function foo(bytes32[] calldata array) internal pure returns (bytes32 merkle_root);`
`function foo(bytes32[] memory array) internal pure returns (bytes32 merkle_root);`
`function foo(uint256[] calldata array) internal pure returns (bytes32 merkle_root);`
`function foo(uint256[] memory array) internal pure returns (bytes32 merkle_root);`

## Backwards Compatibility

Unsure. Likely not possible since no way to decide which location is "default" in that it owns the right to the "location-less" sighash.

**Comment by chriseth** [comment] 2020-12-07 11:51
Duplicate of #1256

**Closed as completed by chriseth** 2020-12-07 11:51 UTC
Labels: language design :rage4:
